### ISSUE TITLE
Replacing a collapsed SubProcess deletes all contained elements

### ISSUE THREAD

**Issue by rene5141** [bpmn-io/bpmn-js#1000]
__Describe the Bug__

When a collapsed SubProcess is being replaced with a normal Task all containing elements are deleted.

__Steps to Reproduce__
![BPMN modeler bug](https://user-images.githubusercontent.com/5740840/56722864-2c4c1280-6748-11e9-8e04-33a3ba810295.gif)

__Expected Behavior__

When a SubProcess is collapsed the user should be not allowed to change the type. Otherwise the contained elements will be deleted.

__Environment__

 - Browser: IE 11
 - OS: Windows 10
 - Library version: 3.3.1

**Comment by nikku** [comment]
Thanks for filing this issue.

To understand you correctly, your case is the following: A user replaces a collapsed sub-process with a task, however she is not aware that it contains actual elements. some time later _?_ he is surprised to see the children got removed.

As tool vendors we tend to not block users from doing what they intend to do (i.e. changing a sub-process to a task). We assume a user is empowered enough to understand what the result of his / her actions is. As tasks do not have children, what should the user expect, other than the children being removed?

Can you think of another way to improve the situation other than blocking the transform operation?

**Comment by pinussilvestrus** [comment]
@rene5141 Any additional thoughts about that?

I agree Nico that we shouldn't block modeling operations (except when definitely not valid by the official BPMN 2.0 reference).

**Comment by philippfromme** [comment]
I think we all agree that this behavior is perfectly fine. Closing this.
