### ISSUE TITLE
'.git' directory is published to NPM for the version 3.4.0

### ISSUE THREAD

**Issue by agavrilov** [bpmn-io/bpmn-js#1001]
__Describe the Bug__

'.git' directory is published to NPM for the version 3.4.0. It prevents the installation/upgrades of other packages. Running 'npm install' after 3.4.0 is installed outputs the following:

```
npm ERR! path C:\P\git\c8\Projects\WebAccess\node_modules\bpmn-js
npm ERR! code EISGIT
npm ERR! git C:\P\git\c8\Projects\WebAccess\node_modules\bpmn-js: Appears to be a git repo or submodule.
npm ERR! git     C:\P\git\c8\Projects\WebAccess\node_modules\bpmn-js
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

```

__Steps to Reproduce__

1. add "bpmn-js": "3.4.0" as a dependency to package.json
2. run "npm install"
3. run "npm install" again

__Expected Behavior__

'.git' directory should not be published to NPM

__Environment__

Please complete the following information:

 - OS: Windows 10
 - Library version: 3.4.0

**Comment by nikku** [comment]
Seems like the `.git` directory slipped into the package due to a `npm` bug that causes a nested `CHANGELOG` file to be included.

We published `v3.4.1` that should be fixed.
