### ISSUE TITLE
Improve type hints to support advanced code navigation and assistance in IDEs (Intellij, VSCode) and LSPs

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1002]
__What should we do__

We should fix the JSDoc type definitions across our projects and leverage [TypeScript's support for JavaScript projects](https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html). 

* [ ] Fix type definitions on services and service APIs (https://github.com/bpmn-io/diagram-js/issues/501, https://github.com/bpmn-io/diagram-js/issues/502, https://github.com/bpmn-io/bpmn-js/issues/1378, https://github.com/bpmn-io/bpmn-js/issues/1379)
* [ ] Verify correct usage of types via type linting `tsc --noEmit --pretty`
* [ ] Introduce actual type definitions for core entities (i.e. the model), unless they can be safely consumed from JS 
* [ ] Consider publishing types generated from `JSDoc` (https://github.com/bpmn-io/bpmn-js/issues/332#issuecomment-762079804)
* [ ] Consider strategies to type our DI container `bpmnJS.get`
* [ ] Consider generating type definitions from our source files to aid type support in bundled setups

__What we should not do__

We should not, as of today, migrate our projects to TypeScript:

* Type checking JavaScript projects and _correct_ JSDoc on JavaScript projects provides equal capabilities and DX on the consumer side. 
* Not transpiling our code base during development (and run) is a major benefit.

**Comment by nikku** [comment]
@philippfromme I've updated the issue with a few more findings.

@barmac Would be amazing if you could fill in the TypeScript blanks :wink:.

**Comment by lppedd** [comment]
@nikku I'll work with this project using Typescript, thus I will most likely produce type definitions for it.
There is currently a request for it [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10256).

My opinion is that you should move everything to Typescript incrementally.

**Comment by nikku** [comment]
@lppedd Thanks for sharing your feedback. 

Just to manage expectations: We cannot promise any move to TypeScript any time soon :wink: .

**Comment by nikku** [comment]
As mentioned in the issue text, there exists other solution approaches that will likely give you the same amount of type hints without the need for us to move fully to TypeScript. We'd appreciate your help improving the typed support.

**Comment by lppedd** [comment]
@nikku I almost completed typings for `BpmnJS `and `EventBus`. I would just love to have more documentation on the objects returned to the callback functions, which seems to change between event types.

**Comment by lppedd** [comment]
@nikku here https://github.com/lppedd/bpmnio-typings you can find an initial attempt at typings. I've done a bit of everything, but still I'm losing a lot of time debugging. If you could give a look and comment with some suggestion, it would be awesome!

**Comment by nikku** [comment]
I like [this one in particular](https://github.com/lppedd/bpmnio-typings/blob/master/src/%40types/bpmn-js/index.d.ts#L257) that implements your example.

**Comment by lppedd** [comment]
@nikku yeah, that was a good idea! The same concept is applied also to `Moddle#create` [here](https://github.com/lppedd/bpmnio-typings/blob/704e2ffb2e45429eb83cf305f9a43a0a6a391a42/src/%40types/moddle/index.d.ts#L20).
Example:

```
const startEvent = moddle.create('bpmn:StartEvent');
      ^ type is BpmnStartEvent
const startEvent = moddle.create('bpmn:ExtensionElements');
      ^ type is BpmnExtensionElements
```
I've provided "defaults" for bpmn-js, but a user can extend those typings by simply redefining `BpmnElementMap` ([here](https://github.com/lppedd/bpmnio-typings/blob/704e2ffb2e45429eb83cf305f9a43a0a6a391a42/src/%40types/moddle/index.d.ts#L58)).
These means I can do, in my module
```
declare module 'moddle/lib/moddle' {
   interface BpmnElementMap {
      'myns:CustomElement': MyCustomElement;
   }
}
```
and then, in implementation code
```
const myElement = moddle.create('myns:CustomElement', { ... });
      ^ type is MyCustomElement

const definitions = moddle.create('bpmn:Definitions', { ... });
      ^ type is BpmnDefinitions
```

**Comment by lppedd** [comment]
That's how I implemented `didi` injection. I throw this in here because it might be useful for future reference.

```
@Inject(
  'eventBus',
  'styles',
  'pathMap',
  'canvas',
  'textRenderer'
)
class CustomRenderer extends BpmnRenderer {
  constructor(
    eventBus: EventBus,
    ...
```

The Inject decorator is pretty simple
```
export function Inject(injection: string, ...others: string[]) {
  return <T extends Ctor>(ctor: T): void => {
    ctor.$inject = [injection, ...others];
  };
}
```

Which is basically what you'd do with
```
CustomRenderer.$inject = [
  'eventBus',
  'styles',
  'pathMap',
  'canvas',
  'textRenderer'
];
```

Just a lot cleaner for TS.

**Comment by yfwz100** [comment]
This is awesome! Is it planned to release in npm?

**Comment by nikku** [comment]
Nothing planned here.

**Comment by patoncrispy** [comment]
It would be great to see detailed API documentation and/or TypeScript added to this project. It is quite a lot of effort to find out what properties certain objects have (contexts, elements, events, etc.) what events are available, what parts of the system respond to which events, what the 'best practices' are for using/overriding/creating modules, what modules do, among other things.

This would be particularly useful when breaking changes are introduced, as while there is a changelog, type safety really does help the developer experience. 

I would be happy to help out with at least the TypeScript effort if there is to be one.

**Comment by lppedd** [comment]
@nikku Hi! I've made some progress with typings. I'd like some help with this declaration, the `context` parameter.  
https://github.com/lppedd/bpmnio-typings/blob/cc78174f2ff610b9d410928d1f2be779ec431f8b/src/%40types/diagram-js/index.d.ts#L1226

**Comment by lppedd** [comment]
@patoncrispy If you want you can PR here https://github.com/lppedd/bpmnio-typings for now.
I'd like to move it to DefinitelyTyped but it's still early imho.

**Comment by patoncrispy** [comment]
Cool thanks @lppedd I'll take a look soon.

**Comment by patoncrispy** [comment]
Hey @lppedd what more work do you think would need to be done to get your typings work into DefinitelyTyped?

**Comment by lppedd** [comment]
@patoncrispy it has been months I haven't worked on TS/JS projects, but I can assure you what I have done is a small portion of the framework. There is much much more

**Comment by nikku** [comment]
For historical purposes, this is what we've found in the past:


----

## Option 1: Leverage TypeScript foundations

...

## Option 2: Leverage existing JSDoc annotations

Right now we have a quite comprehensive set of existing type definitions, baked into our JSDoc statements. One example from our code base (`Viewer#importXML`):

```javascript
/**
 * Parse and render a BPMN 2.0 diagram.
 *
 * Once finished the viewer reports back the result to the
 * provided callback function with (err, warnings).
 *
 * ## Life-Cycle Events
 *
 * During import the viewer will fire life-cycle events:
 *
 *   * import.parse.start (about to read model from xml)
 *   * import.parse.complete (model read; may have worked or not)
 *   * import.render.start (graphical import start)
 *   * import.render.complete (graphical import finished)
 *   * import.done (everything done)
 *
 * You can use these events to hook into the life-cycle.
 *
 * @param {String} xml the BPMN 2.0 xml
 * @param {ModdleElement<BPMNDiagram>|String} [bpmnDiagram] BPMN diagram or id of diagram to render (if not provided, the first one will be rendered)
 * @param {Function} [done] invoked with (err, warnings=[])
 */
Viewer.prototype.importXML = function(xml, bpmnDiagram, done) {
...
```

This allows VSCode to provide decent hints already. It does not know about `ModdleElement` though, as we do not declare it. 

### Idea: Create type definitions for all types we refer to

By providing the corresponding JSDoc type definitions we can improve the existing developer experience. Given the following typings:

#### `typeDefs.js`

```javascript
/**
 * @typedef Bounds
 * @type {object}
 * @property {number} x
 * @property {number} y
 * @property {number} width
 * @property {number} height
 */

/**
 * @typedef TRBL
 * @type {object}
 * @property {number} top
 * @property {number} right
 * @property {number} bottom
 * @property {number} left
 */
```

... and the following feature:

#### `MyFeature.js`

```javascript
import 'typeDefs';

class Foo {

  /**
   * @param {Bounds}
   */
  foo(bounds) {
    // ...
  }
}
```

... the assistance in VSCode (IntelliSense) can properly provide full information about `fooFeature#foo`:

```javascript
import FooFeature from 'FooFeature';

class BarFeature {
  
  /**
   * @param {FooFeature} fooFeature
   */
  constructor(fooFeature) {
    fooFeature.foo(); // IntelliSense to the rescue!
  }
}
```

A better way of importing things (seen in TypeScript, too) is by actually importing the used types from somewhere and use them in the documentation tags, only:

```javascript
import { Bounds } from 'diagram-js-types';

class Foo {

  /**
   * @param {Bounds}
   */
  foo(bounds) {
    // ...
  }
}
```

### Areas of Research

* How to properly declare inherits relationships
* How to properly declare types for utilities, i.e. Bounds
* Does importing types for typing support only impact bundle sizes (initial research shows no, as these import declarations are being tree-shaken)

**Comment by nikku** [comment]
As indicated via https://github.com/bpmn-io/bpmn-js/issues/332#issuecomment-762079804 you can now generate TypeScript definitions from JSDoc types.

**Comment by philippfromme** [comment]
Closed by https://github.com/bpmn-io/internal-docs/issues/688. [bpmn-js@13](https://www.npmjs.com/package/bpmn-js/v/13.0.0) includes type declarations.
