### ISSUE TITLE
Adding an element on a very narrow connection with label breaks the diagram

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1007]
__Describe the Bug__

When I try to add a task on a very narrow connection, the diagram is no more editable and the action cannot be undone.

![broken](https://user-images.githubusercontent.com/28307541/56949810-22555580-6b34-11e9-9ce1-8971e6ce07b8.gif)

__Steps to Reproduce__

1. Open `simple.bpmn` from BPMN test fixtures.
2. Move the subprocess down so that the connection is very narrow.
3. Try to place a new task on that connection.

Note: it's reproducable only when the connection has a label.

__Expected Behavior__

It shouldn't break 🤪.

__Environment__

Please complete the following information:

 - Browser: Chrome 73
 - OS: MacOS
 - Library version: demo.bpmn.io

**Comment by nikku** [comment]
Cannot reproduce with `bpmn-js@5`:

![capture sps4Vq_optimized](https://user-images.githubusercontent.com/58601/64112835-d720ad00-cd88-11e9-9888-c64a5bae95fb.gif)
