### ISSUE TITLE
Show Orange Markers When Moving Connection

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1013]
When moving a connection the [markers are removed](https://github.com/bpmn-io/diagram-js/commit/8d4d555da32c5507f6673d9b84e9338862b25c49) from the move visuals. Instead of removing them they should be orange.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/diagram-js/commit/06fb7177f3bc6032aabf21b18d89c3ad753abe77.
