### ISSUE TITLE
Grid Snapping Auto Resize Not Working

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1015]
Due to refactorings in [diagram-js](https://github.com/bpmn-io/diagram-js) the function signature of [AutoResize#resize](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/auto-resize/AutoResize.js#L240) has changed and needs to be adjusted for grid snapping to work.

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1018
