### ISSUE TITLE
Unexpected Layout After Using Space Tool

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1019]
### Reproduce

1. Create a `bpmn:SubProcess` with an appended flow node
2. Use the space tool to create space to the right

### Expected Behavior:

The connection bewteen the two doesn't change.

### Actual Behavior:

The connection between the two is laid out in an unexpected way.

![foobar](https://user-images.githubusercontent.com/7633572/57385045-faa86200-71b1-11e9-84d3-ecbf0ccb3ac2.gif)

---

Related to [SUPPORT-5824](https://app.camunda.com/jira/browse/SUPPORT-5824)

**Comment by philippfromme** [comment]
Due to the sequence of first resizing and then moving shapes when using the space tool the layout ends up broken.

To prevent that from happening we should __differenciate between adding space and removing space__ and __split up moving shapes__:

### Adding Space
1. move outer shapes
2. resize
3. move inner shapes

### Removing Space
1. move inner shapes
2. resize
3. move outer shapes

**Comment by nikku** [comment]
Could you link the support case?

**Comment by kurtudis** [comment]
> Could you link the support case?

SUPPORT-5824

**Comment by nikku** [comment]
Thanks!

**Comment by philippfromme** [comment]
@nikku Let's have a look at this together next week. 🍻

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1269
