### ISSUE TITLE
Reopen the same file on the modeler do not work

### ISSUE THREAD

**Issue by LuigiMaestrelli** [bpmn-io/bpmn-js#1022]
I opened a bpmn file on the modeler and did some changes.
But I messed things up and decide to start over by opening the same file again.

The modeler did not loaded the file or gave me any messages.

1. Open https://demo.bpmn.io/
2. Load some bpmn file
3. Edit the bpmn
4. Try to load the same file used on step 2.

The BpmnModeler should have reopened the file

 - Browser:  Chrome 74
 - OS: Windows 10
 - Library version: 
   - bpmn-js: 3.4.1
   - bpmn-js-bpmnlint: 0.10.1
   - bpmn-js-properties-panel: 0.30.0
   - bpmnlint: 5.0.0
   - bpmnlint-loader: 0.1.3

**Comment by barmac** [comment]
We do not clear the file input when before the dialog opens. This is an easy fix.

**Comment by barmac** [comment]
This should now be working as expected.
