### ISSUE TITLE
Improve Color Palette

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1025]
diagram-js/bpmn-js has quite a wild color palette that doesn't look very pleasant. We should improve it.

Current Color Palette: https://codesandbox.io/s/q8w69my684

---

Related to https://github.com/bpmn-io/diagram-js/pull/349

**Comment by philippfromme** [comment]
Improved Color Palette: https://github.com/bpmn-io/bpmn-js/tree/1025-color-palette

**Comment by nikku** [comment]
Could you add two screen casts that show how the proposed change is an improvement? That would be :rose:.

**Comment by philippfromme** [comment]
Outline and bendpoint/segment draggers:

<img width="563" alt="1" src="https://user-images.githubusercontent.com/7633572/57855388-d1f41e00-77ea-11e9-9121-755bb099d00a.png">

Replace menu:

<img width="512" alt="2" src="https://user-images.githubusercontent.com/7633572/57855414-e33d2a80-77ea-11e9-8bfb-17f8831fb07d.png">

Connecting allowed:

<img width="411" alt="3" src="https://user-images.githubusercontent.com/7633572/57855436-f4863700-77ea-11e9-8472-a8f84c503b85.png">

Connecting disallowed:

<img width="489" alt="4" src="https://user-images.githubusercontent.com/7633572/57855451-049e1680-77eb-11e9-9732-7d5387fc4a20.png">

Moving shapes:

<img width="471" alt="5" src="https://user-images.githubusercontent.com/7633572/57855477-12ec3280-77eb-11e9-8b8f-dc5402d9bddd.png">
