### ISSUE TITLE
Consistently change connection type on re-connect

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1030]
__Is your feature request related to a problem? Please describe.__

When https://github.com/bpmn-io/diagram-js/pull/338 and https://github.com/bpmn-io/bpmn-js/pull/1028 are merged, we will be able to display preview during re-connection. Still, most of the connections from preview are gone after action due to https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/behavior/ReplaceConnectionBehavior.js

__Describe the solution you'd like__

The connection should be converted to the allowed type just like it already happens with Sequence Flows and Message Flows.

__Describe alternatives you've considered__

Disallow re-connection or somehow remove preview if connection might be removed.

__Additional context__

![removal](https://user-images.githubusercontent.com/28307541/57835841-bb849d00-77bf-11e9-8b26-ff749e3ea2d7.gif)

Connection should be converted to data association.

**Comment by nikku** [comment]
Apparently this works for the `4.0.0` release:

![capture H1Wwph_optimized](https://user-images.githubusercontent.com/58601/60743399-b3500f00-9f71-11e9-8784-919ce83de504.gif)
