### ISSUE TITLE
Constant position shifting of subprocess on repeated expand/collapse actions 

### ISSUE THREAD

**Issue by gustavjf** [bpmn-io/bpmn-js#1031]
Currently, expanding a collapsed subprocess with incoming sequence flows shifts the position of the subprocess to the right to [prevent overlap](https://github.com/camunda/camunda-modeler/issues/1244) with previous content.

If we collapse from expanded after this operation, the collapsed subprocess stays in the same position relative to the center of the expanded subprocess.

This means if we expand/collapse/expand/collapse/etc., the position of the element is constantly shifted towards the right.

![bpmn-js#XXX](https://user-images.githubusercontent.com/3981598/57844916-373b1580-77d1-11e9-9e9c-b530b26b2319.gif)

Is there a scenario where we would _not_ want to collapse back to the original position?

![bpmn-js#XXX_02](https://user-images.githubusercontent.com/3981598/57845122-a284e780-77d1-11e9-9ac6-3e701c47a558.gif)

**Comment by nikku** [comment]
The problem goes away once the sub-process is embedded in a BPMN process, right?

**Comment by gustavjf** [comment]
After having a discussion, it may be this issue could be avoided by expanding/collapsing subprocesses in general from/to the left instead of from/to the center, considering diagrams are mostly created from left to right/top to bottom.

This might also result in a simpler solution for overlapping of previous content since we would not have to adjust the position of the subprocess after it has caused an overlap.

**Comment by gustavjf** [comment]
To answer your question @nikku, yes. Position adjustment currently does not occur in the case of outgoing sequence flows.

**Comment by gustavjf** [comment]
I checked if collapsing/expanding a subprocess to/from the left instead of the center would address this and decided it would be better to fix this in the [SubProcessBehavior](https://github.com/bpmn-io/bpmn-js/blob/93a4a579dd5568370f37f0aac1a5da12927c40c5/lib/features/modeling/behavior/SubProcessBehavior.js#L37-L56) module as the changes are straightforward and self-contained.

Otherwise it requires changing general bounds calculations for both [toggling](https://github.com/bpmn-io/bpmn-js/blob/93a4a579dd5568370f37f0aac1a5da12927c40c5/lib/features/modeling/behavior/ToggleElementCollapseBehaviour.js#L100-L135) (in bpmn-js) and [replacing](https://github.com/bpmn-io/diagram-js/blob/487ffd40b984d94e4d886db109a216cfe0442caa/lib/features/replace/Replace.js#L33-L34) (in diagram-js). In diagram-js, we can't assume diagrams are created left-to-right so that change wouldn't be appropriate in my opinion.

Additionally, changing only the expand/collapse bounds calculation would not address the overlap problem described [here](https://github.com/camunda/camunda-modeler/issues/1244) since that is about replace/create, not toggling.

**Comment by nikku** [comment]
Closing this as invalid, as we decided to postpone the actual feature.
