### ISSUE TITLE
I color sequence flows and lose the arrowheads.

### ISSUE THREAD

**Issue by sebwarnke** [bpmn-io/bpmn-js#1037]
__Describe the Bug__

__Steps to Reproduce__

![LoZWp0B18Z](https://user-images.githubusercontent.com/26740468/58023738-dc772600-7b10-11e9-8c32-53cb686b7cd0.gif)

__Expected Behavior__

I expect the arrowhead to stay and take the color.

__Environment__

Please complete the following information:
Camunda Modeler 3.1.0

**Comment by sebwarnke** [comment]
Whoops... Of course this is no bpmn-js issue but a Camunda Modeler one.

**Comment by nikku** [comment]
Downstream issue this one is a duplicate of: https://github.com/camunda/camunda-modeler/issues/1377
