### ISSUE TITLE
Participant resizes when group is moved / resized

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js#1043]
__Describe the Bug__

Whenever a group element is dropped or resized to the border of a participant, it is automatically resized (cf. Screencast)

![May-23-2019 15-14-56](https://user-images.githubusercontent.com/9433996/58255661-ca45f380-7d6d-11e9-807f-8d720f38f28a.gif)

__Steps to Reproduce__

1. Move or Resize a group to the border of a participant
2. The participant is automatically resized

__Expected Behavior__

The participant should not be resized since groups should _always_ be rendered on top. The auto-resizing behavior should _not_ be triggered in this case.

__Environment__

Please complete the following information:

 - Browser: Chrome 74
 - OS: macOS 10-14
 - Library version: current `master`

**Comment by nikku** [comment]
I'd fix it in the following way:

* Always render groups on collaboration level, if possible

Is there a legitimate case for groups in containers, @pinussilvestrus?

**Comment by pinussilvestrus** [comment]
+1 for the rendering on collaboration level

Given the BPMN 2.0 specification:

![image](https://user-images.githubusercontent.com/9433996/58311612-a801b380-7e09-11e9-9363-41423a216028.png)

I could think about having groups in _complex_ processes inside containers, to group certain parts of a participant flow, for example. But just in a _visually_ manner ... however, they should be rendered _on top_ and not inside the context of a container (only visual).

Not quite sure right now whether it is an easy task to do it this way, but I'll have a look.

**Comment by nikku** [comment]
It should be an easy thing to do, as it is a matter of defining the order via the [`BpmnOrderingProvider`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/ordering/BpmnOrderingProvider.js).

**Comment by pinussilvestrus** [comment]
Closed via 46c5a8cb365eef7d8825deb2ab7bae5cc57b5b60
