### ISSUE TITLE
Connection layout preview breaks on bendpoint move

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1048]
__Describe the Bug__

When manually moving a bendpoint the preview shows a direct, non-layouted line instead of the correctly layouted connection shown on bendpoint drop:

 
![bendpoint_layout_preview](https://user-images.githubusercontent.com/58601/58405971-e648de00-8068-11e9-9ee1-bd58eec9389d.gif)

__Steps to Reproduce__

* Create three segment connection
* Move corner bendpoint
* Observe behavior shown in the screen cast

__Expected Behavior__

* Preview is shown as in previous library releases.

__Environment__

Please complete the following information:

 - Browser: Any
 - OS: Any
 - Library version: v3 (master)

**Comment by barmac** [comment]
This is a regression introduced in https://github.com/bpmn-io/diagram-js/commit/581c07829273c9da90dcee5d1c82cd9f95d6229c. Before, connection preview worked fine.

**Comment by nikku** [comment]
Good catch, thanks for investigating.

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1050
