### ISSUE TITLE
Connection layout preview / final miss-match

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1049]
__Describe the Bug__

When reconnecting a sequence flow to a message flow the layout preview does not match the actual layout.

![messageflow_layout_preview](https://user-images.githubusercontent.com/58601/58408701-9f5de700-806e-11e9-94d5-4b5d3386b828.gif)

__Steps to Reproduce__

* open [test diagram](https://github.com/bpmn-io/bpmn-js/files/3222660/diagram.bpmn.txt)
* follow instructions in screen cast shown above

__Expected Behavior__

* [ ] the previewed layout matches the actual layout

__Environment__

Please complete the following information:

 - Browser: Any
 - OS: Any
 - Library version: v3.x (next)

**Comment by barmac** [comment]
This is probably a bug inside https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/behavior/ReplaceConnectionBehavior.js#L94

First we allow to reconnect connection, then it's laid out and after that the type is changed. In the attached example, message flow is first laid out according to the sequence flow's rules.

**Comment by pinussilvestrus** [comment]
Closed via 4c10420017b0142c9923912811d7145338e93046
