### ISSUE TITLE
Group label should be moved after resizing

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js#1051]
__Is your feature request related to a problem? Please describe.__

As a follow-up of https://github.com/bpmn-io/bpmn-js/pull/1040 it reveals that external labels of a `bpmn:Group` element should be moved after certain resize operations, e.g.

![direct-editing](https://user-images.githubusercontent.com/28307541/58335915-f5e6dd80-7e42-11e9-8118-c093a9ef97fe.gif)

__Describe the solution you'd like__

The label should be moved in a reasonable manner.

There are different scenarios where label movement after the resize operation makes sense.

cf. https://github.com/bpmn-io/bpmn-js/issues/1051#issuecomment-496390489

__Describe alternatives you've considered__

Leave it as it is.

__Environment__

 - Browser: Chrome 74
 - OS: macOS 10.14
 - Library version: current `master`

**Comment by pinussilvestrus** [comment]
#### Scenarios

_tba_

**A: When Label is outside of its related Group**

_A.1 Group is resized to the left/right (`y` coordinate is not changing)_: Label should be moved by the `deltaX` of the resize operation 

....

**Comment by pinussilvestrus** [comment]
`hint`: Have a look at [how we doing it with attached elements](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/attach-support/AttachSupport.js#L198).

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/144157f9eb474097c88874d997ba97517b0a1d89.
