### ISSUE TITLE
Disable "drop allowed" overlay when moving label over group

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1054]
__Is your feature request related to a problem? Please describe.__

The overlay/marker displayed on a group when we move a label over the borders hides elements inside.

__Describe the solution you'd like__

The elements should be still visible. I think we should get rid of the overlay completely.

__Describe alternatives you've considered__

Move the overlay to the background (behind elements).

__Additional context__

![gruppe](https://user-images.githubusercontent.com/28307541/58535803-0dc9b300-81ef-11e9-8262-a59d838b573b.gif)

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/0c0932d4c6f54181d7f06a626ef109ae7c00dccb.
