### ISSUE TITLE
Do Not Snap to Grid When Reconnecting Start or End

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1056]
Whenever a connection is laid out it's snapped to the grid.

![29-05-_2019_10-42-42](https://user-images.githubusercontent.com/7633572/58542812-87b56880-81fe-11e9-8607-aecbbe097bb4.gif)

When reconnecting start or end this behavior causes a lot of noise. There should be no snapping in these cases.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1058.
