### ISSUE TITLE
Build breaks on diagram-js connection-preview

### ISSUE THREAD

**Issue by epeschier** [bpmn-io/bpmn-js#1059]
The build does not seem to work anymore.
If you follow the instructions for git clone and run 'npm run all' the following error occurs:
Unable to resolve path to module 'diagram-js/lib/features/connection-preview' in Modeler.js

This folder does not exist in the diagram-js library.

**Comment by pinussilvestrus** [comment]
This is causing by unreleased changes in [`diagram-js`](https://github.com/bpmn-io/diagram-js). Please see our [setup instrucitons](https://github.com/bpmn-io/bpmn-js/blob/master/docs/project/SETUP.md) to link the current, unreleased changes inside dependencies.
