### ISSUE TITLE
Loading .bpmn file - Webpack loader instead of handling strings?

### ISSUE THREAD

**Issue by brucou** [bpmn-io/bpmn-js#1060]
__Is your feature request related to a problem? Please describe.__

I can't call that a problem but I am going to describe a DX feature that seems easy to implement (! I know I know it always seems easy). This refers to loading a xml bpmn string for use with the viewer component.

Currently:

```js
var xml; // my BPMN 2.0 xml
var viewer = new BpmnJS({
  container: 'body'
});

viewer.importXML(xml, function(err) {

  if (err) {
    console.log('error rendering', err);
  } else {
    console.log('rendered');
  }
});
```

I assume `xml` here is a string. I am thinking about a process where the user can work on .bpmn file with the online editor - that means create, load, and save modifications.

Then that would interface with a program which would need to access that modified .bpmn file, ideally without having to copy-paste the string manually into the program. I am not sure if you use wbpack for bundling bpmn. If you do, there is something called a webpack loader which seem to do this naturally. For what I read a webpack loader is just a node.js function which is passed a file as a string parameter, which is exactly what is needed.

__Describe the solution you'd like__

```js
// var xml; // my BPMN 2.0 xml
import xml from "file.bpmn"
var viewer = new BpmnJS({
  container: 'body'
});

viewer.importXML(xml, function(err) {

  if (err) {
    console.log('error rendering', err);
  } else {
    console.log('rendered');
  }
});
```

__Describe alternatives you've considered__

[Webpack loader](https://webpack.js.org/contribute/writing-a-loader/#simple-usage). 

__Additional context__

Trying to use bpmn to animate (debug?) a bpmn process. So I need to load the latest version of a process, then iterate step by step through it according to events.

**Comment by brucou** [comment]
just read this : https://github.com/bpmn-io/bpmn-js/issues/838

Is it still accurate?

**Comment by nikku** [comment]
Essentially, when using bpmn-js you are free to use any module bundler you like. From what I understand, you'd like to inline files contents for a BPMN file such as `foo.bpmn` into your script?

Simply import it:

```js
import diagram from './diagram.bpmn'
```

Then use the raw loader to pack it into your bundle.

How is bundler setup / loaders related to this library?

**Comment by brucou** [comment]
Alright, that was I wanted to know. From the documentation, I was under the impression that the diagram had to be imported as a string. That is why I was recommending adding that detail to the documentation. Those little details help novice users.
