### ISSUE TITLE
Add Icon in Styled Component 

### ISSUE THREAD

**Issue by 1994samaneh** [bpmn-io/bpmn-js#1063]
I do not have access to js file, and I want to add Icon in my project, I used to use:

.something{
     &:after { 
            font-family: "Font Awesome 5 Free";
            font-weight: 900;
            content: "\f007";
     }
  }

Now I am using Styled Component and my icon is not loading with this method.

**Comment by nikku** [comment]
How is styled components related to the bpmn-js library?

**Comment by 1994samaneh** [comment]
This is submitted her by mistake.
