### ISSUE TITLE
Sequence Flow has wrong parent or crashes modeler after replacement

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1072]
__Describe the Bug__

It looks like we do not put the new connection in the appropriate target if we replace a message flow with a sequence flow.

The modeler stops to work when you the previous connection source is a Participant.

__Working Interaction (bpmn-js@3.3.x)__

![old](https://user-images.githubusercontent.com/58601/59101607-cac3ba00-8929-11e9-93bd-487418827d06.gif)

__Broken Interaction (`master` branch)__

![new](https://user-images.githubusercontent.com/58601/59101749-47569880-892a-11e9-99ab-c624f3f09797.gif)

__Steps to Reproduce__

* Open [this test diagram](https://github.com/bpmn-io/bpmn-js/files/3265424/test.bpmn.txt)
* Reconnect message flow start to task end (creating a loop)
* Observe sequence flow not being part of second participant

__Expected Behavior__

* Sequence Flow is part of second participant / process and rendered accordingly

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: `master`

**Comment by barmac** [comment]
Added notice about a crash when the previous source is Participant

**Comment by pinussilvestrus** [comment]
Closed via 9ee90ef0894f6651e535cf144885a98ad479edd0
