### ISSUE TITLE
Text pasted from clipboard is evaluated as HTML

### ISSUE THREAD

**Issue by naoey** [bpmn-io/bpmn-js#1073]
__Describe the Bug__

Pasting HTML text anywhere that allows text input in the modeler evaluates the HTML as is, creating a potential XSS vulnerability.

__Steps to Reproduce__

1. Add any element onto the canvas
2. Begin editing the name of the element
3. Copy and paste the text `<video src=1 onerror=alert('hueh')>`

Observe displayed alert. The issue is reproducible on the demo site.

<img width="1978" alt="image" src="https://user-images.githubusercontent.com/3889501/59183803-60f61b00-8b8a-11e9-94e5-00edff9fb7ff.png">

__Expected Behavior__

HTML clipboard content should not be evaluated.

__Environment__

Please complete the following information:

 - Browser: Firefox 67, Chrome 74
 - OS: macOS 10.14.5
 - Library version: ^2.5.2, ^3.4.1

**Comment by nikku** [comment]
The problem is that we use a content editable for text editing and that we do not properly escape the pasted text.

**Comment by naoey** [comment]
Is there a priority or target that you could say this issue would be resolved in? Mainly to set our expectations about getting a fix in.

**Comment by nikku** [comment]
We are currently looking into the issue and building a fix.

**Comment by nikku** [comment]
Upstream fix, currently in review: https://github.com/bpmn-io/diagram-js-direct-editing/issues/13.

**Comment by nikku** [comment]
Needs backport:

* [ ] 3.x
* [ ] 2.x

**Comment by nikku** [comment]
Released fix as `v2.5.3`, `v3.4.2`.

**Comment by nikku** [comment]
See [security notice](https://bpmn.io/blog/posts/2019-html-injection-vulnerabilities-fixed.html) for further details.
