### ISSUE TITLE
Allow group movement everywhere

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1076]
__Is your feature request related to a problem? Please describe.__

It is quite anoying at the moment to create a new group, as dropping it onto a large number of elements is forbidden (visually and by rules). This is despite the fact that we always drop it onto the root anyway:

![bug](https://user-images.githubusercontent.com/58601/59429928-2cc86780-8de1-11e9-94a9-1133e0bdda73.gif)

__Describe the solution you'd like__

Groups should behave very similar to labels as discussed and implemented in the context of https://github.com/bpmn-io/bpmn-js/issues/1054.

__Describe alternatives you've considered__

None.

**Comment by pinussilvestrus** [comment]
Closed via 055fdf75e1d237d470270f6c10207cfa65800a0c
