### ISSUE TITLE
Attached boundary events should be sticky

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1078]
__Is your feature request related to a problem? Please describe.__

It is quite easy right now to accidentaly detach an attached boundary event:

![bug](https://user-images.githubusercontent.com/58601/59433666-520da380-8dea-11e9-83ad-011874e3de8c.gif)

__Describe the solution you'd like__

Boundary events should be sticky, i.e. snap to the boundary target and keep their attach overlay on move.

__Describe alternatives you've considered__

No valid alternatives.

**Comment by barmac** [comment]
Note for myself:

When dragging (_potential_) Boundary Event, make the hitbox of _potential_ hosts significantly bigger.
