### ISSUE TITLE
Restore center-only snapping for Gateways and Events

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1079]
__Is your feature request related to a problem? Please describe.__

The released version of our toolkit enforces center snapping for gateways and events. That makes a lot of sense, as we should not actively support users in building things like this:

![image](https://user-images.githubusercontent.com/58601/59492507-681e7100-8e89-11e9-887f-57143d42e3c5.png)

__Describe the solution you'd like__

Restore center snapping for Gateways and events.

__Describe alternatives you've considered__

Consider the new user freedom a _feature_.

**Comment by pinussilvestrus** [comment]
We removed the target-center-snapping in [this commit](9a714896d987c4884946c0bf4e2f03edaa5fe574). I'd also go for restoring it for events and gateways.

**Comment by pinussilvestrus** [comment]
Close via cfad2f49aa8d25d0a46ec4270a1a566f3de1a974
