### ISSUE TITLE
Docking Snapping gone

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1081]
__Describe the Bug__

In `v3.x` we snapped connected elements on their docking points:

![snap-docking-works](https://user-images.githubusercontent.com/58601/59529953-a72ce080-8ee2-11e9-9a46-6fb9ef981724.gif)

This no longer works in `v4-beta`:

![snap-docking-no-works](https://user-images.githubusercontent.com/58601/59529974-b449cf80-8ee2-11e9-88c4-2c52f0c0f122.gif)

__Steps to Reproduce__

* Open [test diagram](https://github.com/bpmn-io/bpmn-js/files/3291778/snap.bpmn.txt)
* Move event
* __Observe target snapping gone__

Can be reproduced on demo, too.

__Expected Behavior__

`v3.x` behavior is restored.

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: 4.0.0-beta.1

**Comment by philippfromme** [comment]
Shit. I messed this up.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1083.
