### ISSUE TITLE
Unexpected connection alignment when moving center-connected elements

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js#1087]
__Describe the Bug__

When moving centered-connected elements the connection aligns in a wrong manner (it is not centered any more):

![Jun-18-2019 11-27-47](https://user-images.githubusercontent.com/9433996/59670764-bea6ea80-91bc-11e9-9b6d-68a73d0938d9.gif)

This might relates to #1086 + #1079.  

__Steps to Reproduce__

1. Create a centered connection between to elements
2. Move one element
3. Connection is not centered anymore

__Expected Behavior__

After moving, the connection should stay centered between the two elements.

__Environment__

Please complete the following information:

 - Browser: Chrome 75
 - OS: macOS 10.14
 - Library version: v4.0.0-beta.2

**Comment by pinussilvestrus** [comment]
This does not occur when the connection was created via auto-place:

![Jun-18-2019 11-50-14](https://user-images.githubusercontent.com/9433996/59672241-632a2c00-91bf-11e9-8bd4-4a3e12f58b66.gif)

**Comment by pinussilvestrus** [comment]
Might be fixed by https://github.com/bpmn-io/bpmn-js/pull/1092, but let's investigate how this can even happen (root-cause-analysis).

**Comment by pinussilvestrus** [comment]
__Root cause analysis__ 

- [`BpmnLayouter#layoutConnection`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/BpmnLayouter.js#L40) sets wrong waypoint position, due to wrong `hints.connectionEnd` property
- [`MoveHelper#moveClosure`](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/modeling/cmd/helper/MoveHelper.js#L85) sets `hints.connectionEnd` via [`AnchorsHelper#getMovedTargetAnchor`](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/modeling/cmd/helper/AnchorsHelper.js#L15) via [`AttachUtil#getNewAttachPoint` ](https://github.com/bpmn-io/diagram-js/blob/master/lib/util/AttachUtil.js#L20)
- `AttachUtil#getNewAttachPoint` calculates wrong delta from original waypoint to old center
-  should be centered (like it is visually), like `delta = { x: 0, y: 0 }`, but it has little offset, which leads to the misleading movement of the ending waypoint in the end

__Conclusion__

The problem is caused by the original connection. The ending waypoint is not centered correctly after the original connection (as described above).

Since we are going to snap the ending waypoint with #1090 this will also fix the current issue. `aec3765` also offers a test case to ensure the waypoint is snapped correctly to the target mid. I added another test case to ensure the connection stays centered after moving the target (cf. 7200231)

**Comment by nikku** [comment]
Should we fix the `AttachUtil#getNewAttachPoint` miss-calculation seperately?

**Comment by nikku** [comment]
Or is this not an actual bug?

**Comment by pinussilvestrus** [comment]
No, it's not. Since `AttachUtil#getNewAttachPoint` calculates it correctly for the given original waypoint. The failure lays by the `original` property of the waypoint. Snapping it to the center in #1092 sets it correctly.

**Comment by pinussilvestrus** [comment]
I double checked it and can't reproduce it anymore on current `master`. Let's close it.
