### ISSUE TITLE
Viewer: applying zoom fails in custom named div 

### ISSUE THREAD

**Issue by mpgalaxy** [bpmn-io/bpmn-js#1089]
__Describe the Bug__

**Viewer:** If I give the div for the viewer to be rendered in another ID than 'canvas', the .zoom('fit-viewport') isn't being applied. The **diagram zoom fails / is way too high** and you can't see the entire diagram. If I change the ID and references back to 'canvas', everything works fine.
This bug is annoying, because I'm trying to render two instances of the viewer for diff viewing, which can't be done with correct zoom due to this bug.

This bug is browser independent, same behaviour on chromium, firefox, opera and chrome.

__Steps to Reproduce__

1. Take your example code [https://rawgit.com/bpmn-io/bpmn-js-examples/master/starter/viewer.html](https://rawgit.com/bpmn-io/bpmn-js-examples/master/starter/viewer.html) and save it to local html file.
2. change all appearences of container reference 'canvas' to 'canvasa':
`<div id="canvasa"></div>`
`      var bpmnViewer = new BpmnJS({
        container: '#canvasa'
      });`
`var canvas = bpmnViewer.get('canvasa');`
3. Reload the page
4. Alternative: Test change of div references to 'canvasa' on [https://jsfiddle.net/07envcu1/](https://jsfiddle.net/07envcu1/)

__Expected Behavior__

The viewer is being rendered with correct zoom into the custom named div.

__Environment__

Please complete the following information:

 - Browser: Chromium Version 75.0.3770.90
 - OS: Arch Linux
 - Library version: 3.4.3 / your version used in test page

**Comment by nikku** [comment]
Thanks for filing this pull request.

`#canvas` (DOM element with the ID `canvas`) and the [Canvas service](https://github.com/bpmn-io/diagram-js/blob/master/lib/core/Canvas.js) are two entirely different things.

For each viewer, you may retrieve the `canvas` service via `viewerInstance.get('canvas')`.
