### ISSUE TITLE
After deployment

### ISSUE THREAD

**Issue by trinadhkk** [bpmn-io/bpmn-js#1100]
canvas is not shown tools are also not shown but there are no errors

**Comment by trinadhkk** [comment]
in angular 8 after deploying into server toolkit is not displaying

**Comment by pinussilvestrus** [comment]
Can you please share your setup or your project which you refer to? It's hard to help you without any additional information.

**Comment by pinussilvestrus** [comment]
I'll close this one since no new information came in.

@trinadhkk feel free to re-open if you can share additional information.
