### ISSUE TITLE
Disable TLBR snapping for non-container elements

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1104]
__Is your feature request related to a problem? Please describe.__

The latest release (`v4`) introduces snapping on all sides, including top, bottom, left and right.
This results in a lot of snapping noise when moving normal flow elements.

Under the assumption that plain flow elements are usually center aligned we could consider removing that feature for these elements.

__Describe the solution you'd like__

Snap non-container nodes, excluding text annotations only using their mid.

__Describe alternatives you've considered__

See the noise as a feature (I guess?).

__Additional context__

See the attached screencast for a demonstration of this issue:

![bug](https://user-images.githubusercontent.com/58601/60098594-31ccd580-9756-11e9-8285-04727ce296af.gif)

**Comment by nikku** [comment]
Can we look into this one and see if it would result in a better user experience?

We can always add additional snap points, too if we receive the relevant feedback to do so.

**Comment by nikku** [comment]
I'll have a lookie lookie :eyes:

**Comment by barmac** [comment]
I think the solution you proposed makes a lot of sense. It feels more natural to align to the center of another shape, but never to any of the bounds.

![kap](https://user-images.githubusercontent.com/28307541/60249588-6dd27880-98c5-11e9-9b03-52a1421042e8.gif)

**Comment by nikku** [comment]
I'm struggeling and juggeling with writing test cases for this one in bpmn-js. :rescue_worker_helmet:

**Comment by nikku** [comment]
![out qy2aF](https://user-images.githubusercontent.com/58601/60250756-8479cf00-98c7-11e9-9ac4-91c8284472ea.gif)

Feels way better now and moves the responsibility for special snapping to bpmn-js (and friends).

**Comment by nikku** [comment]
Ready for review via https://github.com/bpmn-io/diagram-js/pull/376 and https://github.com/bpmn-io/bpmn-js/pull/1108. Please check it out. For me it feels like another substantial UX improvement.

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1108
