### ISSUE TITLE
Space Tool Can Leave Elements Outside Of Participant

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1115]
__Describe the Bug__

Elements can be left outside of participant if spacetool is activated after them and dragged behind them.

__Steps to Reproduce__

![participant-resize](https://user-images.githubusercontent.com/28307541/60345672-d1d66900-99b9-11e9-8b71-930c63daea34.gif)

__Expected Behavior__

Participant does not shrink further than to the children.

__Environment__

 - Browser: Chrome 75
 - OS: MacOS
 - Library version: <3 as well as 4

**Comment by pinussilvestrus** [comment]
Sends it to Backlog this it's not a regression of `bpmn-js@4-beta.x`.

**Comment by philippfromme** [comment]
Fixed via https://github.com/bpmn-io/diagram-js/pull/364
