### ISSUE TITLE
import XML，occur  a error，why ??

### ISSUE THREAD

**Issue by hnliji1107** [bpmn-io/bpmn-js#1117]
![image](https://user-images.githubusercontent.com/3294058/60433246-ed01dc80-9c36-11e9-85e4-11f50a54a05a.png)

![image](https://user-images.githubusercontent.com/3294058/60433491-88934d00-9c37-11e9-92e7-ed37925be79a.png)

import XML，occur  a  error，why ??

**Comment by pinussilvestrus** [comment]
Hi @hnliji1107 

Can you maybe post your diagram in a form we can directly copy it? This way we would be able to reproduce the error.

**Comment by hnliji1107** [comment]
ok，my diagram：
```
<?xml version="1.0" encoding="UTF-8"?>
<definitions
  xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:smart="http://smart.alibaba-inc.com/schema/process"
  id="111"
  targetNamespace="smart"
  version="11">
  <process id="Process_1" name="好的" isExecutable="false">
    <startEvent id="StartEvent_1" name="二蛋">
      <extensionElements>
        <smart:properties>
          <smart:value name="111" value="2222" />
          <smart:value name="333" value="444" />
        </smart:properties>
      </extensionElements>
    </startEvent>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="80" y="240" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="87" y="276" width="22" height="13" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
```

**Comment by pinussilvestrus** [comment]
I tried out your diagram on [http://demo.bpmn.io](http://demo.bpmn.io) and it reveals your definition has a malformed id. With the newest release, we don't allow ids with only numbers: cf. https://github.com/bpmn-io/moddle-xml/commit/3bb3e0288591027d71f4e5318da0d26264ded4d4

Editing to something like `id="a1"` will work. 

Feel free to re-open the issue if you get stuck again. Also use [our forum](demo.bpmn.io) for questions, GitHub issues is more for bug reports and feature requests
