### ISSUE TITLE
Markers are not displayed on Safari at demo.bpmn.io

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1120]
__Describe the Bug__

<img width="377" alt="Screenshot 2019-07-03 at 10 52 42" src="https://user-images.githubusercontent.com/28307541/60578074-de274100-9d80-11e9-9649-54cc0d7e489b.png">

__Steps to Reproduce__

1. Open https://demo.bpmn.io/new with Safari

Note: I tried to reproduce it with bpmn-js-examples/modeler and bpmn-js-examples/viewer, but on both it worked as expected.

__Expected Behavior__

Markers are displayed.

__Environment__

Please complete the following information:

 - Browser: Safari 12.1.1 (14607.2.6.1.1)
 - OS: MacOS
 - Library version: `4.0.0-beta.11`

**Comment by barmac** [comment]
What is more, it works fine when running dev mode in `bpmn-js`.

<img width="617" alt="Screenshot 2019-07-03 at 10 59 28" src="https://user-images.githubusercontent.com/28307541/60578568-b4224e80-9d81-11e9-8665-19c7aa3e34ee.png">

**Comment by pinussilvestrus** [comment]
Relates to https://github.com/bpmn-io/bpmn-io-demo/issues/82 (internally).

**Comment by barmac** [comment]
It works now with Safari 13.1. @pinussilvestrus can you confirm it?

**Comment by pinussilvestrus** [comment]
LGTM

![image](https://user-images.githubusercontent.com/9433996/87425328-bac2e300-c5dd-11ea-8c37-72fcfe5d90f8.png)

**Comment by barmac** [comment]
Let's close it then.
