### ISSUE TITLE
Broken connection layout when reconnecting to create a loop

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1121]
__Describe the Bug__

This applies only to connections with more than 2 waypoints. When reconnecting start/end to form a loop, the connection is laid out incorrectly. It applies to both old and current bpmn-js versions, although the way the connection is laid out is different.

`bpmn-js@<=3`

![layout-1](https://user-images.githubusercontent.com/28307541/60582557-5b56b400-9d89-11e9-8d78-984d2662761c.gif)

`bpmn-js@4.0.0-beta.11`

![layout-2](https://user-images.githubusercontent.com/28307541/60582558-5bef4a80-9d89-11e9-8bcd-b867e425ccb8.gif)

__Steps to Reproduce__

1. Create two flow nodes connected with a complex connection
2. Reconnect start/end to form a loop

__Expected Behavior__

Layout as if the loop were created from scratch.

__Environment__

Please complete the following information:

 - Browser: Camunda Modeler
 - OS: MacOS
 - Library version: applies to bpmn-js used in Camunda Modeler 2.2.4, 3.1.1 and `bpmn-js@4.0.0-beta.11`

**Comment by pinussilvestrus** [comment]
Closed via 6aaf816802c9513f629c33ef46f82898f80db999
