### ISSUE TITLE
Sequence Flow still editable after collapsing Sub Process 

### ISSUE THREAD

**Issue by mschoe** [bpmn-io/bpmn-js#1122]
// given
![caw_subProcess_expanded](https://user-images.githubusercontent.com/2777965/59999277-df11f180-9661-11e9-8d17-eeae0aab4200.png)

A new element has been dropped on the first sequence flow in the sub process

![caw_subProcess_selected_flow](https://user-images.githubusercontent.com/2777965/59999183-aa059f00-9661-11e9-80b4-25c651ec3cd1.png)

// when
I collapse the sub process

// then
the first sequence flow is still selected and editable

![caw_subProcess_collapsed_selected_flow](https://user-images.githubusercontent.com/2777965/59999369-154f7100-9662-11e9-9f6e-67b90414c114.png)

// hint
issue appears in cawemo and https://demo.bpmn.io/s/start not in the modeler

**Comment by nikku** [comment]
Not reproducible with `bpmn-js@6.3.0`.
