### ISSUE TITLE
Element not placed after drag and drop

### ISSUE THREAD

**Issue by mschoe** [bpmn-io/bpmn-js#1123]
__Description__

When I model quickly it sporadically happens that the modeling operation cannot be completed. This is annoying, because I have to repeat the operation in slow motion, hoping it works then.
 
__Reproduce (only sometimes)__

* I place a new element by drag and drop from the modelling palette 
* Then the element is not placed on the diagram canvas

Cf. the following screen cast that captured the behavior:

![drag_drop](https://user-images.githubusercontent.com/2777965/60591288-7384fe00-9d9e-11e9-9de2-b107a334f7fa.gif)

__Expected Behavior__

* Modeling works consistently without rejecting the operation.

__Hints__

* This appears in the [Camunda Modeler](https://github.com/camunda/camunda-modeler) quite often and is also reproducible on [demo.bpmn.io](https://demo.bpmn.io/). It is way harder to reproduce on the demo though.
* It seems to happen when the drag and drop movement is to fast. When I repeat the same move, but slower, it works fine.

__Environment__

* bpmn-js `v4.0.0.beta8`

**Comment by philippfromme** [comment]
Hint: We might be able to still check on `mousemove` if dragging is active and if buttons are pressed https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons

**Comment by nikku** [comment]
Let's assume this issue got fixed via https://github.com/bpmn-io/diagram-js/pull/391 and reopen it as needed.
