### ISSUE TITLE
How to remove elements on palette and contextpad without changing node module？

### ISSUE THREAD

**Issue by kaiyingzhang** [bpmn-io/bpmn-js#1125]
I know there's a way to remove the elements/actions from the node module part in ContextPadProvider.js and PaletteProvider.js. But is there a way to replace it in our own code without changing it in module?

I know for the example you provide [customize-element](https://github.com/bpmn-io/bpmn-js-example-custom-controls) is to add customize element, is there a similar way to hide some?

Thanks!
![Screen Shot 2019-07-10 at 3 15 02 PM](https://user-images.githubusercontent.com/22136189/61008819-84e18380-a325-11e9-96b2-674af3f82c28.png)

**Comment by nikku** [comment]
You'd override the default [`paletteProvider`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/palette/PaletteProvider.js) with your own version.

This way you have full control over which elements to provide.

```js
import YourPaletteProvider from './YourPaletteProvider';

// your module
export default {
  'paletteProvider': [ 'type', YourPaletteProvider ]
}
```

Extension modules are able to override services defined by the base toolkit. Given the above example, the base provider won't be used anymore but your provider will be used instead.

**Comment by debojyotichatterjee9** [comment]
@nikku Thanks a lot I was looking for a solution half my day.... Cheers!!!
