### ISSUE TITLE
Bpmn not loaded in Angular 8+

### ISSUE THREAD

**Issue by MuthiahMazzle** [bpmn-io/bpmn-js#1126]
I have added bpmn modeler into angular 8+ application but the modeler and xml was not loaded,please advise me

![bpmnissue](https://user-images.githubusercontent.com/49274570/61211664-cefba800-a71d-11e9-94fb-996546d50e34.PNG)

**Comment by nikku** [comment]
Please ask questions [in our forum](https://forum.bpmn.io/). Please provide the necessary details regarding your setup and steps that allow us to reproduce your issue. Otherwise you won't get the answers you desire.
