### ISSUE TITLE
Debugger giving synax error while i am getting output

### ISSUE THREAD

**Issue by PrateekNaik9** [bpmn-io/bpmn-js#1128]

**Comment by PrateekNaik9** [comment]
I was trying to run bpmn-js on my local machine and wanted to debug to find the flow of the project. But debugger is giving syntax error even when i am getting he results in localhost.

I m getting the error as unexpected identifier on line 'Import diagram from 'diagram-js' '

**Comment by nikku** [comment]
Two things to note:

* bpmn-js is a front-end library that requires the browser to run
* bpmn-js requires a modern JavaScript bundler that understands ES modules

As a result it cannot be debugged (i.e. using `ndb`) like a plain node library.

**Comment by PrateekNaik9** [comment]
Is there any other way to figure out the flow of the program and its call back function

**Comment by nikku** [comment]
Yes.

```
git clone bpmn-js
cd bpmn-js
npm run dev
```

Open `http://localhost:9876/debug.html` in your browser.
