### ISSUE TITLE
Element Behind Parent

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1129]
Unfortunately the fix I provided in https://github.com/bpmn-io/diagram-js/pull/381 results in a bug.

![fail](https://user-images.githubusercontent.com/7633572/61293470-075dbd80-a7d4-11e9-8273-e31cfecfb897.gif)

Instead of not updating when there are less than two children the prepending should be executed in a save way.

**Comment by nikku** [comment]
Good catch. Do you look into this issue?

**Comment by philippfromme** [comment]
I fucked up, I'll fix it. 👍

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/diagram-js/issues/385.
