### ISSUE TITLE
Correctly set label bounds and .djs-hit

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#113]
The labels  .djs-hit element that is added by interaction events and ensures the user can select labels is not properly updated after label set.

This makes labels unselectable after they have been updated.

Must be fixed in InteractionEvents, possibly updating on `shape.changed`.

Must update label di accordingly, too.

**Comment by pedesen** [comment]
Fixed with https://github.com/bpmn-io/diagram-js/commit/509ca23a33b9b74b177216a0b45abae36ffb9fab
