### ISSUE TITLE
Text input cursor is not center aligned in Firefox

### ISSUE THREAD

**Issue by volkergersabeck** [bpmn-io/bpmn-js#1136]
__Describe the Bug__

When editing a label of a new task, the text input cursor is not positioned in the center of the task.

![Screen Shot 2019-07-30 at 14 04 09](https://user-images.githubusercontent.com/232571/62129052-08174900-b2d6-11e9-896c-2313589dd3b3.png)

__Steps to Reproduce__

Open demo.bpmn.io in Firefox (MacOS, not tested on Windows or Linux though)
Add a new task
Edit the task label
The cursor is positioned in the lower left corner of the text input field

__Expected Behavior__

The text cursor is shown where the label will be positioned, in the center of the task

__Environment__

Firefox 67 on Max OS 10.13

Does not happen on Chrome

**Comment by nikku** [comment]
This is a minor visual flaw that goes away once the user starts to type.

Let's check whether this is an easy pick (if so, fix it) or move it to the backlog otherwise.

**Comment by nikku** [comment]
Closing this, as we won't work on this issue unless we receive an external contribution.
