### ISSUE TITLE
Could I hide the right bottom  bpmn logo,the copyright of license is expired

### ISSUE THREAD

**Issue by RichieChoo** [bpmn-io/bpmn-js#1140]
![image](https://user-images.githubusercontent.com/17178139/62270706-3a0ce480-b469-11e9-81e8-ce28c4b52edf.png)

**Comment by nikku** [comment]
You cannot hide the logo. Cf. [up to date license](https://github.com/bpmn-io/bpmn-js/blob/develop/LICENSE).

**Comment by nikku** [comment]
Updated on the website.
