### ISSUE TITLE
Consistently Mark Elements as Expanded

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1142]
Sub processes are marked as expanded through setting `isExpanded` of their DI. Participants do not have this property, instead they are [considered expanded when they have a `processRef`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/util/DiUtil.js#L11).

**Comment by pinussilvestrus** [comment]
The BPMN specification permits participants to have a `isExpanded` flag (page 373)

![image](https://user-images.githubusercontent.com/9433996/62443424-1e505980-b75b-11e9-8be5-e76acfded7f0.png)

So what would you think would be a consistent solution instead of using the flag?

**Comment by philippfromme** [comment]
You mean it does __not__ permit participants to have that flag?

I think my assumption that you can treat both sub-processes and participants the same is probably wrong. In the case of sub-processes, it's merely a visual property, the sub-process and its children are not affected. In the case of participants, a participant does either have a process reference or it doesn't which changes the semantic of the participant (no process reference means its collapsed and can't have children).

I'll close this ticket since it probably doesn't make sense.
