### ISSUE TITLE
Dropping element on palette or tooltip blows up editor

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1144]
__Describe the Bug__

Whenever I drop an element on the palette _or_ the _cannot create flow element on collaboration_ tooltip the editor blows up:

![capture yGQ26s_optimized](https://user-images.githubusercontent.com/58601/62462993-27581f80-b789-11e9-8fe0-8196f5dbb748.gif)

The following stack trace manifests the error: 

```
EventBus.js:375 TypeError: Cannot read property 'push' of undefined
    at BpmnUpdater.updateSemanticParent (BpmnUpdater.js:607)
    at BpmnUpdater.updateParent (BpmnUpdater.js:349)
    at updateParent (BpmnUpdater.js:71)
    at eval (BpmnUpdater.js:721)
    at invokeFunction (EventBus.js:507)
    at EventBus._invokeListener (EventBus.js:360)
    at EventBus._invokeListeners (EventBus.js:346)
    at EventBus.fire (EventBus.js:308)
    at CommandStack._fire (CommandStack.js:346)
    at eval (CommandStack.js:410)
```

__Steps to Reproduce__

* Create collaboration with participant
* Drop task on root to see tooltip
* Drop element on tooltip

__Alternative Steps to Reproduce__

![capture 7UYbVI_optimized](https://user-images.githubusercontent.com/58601/62463124-7f8f2180-b789-11e9-93e1-f74c72d833c9.gif)

* Pick up element from the palette
* Drop on palette border (narrow path)

__Expected Behavior__

* Dropping elements outside the canvas (i.e. on overlays, the palette _or_ tooltips) is rejected

__Environment__

 - Browser: Chrome 73
 - OS: Arch Linux
 - Library version: v4.0.3

**Comment by pinussilvestrus** [comment]
Interesting finding: The second scenario only happens inside collaboration diagrams. Otherwise, no error is been thrown. Sometimes the element is added to the canvas, sometimes it just disappears.

![Aug-06-2019 09-06-03](https://user-images.githubusercontent.com/9433996/62518288-83728080-b829-11e9-83b0-d672cb15c546.gif)

However, it s_houldn't_ be allowed to do that stuff either.

**Comment by philippfromme** [comment]
Will be fixed by https://github.com/bpmn-io/diagram-js/pull/399.
