### ISSUE TITLE
Missing palette translation in 4.0.4 version

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/bpmn-js#1146]
'create.group' action is not translatable in 'bpmn-js/lib/features/palette/PaletteProvider.js':

![Screenshot 2019-08-06 at 18 15 10](https://user-images.githubusercontent.com/3993987/62556907-29e47300-b876-11e9-8895-c8214f2694e6.png)

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/issues/1149.
