### ISSUE TITLE
Release bpmn-js@5

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1148]
* [x] Check pending releases in utility libraries @barmac 
  * [x] moddle
  * [x] moddle-xml
  * [x] bpmn-moddle
  * [x] diagram-js-direct-editing `-> add diagram-js@5 to peerDependency range`
  * [x] diagram-js-origin `-> add diagram-js@5 to peerDependency range`
  * [x] bpmn-js-cli `-> add bpmn-js@5 to peerDependency range`
* [x] Release the bpmn-io projects in order
  * [x] diagram-js -> `diagram-js@5`
  * [x] bpmn-js -> `diagram-js@5`
* [x] Integration test via `bpmn-js-integration` packaging (_AUTOMATED_)
  * [ ] upgrade dependencies (_AUTOMATED_)
* [x] Update the examples `bpmn-js-examples` (_AUTOMATED_)
  * [ ] bump used `bpmn-js` version (_AUTOMATED_)
  * [ ] perform clean/install and test
  * [ ] release
* [x] Release `bpmn-io-demo`
  * [x] integration test `bpmn-js` against app
  * [x] release app
* [x] Write [blog post](https://github.com/bpmn-io/bpmn.io/tree/master/src/blog) (https://github.com/bpmn-io/bpmn-js/issues/1147) @pinussilvestrus 
* [x] Spread the word

**Comment by nikku** [comment]
We've cut the following pre-releases already:

* `diagram-js@5.0.0-beta.1`
* `bpmn-js@5.0.0-beta.1`

**Comment by barmac** [comment]
We can perform the tests on [Camunda Modeler Nightly](https://camunda.org/release/camunda-modeler/nightly/)

**Comment by barmac** [comment]
[Camunda Modeler 3.3.0-alpha.2](https://camunda.org/release/camunda-modeler/3.3.0-alpha.2/) is the current alpha with the release.
