### ISSUE TITLE
After pasting, all pasted elements should be selected

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1152]
__Describe the Bug__

The old (< 5) behavior of the library was that all elements that got pasted are selected afterwards. This is a standard behavior seen in all sorts of applications.

The new behavior is that the first element created is being selected. As a side-effect, direct editing gets enabled when it should not:

![capture dmRJ2s_optimized](https://user-images.githubusercontent.com/58601/62680843-7f289d80-b9b8-11e9-8012-d88dc69ea71f.gif)

__Steps to Reproduce__

* Create two tasks
* Select both
* Copy + Paste them
* See how only first element is selected, direct editing activates for it

__Expected Behavior__

* [ ] all pasted elements are selected

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: v5.0.0-beta.0

**Comment by philippfromme** [comment]
Needs fix in [SelectionBehavior](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/selection/SelectionBehavior.js#L14). 🛠

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/issues/1152.
