### ISSUE TITLE
Labels of Boundary Events Not Copied

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1153]
Due to the [implementation of the `element.copy` rule](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/rules/BpmnRules.js#L902) labels of boundary events are not allowed to be copied.

**Comment by nikku** [comment]
:tada:

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1155
