### ISSUE TITLE
Allow Copying Boundary Events

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1154]
Since detaching of boundary events is now possible it should be possible to copy boundary events. This is only prevented by the [`element.copy` rule](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/rules/BpmnRules.js#L902).

When disabling this rule:

![foobar](https://user-images.githubusercontent.com/7633572/62688525-552ba700-b9c9-11e9-80db-6eff81de0a60.gif)

**Comment by nikku** [comment]
Works? :octopus:

**Comment by nikku** [comment]
Makes a lot of sense, thanks for reporting :+1:

**Comment by philippfromme** [comment]
> Works? 🐙

Yeah, it works.

**Comment by oguzeroglu** [comment]
Realised `[this behaviour](https://github.com/bpmn-io/bpmn-js/issues/1190)` while working on this issue.
