### ISSUE TITLE
Copying / replacing elements generates unnecessary IDs

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1162]
__Describe the Bug__

After copying / replacing elements I see unnecessary IDs in the copied results.

__Steps to Reproduce__

* Open [`before.bpmn.txt`](https://github.com/bpmn-io/bpmn-js/files/3491416/copy-before.bpmn.txt)
* Replace boundary event with non-interruping version
* See `id` attribute attached to `escalationEventDefinition` (cf. [`after.bpmn.txt`](https://github.com/bpmn-io/bpmn-js/files/3491444/copy-after.bpmn.txt)

__Expected Behavior__

* [ ] No ID is generated, if it is not required

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: `v3, v4, v5.0.0-beta.2`

**Comment by pinussilvestrus** [comment]
This is actually no regression, also visible in older versions. I checked it with

* camunda-modeler@3.1.0 (bpmn-js@3)
* camunda-modeler@3.2.0 (bpmn-js@4)

**Comment by nikku** [comment]
Thanks for investigating.
