### ISSUE TITLE
App Freezes on copy/paste event based gateway

### ISSUE THREAD

**Issue by akifhazarvi** [bpmn-io/bpmn-js#1163]
__Describe the Bug__
 when I'm trying to copy the event-based gateway which has some other events attached to it and try to paste it. Application freezes and have to kill/Restart to make it work.

__Steps to Reproduce__

1. Make an event based gateway
2. Attache some message events to it.
2. Copy the whole diagram.
3. Paste it and application will be frooze.

__Expected Behavior__

Copy/paste of diagram should work as expected and shouldn't freeze the application.

__Environment__

 - Browser: [Chrome 76.0.3809.100]
 - OS: [Mac OS 10.14.6]
 - Library version: [5.0.0-BETA.2]

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1166.
