### ISSUE TITLE
After pasting task direct editing is enabled

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js#1164]
__Describe the Bug__

After pasting certain elements, with a task on _first_ position, direct editing is activated for the task element.

![Kapture 2019-08-12 at 11 54 12](https://user-images.githubusercontent.com/9433996/62857445-eebfc500-bcf7-11e9-9aad-239c93734e32.gif)

https://github.com/bpmn-io/bpmn-js/issues/1152 aimed to solve this by selecting all elements after pasting, but it's still present. The bug is not appearing if a non-task element is in the first position.

__Steps to Reproduce__

1. Copy a bunch of elements with a task in the first position
2. Paste --> direct editing is activated for the task in first position

__Expected Behavior__

Direct editing is not activated at all.

__Environment__

 - Browser: Chrome 76
 - OS: MacOS 10.14
 - Library version: 5.0.0-beta.2

**Comment by nikku** [comment]
This should have been fixed via https://github.com/bpmn-io/bpmn-js/issues/1152.

But never mind, was not part of the issue description :wink:.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1168
