### ISSUE TITLE
Confusing snap lines shown on multi-element create

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1165]
__Describe the Bug__

![capture f7P4xG_optimized](https://user-images.githubusercontent.com/58601/62857974-5c202580-bcf9-11e9-98f4-5563a721ead0.gif)

It seems like we add some virtual snap lines that should not be added in the first place.

__Steps to Reproduce__

* Copy a number of elements (cf. [sample diagram](https://github.com/bpmn-io/bpmn-js/files/3492173/phantom-snaplines.bpmn.txt))
* Paste and move preview to the top left
* See phantom snap lines appearing

__Expected Behavior__

* [ ] No phantom snap lines appear

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: `v5.0.0-beta.2`

**Comment by barmac** [comment]
The snap lines are displayed also during the single-element create.

![snap](https://user-images.githubusercontent.com/28307541/62922862-ba5a1080-bdac-11e9-878d-034d77a8f653.gif)

**Comment by barmac** [comment]
Note: This seems to be a problem within `diagram-js`.

**Comment by barmac** [comment]
This is about snapping to the origin of the diagram 😱 
<img width="1680" alt="Screenshot 2019-08-13 at 13 39 19" src="https://user-images.githubusercontent.com/28307541/62938696-d15e2a00-bdcf-11e9-9980-5e3c7269ea7e.png">

**Comment by barmac** [comment]
Got it. I'll prepare a PR in a while.
