### ISSUE TITLE
After copy and paste elements can have fractional coordinates

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1167]
__Describe the Bug__

Copy and paste of un-snapped diagrams may lead to fractional element positions:

![capture be3HDu_optimized](https://user-images.githubusercontent.com/58601/62863969-b8d80c00-bd0a-11e9-954c-5c21840a961d.gif)

__Steps to Reproduce__

* Open [test diagram](https://github.com/bpmn-io/bpmn-js/files/3492228/fractional.bpmn.txt)
* Copy all elements
* Paste to preview
* Snap elements to phantom snap lines (top-left of source)
* Drop
* __See elements having `.5` coordinates in BPMN DI__

__Expected Behavior__

* [ ] We round coordinates and prevent fractional positioning

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: `v5.0.0-beta.2`

**Comment by pinussilvestrus** [comment]
Could be fixed by removing the unnecessary snap lines, cf. https://github.com/bpmn-io/bpmn-js/issues/1165

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/diagram-js/pull/395.
