### ISSUE TITLE
How can I call zoom-in, zoom-out and reset in my code?

### ISSUE THREAD

**Issue by bungder** [bpmn-io/bpmn-js#1176]
In online demo(https://demo.bpmn.io/new), there is some buttons that could zoom-in, zoom-out and resset canvas components:

![image](https://user-images.githubusercontent.com/3251115/63439030-e7b75600-c45f-11e9-9a26-cd0b15add9e2.png)

But those do not occur in this demo: https://github.com/bpmn-io/bpmn-js-examples/blob/master/modeler/README.md

I am wondering how could I do that in my project.

I am using bpmn-js like this:

```js
import BpmnModeler from 'bpmn-js/lib/Modeler'
// some code...
this.modeler = new BpmnModeler({
  container: '#js-canvas',
  propertiesPanel: {
	parent: '#js-properties-panel'
  },
  additionalModules: [
	cPaletteProvider,
	propertiesPanelModule,
	propertiesProviderModule
  ],
  moddleExtensions: {
	magic: magicModdleDescriptor,
	camunda: camundaModdleDescriptor
  },
  common: {
	keyboard: {
	  bindTo: document
	}
  }
})
```

I am using:

- nodejs: v10.15.2
- "bpmn-js": "^5.0.0",
- "bpmn-js-properties-panel": "^0.32.0",
- "camunda-bpmn-moddle": "^4.0.1",
- "diagram-js": "^5.0.0"

**Comment by philippfromme** [comment]
For questions please head over to our [forum](https://forum.bpmn.io/).
