### ISSUE TITLE
Message flow line from or to events impossible

### ISSUE THREAD

**Issue by sunsided** [bpmn-io/bpmn-js#1180]
__Describe the Bug__

When trying to connect an action to a message receive event, or connect a message throw to a message catch intermediate event, the line is currently either incorrectly disallowed (first scenario) or solid (second scenario).

However both actions that send a message as a byproduct or send intermediate events yield a message that's passed to the according message receive start event, catch intermediate event, or message receiving action. As a result, the line between those should be dashed with a closed arrow head.

Right now a workaround is to introduce a dummy artifact, however this draws a data association
rather than a message flow line, which makes it technically incorrect.

__Steps to Reproduce__

1. Create action
2. Create message receive start event
3. Try to connect action and start event - this fails

![send-action-to-start](https://user-images.githubusercontent.com/495335/64126722-2c6fb500-cdaf-11e9-8d4f-74e617a83720.gif)

or

1. Create action
2. Create message catch intermediate
3. Connect action to intermediate event - this creates the wrong link

![send-action-to-intermediate](https://user-images.githubusercontent.com/495335/64126764-56c17280-cdaf-11e9-952c-04ade8df3431.gif)

or

1. Create message throw intermediate event
2. Create message catch intermediate event or an message receive start event
3. Connect both events - this creates the wrong link

![message-send-to-receive](https://user-images.githubusercontent.com/495335/64126776-63de6180-cdaf-11e9-9a33-ab749d1d9d5c.gif)

__Expected Behavior__

In the first scenario, the line between the action and the event should be dashed with a closed arrow (message flow).

In the second scenario, the line should _optionally_ be a message flow line for the intermediate events, and _always_ be message flow for the start event.

Here's an internet example screenshot showcasing an intermediate-to-start message flow:

![other](https://user-images.githubusercontent.com/495335/64126891-cfc0ca00-cdaf-11e9-88b8-3bdd4a924fae.png)

Here's an internet example for an action-to-start and an end-to-action message flow:

![camunda](https://user-images.githubusercontent.com/495335/64126905-dc452280-cdaf-11e9-8984-9638cc3cd0d3.png)

__Environment__

 - Browser: Chrome 76.0.3809.100 
 - OS: Ubuntu Linux 18.04
 - Library version: bpmn.io, "bpmn-io-demo - bpmn - Thu, 29 Aug 2019 13:23:23 GMT"

**Comment by nikku** [comment]
Thanks for reporting this issue. Could you back up your steps to reproduce with actual images? You can screenshot what you got and paste it into the issue description _or_ use a screen recorder to create an animated gif. This helps us what you're trying to do.

**Comment by sunsided** [comment]
Absolutely! Updated with gifs and two examples quasi-randomly sampled from the internet.

**Comment by pinussilvestrus** [comment]
There exists a difference between your gifs and the examples you attached.  In your scenarios you modeled _one_ pool with two lanes. Inside a pool it is permitted to have message flows (dashed connections). On top, there can't be an incoming connection to a start event, that's why it is not allowed to create the connection in the first scenario.

The examples include _two_ pools. Between pools there exist message flow.

Reference: [BPMN 2.0 Specification](https://www.omg.org/spec/BPMN/2.0/About-BPMN/)

**Comment by nikku** [comment]
As mentioned by @pinussilvestrus this is a misunderstanding on your side.

As mandated by the BPMN specification message flows can only be drawn across pool / participant boundaries. This is, of course, supported by our tools:

![capture 2uo82x_optimized](https://user-images.githubusercontent.com/58601/64153919-1ce48080-ce30-11e9-8c06-691c15951bf2.gif)

**Comment by sunsided** [comment]
Ah, right! It was this one that was confusing me, but I just realized that this is actually by design.

![Screenshot from 2019-09-03 09-47-20](https://user-images.githubusercontent.com/495335/64154182-92e8e780-ce30-11e9-834c-1d9219822f28.png)

Thanks for clarifying and sorry for the interruption!
