### ISSUE TITLE
"Timer Intermediate Catch Event" removes "default" attribute from exclusive gateways

### ISSUE THREAD

**Issue by ssoorriiin** [bpmn-io/bpmn-js#1197]
__Describe the Bug__

Having an exclusive gateway with 2 output sequence flows, one of them set as _Default Flow_. Adding a _Timer Intermediate Catch Event_ to the non Default Flow, removes the _default_ attribute on gateway and keeps the default flow rendered.

This is happening with other types of catch events too. Haven't verified them all.

__Steps to Reproduce__

See attached GIF.
![Default sequence flow issue](https://user-images.githubusercontent.com/8074799/65500496-0f1e9a00-dec8-11e9-889c-bff0582f1c6f.gif)

__Expected Behavior__

Don't remove the _default_ attribute on gateway.

__Environment__

 - Browser: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
 - Library version: 5.0.4 and before

**Comment by pinussilvestrus** [comment]
I was also able to reproduce it with the `bpmn-js` version used in Camunda Modeler@2.2.4. So this is an old issue.

**Comment by oguzeroglu** [comment]
Closed via #1198
