### ISSUE TITLE
"Timer Intermediate Catch Event" removes "conditionExpression" from sequence flows

### ISSUE THREAD

**Issue by ssoorriiin** [bpmn-io/bpmn-js#1199]
__Describe the Bug__

Drop an intermediate event on a sequence flow that has a condition type of expression (with a value set). Changing event into a "Timer Intermediate Catch Event" removes expression from sequence flow.

Similar to [#1197 ](url).

__Steps to Reproduce__

See attached GIF.
![expression removed](https://user-images.githubusercontent.com/8074799/65552698-bc77c900-df2d-11e9-9327-c9e8ed50a64d.gif)

__Expected Behavior__

Don't remove expression from sequence flow.

__Environment__

 - Browser: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
 - Library version: 5.0.4

**Comment by oguzeroglu** [comment]
Closed via #1200
