### ISSUE TITLE
Intermediate Events with labels cannot be pasted as Boundary Events

### ISSUE THREAD

**Issue by oguzeroglu** [bpmn-io/bpmn-js#1204]
__Describe the Bug__

If an intermediate event has a label, it cannot be pasted as a boundary event. See the GIF:
![bug](https://user-images.githubusercontent.com/15003836/65763643-28bc1d80-e124-11e9-8fca-38248ed2fad6.gif)

__Steps to Reproduce__

1. Create an intermediate event with label
2. Copy the event
3. Try to paste it over a Task, as a boundary event.

__Expected Behavior__

Intermediate Event can be pasted as Boundary Event

__Environment__

 - OS: Mac OS Mojave 10.14.5
 - Library version: v5.0.5

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1208

**Comment by philippfromme** [comment]
Will be properly fixed through https://github.com/bpmn-io/bpmn-js/pull/1203
