### ISSUE TITLE
Custom fill and stroke colors lead to exception when moving multiple elements via drag

### ISSUE THREAD

**Issue by FlexiGit** [bpmn-io/bpmn-js#1209]
__Describe the Bug__

This is a follow up of #981.

When using the described custom colors the preview feature while moving multiple elements doesn't work and result in uncaught exceptions in the console.

__Steps to Reproduce__

https://jsfiddle.net/hayrcs57/

1. Mark multiple elements via lasso tool
2. Move elements via drag

__Expected Behavior__

Preview is visible and no exceptions in console.

__Environment__

 - Browser: Chrome 76
 - OS: Windows 10
 - Library version: bpmn-js 5.0.4, diagram-js 5.0.2

__Some background info__
With the described colors the markers (sequence flow end, etc.) get ids like this `sequenceflow-end-_rgba_32_31_30_1_-_rgba_255_255_255_0.95_-cl97j5dip3upxkha4o3poek3n`.
When this id is used in `diagram-js/lib/features/preview-support/PreviewSupport.js.PreviewSupport._cloneMarkers` it will be passed to `Element.querySelector`. There the `.95_...` part is interpreted as a class selector, which is invalid because class selectors must start with a letter. This results in following exception `Failed to execute 'querySelector' on 'Element': 'marker#sequenceflow-end-_rgba_32_31_30_1_-_rgba_255_255_255_0.95_-cl97j5dip3upxkha4o3poek3n' is not a valid selector.`.

**Comment by philippfromme** [comment]
Good catch, thanks for reporting.
