### ISSUE TITLE
Boundary Event Can Be Modeled Inside a Task

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1213]
__Describe the Bug__

![snapping](https://user-images.githubusercontent.com/28307541/66296496-f82b6f00-e8ed-11e9-8278-bf7363e29188.gif)

__Steps to Reproduce__

1. Have a Timer Event with a label
2. Drag it but not from the center
3. Attach in the wrong position

__Expected Behavior__

Snapped to the boundary.

__Environment__

 - Browser: Chrome
 - OS: MacOS
 - Library version: `develop` at https://github.com/bpmn-io/bpmn-js/commit/33f9e3e395cd9ce9c975da9c024587d903319791; couldn't reproduce it on demo

**Comment by barmac** [comment]
I can't reproduce it anymore with `diagram-js#develop` linked .

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1203
