### ISSUE TITLE
I hope all the pictures can be displayed.

### ISSUE THREAD

**Issue by xhuihui** [bpmn-io/bpmn-js#1222]
I integrated the project into React

```
// import BpmnViewer from 'bpmn-js/lib/Viewer';
import BpmnViewer from 'bpmn-js/lib/NavigatedViewer';

...
const container = this.containerRef.current;   
       
        // create modeler
        this.bpmnModeler = new BpmnViewer({
            container: container,
          
        });
      bpmnModeler.importXML(xml)
            
```

I hope

![image](https://user-images.githubusercontent.com/3157194/66740115-e6753900-eea4-11e9-8a32-4ec598eefa00.png)

Real situation

![image](https://user-images.githubusercontent.com/3157194/66740215-2c320180-eea5-11e9-9a5c-0e3300bb2d28.png)

What should I do?

**Comment by pinussilvestrus** [comment]
You can use 

```js

const canvas = this.bpmnModeler.get("canvas");

canvas.zoom("fit-viewport");
```

Generally speaking, I'd recommend to not model like this, but having left-to-right and top-to-bottom diagrams.

I'll close this since no bug report or feature request is described. In the future, please use our [forum](https://forum.bpmn.io) to ask questions like this.

**Comment by xhuihui** [comment]
> 您可以使用
> 
> ```js
> const  canvas  =  this。bpmnModeler。得到（“画布”）；帆布。zoom（“ fit-viewport ”）;
> ```
> 
> 一般来说，我建议不要建模，而要使用从左到右和从上到下的图表。
> 
> 由于没有描述错误报告或功能请求，因此我将关闭它。将来，请使用我们的[论坛](https://forum.bpmn.io)来问这样的问题。

感谢，这个并没有解决我的问题，不过我暂时规避了这个现象

`
canvas.zoom('0.5');
`

**Comment by xhuihui** [comment]
> 您可以使用
> 
> ```js
> const  canvas  =  this。bpmnModeler。得到（“画布”）；帆布。zoom（“ fit-viewport ”）;
> ```
> 
> 一般来说，我建议不要建模，而要使用从左到右和从上到下的图表。
> 
> 由于没有描述错误报告或功能请求，因此我将关闭它。将来，请使用我们的[论坛](https://forum.bpmn.io)来问这样的问题。



> You can use
> 
> ```js
> const canvas = this.bpmnModeler.get("canvas");
> 
> canvas.zoom("fit-viewport");
> ```
> 
> Generally speaking, I'd recommend to not model like this, but having left-to-right and top-to-bottom diagrams.
> 
> I'll close this since no bug report or feature request is described. In the future, please use our [forum](https://forum.bpmn.io) to ask questions like this.

Thank you, this did not solve my problem, but I temporarily avoided this phenomenon.

`canvas.zoom('0.7');`

**Comment by xhuihui** [comment]
> You can use
> 
> ```js
> const canvas = this.bpmnModeler.get("canvas");
> 
> canvas.zoom("fit-viewport");
> ```
> 
> Generally speaking, I'd recommend to not model like this, but having left-to-right and top-to-bottom diagrams.
> 
> I'll close this since no bug report or feature request is described. In the future, please use our [forum](https://forum.bpmn.io) to ask questions like this.


Thank you, this did not solve my problem, but I temporarily avoided this phenomenon.

`canvas.zoom('0.7');`
