### ISSUE TITLE
Modeler crashes when context pad entry of non-existing element is clicked

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1225]
__Describe the Bug__

![edge_case](https://user-images.githubusercontent.com/28307541/66917363-89e95980-f01d-11e9-9549-79755e2374c0.gif)

__Steps to Reproduce__

1. Create and select an element.
2. Copy the element and start pasting operation.
3. Undo.
4. Try to click the remaining context pad.

__Expected Behavior__

Context pad should be closed.

__Environment__

 - Browser: Chrome 77
 - OS: MacOS
 - Library version: 5.1.0

**Comment by pinussilvestrus** [comment]
For me, it's only reproducible if I don't start moving the pasting element. So this seems to be a regression of this fixed bug: https://github.com/camunda/camunda-modeler/issues/1467

**Comment by pinussilvestrus** [comment]
Fixed upstream by https://github.com/bpmn-io/diagram-js/commit/401412d8054bec277de54662663b0388f7a73365
