### ISSUE TITLE
Ad Hoc Collapsed Subprocess gets weird dimensions

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1231]
__Describe the Bug__

![ad-hoc](https://user-images.githubusercontent.com/28307541/68217768-78bfb700-ffe3-11e9-9281-080ad0fc2b05.gif)

__Steps to Reproduce__

1. Create an expanded Sub Process with a child element inside
2. Collapse the Sub Process
3. Turn the Sub Process into an Ad Hoc Sub Process

__Expected Behavior__

Dimensions don't change.

__Environment__

 - Browser: Chrome 78
 - OS: MacOS 10.14
 - Library version: `demo.bpmn.io`

**Comment by barmac** [comment]
This will be probably _resolved_ as soon as we disallow collapsing non-empty Sub Process.

**Comment by nikku** [comment]
This will not be resolved by disallowing collapsing via a plug-in, as it requires the plug-in to be fixed then.

:speak_no_evil:

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/dd3a139a29905e3363c869cedf945063d6bbdc26
