### ISSUE TITLE
When remove child lane in diagram, other related lane and diagram deformed

### ISSUE THREAD

**Issue by Varooneh** [bpmn-io/bpmn-js#1253]
__Describe the Bug__
If you create bpmn model in new version at [bpmn online demo](http://demo.bpmn.io/new) and need to create multiple child lanes in a parent lane, when remove any child from parent, diagram deformed and sometimes you can not continue edit diagram.

__Steps to Reproduce__
1. I created a diagram in demo.bpmn.io like this :
    ![before_remove](https://user-images.githubusercontent.com/16257304/70031577-c61e4c80-15c0-11ea-8d4f-7f7cf4bfe39d.png)

2. And need to remove a child lane, when remove child, diagram deformed, like this:
    ![after_remove](https://user-images.githubusercontent.com/16257304/70031638-f0700a00-15c0-11ea-8259-a3f0f8c68fd0.png)

__Environment__

 - Browser: [e.g. Chrome (latest version)]
 - OS: [Windows 10]
 - Library version: `v5.x`, `v6.x`

Works in `v3.0.1` and `v4.0.1`.

**Comment by nikku** [comment]
What is the last version of bpmn-js that worked here?

**Comment by Varooneh** [comment]
> What is the last version of bpmn-js that worked here?

Yes

**Comment by nikku** [comment]
> Yes

I expected something linke "`v3.5.0` is the last version that properly handles lanes".

**Comment by Varooneh** [comment]
@nikku 
I used bpmn version 3.0.4, in this version I've not any problem, also I draw diagram in demo.bpmn.io and see this problem.

**Comment by pinussilvestrus** [comment]
The last version which worked is `v4.0.4`, beginning with `v5.x` the bug occurs.

**Comment by nikku** [comment]
Thanks for verifying this @pinussilvestrus.

**Comment by nikku** [comment]
I've updated the issue description accordingly.

**Comment by nikku** [comment]
This is tightly related to https://github.com/bpmn-io/bpmn-js/issues/1254, let me elaborate:

Due to a bug introduced with bpmn-js@5 nested lanes are not properly serialized to the BPMN 2.0 anymore. In fact, they are always serialized as a direct child of the participant/pool root.

As a result, our layout algorithm fails.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/issues/1256.
