### ISSUE TITLE
When I create child lane, I've not childLaneSet in xml export (in new version also in online demo)

### ISSUE THREAD

**Issue by Varooneh** [bpmn-io/bpmn-js#1254]
__Describe the Bug__
In bpmn-js version 3.* when I create child lane in a lane, exported XML has ```bpmn2:childLaneSet``` XML node and define child lanes in this node.
In new version (also online demo), when I create child lane, in exported XML I've not ```bpmn2:childLaneSet``` .

__Steps to Reproduce__
1- I create a bpmn diagram in old version (3.*)
![old_version](https://user-images.githubusercontent.com/16257304/70035530-3f6d6d80-15c8-11ea-8741-bb525f38b1d7.png)

And in exported XML I've like this:
```
<bpmn2:laneSet id="LaneSet_0dz1dwx">
      <bpmn2:lane id="Lane_1amw7ib">        
        <bpmn2:flowNodeRef>StartEvent_1</bpmn2:flowNodeRef>
  </bpmn2:lane>
  <bpmn2:lane id="Lane_0ccivr4">        
    <bpmn2:childLaneSet id="LaneSet_1pbfwpy">
      <bpmn2:lane id="Lane_0imicyw" />
      <bpmn2:lane id="Lane_01xan8i">            
        <bpmn2:childLaneSet id="LaneSet_0p041z7">
          <bpmn2:lane id="Lane_00syf83" />
          <bpmn2:lane id="Lane_1xnempi" />
        </bpmn2:childLaneSet>
      </bpmn2:lane>
    </bpmn2:childLaneSet>
  </bpmn2:lane>
</bpmn2:laneSet>
```

2- And again, I create above diagram in new version on [online demo](http://demo.bpmn.io/new) and when export as xml, I've this:

```
<bpmn:laneSet id="LaneSet_0nj9tm1">
  <bpmn:lane id="Lane_126mif5" />
  <bpmn:lane id="Lane_16t32x1" />
  <bpmn:lane id="Lane_0i7203j" />
  <bpmn:lane id="Lane_1rwva4y" />
</bpmn:laneSet>
```

__Environment__

 - Browser: [Chrome (latest version)]
 - OS: [Windows 10]
 - Library version: [3.*, 5,*]

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/issues/1256.
