### ISSUE TITLE
Unable to render a Bpmn Diagram in jsdom for testing with Jest

### ISSUE THREAD

**Issue by ealexhaywood** [bpmn-io/bpmn-js#1258]
__Describe the Bug__

I'm unable to render an instance of the Modeler or the Viewer in jsdom for testing.  I am using bpmn-js in the context of React.

I get the error
```
TypeError: this.getDefaultLayer(...).getBBox is not a function
  at Canvas.getBBox (/diagram-js/lib/core/Canvas.js:791)
  at Minimap.viewbox (/diagram-js-minimap/lib/Minimap.js:417A)
  at _update (/diagram-js-minimap/lib/Minimap.js:335)
  ...
```
I did some inspecting and `this.getDefaultLayer()` in Canvas is outputting an `SVGElement` but not a graphical one.

Since the error seemed unique to the minimap module,  I tried disabling it in my component and re-rendering, but got another error when importing XML:

```
TypeError: node.createSVGTransform is not a function
  at createSVGTransform (/tiny-svg/dist/index.cjs.js:584)
  at translate (/diagram-js/lib/util/SvgTransformUtil.js:34)
  at GraphicsFactory.Object.<anonymous>.GraphicsFactory.update
  at Canvas.update [as _addElement] (/diagram-js/lib/core/Canvas.js:553)
```
Soo I'm not sure what's going on.  Any thoughts to why this is happening or tips to resolve the problem?
  
__Steps to Reproduce__

1. Create a react component and initialize a modeler
```
import React from 'react';
import Modeler from 'bpmn-js/lib/Modeler';
import MinimapModule from 'diagram-js-minimap';
import { someBpmnXml } from './bpmn-samples';

export default class BpmnDiagram extends React.Component {
  constructor(props) {
    super(props);
    this.containerRef = React.createRef();
  }

  componentDidMount() {
    this.modeler = new Modeler({ container: this.containerRef.current, keyboard: { bindTo: window }, additionalModules: [ MinimapModule ] });
    this.modeler.importXML(someBpmnXml);
  }

  render() {
    return (
      <div ref={this.containerRef} />
    );
  }
}
```
2. Try to render it into jsdom
```
import React from 'react';
import BpmnDiagram from './BpmnDiagram';
import { render } from '@testing-library/react';

describe('BpmnDiagram', () => {
  test('it renders', () => {
    render(<BpmnDiagram />);
  });
});
```

__Expected Behavior__

It renders without errors in Jest/jsdom.

__Environment__

 - Browser: N/A
 - OS: N/A
 - bpmn-js: 3.5.0
 - bpmn-moddle: 5.1.6
 - diagram-js: 3.3.1
 - diagram-js-direct-editing: 1.6.0
 - diagram-js-minimap: 1.3.0
 - moddle: 4.1.0
 - moddle-xml: 7.4.1
 - jest: 24.7.1
 - jest-environment-jsdom-fifteen: 1.0.0

Running Node.js version 10.15.2

**Comment by nikku** [comment]
This libary uses SVG under the hood. JSDom does not support SVG as far as I understand. 

You may run your tests in a browser setup ([Karma](https://karma-runner.github.io/) can be your friend) or you mock bpmn-js in your test cases using JSDom or bundler facilities.

**Comment by ealexhaywood** [comment]
Makes sense, thanks for the quick response!

**Comment by issaouedraogo** [comment]
Hey sorry, Hopping I am late in this, I am having the same issue, would someone mind giving me some pointers on how mock this library?

**Comment by ealexhaywood** [comment]
Hey there, "mock" may not be the right word, but we used https://github.com/puppeteer/puppeteer to test click/drag/keyboard behavior in our BPMN rendered content
