### ISSUE TITLE
Drop on flow removes outgoing sequence flow unnecessarily

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1263]
__Describe the Bug__

When dropping a gateway with an outgoing flow onto an existing sequence flow the outgoing flow is removed:

![capture zUyTve_optimized](https://user-images.githubusercontent.com/58601/72102123-861c5900-3326-11ea-99f4-b61cde3c29bc.gif)

__Steps to Reproduce__

* Open [test diagram](https://github.com/bpmn-io/bpmn-js/files/4042343/test.bpmn.txt)
* Drop gateway `A` onto sequence flow `S`
* See that flow outgoing from gateway is being removed

__Expected Behavior__

* Outgoing sequence flow from gateway is being kept

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: v6.2.1

**Comment by DeepakImaginate** [comment]
How to reopen flow diagarma?
