### ISSUE TITLE
ERROR Error: unknown type <camunda:Properties> Angular

### ISSUE THREAD

**Issue by sinanasiriamirbande** [bpmn-io/bpmn-js#1264]
when i click to on startevent bpmn properties panel  to add forms or listeners
i got this error 
ERROR Error: unknown type <camunda:Properties>
    at un.mapTypes (bpmn-modeler.production.min.js:1672)
    at un.getEffectiveDescriptor (bpmn-modeler.production.min.js:1676)
    at yi.fn.getType (bpmn-modeler.production.min.js:1703)
    at yi.fn.create (bpmn-modeler.production.min.js:1698)
    at Gu.create (bpmn-modeler.production.min.js:11736)
    at Object.push../node_modules/bpmn-js-properties-panel/lib/helper/ElementHelper.js.ElementHelper.createElement (ElementHelper.js:19)
    at addElement (Properties.js:123)
    at Object.set (TableEntryFactory.js:205)
    at PropertiesPanel.push../node_modules/bpmn-js-properties-panel/lib/PropertiesPanel.js.PropertiesPanel.applyChanges (PropertiesPanel.js:714)
    at HTMLDivElement.onClick (PropertiesPanel.js:581)

my code : 
`
import {
  AfterContentInit, Component,ElementRef,EventEmitter,Input, OnDestroy,OnInit,Output,ViewChild,
} from '@angular/core';

import {HttpClient, HttpErrorResponse, HttpHeaders} from '@angular/common/http';
import * as BpmnJS from 'bpmn-js/dist/bpmn-modeler.production.min.js';
import * as BpmnPropertyPanel from 'bpmn-js-properties-panel';
import * as BpmnComunda from 'bpmn-js-properties-panel/lib/provider/camunda';
import * as ComundaModel from 'camunda-bpmn-moddle/resources/camunda.json';
import {BpmnObject, FormService} from '../services/form.service';
import {LocalStorageService, LocalStorageValues} from '../services/local-storage.service';
import {ChangeableService} from '../services/changeable.service';
import {FormContainer, FormPropEnum, ServiceTools} from '../models/models';
import {BpmnService} from '../services/bpmn.service';
import {MatDialog} from '@angular/material/dialog';
import {BpmnNameInputComponent} from '../components/ui/bpmn-name-input/bpmn-name-input.component';
import {MatSnackBar} from '@angular/material/snack-bar';
import {ActivatedRoute, Router} from '@angular/router';
import {PermittedUserComponent} from '../components/ui/permitted-user/permitted-user.component';
import {importDiagram} from './rx';
import {throwError} from 'rxjs';
import {catchError} from 'rxjs/operators';
import {BpmnActionTypes} from '../components/shared/bpmn-actions/bpmn-actions.component';

 initializeBpmn() {
    this.bpmnJS = new BpmnJS({
      bpmnRenderer: {
        defaultFillColor: '#ececec',
        defaultStrokeColor: '#333'
      },
      keyboard: {
        bindTo: document
      },
      propertiesPanel: {
        parent: '#properties'
      },
      additionalModules: [
        BpmnPropertyPanel,
        BpmnComunda
      ],
      moddleExtensions: {
        camunda: ComundaModel
      }
    });
    this.bpmnJS.on('import.done', ({error}) => {
      if (!error) {
        this.bpmnJS.get('canvas').zoom('fit-viewport');
      }
    });
  }

`

**Comment by nikku** [comment]
Please use our existing bug report template.

Please make your issue reproducible in a [Codesandbox](https://codesandbox.io/).

**Comment by sinanasiriamirbande** [comment]
https://forum.bpmn.io/t/error-error-unknown-type-camunda-properties-angular/4302

**Comment by philippfromme** [comment]
This is not a bug but an issue with your setup. Opening two issues in addition to a [forum topic](https://forum.bpmn.io/t/error-error-unknown-type-camunda-properties-angular/4302/2) isn't necessary. Please head over to the forum for help with your setup.
