### ISSUE TITLE
I can add markers for sequence flows

### ISSUE THREAD

**Issue by saig0** [bpmn-io/bpmn-js#1268]
__Is your feature request related to a problem? Please describe.__

Using bpmn-js, I need to mark elements on the diagram. The use case is to show runtime/history information, for example, the elements and flows that are taken by a workflow instance.

I can mark elements using `canvas.addMarker(elementId, 'my-marker')` but I'm not able to mark sequence flows in the same way.

__Describe the solution you'd like__

I can add/remove markers for sequence flows in a similar way as other elements.

`canvas.addMarker(sequenceFlowId, 'my-marker')` 

__Describe alternatives you've considered__

The current workaround is to modify the DI object of the sequence flow and update the connection via graphics factory.

__Additional context__

![image](https://user-images.githubusercontent.com/4305769/72518476-bcd9fe00-3855-11ea-83e1-8dc0af5a2ec1.png)

**Comment by nikku** [comment]
`Canvas#addMarker` adds a CSS class to the respective element.

That works perfectly fine, cf. [this example](https://codesandbox.io/s/bpmn-js-connection-markers-test-bjggf).

Do you expect anything beyond that functionality?

**Comment by saig0** [comment]
Thank you for your fast and helpful response :+1:  
You're right. It works. The failure was in my CSS.
