### ISSUE TITLE
Copy-pasting collapsed subprocess does not past child elements correctly 

### ISSUE THREAD

**Issue by yT0n1** [bpmn-io/bpmn-js#1270]
__Copying and pasting collapsed subprocess does not paste task inside subprocess__

When copy-pasting a collapsed subprocess that contains a task, the task is pasted on top of the collapsed subprocess. However, this appears to be just a visual problem. When downloading and reimporting the .bpmn file everything is fine.

![BrokenCopy](https://user-images.githubusercontent.com/4279289/73074614-52ab0400-3eba-11ea-80a9-ef2e0d33b1b5.gif)

__Steps to Reproduce__

1. Create expanded subprocess and add at least one child task
2. Collapse the subprocess
3. Copy the sub process
4. Paste the sub process.

__Expected Behavior__

The child task should be visually hidden. 

__Environment__

 - Browser: [e.g. Firefox Developer Edition]
 - OS: [ Mac OS X ]
 - Library version: [v6.2.0]

**Comment by yT0n1** [comment]
As far as I can see, the problem appears to be that the shape.hidden property is not copied.

**Comment by nikku** [comment]
Thanks for your report and thanks for conducting further investigation.

The place in the source code where this one is missing is probably [`CopyPaste` in diagram-js](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/copy-paste/CopyPaste.js).

Would you like to contribute a PR?

**Comment by yT0n1** [comment]
I will give it a try.
