### ISSUE TITLE
CSP header prevent inlined ressources to be loaded

### ISSUE THREAD

**Issue by makidelille** [bpmn-io/bpmn-js#1273]
__Describe the Bug__

If the web server serving the files has  strong security policies, inlined ressources won't be loaded.
I followed the recommandenation on https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src

__Steps to Reproduce__

1. set up your webserver with the header : `Content-Security-Policy: img-src 'self';`
2. open your web browser. logo wont show

__Environment__

 - Browser: Chrome 79
 - OS: Win 10
 - Library version:  3.4.1

**Comment by nikku** [comment]
Why would you configure that in the first place?
