### ISSUE TITLE
Events are not triggered on elements inside group for Viewer and NavigatedViewer

### ISSUE THREAD

**Issue by OmranAbazid** [bpmn-io/bpmn-js#1278]
__Describe the Bug__

For the Viewer and the NavigtatedView, bpmnjs events(e.g hover, click) do not fire on elements inside of a group 
For the modeler, it works fine.

__Steps to Reproduce__

1. Load into a NavigatedViewer a BPMN diagram that has a group element and some flow nodes inside
2. attached a click or hover to the viewer instance that console logs the element name
3. click or hover over the elements inside the group
4. clicking on elements inside the groups logs only the group name

[Please see the example here](https://codesandbox.io/s/pensive-cartwright-ifyxg)

__Expected Behavior__
The event triggers on the child element of the group exactly like the modeler

__Environment__

 - Browser: Chrome 80
 - OS: MacOS high sierra
 - Library version: 6.1.2

**Comment by pinussilvestrus** [comment]
Thanks for reporting!

Seems like the `pointer-events: stroke` property is not properly set on groups inside the Viewer

**Comment by nikku** [comment]
Addressed via https://github.com/bpmn-io/bpmn-js/pull/1279.
