### ISSUE TITLE
nodes changes their position when loading them in the view

### ISSUE THREAD

**Issue by rabeashi** [bpmn-io/bpmn-js#1280]
Hi
We have BPMN JS version: 3.4.3
We use bpmn-js as visualization library.
We want to support creating layers inside bpmn tree.
when click on layer's root we want to display all of children nodes in the view and hide the main tree.
we have notice that when changing nodes position is some layer this can affect positions of another nodes.
this behavior we have saw occasionally
do you have any idea why this happen ?

Thanks in advance

**Comment by nikku** [comment]
Please use our [existing issue templates](https://github.com/bpmn-io/bpmn-js/issues/new/choose) or we cannot help you.
