### ISSUE TITLE
Diagram doesn't render correctly with Angular 9

### ISSUE THREAD

**Issue by maratkalibek** [bpmn-io/bpmn-js#1282]
__Describe the Bug__

![image](https://user-images.githubusercontent.com/4571314/74603838-0d0ce000-50e2-11ea-808c-6713be0d1705.png)

__Steps to Reproduce__

1. Start new project with Angular 9
2. Introduce bpmn-js to project
3. After start, select any of the connection lines

Here is github repo - https://github.com/maratkalibek/bpmn-js-angular9

__Expected Behavior__

![image](https://user-images.githubusercontent.com/4571314/74603889-86a4ce00-50e2-11ea-932a-1a6d858d6ab5.png)

__Environment__

 - Browser: Chromium 80.0.3987.87 (Official Build)
 - OS: Ubuntu Linux
 - Library version: bpmn-js 6.3.0

**Comment by nikku** [comment]
You are missing the required stylesheets, cf. [example](https://github.com/bpmn-io/bpmn-js-examples/blob/master/starter/modeler.html#L8).
