### ISSUE TITLE
Component name generation does not match component type

### ISSUE THREAD

**Issue by AndyBan** [bpmn-io/bpmn-js#1285]
__Describe the Bug__

Components are generated with a type_random id however some components do not have the correct type.

__Steps to Reproduce__

I tested adding elements by clicking the menu then the canvas to add them and get an incorrect prefix for the following items:

    <bpmn:dataObjectReference id="Flow_03tcnqb" dataObjectRef="Flow_0ud25nw" />
    <bpmn:dataObject id="Flow_0ud25nw" />
    <bpmn:dataStoreReference id="Flow_0tlyjqx" />

All the other types look to be ok. Tested demo.bpmn.io:

__Expected Behavior__

Name prefix should match component type. 

__Environment__

 - Latest Chrome

**Comment by nikku** [comment]
Thanks for your report. I can reproduce the issue.
