### ISSUE TITLE
Adding lane does not re-connect message flows

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1289]
__Describe the Bug__

When adding a lane _above_ or _below_, connected message flows are not re-connected:

![capture AjhP9h_optimized](https://user-images.githubusercontent.com/58601/76213687-81333300-620b-11ea-9633-56f3ab7103bf.gif)

__Steps to Reproduce__

* Open [test diagram](https://github.com/bpmn-io/bpmn-js/files/4306597/collaboration-message-flows.bpmn.txt)
* Add lane below upper participant
* __Observe message flow not re-connecting__

__Expected Behavior__

Message flow re-connects.

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: v6.3.1

**Comment by wojtask9** [comment]
This is not only problem with message flows.
See below.

![add_lane_bpmn](https://user-images.githubusercontent.com/6099236/76221770-da09c800-6219-11ea-82f3-255e94e2035f.gif)


BTW. This is regression. It works fine in 5.1.2

**Comment by nikku** [comment]
Your issue is fixed via https://github.com/bpmn-io/bpmn-js/pull/1287.

**Comment by barmac** [comment]
![ezgif-7-891051affaf5](https://user-images.githubusercontent.com/28307541/77528588-82f92980-6e8e-11ea-906b-a924d523cdb1.gif)

This is actually a general problem with the space tool.

**Comment by barmac** [comment]
![space-tool](https://user-images.githubusercontent.com/28307541/77628473-63263c00-6f48-11ea-9c45-281692847307.gif)

Yet another example of how space tool may fail in case of moving only one of two interconnected elements.

**Comment by nikku** [comment]
Is this one fixed via https://github.com/bpmn-io/bpmn-js/pull/1298?

**Comment by barmac** [comment]
More like `fixed upstream`

**Comment by barmac** [comment]
When [this](https://github.com/bpmn-io/diagram-js/pull/454) I will have a PR with diagram-js update which will allow us to close this issue.
