### ISSUE TITLE
Link Events are missing the `name` attribute

### ISSUE THREAD

**Issue by RomanJRW** [bpmn-io/bpmn-js#1296]
__Describe the Bug__

When Link events (either catch or throw) are added to a model, they do not get given a default `name` attribute. I believe that this is a required attribute according to specification, so the resulting model is not considered valid. To demonstrate the failed validation, if I try to deploy a diagram containing link events that haven't been explicitly given a name from the Camunda Modeler, I get the following error:

```
Deploy error: {"deploymentName":"diagram_5","message":"ENGINE-09005 Could not parse BPMN process. Errors: \n* cvc-complex-type.4: Attribute 'name' must appear on element 'bpmn:linkEventDefinition'. | resource diagram_5.bpmn | line 13 | column 35\n* cvc-complex-type.4: Attribute 'name' must appear on element 'bpmn:linkEventDefinition'. | resource diagram_5.bpmn | line 18 | column 35","status":400,"statusText":"Bad Request","url":"http://localhost:8080/engine-rest/deployment/create"} [ deploy-error ]
```
I originally found this in Optimize where we are also getting the same validation error, but it's easier to reproduce in Camunda Modeler.

__Steps to Reproduce__

1. Create a model containing either or both of link throw intermediate event and link catch intermediate event. Do not set the name property manually.
2. Validate process model, for example when deploying in Camunda Modeler

__Expected Behavior__

I'm not totally sure what the preferred behaviour would be. One option would be for a default value to be assigned to the `name` attribute, perhaps using the id of the intermediate event that it is part of. Although this wouldn't necessarily be useful until overridden, it would at least still not leave models in a potentially invalid state.

__Environment__

 - Browser: Chrome 80.0.3987.149
 - OS: MacOS 10.14.5
 - Library version: 6.3.4

**Comment by nikku** [comment]
Thanks for reporting this issue!

Do you have a valid diagram that can be deployed (and executed) on Camunda?

**Comment by RomanJRW** [comment]
No worries 🙂 

I've had to attach as .txt files as GitHub doesn't allow bpmn or xml files. As you can see, the only difference between the deployable diagram and the undeployable diagram is the presence of the `name` attribute on the link event, which matches the logged parsing exception message too.

[deployable_links.txt](https://github.com/bpmn-io/bpmn-js/files/4388699/deployable_links.txt)
[undeployable_links.txt](https://github.com/bpmn-io/bpmn-js/files/4388700/undeployable_links.txt)

**Comment by nikku** [comment]
To better understand your issue your expected behavior is that Link events, without further configuration

(1) should be deployable?
(2) pass the XSD schema validation check?

I'd argue that (1) will be impossible to achieve as we'd otherwise need to automagically generate sound names for the link event definitions.

If you use a technical implementation tool such as the Camunda Modeler you can configure the link name in a properties panel, cf. the following screenshot:

![image](https://user-images.githubusercontent.com/58601/77687651-0ace5900-6f9f-11ea-9d47-34e52b6ca3cb.png)

**Comment by nikku** [comment]
One simple fix would be to serialize an empty link name (`""` per default).

**Comment by RomanJRW** [comment]
Thanks for the quick response 👍. I  agree and I'm only really concerned about (2), the deployment was just an example to demonstrate the validation failure, sorry for not being clearer there.

Given that there is no sensible default name, I also think that the empty link name quick fix would be fine

**Comment by RomanJRW** [comment]
Thanks for getting this fixed so quickly 🎉. When do you think this is likely to be released? It would be very much appreciated if we could get it before the Optimize 3.0.0 release next week
