### ISSUE TITLE
I can morph BPMN elements (gateways and tasks)

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#130]
AT:
    * BPMN elements can be changed among each other (e.g. from service task to script task or from message event to signal event)
    * Not every element can be changed to anything, the following "groups" apply
      ** Gateways --> all allowed gateway types, except for instanciating gateways
        **** label: 'Event Based Gateway'
      ** Tasks --> all Task Types + call activity + collapsed subprocess

**Comment by ThorbenLindhauer** [comment]
Just played around with the staging build and could not model a transaction.

Are you considering morphing a subprocess to a transaction and vice versa or would you model transactions differently?

**Comment by gimbel** [comment]
Yes sure, but that is an issue of its own
