### ISSUE TITLE
Labels move twice when adding lane

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1302]
__Describe the Bug__

When adding a lane labels move twice.

![bug](https://user-images.githubusercontent.com/7633572/78152797-9aaa5200-743a-11ea-8b2a-d95aa8f27521.gif)

However, using the space tool before adding a lane will prevent this behavior.

![bug-2](https://user-images.githubusercontent.com/7633572/78152849-abf35e80-743a-11ea-8744-75af63170ff1.gif)

__Steps to reproduce__

1. Open [diagram_1.bpmn.txt](https://github.com/bpmn-io/bpmn-js/files/4419369/diagram_1.bpmn.txt)
2. Select Lane_1
3. Add lane below via context pad

__Expected Behavior__

Labels move once.

__Environment__

 - Library version: 6.4.0

**Comment by nikku** [comment]
Could you please share a diagram that allows us to reproduce the behavior?

**Comment by philippfromme** [comment]
Updated the description. 👍
