### ISSUE TITLE
Duplicating the label after update v2

### ISSUE THREAD

**Issue by tuliogoiania** [bpmn-io/bpmn-js#1304]
The label on task component is doubling.
If we erase, it erases from 2, if we leave it, it remains 2.

I opened the website https://demo.bpmn.io/?use-classic=1
  and uploaded an example.

 - Browser:  Chrome Versão 80.0.3987.149 (Versão oficial) 64 bits
 - OS: MacOS 10.15.4
 - Library version: Lasted from site. 

![image](https://user-images.githubusercontent.com/6987331/78253162-5c5c7380-74ca-11ea-9cd8-a08173ea86b5.png)

**Comment by nikku** [comment]
This is a temporary glitch we'll fix in the near future.

**Comment by nikku** [comment]
Just wondering: Why would you still use the classic mode?

**Comment by tuliogoiania** [comment]
Many thanks for the reply.

Answering your question, I use it to validate the process in the company, and I found this new approach very informal.

**Comment by nikku** [comment]
Fixed.
