### ISSUE TITLE
Warnings thrown when using namespace xml

### ISSUE THREAD

**Issue by ChrisSchoe** [bpmn-io/bpmn-js#1319]
__Describe the Bug__
When importing a diagram that uses the namespace xmlns:xml without explicitly declaring it warnings are thrown.
My understanding so far was that this namespace should be included by default in all xml files.

This issue is coming from running tests for the upcoming bpmn miwg demo.
__Fixtures__

[Advertise_job_vacancy_xmlns.zip](https://github.com/bpmn-io/bpmn-js/files/4544440/Advertise_job_vacancy_xmlns.zip) (updated link)

__Steps to Reproduce__

- import the file
- note the numerous warnings thrown due to the nested error "missing namespace for prefix <xml>" 

Adding xmlns:xml="http://www.w3.org/XML/1998/namespace" to the definitions removes these warnings.

__Expected Behavior__

As far as I understand it the standard xml namespace should be included by default in all xmls. Thus, no warnings should be shown if it is not explicitly named in the definitions. 

__Environment__

 - Browser FF 75
 - OS: Win 10
 - Library version: 6.4.2

----

Depends on https://github.com/bpmn-io/moddle-xml/issues/50

**Comment by nikku** [comment]
The diagram you shared does not contain the `xmlns:xml` namespace, nor usages of the `xml` namespace.

Could you share an actual diagram that allows us to reproduce the issue?

**Comment by ChrisSchoe** [comment]
Ah, sorry, appearantly I uploaded the wrong diagram.  Let's try this again.
[Advertise_job_vacancy_xmlns.zip](https://github.com/bpmn-io/bpmn-js/files/4544440/Advertise_job_vacancy_xmlns.zip)

**Comment by nikku** [comment]
You could also rename your diagram to `.bpmn.txt` and upload it directly (without archiving).

**Comment by ChrisSchoe** [comment]
Ah, that makes sense. Thank you, I'll do that next time.

**Comment by nikku** [comment]
Can reproduce the issue.

**Comment by nikku** [comment]
Upstream issue: https://github.com/bpmn-io/moddle-xml/issues/50

**Comment by nikku** [comment]
Happy to take contributions that fix this issue.

**Comment by onlineandy** [comment]
I have provided a PR which should fix this issue: https://github.com/bpmn-io/moddle-xml/pull/51

**Comment by ChrisSchoe** [comment]
I tested an adapted version of @onlineandy 's fix for moddle-xml v 8.0.7 in combination with bpmn-js, worked great!

**Comment by nikku** [comment]
Upstream issue fixed. 

We'll cut patch releases of the required libraries. In the mean time, you may:

```
npm update --depth=10 moddle-xml
```

...to get your bpmn-js version fixed.

**Comment by oguzeroglu** [comment]
Fixed in [bpmn-js@7.0.1](https://github.com/bpmn-io/bpmn-js/releases/tag/v7.0.1)
