### ISSUE TITLE
I can make space in a BPMN diagram

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#132]
A space tool exists that can be used to create and remove horizontal and vertical space in a diagram.

- [x] size of pools, lanes, subprocesses, groups is increased
- [x] sequence flows become longer
- [x] rest of elements is moved

Related to bpmn-io/diagram-js#66

#### Hints

- [x] create test cases that verify the above is working
- [x] add an entry to the palette that switches into the create space mode

**Comment by ISO50** [comment]
Talked with @nikku about adding an key binding for that feature.

Maybe we don't use any STRG | META | ALT | CMD Key combination instead we use just a simple key binding that relates to the feature.
* m -> move mode
* s -> space tool mode

**Comment by ricardomatias** [comment]
We have an open issue regarding the sequence flows laying out after resizing. 

Issue #236

**Comment by nikku** [comment]
@ISO50 We will rework the key bindings in #243
