### ISSUE TITLE
Support BPMN Data Input/Output and Collection elements

### ISSUE THREAD

**Issue by falko** [bpmn-io/bpmn-js#1323]

**Comment by pinussilvestrus** [comment]
Is this a duplicate of https://github.com/bpmn-io/bpmn-js/issues/951?

**Comment by falko** [comment]
Almost. This one also adds the collection marker.

Sent from mobile device.

________________________________

**Comment by nikku** [comment]
Regarding the collection markers, is this covered by https://github.com/bpmn-io/bpmn-js/issues/381?

**Comment by falko** [comment]
Yes if that adds them to Data Inputs and Outputs es well.

**Comment by falko** [comment]
Yes if that adds them to Data Inputs and Outputs as well.

**Comment by nikku** [comment]
Closing this as a duplicate of https://github.com/bpmn-io/bpmn-js/issues/381 and https://github.com/bpmn-io/bpmn-js/issues/951.
