### ISSUE TITLE
Allow associations to BPMN groups

### ISSUE THREAD

**Issue by falko** [bpmn-io/bpmn-js#1327]
I cannot attach a text annotation or just an association to a group in BPMN. IIRC, a group is an artifact in the UML metamodel. Thus, associations should be allowed to connect to groups.

In one particular example, I wanted to illustrate different options for a child process called by a call activity and I (ab?)used groups and associations for that.

**Comment by nikku** [comment]
Makes sense, thanks for that feature request.

**Comment by pinussilvestrus** [comment]
@falko can you maybe share an example diagram for this scenario?
