### ISSUE TITLE
I can move (parts of) flows in parallel

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#133]
As a user I can move horizontal and vertical sections in parallel. This results in bendpoints being created where appropriate. The behavior can be undone. 

* [x] horizontal / vertical sections on connections between two bendpoints can be moved in parallel
* [x] during move a live preview is shown
* [x] upon drop, the move is actually _performed_
* [x] the bendpoint movement can be undone

#### Example

The following screencast shows _a possible_ interaction, illustrating the mechanics behind this feature:

![moveflowparallel](https://cloud.githubusercontent.com/assets/3829733/6863956/c576117a-d45a-11e4-8fc0-727b3d271fea.gif)

#### Specifications

* A drag handle allows users to move horizontal/vertical parts between two bendpoints of a connection in parallel
* This adjusts the bendpoint positions so that layouting (i.e. horizontal/vertical alignment) of the rest of the flow is preserved
* A visual indication is shown during the operation
* The diagram is updated on finish
* The feature is tested
* The modeling operation can be undone

#### Help 

* We already have an implementation that [implements connection updating / bendpoint interaction](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/bendpoints/Bendpoints.js). It can serve as a basis for the horizontal / vertical movement.

**Comment by nikku** [comment]
A few open todos: 

* add Bendpoints#activateBendpointMove test case testing when segment / bendpoint move is triggered
* add test case verifying that stuff works with cropping
* show segment move indicator during move
