### ISSUE TITLE
how to create a <![CDATA[   ]]>  element

### ISSUE THREAD

**Issue by kampiu** [bpmn-io/bpmn-js#1334]
<userTask id="Activity_1h68c0r" renderType="create.UserTask" kkguan:allowAutoComplete="true">
      <extensionElements>
        <kkguan:field name="dataSource">
          <kkguan:string><![CDATA[$user == 100]]></kkguan:string>
        </kkguan:field>
      </extensionElements>
    </userTask>

<      transformation       &lt;!
>      transformation       &gt;

**Comment by pinussilvestrus** [comment]
Please use one of our [issue templates](https://github.com/bpmn-io/bpmn-js/issues/new/choose) otherwise we won't be able to help you.

**Comment by pinussilvestrus** [comment]
I will close this due to incomplete information. Feel free to re-open.
