### ISSUE TITLE
Issue with droping new task on a too short sequenz flow

### ISSUE THREAD

**Issue by mnp-mid** [bpmn-io/bpmn-js#1336]
There is a issue with new tasks on a too short sequenz flow.
Issue reproduced on bpmn.io

Steps:
- Append Task to Start event
- Append End Event to Task
- Create new Task using left tool panel and hover over the sequenzflow between the existing Task and the End Event
- Drop the Task.

![image](https://user-images.githubusercontent.com/33545902/88798526-50956b00-d1a5-11ea-80f2-784ba69aabff.png)

![image](https://user-images.githubusercontent.com/33545902/88798585-66a32b80-d1a5-11ea-935b-c1b7a1be0334.png)

Issue: 
Sequenz flow is destroyed.

Expectation:
- Either drop is prevented due to to short sequenz flow   OR
- End is moved a bit more to the right side

**Comment by philippfromme** [comment]
Thanks for reporting this. I honestly don't think we're going to fix this. The user can easily avoid this situation by making sure there is enough space before inserting a shape into an existing connection.

**Comment by pinussilvestrus** [comment]
As Philipp mentioned, it's unlikely we are going to fix this. I will close this, feel free to re-open if it turns out to be a bigger problem.
