### ISSUE TITLE
Typed Start Event Can Be Pasted Onto Sub Process

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1340]
__Describe the Bug__

Creating typed start events is not allowed within a subprocess. However, they can still be copied and pasted onto a subprocess which shouldn't be allowed either.

![06-08-_2020_14-19-57](https://user-images.githubusercontent.com/7633572/89532801-a647c400-d7f2-11ea-87d6-ea536b0197ba.gif)

The same issues occurs with non-interrupting events copied out of a event sub-process. (see [comment](https://github.com/bpmn-io/bpmn-js/issues/1340#issuecomment-669970364)).

__Steps to Reproduce__

1. Copy a typed start event
2. Paste onto a subprocess

__Expected Behavior__

Pasting is not allowed.

__Environment__

 - Library version: v7.3.0

**Comment by MaxTru** [comment]
We have the same issue with non-interrupting events, so we should extend the scope of this ticket (alternatively create another ticket). I will investigate
![CopyPasteBug2](https://user-images.githubusercontent.com/42800119/89545397-95ec1500-d803-11ea-9d36-3da23c68150e.gif)

**Comment by MaxTru** [comment]
Alternative I: We can disallow this by adding this as rule to [BpmnRules @canDrop](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/rules/BpmnRules.js#L443). But this will then also disallow the replace ("morph" behaviour, which we implemented in [BpmnRules @canReplace](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/rules/BpmnRules.js#L660).

Alternative II: We can also implement the replace ("morphing") behaviour when copy pasting, but this is something that we don't do at the moment.

**Comment by MaxTru** [comment]
Not in scope for 4.2.0 release since this is more complex than initially thought. (see [comment](https://github.com/bpmn-io/bpmn-js/issues/1340#issuecomment-670146825)). We might to implement a new rule bin BpmnRules.

**Comment by nikku** [comment]
In terms of where we want to go, I suggest that we consider replacing during paste + an updated paste preview to match our existing behavior (https://github.com/bpmn-io/bpmn-js/issues/1340#issuecomment-669970364).

It is otherwise hard to understand for users why pasting won't work if a bigger pattern is pasted.

On a side note, I think this is not too big of a deal, given that the resulting diagram could be linted to indicate + fix the error.

**Comment by imrishabh18** [comment]
@MaxTru I would like to take up this issue

**Comment by MaxTru** [comment]
@imrishabh18 please feel free to go ahead and propose a PR for that. But please note that this does require some changes and according tests (ie. not just a few lines of code).

**Comment by barmac** [comment]
I want to implement it as

> Alternative II: We can also implement the replace ("morphing") behaviour when copy pasting, but this is something that we don't do at the moment (and what is not described in the expected behaviour above).

So the event will be replaced just like it happens when you move a typed start event.

**Comment by nikku** [comment]
It makes a lot of sense to go that route and fits very well with our existing interactions :+1:.

**Comment by barmac** [comment]
It seems that it's not that easy to replace the previews for Create. I'll have a PR for the core behavior and create a follow-up issue for the preview.

**Comment by barmac** [comment]
Follow-up issue: https://github.com/bpmn-io/bpmn-js/issues/1435
