### ISSUE TITLE
Intermediate message catch boundary events shall be allowed targets for message flows

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js#1346]
__Describe the Bug__

Message flows targeting **intermediate message catch boundary events** are disallowed but shall be allowed according to BPMN 2.0 spec.

This issue was first raised in Camunda Modeler: https://github.com/camunda/camunda-modeler/issues/1919.

__Steps to Reproduce__

1. Try to connect a message flow from an activity in one participant to an intermediate message catch boundary event
2. Modeler disallows the connection

![messageFlowWithMessageCatchTarget](https://user-images.githubusercontent.com/42800119/91721650-65e12900-eb99-11ea-9152-2e1ce15134f5.gif)

__Expected Behavior__

Modeler shall allow to have a message flow target an intermediate message catch boundary event.

**Note that in general boundary events shall not be allowed targets for message flows. Message catch events are a special case (also see below)**

Relevant parts in BPMN 2.0 spec.:

 [BPMN 2.0 spec](https://www.omg.org/spec/BPMN/2.0/PDF) page 254, table 10.90, row 1 talks about message boundary events:
> **Intermediate Event Types Attached to an Activity Boundary**
> 
> A Message arrives from a participant and triggers the Event. If a
> Message Event is attached to the boundary of an Activity, it will change
> the normal flow into an exception flow upon being triggered.
> For a Message Event that interrupts the Activity to which it is attached,
> the boundary of the Event is solid (see upper figure on the right). Note
> that if using this notation, the attribute cancelActivity of the Activity
> to which the Event is attached is implicitly set to true.
> For a Message Event that does not interrupt the Activity to which it is
> attached, the boundary of the Event is dashed (see lower figure on the
> right). Note that if using this notation, the attribute cancelActivity of
> the Activity to which the Event is attached is implicitly set to false.
> **The actual Participant from which the Message is received can be**
> **identified by connecting the Event to a Participant using a Message Flow**
> **within the definitional Collaboration of the Process – see Table 10.1.**

According to page 44, table 7.4. this shall only be valid for intermediate boundary catch events with a message event definition:
![Screenshot_20200831_145509](https://user-images.githubusercontent.com/42800119/91722034-f91a5e80-eb99-11ea-891e-835d14dca192.png)

Also see issue #1300 which introduced a code change directly in the rules affected by this ticket.

__Environment__

 - Library version v7.3.0

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/a9ce32449aa3615abbfb715b698fa1d8592c6201
