### ISSUE TITLE
Add multi-selection and move for BPMN Shapes

### ISSUE THREAD

**Issue by Nikku** [bpmn-io/bpmn-js#135]
~~- [ ] if more than one element is selected a bounding box must be drawn around the elements~~
- [x] select + left click on element add/removes the element from selection
- [x] Interaction
 - [x] move
 - [x] delete

**Comment by Nikku** [comment]
Related to #168?

**Comment by ISO50** [comment]
Yes. I've created #168 to split the work to smaller parts.

**Comment by ISO50** [comment]
Decided against Bounding Box Rect.
