### ISSUE TITLE
Allow rendering subProcess root elements in different diagrams in the navigated viewer

### ISSUE THREAD

**Issue by tdauth** [bpmn-io/bpmn-js#1350]
__Describe the Bug__

When I pass a diagram ID and the diagram contains a plane element and a subProcess element as root element it will throw an error:
`Error: unsupported bpmnElement for <bpmndi:BPMNPlane id="bpmndiBPMNPlane_65" />: <bpmn:SubProcess id="Linebeauftragungvorbereiten" />`
so the specified diagram won't be rendered!

My XML looks like this:

```
<bpmndi:BPMNDiagram id="bpmndiBPMNDiagram_65">
    <bpmndi:BPMNPlane id="bpmndiBPMNPlane_65" bpmnElement="bla">
      <bpmndi:BPMNShape id="bpmndiBPMNShape_1642" bpmnElement="blaaa">
        <omgdc:Bounds x="161" y="389.69731623524405" width="30" height="30" />
        <bpmndi:BPMNLabel labelStyle="bpmndiBPMNLabel_131">
          <omgdc:Bounds x="83.71785736083984" y="421.69731623524405" width="184.5642852783203" height="11" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="bpmndiBPMNShape_1643" bpmnElement="blaaaaa">
        <omgdc:Bounds x="1215" y="203.4825095367933" width="126" height="79.99999999999994" />
        <bpmndi:BPMNLabel labelStyle="bpmndiBPMNLabel_132">
          <omgdc:Bounds x="1232.8714294433594" y="223.4825095367933" width="90.25714111328125" height="35.99999999999997" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
...
```

__Steps to Reproduce__

1. Use a XML with multiple diagrams and subProcess elements as root elements.
2. Try to load the XML by specifying a diagramId of one of the diagrams

__Expected Behavior__

This code fixes the behavior:

```
// my fix: || is$1(rootElement, 'bpmn:SubProcess')
if (is$1(rootElement, 'bpmn:Process') || is$1(rootElement, 'bpmn:SubProcess')) {
	      handleProcess(rootElement, ctx);
	    } else if (is$1(rootElement, 'bpmn:Collaboration')) {
	      handleCollaboration(rootElement);

	      // force drawing of everything not yet drawn that is part of the target DI
	      handleUnhandledProcesses(definitions.rootElements, ctx);
	    } else {
	      throw new Error(
	        translate('unsupported bpmnElement for {plane}: {rootElement}', {
	          plane: elementToString(plane),
	          rootElement: elementToString(rootElement)
	        })
	      );
	    }
```

It worked in a much older version of bpmnjs: ~0.7.0

__Environment__

 - Browser: Firefox 80.0.1
 - OS: 18.04.1-Ubuntu
 - Library version: bpmn-navigated-viewer 6.3.2

**Comment by pinussilvestrus** [comment]
Thanks for reporting! Let's first understand your problem in detail. Mind you sharing an example setup with your diagram inside a [CodeSandbox](https://codesandbox.io/s/bpmn-js-sandbox-3zkw0)? It would help us a lot to reproduce the issues you are experiencing.

**Comment by tdauth** [comment]
Does the CodeSandbox support storing multiple bpmndi:BPMNDiagram elements? I dont see how I can create multiple elements there.

**Comment by pinussilvestrus** [comment]
At least a full example XML file would be helpful.

**Comment by nikku** [comment]
@tdauth Any follow up on this? Based on the code snippet you provided this may be an easy pick. We'd however first need to understand your problem (and need to be able to reproduce it first).

**Comment by tdauth** [comment]
Well I would need a tool where I could create a BPMN XML with multiple bpmndi:BPMNDiagram instead of only one. I cant post the BPMN XML from my company here and I dont know how it was created originally. I don't see any way where I can create such an XML in the CodeSandBox. However, there should be some kind of unit test in this framework with such an XML. If you know any tool which supports multiple bpmndi:BPMNDiagram elements I will gladly create an example.

**Comment by nikku** [comment]
Consider creating a minimal example based on what you got. Without that stuff we cannot reproduce your issue and thus, cannot fix it.

**Comment by nikku** [comment]
Happy to reopen if we receive further input.

**Comment by WaylonSong** [comment]
@nikku We use flowable bpmn modeler may produce the subprocess with multiple BPMNDiagrams, if we use Collapsed Subprocess.
