### ISSUE TITLE
NS_ERROR_FAILURE on Firefox on Windows when rendering more than one BpmnViewer with overlays using the same activityID

### ISSUE THREAD

**Issue by tdauth** [bpmn-io/bpmn-js#1352]
__Describe the Bug__

Hello,
I use multiple BpmnViewers on one single website and add overlays to them with some numbers.
For the first one everything works just fine but for the remaining ones only the first overlay is shown. It shows NS_ERROR_FAILURE: 

```
NS_ERROR_FAILURE: bpmn-navigated-viewer.development-6.3.2.js:8519
    viewbox bpmn-navigated-viewer.development-6.3.2.js:8519
    _addOverlay bpmn-navigated-viewer.development-6.3.2.js:6999
    add bpmn-navigated-viewer.development-6.3.2.js:6780
   ...
    importXML bpmn-navigated-viewer.development-6.3.2.js:18562
    importBpmnDiagram bpmn-navigated-viewer.development-6.3.2.js:18378
    open bpmn-navigated-viewer.development-6.3.2.js:18653
    importDefinitions bpmn-navigated-viewer.development-6.3.2.js:18598
    importXML bpmn-navigated-viewer.development-6.3.2.js:18557
    fromXML bpmn-navigated-viewer.development-6.3.2.js:13354
```

which is the following line:

```
	    // compute the inner box based on the
	    // diagrams default layer. This allows us to exclude
	    // external components, such as overlays
	    innerBox = this.getDefaultLayer().getBBox();
```

This only happens on Firefox 68.9.0 on Windows. It works fine on Chrome and Firefox on Linux.
Note that it happens probably because the activity Ids are all the same:

```
Adding marker to activityId ExclusiveGateway_2 bpmn-processes:726:41
Adding marker to activityId ExclusiveGateway_2 bpmn-processes:726:41
Adding marker to activityId ExclusiveGateway_2 ...
```

__Steps to Reproduce__

1. Create multiple BpmnViewer on one single page
2. Add overlays like I did with the same activity ID in multiple viewers.

__Expected Behavior__

It should be able to handle same activity IDs for overlays in multiple BpmnViewers on the same page in ALL browsers on ALL operating systems.

__Environment__

 - Browser: Firefox 68.9.0
 - OS: Windows 10
 - Library version: 6.3.2

**Comment by nikku** [comment]
Thanks for filing your bug report.

Does it reproduce in a simple, stripped down environment, too? If so, could you provide me with a [CodeSandbox](https://codesandbox.io/s/fancy-breeze-y4pq4) that reproduces the error?

**Comment by tdauth** [comment]
https://codesandbox.io/s/two-navigated-viewers-with-overlays-1cfux?file=/src/index.js

I get:

> [Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: https://lhs4p.csb.app/node_modules/diagram-js/lib/core/Canvas.js :: evaluate/Canvas.prototype.viewbox :: line 313"  data: no]
on Firefox on Windows.
This error does not show up if I comment the creation of the second navigated viewer.

Note that the example is only there to show the error. It doesn show two navigated viewers in my browser in both cases.

**Comment by nikku** [comment]
That example helps us to continue! Thanks. We will have a look.

**Comment by philippfromme** [comment]
I'm not able to reproduce this issue using Windows 10 and Firefox v81.0.2

**Comment by nikku** [comment]
I've checked out your sandbox, fixed a couple of errors (i.e. made both editors visible) and updated to the latest version of bpmn-js.

It actually works on Linux and Windows, too: https://codesandbox.io/s/purple-fog-xl318?file=/src/index.js

**Comment by nikku** [comment]
If you can provide further input into where the error originates on our side I'm happy to re-open this issue.
