### ISSUE TITLE
How to get all translations for bpmn-js and  bpmn-js-properties-panel?

### ISSUE THREAD

**Issue by gotounix** [bpmn-io/bpmn-js#1356]
I found `translation-reporter.js` in `test/config` folder, but I don't know how to use it.
Is there some docs telling how to get all string fields for translating in `bpmn-js` and `bpmn-js-properties-panel`?
Thanks.

**Comment by nikku** [comment]
What would you like to achieve?

Up to date translations can be found [here](https://github.com/bpmn-io/bpmn-js-i18n).

**Comment by nikku** [comment]
I kindly ask you to use our issue template to file your issues. For simple questions [our forum](https://forum.bpmn.io/) is the right place to discuss.

**Comment by gotounix** [comment]
> What would you like to achieve?
> 
> Up to date translations can be found [here](https://github.com/bpmn-io/bpmn-js-i18n).

I found the translations in [here](https://github.com/bpmn-io/bpmn-js-i18n) is not accurate and complete. Its coverage is less than 80%.
And I can't found any translation template for bpmn-js-properties-panel.

**Comment by pinussilvestrus** [comment]
This [community maintained plugin](https://github.com/FlowSquad/camunda-modeler-i18n-plugin/tree/master/client/i18n-extension/languages) also offers some translation lists.

**Comment by nikku** [comment]
Closing this as something along https://github.com/bpmn-io/bpmn-js/issues/1356#issuecomment-707820890 serves as a fine workaround. For further questions, please use our forum.

**Comment by nikku** [comment]
As a late update to this one: https://github.com/bpmn-io/bpmn-js/pull/1364 restores the translation reporter that collects translations during a test run. Technically you can use the reporter to collect _all_ translations, i.e. modeler + properties panel, too.

As you indicated, some of our existing translations are outdated. For an up-to-date list of translatable strings, checkout https://github.com/bpmn-io/bpmn-js/pull/1364/files#diff-42ab64542245ba48c4b9b5fc3460c742f6ae7d58e7c279282a3a0d3e0e7716ed.
