### ISSUE TITLE
Unremovable selection of sequence flow when adding gateway between start and end event in Firefox

### ISSUE THREAD

**Issue by OmranAbazid** [bpmn-io/bpmn-js#1366]
__Describe the Bug__

When adding a gateway between start and end event, a weird selection appear on the sequence flow between the start and the gateway

![bpmn-sequence-selection](https://user-images.githubusercontent.com/9063094/98359248-2ff07300-2028-11eb-8e32-4ffcd734ee47.gif)

__Steps to Reproduce__

1. create a start event
2. connect it to an end event
3. drag a gateway into the selection

__Expected Behavior__

No selection happens on the sequence flow

__Environment__

 - Browser: Firefox 81.0.2
 - OS: Mac osx
 - Library version: latest

**Comment by pinussilvestrus** [comment]
Thanks for reporting! Seems like the `hover` marker does not get removed, exclusively in Firefox.

![image](https://user-images.githubusercontent.com/9433996/98372997-e19a9e80-203e-11eb-9f90-8c47ee6982a1.png)

**Comment by nikku** [comment]
Can reproduce this one on Linux, Firefox latest, too.

**Comment by barmac** [comment]
I was able to reproduce it on Firefox 80

**Comment by azeghers** [comment]
Small finding, hovering over anything other than the segment-dragger on the Flow removes the problematic selection.

![unremovable-selection](https://user-images.githubusercontent.com/42282939/99684742-161c4a80-2a82-11eb-8926-3ec7f0aebc54.gif)

**Comment by azeghers** [comment]
Possible fix :

![firefox-2020-11-23-190123](https://user-images.githubusercontent.com/42282939/99998780-7a5f4700-2dbf-11eb-9b11-b36565e1f0a4.gif)

**Comment by nikku** [comment]
Fix released with `v7.4.2`.
