### ISSUE TITLE
Imports with SubProcesses fail

### ISSUE THREAD

**Issue by jookshub** [bpmn-io/bpmn-js#1367]
__Describe the Bug__

When importing a file like the following:

<details>
  <summary>Modelio-Export</summary>

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:ns2="http://www.omg.org/spec/DD/20100524/DI" xmlns:ns3="http://www.omg.org/spec/DD/20100524/DC" xmlns:ns4="http://www.omg.org/spec/BPMN/20100524/DI" targetNamespace="http://www.omg.org/bpmn20">
    <process isClosed="false" isExecutable="false" processType="None" name="Process" id="modelio-041041b9-3ac4-4878-930a-e8af9cba12d1">
        <sequenceFlow sourceRef="modelio-57078e54-44a7-4403-891c-4fd71c8d3e85" targetRef="modelio-903c7131-8d64-4676-aa25-88780558d570" name="" id="modelio-9acfe78d-ca28-470b-8581-875a7b474b88"/>
        <sequenceFlow sourceRef="modelio-56567f6e-d67f-4369-9754-28fb4e9dec5f" targetRef="modelio-57078e54-44a7-4403-891c-4fd71c8d3e85" name="" id="modelio-67a6df4b-a647-4b5d-9a4b-979383bab537"/>
        <startEvent isInterrupting="true" parallelMultiple="false" name="Start" id="modelio-56567f6e-d67f-4369-9754-28fb4e9dec5f">
            <ns5:outgoing xmlns:ns5="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="">modelio-67a6df4b-a647-4b5d-9a4b-979383bab537</ns5:outgoing>
        </startEvent>
        <subProcess triggeredByEvent="false" isForCompensation="false" startQuantity="1" completionQuantity="1" name="Task" id="modelio-57078e54-44a7-4403-891c-4fd71c8d3e85">
            <ns5:incoming xmlns:ns5="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="">modelio-67a6df4b-a647-4b5d-9a4b-979383bab537</ns5:incoming>
            <ns5:outgoing xmlns:ns5="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="">modelio-9acfe78d-ca28-470b-8581-875a7b474b88</ns5:outgoing>
            <sequenceFlow sourceRef="modelio-0145f388-2188-49bf-9b5e-14b62648ac2e" targetRef="c664c1f0-2ea1-4338-903b-a3019c91472f" name="" id="modelio-7baa2808-debf-49f7-b930-54c7e26dca34"/>
            <sequenceFlow sourceRef="modelio-0aeaa618-26ef-4e4a-9975-b9b3c7a39a5a" targetRef="modelio-0145f388-2188-49bf-9b5e-14b62648ac2e" name="" id="modelio-5ad2fea5-0158-4fd7-810b-14106460c968"/>
            <endEvent name="Subtask end" id="c664c1f0-2ea1-4338-903b-a3019c91472f">
                <ns5:incoming xmlns:ns5="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="">modelio-7baa2808-debf-49f7-b930-54c7e26dca34</ns5:incoming>
            </endEvent>
            <task isForCompensation="false" startQuantity="1" completionQuantity="1" name="Subtask" id="modelio-0145f388-2188-49bf-9b5e-14b62648ac2e">
                <ns5:incoming xmlns:ns5="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="">modelio-5ad2fea5-0158-4fd7-810b-14106460c968</ns5:incoming>
                <ns5:outgoing xmlns:ns5="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="">modelio-7baa2808-debf-49f7-b930-54c7e26dca34</ns5:outgoing>
            </task>
            <startEvent isInterrupting="true" parallelMultiple="false" name="Subtask Start" id="modelio-0aeaa618-26ef-4e4a-9975-b9b3c7a39a5a">
                <ns5:outgoing xmlns:ns5="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="">modelio-5ad2fea5-0158-4fd7-810b-14106460c968</ns5:outgoing>
            </startEvent>
        </subProcess>
        <endEvent name="End" id="modelio-903c7131-8d64-4676-aa25-88780558d570">
            <ns5:incoming xmlns:ns5="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="">modelio-9acfe78d-ca28-470b-8581-875a7b474b88</ns5:incoming>
        </endEvent>
        <ns5:boundaryEvent xmlns:ns5="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="" cancelActivity="true" attachedToRef="modelio-57078e54-44a7-4403-891c-4fd71c8d3e85" parallelMultiple="false" name="Error" id="modelio-97bde2aa-d0d8-420d-89db-fa5251d75e41">
            <ns5:errorEventDefinition/>
        </ns5:boundaryEvent>
    </process>
    <ns4:BPMNDiagram name="" id="modelio-22abb34f-059a-4e2d-9285-16aad425d7e4">
        <ns4:BPMNPlane xmlns:ns5="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="" bpmnElement="modelio-57078e54-44a7-4403-891c-4fd71c8d3e85">
            <ns4:BPMNEdge bpmnElement="modelio-7baa2808-debf-49f7-b930-54c7e26dca34" id="modelio-7baa2808-debf-49f7-b930-54c7e26dca34-gr">
                <ns2:waypoint x="10.0" y="21.0"/>
                <ns2:waypoint x="5.0" y="21.0"/>
            </ns4:BPMNEdge>
            <ns4:BPMNEdge bpmnElement="modelio-5ad2fea5-0158-4fd7-810b-14106460c968" id="modelio-5ad2fea5-0158-4fd7-810b-14106460c968-gr">
                <ns2:waypoint x="48.0" y="33.0"/>
                <ns2:waypoint x="10.0" y="33.0"/>
            </ns4:BPMNEdge>
            <ns4:BPMNShape bpmnElement="c664c1f0-2ea1-4338-903b-a3019c91472f" id="c664c1f0-2ea1-4338-903b-a3019c91472f-gr">
                <ns3:Bounds x="5.0" y="5.0" width="33.0" height="33.0"/>
                <ns4:BPMNLabel labelStyle="9b8e5772-1232-4368-bd1b-233c2e0bf67d">
                    <ns3:Bounds x="-4.0" y="38.0" width="51.0" height="16.0"/>
                </ns4:BPMNLabel>
            </ns4:BPMNShape>
            <ns4:BPMNShape bpmnElement="modelio-0145f388-2188-49bf-9b5e-14b62648ac2e" id="modelio-0145f388-2188-49bf-9b5e-14b62648ac2e-gr">
                <ns3:Bounds x="10.0" y="10.0" width="90.0" height="46.0"/>
            </ns4:BPMNShape>
            <ns4:BPMNShape bpmnElement="modelio-0aeaa618-26ef-4e4a-9975-b9b3c7a39a5a" id="modelio-0aeaa618-26ef-4e4a-9975-b9b3c7a39a5a-gr">
                <ns3:Bounds x="15.0" y="15.0" width="33.0" height="33.0"/>
                <ns4:BPMNLabel labelStyle="9b8e5772-1232-4368-bd1b-233c2e0bf67d">
                    <ns3:Bounds x="4.0" y="48.0" width="55.0" height="16.0"/>
                </ns4:BPMNLabel>
            </ns4:BPMNShape>
        </ns4:BPMNPlane>
        <ns4:BPMNLabelStyle id="9b8e5772-1232-4368-bd1b-233c2e0bf67d">
            <ns3:Font name="Arial" size="9.0" isBold="false" isItalic="false"/>
        </ns4:BPMNLabelStyle>
    </ns4:BPMNDiagram>
    <ns4:BPMNDiagram name="" id="fee37d72-3972-42ec-b5fd-7fcbb2684e45">
        <ns4:BPMNPlane xmlns:ns5="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="" bpmnElement="modelio-041041b9-3ac4-4878-930a-e8af9cba12d1">
            <ns4:BPMNEdge bpmnElement="modelio-9acfe78d-ca28-470b-8581-875a7b474b88" id="modelio-9acfe78d-ca28-470b-8581-875a7b474b88-gr">
                <ns2:waypoint x="520.0" y="120.0"/>
                <ns2:waypoint x="766.0" y="120.0"/>
                <ns2:waypoint x="766.0" y="180.0"/>
                <ns2:waypoint x="962.0" y="180.0"/>
            </ns4:BPMNEdge>
            <ns4:BPMNEdge bpmnElement="modelio-67a6df4b-a647-4b5d-9a4b-979383bab537" id="modelio-67a6df4b-a647-4b5d-9a4b-979383bab537-gr">
                <ns2:waypoint x="188.0" y="140.0"/>
                <ns2:waypoint x="329.0" y="140.0"/>
                <ns2:waypoint x="329.0" y="105.0"/>
                <ns2:waypoint x="420.0" y="105.0"/>
            </ns4:BPMNEdge>
            <ns4:BPMNShape bpmnElement="modelio-56567f6e-d67f-4369-9754-28fb4e9dec5f" id="modelio-56567f6e-d67f-4369-9754-28fb4e9dec5f-gr">
                <ns3:Bounds x="152.0" y="122.0" width="36.0" height="36.0"/>
                <ns4:BPMNLabel labelStyle="0afa366a-cd9e-4745-b47e-2c069fff9d1c">
                    <ns3:Bounds x="158.0" y="165.0" width="20.0" height="16.0"/>
                </ns4:BPMNLabel>
            </ns4:BPMNShape>
            <ns4:BPMNShape isExpanded="false" bpmnElement="modelio-57078e54-44a7-4403-891c-4fd71c8d3e85" id="modelio-57078e54-44a7-4403-891c-4fd71c8d3e85-gr">
                <ns3:Bounds x="420.0" y="90.0" width="100.0" height="80.0"/>
            </ns4:BPMNShape>
            <ns4:BPMNShape bpmnElement="modelio-903c7131-8d64-4676-aa25-88780558d570" id="modelio-903c7131-8d64-4676-aa25-88780558d570-gr">
                <ns3:Bounds x="962.0" y="162.0" width="36.0" height="36.0"/>
                <ns4:BPMNLabel labelStyle="0afa366a-cd9e-4745-b47e-2c069fff9d1c">
                    <ns3:Bounds x="970.0" y="205.0" width="17.0" height="16.0"/>
                </ns4:BPMNLabel>
            </ns4:BPMNShape>
            <ns4:BPMNShape bpmnElement="modelio-97bde2aa-d0d8-420d-89db-fa5251d75e41" id="modelio-97bde2aa-d0d8-420d-89db-fa5251d75e41-gr">
                <ns3:Bounds x="482.0" y="152.0" width="36.0" height="36.0"/>
                <ns4:BPMNLabel labelStyle="0afa366a-cd9e-4745-b47e-2c069fff9d1c">
                    <ns3:Bounds x="488.0" y="195.0" width="20.0" height="16.0"/>
                </ns4:BPMNLabel>
            </ns4:BPMNShape>
        </ns4:BPMNPlane>
        <ns4:BPMNLabelStyle id="0afa366a-cd9e-4745-b47e-2c069fff9d1c">
            <ns3:Font name="Arial" size="9.0" isBold="false" isItalic="false"/>
        </ns4:BPMNLabelStyle>
    </ns4:BPMNDiagram>
</definitions>
`
</details>

You will get the following error:

`unsupported bpmnElement for <bpmndi:BPMNPlane" />: <bpmn:SubProcess id="modelio-57078e54-44a7-4403-891c-4fd71c8d3e85" />`

My guess is, this is related to this section of the bpmn-js code:

https://github.com/bpmn-io/bpmn-js/blob/2dd1e1330509d3f6db7939ad8ae22b75144396bd/lib/import/BpmnTreeWalker.js#L217

Which only allows `Process` or `Collaboration` as `bpmnElement` for a BPMNPlane.

__Steps to Reproduce__

1. Save given example as `*.bpmn` or use `SubProcess-Reimport.bpmn` from [demo-files.zip]
2. Import into [demo.bpmn.io](https://demo.bpmn.io/new)

Another way is to:

1. Create a new BPMN File with [demo.bpmn.io](https://demo.bpmn.io/new) including a populated subprocess
2. Export to File
3. Create a new BPMN Project with [Modelio](https://www.modelio.org/)
4. Import the File
5. Export as `*.bpmn`
6. Import into [demo.bpmn.io](https://demo.bpmn.io/new) 

__Expected Behavior__

Based on this quote from the spec:

> A BPMNPlane can only reference a BaseElement of the types: Process, SubProcess, AdHocSubProcess, Transaction,
Collaboration, Choreography or SubChoreography. -- https://www.omg.org/spec/BPMN/2.0/PDF

no error should occur when importing the given example.

__Environment__

 - Version of [demo.bpmn.io](https://demo.bpmn.io/new) as of 2020-11-09
 - [demo-files.zip]

[demo-files.zip]: https://github.com/bpmn-io/bpmn-js/files/5510888/demo-files.zip

**Comment by pinussilvestrus** [comment]
Thanks for sharing this! You already tackled the correct place in our codebase where we could improve the number of supported elements as plane elements. We're open for contributions 👍

**Comment by nikku** [comment]
Open to contributions that improve the situation.
