### ISSUE TITLE
NPM - Package version not updated

### ISSUE THREAD

**Issue by mnp-mid** [bpmn-io/bpmn-js#1369]
__Describe the Bug__

The version of the npm package in the dist folder is not updated.
The latest version is 7.4.1, however the version that is shown in the deployed dist files is set to 7.4.0.

__Steps to Reproduce__

1. yarn add bpmn-js
2. Check files in node_modules/dist/...

=> bpmn-modeler.development.js

![image](https://user-images.githubusercontent.com/33545902/99077799-97289d00-25bd-11eb-917f-d5049ccd431c.png)

![image](https://user-images.githubusercontent.com/33545902/99078181-406f9300-25be-11eb-85b2-9f5ea3c45926.png)

**Comment by barmac** [comment]
I checked previous version and it seems that the banner lags behind the current version. For `v7.4.0`, it displays:

```
/*!
 * bpmn-js - bpmn-viewer v7.3.1
```

[Source](https://unpkg.com/browse/bpmn-js@7.4.0/dist/bpmn-viewer.development.js)
