### ISSUE TITLE
Align collection and parallel instance markers

### ISSUE THREAD

**Issue by azeghers** [bpmn-io/bpmn-js#1371]
__Is your feature request related to a problem? Please describe.__

As discussed with @andreasgeier, the markers for tasks and data objects should not have different designs.

![image](https://user-images.githubusercontent.com/42282939/99390183-7c656980-28d8-11eb-9156-99f3b38a2464.png)

__Describe the solution you'd like__

Aligning the data object collection marker to the parallel instance marker.

**Comment by andreasgeier** [comment]
See also expanded sub process with multi instance marker
<img width="629" alt="Screenshot 2020-11-17 at 13 34 51" src="https://user-images.githubusercontent.com/938244/99390926-ac613c80-28d9-11eb-9cc8-f3d4fe0f8393.png">

**Comment by azeghers** [comment]
Would this be acceptable?

![image](https://user-images.githubusercontent.com/42282939/99425189-ce22e980-2902-11eb-9447-12b95b96bf64.png)

**Comment by andreasgeier** [comment]
LGTM - well done
