### ISSUE TITLE
Add DataStoreReference to DataObjectReference replace menu and vice-versa

### ISSUE THREAD

**Issue by azeghers** [bpmn-io/bpmn-js#1372]
__Is your feature request related to a problem? Please describe.__

In its current state of the DataObjectReference replace menu only contains the collection marker.
It feels empty and out of place.
![image](https://user-images.githubusercontent.com/42282939/99405680-4ed6eb00-28ed-11eb-9c3d-e67679bf3d69.png)

As discussed with @andreasgeier, it has been suggested to make it possible for a DataObjectReference to be switched to a DataStoreReference, and vice-versa.
This will ensure that the menu is always populated with something, at least until the DataObjectInputs/Outputs are handled.

**Comment by azeghers** [comment]
First draft :

![data-object-replace-2020-11-17-1](https://user-images.githubusercontent.com/42282939/99431568-44c3e500-290b-11eb-83f2-614ba396baaf.gif)

@andreasgeier

**Comment by azeghers** [comment]
Second draft, with some help from Mr. Fromme :
![data-object-replace-2020-11-18-1](https://user-images.githubusercontent.com/42282939/99566394-20304180-29cd-11eb-9185-d65281616e48.gif)

@andreasgeier

**Comment by andreasgeier** [comment]
It looks like you use the top left corner as a reference point when switching between symbols of different sizes. I would try the center of the symbol, otherwise, it would be no longer aligned when it is part of a diagram and connected with lines to other elements.

**Comment by andreasgeier** [comment]
The current solution is related to https://github.com/camunda/camunda-modeler/issues/593
