### ISSUE TITLE
Fix JSDoc types for services

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1378]
__What should we do?__

Our existing JSDoc type definitions on services are built in a way that makes it impossible for IDEs to use. Related to https://github.com/bpmn-io/diagram-js/issues/501 we should correct type definitions on services defined within bpmn-js.

Fixing these types by pointing to the actual implementations allows us to TypeScript type hinting to find potential miss-use:

Related, but not necessarily similar we should fix type definitions on service APIs (https://github.com/bpmn-io/bpmn-js/issues/1378).

Related, and likely required, we should integrate type linting `tsc --pretty` into the build.

__Why should we do it?__

This improves the editing experience for new contributors, allows for `jump to definition` on public APIs and so on.

----

Child of https://github.com/bpmn-io/bpmn-js/issues/1002

**Comment by philippfromme** [comment]
Closed by https://github.com/bpmn-io/internal-docs/issues/688. [bpmn-js@13](https://www.npmjs.com/package/bpmn-js/v/13.0.0) includes type declarations.
