### ISSUE TITLE
Discretionary Hyphen (00AD) not respected

### ISSUE THREAD

**Issue by LinqLover** [bpmn-io/bpmn-js#1383]
__Describe the Bug__

When rendering a BPMN element, such as an activity, discretionary hyphens (code point `00AD`; on Windows, they can be typed using ALT + 0173) are not respected. As a result, long words cannot be wrapped correctly.

__Steps to Reproduce__

1. Create an activity
2. Name it:
   ```
   Fight Hippopoto­monstro­sesquippe­daliophobia
   ```
   (Note that most web browsers will not even show the discretionary hyphens in the code box, but still you can copy them into another application.)
3. During editing, the hyphens are used for word-wrapping correctly:
   ![image|40%](https://user-images.githubusercontent.com/38782922/100870781-79a17180-349f-11eb-8679-4f46dca84de8.png)
4. But after accepting the label, the word-wrapping disappears and the hyphens are no longer respected:
   ![image|40%](https://user-images.githubusercontent.com/38782922/100870855-9b025d80-349f-11eb-8442-1743155ea74b.png)

__Expected Behavior__

Discretionary hyphens should be respected correctly for word-wrapping.

__Environment__

 - Browser: Chrome 86
 - OS: Windows 2004
 - Library version: <https://demo.bpmn.io> at 2020-12-02

**Comment by azeghers** [comment]
Hey Linq,

First of all, thank you for this issue, I've learned about a character I didn't know before :smile: 
I'm posting a screenshot of a tool that shows special/invisible characters because it isn't clear in your step 2 that you're adding those hyphens to the word.

![shy](https://user-images.githubusercontent.com/42282939/101181523-44d31d00-364d-11eb-8d72-aee43156e858.png)

I have a couple of questions for you regarding this topic :
- Have you considered using regular hyphens and line-breaks for those cases?
- How often are you confronted to the usage of words too long to visually fit in bpmn task elements? Would you consider this problem a blocker for your purposes?

**Comment by LinqLover** [comment]
Thanks for the reply! :D 

> Have you considered using regular hyphens and line-breaks for those cases?

Yes, I could do that, but I think this is a suboptimal solution in terms of maintenance. :-)

> Would you consider this problem a blocker for your purposes?

No, it's just about convenience.

> How often are you confronted to the usage of words too long to visually fit in bpmn task elements?

I'm using German terms for my models, and in German, compound words are not separated by a space, e.g. "Modellierungsrichtlinie" rather than "modeling guideline". So yes, actually, I miss a proper word-wrapping quite frequently. Automatic word-wrapping would be best, of course, but I see this would be a major effort ...

**Comment by azeghers** [comment]
I will look into how labels are formatted and get back to you. :slightly_smiling_face:

**Comment by LinqLover** [comment]
Great, thanks for implementing! Looking forward to the next release :-)

**Comment by fml2** [comment]
Will these chars be supported and interpreted correctly both in the camunda modeler and in the cockpit when displaying process models and process instances?

**Comment by nikku** [comment]
> Will these chars be supported and interpreted correctly both in the camunda modeler and in the cockpit when displaying process models and process instances?

Nope.

**Comment by fml2** [comment]
Where will they be supported then? Isn't the `bpmn.js` library used in both products? Thank you.

**Comment by nikku** [comment]
The feature will first land in the Camunda Modeler, likely with the next modeler release. The feature may end up in the next version of Cockpit, once the Camunda Platform team decides to update the dependency.

I am afraid there does not exist an automatic update step here.
