### ISSUE TITLE
Does the plug-in support Wechat Mini Program?

### ISSUE THREAD

**Issue by rany1225** [bpmn-io/bpmn-js#1384]
I want to use bpmn on Wechat Mini Program, but I can't find a way.
Does the plug-in support Wechat Mini Program?

**Comment by nikku** [comment]
What is wechat mini program?

**Comment by nikku** [comment]
Please provide the relevant context and use one of our existing issue templates. We cannot help you, otherwise.

**Comment by rany1225** [comment]
tks.
This is the official document url of Wechat Mini Program.
https://developers.weixin.qq.com/miniprogram/en/dev/framework/server-ability/message-push.html
github url
https://github.com/wechat-miniprogram?page=1

**Comment by nikku** [comment]
Rany, I still do not know what wechat mini program and how it relates to our BPMN rendering / editor toolkit.

Because of that I gotta answer with _no_. No, we do not support Wechat Mini Program.
