### ISSUE TITLE
Menu icon for event-based gateway misleading

### ISSUE THREAD

**Issue by LinqLover** [bpmn-io/bpmn-js#1385]
I had trouble finding the event-based gateway option in the online editor. Finally, a colleague pointed out that this option actually exists:

![image](https://user-images.githubusercontent.com/38782922/101209752-9347e200-3674-11eb-86af-c5a3b5878ce8.png)

However, the thumbnail icon is wrong (it is missing the circle around the pentagon to look like a real event-based gateway) so I simply overlooked it when I was searching for the option:

![image](https://user-images.githubusercontent.com/38782922/101209821-b96d8200-3674-11eb-81db-7506f0e85eea.png)

For this reason, it would be nice if the thumbnail icon could be updated with the correct circle. :-)

**Comment by nikku** [comment]
Thanks for your feedback. 

The actual fix needs to land in the [bpmn-font](https://github.com/bpmn-io/bpmn-font) library. It currently ships with that simplified event-based gateway icon.

**Comment by nikku** [comment]
Closing this one as we do not intend to update the icon any time soon. If you are into icons and would like to give it a go, please contribute to [bpmn-font](https://github.com/bpmn-io/bpmn-font).
