### ISSUE TITLE
Hovering Palette While Moving Bendpoint Results in Error

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1387]
__Describe the Bug__

Hovering the palette while moving a bendpoint results in an error.

![08-12-_2020_09-46-36](https://user-images.githubusercontent.com/7633572/101460807-5a409380-393a-11eb-813c-bc1775295ac4.gif)

__Steps to Reproduce__

1. Move a bendpoint
2. Hover the palette

__Expected Behavior__

No error is thrown.

__Environment__

 - Library version: 7.5.0

---

Related to https://sentry.io/share/issue/524ce0be0f384b8ab40fe6c4ab643769/
Depends on https://github.com/bpmn-io/diagram-js/issues/497

**Comment by philippfromme** [comment]
### Why does this error occur?

The error occurs when a connection waypoint is being moved without hovering a diagram element. If, for example, the user moves a waypoint and hovers the palette, an [`out` event is fired](https://github.com/bpmn-io/diagram-js/blob/v7.2.0/lib/features/dragging/Dragging.js#L401) causing the [`BendpointMove`](https://github.com/bpmn-io/diagram-js/blob/v7.2.0/lib/features/bendpoints/BendpointMove.js) feature to [unset `hover`, `source` and `target` and to set `allowed` to `false`](https://github.com/bpmn-io/diagram-js/blob/v7.2.0/lib/features/bendpoints/BendpointMove.js#L115). When the preview of the connection is to be drawn `allowed` (which is called `canConnect` in the context of [`drawPreview`](https://github.com/bpmn-io/diagram-js/blob/v7.2.0/lib/features/connection-preview/ConnectionPreview.js#L71)) having the value of `false` will cause the [`ConnectionPreview`](https://github.com/bpmn-io/diagram-js/blob/v7.2.0/lib/features/connection-preview/ConnectionPreview.js) feature to draw a no-op preview. Note, that this works fine when creating a new connection or reconnecting an existing one. In this case, a no-op preview isn't what we want. Anyway, drawing the no-op preview causes the error since `source` and `target` are missing (they were unset on `out`).

### What is the proposed fix?

I'd argue that setting `allowed` to `false` on `out` is not necessary (it is when connecting or reconnecting). It's okay to allow the user to move a connection waypoint regardless of where the mouse cursor is. What would that look like?

![fix](https://user-images.githubusercontent.com/7633572/109540690-1f767380-7ac3-11eb-8255-70c2b6a60351.gif)

I'd say that's exactly what we want. I will create a pull request that implements the proposed fix.

**Comment by nikku** [comment]
Addressed via https://github.com/bpmn-io/diagram-js/pull/536.

**Comment by nikku** [comment]
Addressed via https://github.com/bpmn-io/diagram-js/pull/536.
