### ISSUE TITLE
Data Object Reference should show its dataState after the name

### ISSUE THREAD

**Issue by SanjiApollo** [bpmn-io/bpmn-js#1395]
__Describe the Bug__

As BPMN2.0 standard states (formal-13-12-09.pdf, page 204), "The names of Data Object References are derived by concatenating the name of the referenced Data Data Object the state of the Data Object Reference in square brackets as follows: \<Data Object Name> [ \<Data Object Reference State> ]."

Currently, only the name shows.

**Comment by nikku** [comment]
Could you spend some of your precious time to fill out our full bug report?

Especially I'd be interested in 

* The document you're referencing (link it)
* An example diagram I can reproduce the issue with

 We may not be able to help you, otherwise.

**Comment by o314** [comment]
Should be reopened IMO
![5-2-1](https://user-images.githubusercontent.com/4026002/165434592-06387fea-da81-49c0-8801-ff32c3148a55.JPG)
