### ISSUE TITLE
Update translations as a release step

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1399]
__What should we do?__

The command `npm run collect-translations` updates the `docs/translations.json` string with all translatable entities.

We do the following things right now that can easily be automated as a pre (or post) release step:

```
npm run collect-translations

# if changes in translations.json
git add -A
git commit -m "chore: update translations"
```

__Why should we do it?__

Automation helps us to do whatever should be done, without worrying about it.

__Context__

We already have a number of post release steps, currently orchestrated via CI (see `tasks` directory and `.travis.yml`).

**Comment by barmac** [comment]
I run the `collect-translations` task for test, and discovered that automatic commit would remove some of the messages which are still present in the code base. Therefore, I think we should rather create pull request with updates than commit changes without human intervention.

**Comment by barmac** [comment]
So the task relies currently on `translate` being invoked in the tests. If somehow the test suite does not encounter invocation, the translation is removed.
Perhaps we could just make sure all calls to `translate` are collected at the code compilation stage, i.e. via a babel plugin. I'll try to write it but first prepare a GitHub Action to collect translations.

**Comment by nikku** [comment]
@barmac If we can figure https://github.com/bpmn-io/bpmn-js/issues/1399#issuecomment-1550862033 out that would be great. 

We could also consider simply merging with the existing translations, and do manual clean-ups once in a while.
