### ISSUE TITLE
Diagram svg gets truncated in Chrome

### ISSUE THREAD

**Issue by jhajkom** [bpmn-io/bpmn-js#1409]
__Describe the Bug__

Diagram svg gets truncated. This only started happening when Chrome updated version 87 and up. 

In the image below, scrolling of the diagram lower will make it fully disappear. But then scrolling back up you can only see a small portion of it. 

![example diagram disapears](https://user-images.githubusercontent.com/55394178/105169170-0e753280-5b13-11eb-99af-4c35cc8d8e74.png)

__Steps to Reproduce__

1. Display a diagram. That is all.

The project is inside and Angular 10 application. But this was happening when it was on Angular 9 also. DOn't think its an issue with combining the two (as in this lib and Angular).

The way I got around it for now is adding a listening for the window size and updating the height of the svg. However this has its limitations also. Still running into issues sometimes like when there is a scroll bar on the window. 

    const canvas = this.diagram.get('canvas');

    function updateDiagramHeight(): void {
      const height = document.documentElement.clientHeight;
        canvas._svg.setAttribute('height', height);
    }

    window.addEventListener('resize', updateDiagramSize);

    updateDiagramHeight();
 
NOTE: I don't seem to be able to reproduce the issue in the demo project. 

__Expected Behavior__

Diagram should not truncate. It should be displayed full screen. 

__Environment__

 - Browser: Chrome 87.0.4280.141
 - OS: macOS Catalina 10.15.7
 - Library version: 7.2.1

**Comment by nikku** [comment]
This is likely a CSS issue on your side.

Please ensure that the diagram container has a height of 100%.

To get further help from our side, please share a code sandbox that demonstrates how you embed the diagram viewer into your application.

**Comment by jhajkom** [comment]
I have height and width set to 100%.

      .bpmn-renderer {
        width: 100%;
        height: 100%;
      }

Its embedded with a component which contains just this 

`<div #bpmnRenderer class="bpmn-renderer"></div>`

I actually spotted a scrolling issue in our project. I think it might be related to that. Apologies, I will close this ticket.
