### ISSUE TITLE
Modeler Not Fully Visible Unless Position = Absolute

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1412]
__Describe the Bug__

__Steps to Reproduce__

1. Open https://codesandbox.io/s/position-absolute-bug-8newd?file=/src/App.js
2. Modeler not fully visible

![image](https://user-images.githubusercontent.com/7633572/105680765-7dc29c00-5ef0-11eb-91a7-7785562abb26.png)

__Expected Behavior__

Modeler should be fully visible by default. This can be achieved by adding `position: absolute` to the container.

__Environment__
 - Library version: v8.0.1

**Comment by nikku** [comment]
Do we have test cases that verify embedding scenarios? I'd assume [our starters](https://github.com/bpmn-io/bpmn-js-examples) but also the properties panel example or the Camunda Modeler are good candidates.

I know we received some feedback regarding this in recent months. I'd like to understand _how you embed_ though before rushing to fix what exactly?

**Comment by philippfromme** [comment]
We don't have test cases verifying that the modeler has the same dimensions as its parent DOM element and doesn't collapse for some reason.

Anyway, the issue in the CodeSandbox was actually due to one of the parents not haven `height: 100%`. I'll close this issue for now. Sorry for the 🔉 .
