### ISSUE TITLE
Partipant New Parent Indication Stays after Adding Boundary Event

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1413]
__Describe the Bug__

If a participant has lanes the `new-parent` marker is not removed from it when adding a boundary event to a child.

![participant-background](https://user-images.githubusercontent.com/7633572/105758351-71b9f700-5f4f-11eb-82e9-6c7efa88bb0d.gif)

__Steps to Reproduce__

1. Create a participant with lanes
2. Add a task
3. Add a boundary event to the task

__Expected Behavior__

The `new-parent` should be reset.

__Environment__

 - Library version: v8.0.1

**Comment by nikku** [comment]
That bug [is in the code base since November 2019](https://github.com/bpmn-io/bpmn-js/commit/748674fb351c5b8168ff3497b674d643c99da17d).
