### ISSUE TITLE
`canvas.updateRoot` does not update existing flowNodes / children

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js#1420]
__Describe the Bug__

From the design of the `canvas.updateRoot` command, I assume that using this command I should be able to update the root element of a process, even though is has flow Elements. However, this does not work.

Example 1: https://codesandbox.io/s/replace-process-qwfld?file=/src/index.js (Note that you cannot edit the diagram)
Example 2: Add the following testcase to BpmnUpdaterSpec.js:
```javascript
  describe('update parent', function() {

    var diagramXML = require('./BpmnUpdateChildren.bpmn');

    beforeEach(bootstrapModeler(diagramXML, {
      modules: testModules
    }));


    it.only('should update children on canvas.updateRoot', inject(
      function(modeling, elementRegistry, commandStack, canvas, elementFactory) {

        // given
        var processElement = elementFactory.create('root', {
          type: 'bpmn:Process'
        });

        var context = {
          newRoot: processElement
        };

        var oldRoot = canvas.getRootElement();

        // assume
        expect(oldRoot.children.length).to.eql(5);

        // when
        commandStack.execute('canvas.updateRoot', context);

        // then
        expect(canvas.getRootElement()).to.exist;
        expect(canvas.getRootElement().children.length).to.eql(5);
      }
    ));

  });
```

Note this testCase will fail since `canvas.getRootElement().children.length` will yield `0`.

__Steps to Reproduce__

1. Copy the test case given above and paste into BpmnUpdaterSpec.js
2. run `npm run test`

__Expected Behavior__

`canvas.updateRoot` works even when flowElements are present in the respective process.

__Environment__

 - Library version: 8.2.1

**Comment by nikku** [comment]
This is not a bug but intentional behavior. 

We do replace the two roots and deliberately do not transfer children. It is in the callers responsibility to actually transfer the elements over that ought to be transferred. Cf. [`CreateParticipantBehavior`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/behavior/CreateParticipantBehavior.js) that implements this, for example.

**Comment by MaxTru** [comment]
I see, thanks for the explanation and example

**Comment by nikku** [comment]
I'm always open to improvements, i.e. if we figure that `updateRoot` should do more than it does today, in order to avoid duplication for instance. 

That may require substantial changes in other parts of the toolkit though and I'd rather classify that as a feature, not a bug.
