### ISSUE TITLE
Connection Preview Broken When Creating Message Flow Starting at Start Event

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1431]
__Describe the Bug__

When creating a message flow starting the interaction at a start event the preview is broken. The resulting message flow is correct, though.

![n2KxjHf7pG](https://user-images.githubusercontent.com/7633572/114846583-2213fa80-9ddd-11eb-8db8-5510be466fb8.gif)

__Steps to Reproduce__

1. Start connect at start event
2. Hover participant
3. Connection preview broken

__Expected Behavior__

Correct connection preview.

__Environment__

 - Library version: v8.3.0

**Comment by nikku** [comment]
I can reproduce this issue. 

It seems to be related to the start event, indeed, as previewing from a task works just fine:

![capture z4yiKR_optimized](https://user-images.githubusercontent.com/58601/114861724-f2b9b980-9ded-11eb-9d7c-4e25e5613a99.gif)

Note that technically connecting _from_ a start event does not make sense. So I presume this is an issue in conjunction with previewing + flipping the source and target of the connection.

**Comment by marstamm** [comment]
__Root cause__
The logic for reversing the preview only works if the `connectionStart` and `-end` are not specified in the event:
https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/connect/ConnectPreview.js#L30-L41

Additionally, `startPosition` can be `null`.

__Solution Idea__
Make the reverse logic independent of the null-check

**Comment by philippfromme** [comment]
@marstamm Good finding! 🏅
