### ISSUE TITLE
Inconsistent redo behaviour when recreating the first participant in the model

### ISSUE THREAD

**Issue by klicpjan** [bpmn-io/bpmn-js#1439]
__Describe the Bug__

When adding a first participant/pool into the model, the ID of the process element does not change. If I undo this action, the participant gets removed and the ID of the process still stays the same as expected. However, when I redo this undo (re-add the participant), the id of the process is different this time. 
Note: note sure if this is also a bug, but when I remove the participant via delete (removing the only participant in the model), the id of the process also changes. 

__Steps to Reproduce__

- Start with a fresh model, the process has id Process_1
- Add the first participant, the process still has id Process_1
- Undo the action. The participant gets removed and the process still has id Process_1
- Redo the undo. The first participant gets re-added, however the process now has a different id

__Expected Behavior__

I would have expected the redo action to bring the model into the same state as before, not modifying the id of the process. 

I would have also expected the "id transfer" to work both ways. The process id is typically kept the same when the first participant is added (except for the mentioned edge case). This is however not the case when removing the last participant in the model using the delete functionality (not an undo), as the id of the process changes. 

__Environment__

 - Browser: Chrome 90
 - OS: Windows 10
 - Library version: 7.3.0

**Comment by klicpjan** [comment]
.I have noticed that my library version is outdated, however the bug persistent even on the newest version (8.3.1)

**Comment by barmac** [comment]
Hi,

Thank you for reporting this. I was able to reproduce the issue. Indeed, it seems unreasonable that we re-generate the Process id. I suspect that the bug may have something to do with the [CreateParticipantBehavior](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/behavior/CreateParticipantBehavior.js).

We will happily accept a pull request with a fix. If you want to implement that, I will support you if you get stuck.

**Comment by klicpjan** [comment]
Hi,

Thank you for the reply and confirmation. Unfortunately, I am still quite a javascript newbie, and even more so a newbie to the bpmn-js library, so I am worried that I would do more harm than good by trying to fix it (I have taken a look around the file and I am not quite sure what might be causing the behaviour, unfortunately). If this issue will still be open in the future when I gradually gain more insight, I might gladly give it a go :).

**Comment by barmac** [comment]
That's OK :) Reporting a valid issue is already a great contribution.
