### ISSUE TITLE
Validation issue with Parallel Gateway

### ISSUE THREAD

**Issue by paynest1988** [bpmn-io/bpmn-js#1445]
__Describe the Bug__

__Steps to Reproduce__

1. Create a valid BPMN Model such as:
![Valid Model](https://user-images.githubusercontent.com/83663008/117046119-4bd68800-acde-11eb-9b1e-ac41f6b5b788.png)
This will validate successfully.

2. Delete nodes and rearrange to look like:
![Invalid Model](https://user-images.githubusercontent.com/83663008/117046744-09fa1180-acdf-11eb-8023-1626ac4e726b.png)
This should error out that the gateway does not have at least two paths set; however, it does not.

__Expected Behavior__

Expected behavior is that the modeler will throw an error that the gateway needs to have at least two paths set.

__Environment__

 - Browser: Chrome 90
 - OS: Windows 10
 - Library version: bpmn-js: 7.4.0

**Comment by pinussilvestrus** [comment]
Thanks for reporting! Are you referring to [our linting tool](https://github.com/bpmn-io/bpmnlint)? There you would also be able to [give more details about the validation rule](https://github.com/bpmn-io/bpmnlint/issues/new?assignees=&labels=&template=NEW_RULE.md) you're proposing.

**Comment by paynest1988** [comment]
Incorrect bug
