### ISSUE TITLE
TypeError: 'get' on proxy: property '$pkg' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '[object Object]')

### ISSUE THREAD

**Issue by xietongjian** [bpmn-io/bpmn-js#1452]
__Describe the Bug__
`index.vue:101 TypeError: 'get' on proxy: property '$pkg' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '[object Object]')
    at Proxy.Registry.getEffectiveDescriptor (index.esm.js:550)
    at Proxy.Moddle.getType (index.esm.js:768)
    at RootElementHandler.ElementHandler (index.esm.js:269)
    at new RootElementHandler (index.esm.js:526)
    at Reader.handler (index.esm.js:917)
    at Proxy.BpmnModdle.fromXML (index.esm.js:56)
    at BaseViewer.js:144
    at new Promise (<anonymous>)
    at Proxy.importXML (BaseViewer.js:138)
    at Proxy.<anonymous> (CompatibilityUtil.js:33)`

1. package.json code:
`
"bpmn-js": "^8.5.0",
    "camunda-bpmn-moddle": "^5.1.2",
`
2. index.vue code:
`
<template>
  <div class="containers" ref="container">
    <div class="canvas" ref="bpmnCanvas"></div>
  </div>
</template>
<script lang="ts">
  import { defineComponent, ref, nextTick } from 'vue';
  import { PageWrapper } from '/@/components/Page';
  import { Divider, Card, Empty, Descriptions} from 'ant-design-vue';
  import BpmnViewer from 'bpmn-js/lib/Viewer'

  import ProcessHeader from '/@/views/process/components/ProcessHeader.vue';

  export default defineComponent({
    components: {
      ProcessHeader,
      PageWrapper,
      [Divider.name]: Divider,
      [Card.name]: Card,
      AEmpty: Empty,
      [Descriptions.name]: Descriptions,
      [Descriptions.Item.name]: Descriptions.Item,
    },
    setup() {
      const bpmnCanvas = ref<ElRef>();
      const container  = ref<ElRef>();
      const bpmnViewer  = ref();

      nextTick(()=>{
        bpmnViewer.value = new BpmnViewer({
          container: bpmnCanvas.value,
          width: '50%',
          height: '50%'
        });

        const bpmnXmlStr =
          '<?xml version="1.0" encoding="UTF-8"?>\n' +
          '<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_0fppxr8" targetNamespace="http://bpmn.io/schema/bpmn">\n' +
          '  <bpmn:process id="Process_1" isExecutable="false">\n' +
          '    <bpmn:startEvent id="StartEvent_1" name="begin&#10;">\n' +
          '      <bpmn:outgoing>SequenceFlow_0nrfbee</bpmn:outgoing>\n' +
          '    </bpmn:startEvent>\n' +
          '    <bpmn:task id="Task_0ho18x0" name="hello&#10;">\n' +
          '      <bpmn:incoming>SequenceFlow_0nrfbee</bpmn:incoming>\n' +
          '      <bpmn:outgoing>SequenceFlow_00ho26x</bpmn:outgoing>\n' +
          '    </bpmn:task>\n' +
          '    <bpmn:task id="Task_1ymuvem" name="world">\n' +
          '      <bpmn:incoming>SequenceFlow_00ho26x</bpmn:incoming>\n' +
          '      <bpmn:outgoing>SequenceFlow_18df8vb</bpmn:outgoing>\n' +
          '    </bpmn:task>\n' +
          '    <bpmn:endEvent id="EndEvent_1c0ed2n" name="end">\n' +
          '      <bpmn:incoming>SequenceFlow_18df8vb</bpmn:incoming>\n' +
          '    </bpmn:endEvent>\n' +
          '    <bpmn:sequenceFlow id="SequenceFlow_0nrfbee" sourceRef="StartEvent_1" targetRef="Task_0ho18x0" />\n' +
          '    <bpmn:sequenceFlow id="SequenceFlow_00ho26x" sourceRef="Task_0ho18x0" targetRef="Task_1ymuvem" />\n' +
          '    <bpmn:sequenceFlow id="SequenceFlow_18df8vb" sourceRef="Task_1ymuvem" targetRef="EndEvent_1c0ed2n" />\n' +
          '  </bpmn:process>\n' +
          '  <bpmndi:BPMNDiagram id="BPMNDiagram_1">\n' +
          '    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">\n' +
          '      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">\n' +
          '        <dc:Bounds x="173" y="102" width="36" height="36" />\n' +
          '        <bpmndi:BPMNLabel>\n' +
          '          <dc:Bounds x="178" y="145" width="27" height="27" />\n' +
          '        </bpmndi:BPMNLabel>\n' +
          '      </bpmndi:BPMNShape>\n' +
          '      <bpmndi:BPMNShape id="Task_0ho18x0_di" bpmnElement="Task_0ho18x0">\n' +
          '        <dc:Bounds x="485" y="244" width="100" height="80" />\n' +
          '      </bpmndi:BPMNShape>\n' +
          '      <bpmndi:BPMNShape id="Task_1ymuvem_di" bpmnElement="Task_1ymuvem">\n' +
          '        <dc:Bounds x="712" y="391" width="100" height="80" />\n' +
          '      </bpmndi:BPMNShape>\n' +
          '      <bpmndi:BPMNShape id="EndEvent_1c0ed2n_di" bpmnElement="EndEvent_1c0ed2n">\n' +
          '        <dc:Bounds x="1056" y="568" width="36" height="36" />\n' +
          '        <bpmndi:BPMNLabel>\n' +
          '          <dc:Bounds x="1065" y="611" width="19" height="14" />\n' +
          '        </bpmndi:BPMNLabel>\n' +
          '      </bpmndi:BPMNShape>\n' +
          '      <bpmndi:BPMNEdge id="SequenceFlow_0nrfbee_di" bpmnElement="SequenceFlow_0nrfbee">\n' +
          '        <di:waypoint x="209" y="120" />\n' +
          '        <di:waypoint x="347" y="120" />\n' +
          '        <di:waypoint x="347" y="284" />\n' +
          '        <di:waypoint x="485" y="284" />\n' +
          '      </bpmndi:BPMNEdge>\n' +
          '      <bpmndi:BPMNEdge id="SequenceFlow_00ho26x_di" bpmnElement="SequenceFlow_00ho26x">\n' +
          '        <di:waypoint x="585" y="284" />\n' +
          '        <di:waypoint x="649" y="284" />\n' +
          '        <di:waypoint x="649" y="431" />\n' +
          '        <di:waypoint x="712" y="431" />\n' +
          '      </bpmndi:BPMNEdge>\n' +
          '      <bpmndi:BPMNEdge id="SequenceFlow_18df8vb_di" bpmnElement="SequenceFlow_18df8vb">\n' +
          '        <di:waypoint x="812" y="431" />\n' +
          '        <di:waypoint x="934" y="431" />\n' +
          '        <di:waypoint x="934" y="586" />\n' +
          '        <di:waypoint x="1056" y="586" />\n' +
          '      </bpmndi:BPMNEdge>\n' +
          '    </bpmndi:BPMNPlane>\n' +
          '  </bpmndi:BPMNDiagram>\n' +
          '</bpmn:definitions>\n';

        bpmnViewer.value.importXML(bpmnXmlStr, function (err) {
          debugger;
          console.error(err);
        });
      });
      
      return {
        container,
        bpmnCanvas,
      };
    },
  });
</script>
`
__Steps to Reproduce__

__Expected Behavior__
1. error preview

__Environment__

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

**Comment by zxiaozhou** [comment]
如果是vue3,数据不要初始化在data中就没问题，这是vue3 proxy导致的
![image](https://user-images.githubusercontent.com/62740686/119310652-a42bf480-bca2-11eb-8106-b7f371e0a66a.png)

**Comment by xietongjian** [comment]
多谢指点，问题解决了。

**Comment by zxiaozhou** [comment]
> 多谢指点，问题解决了。

我也是刚好遇到，就初始化的时候需要，，后面还是可以使用代理后的对象的，，这个是带有事件、函数、变量等等的一些信息，估计进过proxy代理后会出问题，，但是这个官方应该要做适配的
![image](https://user-images.githubusercontent.com/62740686/119429187-f4f22a80-bd40-11eb-9922-7424c4ff574d.png)

**Comment by nikku** [comment]
Unfortunately we cannot support you in languages other than English.

Maybe you could provide a code sandbox that clearly demonstrates your issue?

**Comment by qingtian5266** [comment]
终于找到你了，困扰了很久
