### ISSUE TITLE
Data Store Reference is not serialized if the first participant is an empty pool

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1456]
__Describe the Bug__

Data Store Reference is not created in the XML if the first participant is an empty pool.

__Steps to Reproduce__

1. Create a participant and morph it into an empty pool
2. Place a Data Store shape on diagram
3. Save and reopen diagram.

__Expected Behavior__

Two options:

1. DataStoreReference should be a child of the first process referenced in any participant.
2. Operation should be disallowed if there are no participants with processRef.

__Environment__

 - Browser: any
 - OS: any
 - Library version: 8.6.0

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1457
