### ISSUE TITLE
Import Class has not id property

### ISSUE THREAD

**Issue by cheepine** [bpmn-io/bpmn-js#1461]
![RefToImport](https://user-images.githubusercontent.com/74293057/120783274-7164e480-c55d-11eb-947c-3b3ebb6caf91.png)
It doen't working when I want to reference to a Import( from Definitions's imports property) in ItemDefinition . I found that Import Class has not id property in "bpmn-moddle/dist/index.esm.js" at line 2832. 
![bpmn-moddle-dist-index-esm-js-2832](https://user-images.githubusercontent.com/74293057/120782659-cc4a0c00-c55c-11eb-8c77-d21af30d363c.png)

**Comment by marstamm** [comment]
Hi,

to help us understand the issue, could you please describe what you are trying to achieve and what the expected behavior would be? You can use the [Bug Issue Template](https://github.com/bpmn-io/bpmn-js/blob/develop/.github/ISSUE_TEMPLATE/BUG_REPORT.md) for this.

**Comment by barmac** [comment]
Until we get more details, we are not able to work on this issue. Because of that, I am closing this.

**Comment by cheepine** [comment]
ItemDefinition class has a property named 'import', this property is reference. I want to reference to a Import from Definitions, but it doen't working.
![ItemDefinition](https://user-images.githubusercontent.com/74293057/123729488-a0097d00-d8c7-11eb-851c-8c84d3973051.png)

**Comment by barmac** [comment]
Import type does not have `id` property in BPMN 2.0. I looked for examples of using import with item definition and couldn't find anything helpful. Perhaps your issue can be solved without imports.
