### ISSUE TITLE
Cannot connect Message Flows to Call Activities

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1467]
__Describe the Bug__

Message Flows where a Call Activity is either a source or a target are disallowed.

According to BPMN 2.0.2 spec, a Message Flow connects Interaction Nodes. Interaction Node is a type which includes Pools, Activities and Events:

> The InteractionNode element is used to provide a single element as the source and target Message Flow associations (see Figure 9.14, above) instead of the individual associations of the elements that can connect to Message Flows (see above). Only the Pool/Participant, Activity, and Event elements can connect to Message Flows. The InteractionNode element is also used to provide a single element for source and target of Conversation Links, see page 131.

(p. 122)

Call Activity is an Activity and therefore it should be allowed to connect it with a Message Flow given the other shape is in a different Participant.

__Steps to Reproduce__

1. Create a collaboration with call activity in one of participants
2. Try to connect the call activity to another participant.

__Expected Behavior__

Call Activity is an Activity and therefore it should be allowed to connect it with a Message Flow given the other shape is in a different Participant.

__Environment__

 - Browser: any
 - OS: any
 - Library version: any modern

**Comment by barmac** [comment]
This has to be fixed within bpmn-io/bpmn-moddle: https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmn.json#L1894

[We implement the rule correctly](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/rules/BpmnRules.js#L274), it's just the schema being incorrect.

**Comment by nikku** [comment]
It is wrong in the meta-model, hence our derived moddle is wrong, too.

**Comment by barmac** [comment]
> It is wrong in the meta-model, hence our derived moddle is wrong, too.

Oops :D

**Comment by nikku** [comment]
Fun fact: We already fix this for sub-processes: https://github.com/bpmn-io/bpmn-moddle/blob/master/tasks/transforms/transformBPMN.js#L222.

**Comment by barmac** [comment]
Oh nice. I should not forget to remove that line in my fix 👍
