### ISSUE TITLE
After 8.0, I can't use ctrl and the left mouse button to select multiple nodes, it is possible before 8.0 

### ISSUE THREAD

**Issue by threefish** [bpmn-io/bpmn-js#1475]
__Describe the Bug__

After 8.0, I can't use ctrl and the left mouse button to select multiple nodes, it is possible before 8.0 .I think it's a bug . Can be reproduced on https://demo.bpmn.io/bpmn 

__Environment__

 - Browser: [ Chrome 90 ]
 - OS: [Windows 10]
 - Library version: [>8.0]

**Comment by nikku** [comment]
Thanks for opening this issue @threefish!

This seems to be a side-effect of a number of keyboard shortcut related improvements we shipped with `v8.0.0`: https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#800.

**Comment by nikku** [comment]
Also reported by [internal tester](https://camunda.slack.com/archives/CKGH9LR40/p1673445210622109).

**Comment by hkupitz** [comment]
As @marstamm told me, _Ctrl + Shift_ still works so that's a workaround for now.

**Comment by saumyaupadhyay95** [comment]
Hi @nikku, this is an important issue that my team and I are relying on to be fixed. Could you please let us know when can we have this fixed? Thanks!

**Comment by nikku** [comment]
> Could you please let us know when can we have this fixed?

This has no priority for us at the moment. The shortcut `SHIFT` is available to do multi-selection, and it is common across tools for the job.

`CTRL` is now our _drag canvas_ modifier, an important tool to navigate around larger diagrams, and clashes with the previous _add to selection_ feature.

I'll close the issue as _won't fix_.
