### ISSUE TITLE
Can't resize task box

### ISSUE THREAD

**Issue by fell-lucas** [bpmn-io/bpmn-js#1479]
__Describe the Bug__

There are no resizing handles in the online version of the tool.

__Steps to Reproduce__

1. Go to [bpmn.io](https://demo.bpmn.io/new)
2. Create a new task
3. Click on it
4. No handles to resize outwards or inwards

https://user-images.githubusercontent.com/47724710/131228609-06750747-3e4e-4b94-8a73-07ab6db0412c.mp4

__Expected Behavior__

The handles should appear and I should be able to resize the task box.

__Environment__

 - Browser: Firefox 91.0.2
 - OS: Linux Manjaro
 - Library version: v8.7.2. (as it says on the home page as of 08-28-2021)

**Comment by nikku** [comment]
Tasks cannot be resized, [for a good reason](https://forum.bpmn.io/t/resizable-tasks/480).

Closing this one as _wont fix_.
