### ISSUE TITLE
Why is the XML content of messageRef in receiveTask updated with updateProperties undefined

### ISSUE THREAD

**Issue by zxiaozhou** [bpmn-io/bpmn-js#1486]
__Describe the Bug__

Call the Modeling updateProperties method to update the receiveTask messageRef property and get undefined

__Steps to Reproduce__

1. Add the receiveTask task and add BPMN :message ID to Message_08o0uty
2.
```
bpmnModeler.get('modeling').updateProperties(element, {
        messageRef: 'Message_08o0uty',
      });
```
3. 
![image](https://user-images.githubusercontent.com/62740686/132853775-f2ed993f-d770-451d-aca1-f9470f93a32d.png)

__Expected Behavior__

1. messageRef=Message_08o0uty

__Environment__

 - Browser: [e.g. IE 11, Chrome 69]  Chrome 93
 - OS: [e.g. Windows 7] mac 11.5.2 
 - Library version: [e.g. 2.0.0]  bpmn-js  8.7.3

**Comment by pinussilvestrus** [comment]
Are you able to share your setup inside a [CodeSandbox](https://codesandbox.io/s/bpmn-js-sandbox-3zkw0)? Otherwise, it will be hard to find out what's wrong on your side.

**Comment by pinussilvestrus** [comment]
It's not enough to set the id of the message element to update a reference. You need the complete element.

```js
const task = elementRegistry.get('MessageTask_1');

const message = findElementById(task, 'bpmn:Message', 'Message_2');

modeling.updateProperties(task, {
  messageRef: message
});
```

Source: https://codesandbox.io/s/set-message-jtebu?file=/src/index.js

**Comment by zxiaozhou** [comment]
@pinussilvestrus Thank you so much
