### ISSUE TITLE
version@8 bug

### ISSUE THREAD

**Issue by ningsy1017** [bpmn-io/bpmn-js#1488]
when i use the version@8 I get the error like this : bo.get is not a function
![image](https://user-images.githubusercontent.com/20644193/133381701-728cba76-6dc2-4d68-893a-e434cfcf66d5.png)
 then i change version to ^7.4.0 it work ,why?

**Comment by nikku** [comment]
The issue is introduced with `diagram-js@7.4` and the properties panel version you're using.

Please update to the latest version of `bpmn-js-properties-panel` to resolve the issue.

See also https://github.com/bpmn-io/diagram-js/issues/568 for another issue that is tracking this.
