### ISSUE TITLE
Incorporate color and alignment helpers into context pad

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1491]
__Is your feature request related to a problem? Please describe.__

Coloring and alignment utilities are currently only exposed via API and been must be provided to users via custom UI controls. 

For the sake of a unified modeling experience it would make sense to make these elements available directly from the modeler user interface.

__Describe the solution you'd like__

These actions are available through the context pad:
* [ ] Alignment and distribution
* [ ] Coloring  (single and multi element) -> ⚠️ warn web-modeler team after release, since they currently have their own color picker built on top of bpmn-js
     * Design issue: https://github.com/camunda/camunda-modeler-design/issues/101
     * **Note:** related issue on vs-code-bpmn-io: https://github.com/bpmn-io/vs-code-bpmn-io/issues/93 (mark as fixed-upstream after color picker feature is completed

__Describe alternatives you've considered__

Keep it as is.

__Additional context__

All mentioned tools are _multi element_, which we do not support in the context pad just yet (https://github.com/bpmn-io/diagram-js/issues/278).

----

Depends on https://github.com/bpmn-io/diagram-js/pull/587
Related PR: https://github.com/bpmn-io/bpmn-js/pull/1525

**Comment by AsianCat54x** [comment]
Hey, Can I work on this issue?

**Comment by nikku** [comment]
A demo showcasing this end-to-end is [available here](https://github.com/bpmn-io/bpmn-js-color-picker/compare/master...bpmn-io:multi-element-context-pad) (link to respective `multi-element-context-pad` branches in `bpmn-js` and `bpmn-js -> diagram-js`.

__Demo using the feature end-to-end:__

![capture AJc7CN_optimized](https://user-images.githubusercontent.com/58601/140891970-8c58bd60-f05b-4bae-9111-1bb90f1499e4.gif)
