### ISSUE TITLE
Support custom disabled drag elements

### ISSUE THREAD

**Issue by Banana-energy** [bpmn-io/bpmn-js#1496]
__Is your feature request related to a problem? Please describe.__

When I want to prevent the user from dragging the element, I am very distressed, because I can't directly display a picture, I need to respond to the click event of the element.

__Describe the solution you'd like__

Support custom disabled drag elements

__Describe alternatives you've considered__

I found that this requirement can be achieved by customRules, but when I rewrite the canDrop function, it did not take effect.

__Additional context__

**Comment by Banana-energy** [comment]
I replaced the canXXX function called by the init function with the this.canXXX function, and then rewritten the canDrop function in BpmnRules.prototype, which seemed to take effect

Ex

![image](https://user-images.githubusercontent.com/49467518/135206052-a113a361-4515-45c5-aeb0-e3cf25ab10ee.png)

![image](https://user-images.githubusercontent.com/49467518/135205980-1e0dceb3-55ad-482f-9ef6-56552f90f8d3.png)

**Comment by Banana-energy** [comment]
Well, After I modified this.canXXX, rewriting the canMove function took effect发😀

**Comment by MaxTru** [comment]
Hi @Banana-energy,

following [your comment](https://github.com/bpmn-io/bpmn-js/issues/1496#issuecomment-929840993) I understand this is resolved? Closing this issue. Please feel free to re-open, in case this still is a Feature Request.

Thanks
