### ISSUE TITLE
`bpmnReplace` fails when custom meta model uses a `String` array

### ISSUE THREAD

**Issue by alexbisaillion** [bpmn-io/bpmn-js#1518]
__Describe the Bug__

I am using a custom meta model that has a property of type `String` and `isMany` set to true. I am attempting to call `bpmnReplace` (from `modeler.get("bpmnReplace")`) and an error is being thrown when the element is being copied:

![](https://i.imgur.com/TGbzNIf.gif)

The error prevents the element from being replaced.

I set up an example reproduction using one of the bpmn example [repos](https://github.com/bpmn-io/bpmn-js-example-react-properties-panel). Here's a [fork](https://github.com/alexbisaillion/bpmn-js-example-react-properties-panel) of it.

It is worth noting that the example repo was using bpmn-js v3.2.1, where the issue does not happen:
![](https://i.imgur.com/eAdMYNs.gif)

It happens with v8.8.2, so it looks like it is a regression.

__Steps to Reproduce__

1. Clone my example repo available [here](https://github.com/alexbisaillion/bpmn-js-example-react-properties-panel)
2. Run the example as normal (`npm install && npm start`)
3. Click the "Do work" task
4. Click "Make task" in the properties panel. The call to `bpmnReplace` will fail.

__Expected Behavior__

The task should be replaced successfully.

__Environment__

 - Browser: Chrome Version 95.0.4638.54
 - OS: Windows 10
 - Library version: 8.8.2

**Comment by pinussilvestrus** [comment]
Thanks for reporting! Sorry for not reaching out to you.

So you have the following metamodel

```json
{
  "name": "AnalysisDetails",
  "superClass": [."Element" ],
  "properties": [
    {
      "name": "path",
      "type": "String",
      "isMany": true
    }
  ]
}
```

How should the resulting XML look like? Something like this?

```xml
<analysisDetails path=[ "one", "two", "three" ] />
```

I'm not even sure, whether this is possible, syntax-wise. When you want to have a collection attribute, why you don't do it like this

```json
{
  "name": "Path",
  "superClass": [ "Element" ],
  "properties": [
    {
      "name": "value",
      "isBody": true,
      "type": "String"
    }
  ]
},
{
  "name": "AnalysisDetails",
  "superClass":  ["Element" ],
  "properties": [
    {
      "name": "path",
      "type": "Path",
      "isMany": true
    }
  ]
}
```

That would result in what you also defined in your [example diagram](https://github.com/alexbisaillion/bpmn-js-example-react-properties-panel/blob/master/app/diagram.bpmn)

```xml
<qa:analysisDetails">
  <qa:path>A</qa:path>
  <qa:path>B</qa:path>
  <qa:path>C</qa:path>
</qa:analysisDetails>
```

Does this resolve your error?

**Comment by alexbisaillion** [comment]
Hi there! So the resulting xml should indeed look like how I have it defined in the example diagram, so something like this:

```
<qa:analysisDetails>
  <qa:path>A</qa:path>
  <qa:path>B</qa:path>
  <qa:path>C</qa:path>
</qa:analysisDetails>
```

The main issue I would have with defining it as you suggested would be that it doesn't map well to our XML schema, which we use to create the moddle descriptor.

This should be valid in an XML schema definition:
`<xsd:element name="path" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>` 

And I think it should map to what I had in the meta model:
```
{
  "name": "AnalysisDetails",
  "superClass": [ "Element" ],
  "properties": [
    {
      "name": "path",
      "type": "String",
      "isMany": true
    }
  ]
}
```

I think your suggested meta model would look more like this in an xml schema: 
`<xsd:element name="path" type="Path" minOccurs="0" maxOccurs="unbounded"/>` .
And you would need another type defined in the definition for `Path`.

And we have been saving/updating these elements on our diagrams with no problems, except for this instance where `bpmnReplace` is failing.

**Comment by pinussilvestrus** [comment]
Thanks for sharing! 

I checked our `moddle-xml` library we use for the XML parsing and verified that we actually support the case you've mentioned. Notice that we have test cases for [reading](https://github.com/bpmn-io/moddle-xml/blob/master/test/spec/reader.js#L528-L550) and [writing string arrays](https://github.com/bpmn-io/moddle-xml/blob/master/test/spec/writer.js#L497-L518).

So indeed, that seems to be a bug in [`bpmn-js#ModdleCopy` to cover this case](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/copy-paste/ModdleCopy.js#L237). The reason for it could be that we actually don't use this format for our BPMN 2.0 descriptors, but we don't encourage that one for custom element extensions. 

Since [there is a workaround](https://github.com/bpmn-io/bpmn-js/issues/1518#issuecomment-968965131), I will move that one to backlog. We are open to contributions that improve the situation!

I'll likely follow up with a test case that reproduces the problem.

**Comment by pinussilvestrus** [comment]
With https://github.com/bpmn-io/bpmn-js/commit/ed0b5a9c38826289ab096b76e9c80579bdf94643 I added a simple test case that show cases the broken behavior.

Branch: https://github.com/bpmn-io/bpmn-js/tree/string-array-moddle
