### ISSUE TITLE
Resize handles hidden behind elements

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1520]
__Describe the Bug__

On our `develop` branch the resize handles are hidden behind elements as well as the context pad, making it hard to impossible to resize in many common usage scenarios:

__`develop`__

![capture BxYD9w_optimized](https://user-images.githubusercontent.com/58601/140287617-0a8abb8a-f486-4494-8a94-e415faff3085.gif)

__Released (`v8.8.x`, [demo](https://demo.bpmn.io/))__

![capture 09kI4y_optimized](https://user-images.githubusercontent.com/58601/140287458-eab1a288-28da-4c82-b364-a1d54b42cbc0.gif)

__Steps to Reproduce__

1. Run `npm start` on `develop` branch
2. Try resizing sub-process center left or center right
3. __Observe behavior shown above__

__Expected Behavior__

* [ ] Resize handles are shown always on top (take pointer precedence over context pad and flow handles)

__Environment__

 - Browser: Chrome
 - OS: Any
 - Library version: `bpmn-js@develop`

**Comment by marstamm** [comment]
Root Cause: the `layer-resizers` is rendered behind the Process layer:
![image](https://user-images.githubusercontent.com/21984219/140288668-c1d2e6ba-b4e4-465a-809b-3501ea41bca0.png)

Introduced with https://github.com/bpmn-io/bpmn-js/pull/1481

**Comment by nikku** [comment]
Thanks for investigating.

So we shall make sure our plane layers always sit before _always on top_ layers.
