### ISSUE TITLE
CallActivity Markers are to wide

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/bpmn-js#1527]
__Describe the Bug__

With https://github.com/bpmn-io/bpmn-js/pull/1515, we pass attrs to all render functions. This has side effects on rendering markers that were not caught in the review:

![image](https://user-images.githubusercontent.com/21984219/140744330-41b0ed21-55d7-41f7-82f4-f82731b9afbe.png)

__Steps to Reproduce__

1. Model a Call Activity
2. The Task Marker have the same strokeWidth as the border

__Expected Behavior__

- The Taskmarkers have the correct stroke width

__Environment__
- Library version: bpmn-js@dev

**Comment by marstamm** [comment]
This Issue as well as https://github.com/bpmn-io/bpmn-js/pull/1516 shows that we did not think the implementation through to the end. 

**Root Cause**
We pass attributes down the render chain (e.g. CallActivity -> SubProcess -> TaskMarkers). In the CallActivity renderer, we change the `strokeWidth` that is then used in the `TaskMarkers`. Per default, provided attrs override the default ones.

We need to decide which attribute takes precedent in certain situations, or only handle custom attributes on one level.
Both are not necessarily what a user expects, e.g. when setting the stroke color, I expect that Task markers are also in the provided color. On the other hand, I want to override all attributes.

**Comment by marstamm** [comment]
The feature was originally implemented for ghost element rendering https://github.com/bpmn-io/bpmn-js/pull/1506.
I propose to revert the changes made in the original PR. The feature was internally motivated and never shipped with a bpmn-js release. This way, we minimize the risk of overlooking something that then blows up at the users.

@nikku , can you give a quick sanity check if it is okay to revert https://github.com/bpmn-io/bpmn-js/pull/1515?

**Comment by nikku** [comment]
Let us revert it, if we found it to be only partially usable in the first place :+1:
