### ISSUE TITLE
Incorrect `BPMNEdge#waypoints` is added when creating/appending shape

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1544]
__Describe the Bug__

When I append or create a shape from another shape via the context pad, the added connection contains an incorrect attribute as seen below:

```xml
<bpmndi:BPMNEdge id="Flow_0o53f0k_di" bpmnElement="Flow_0o53f0k" waypoints="">
  <di:waypoint x="215" y="97" />
  <di:waypoint x="272" y="97" />
</bpmndi:BPMNEdge>
```

__Steps to Reproduce__

1. Append a shape via context pad
2. now this happens

I added a test case which allowed to identify the broken commit. It's on the branch: https://github.com/bpmn-io/bpmn-js/tree/incorrect-di-attrs

The test case succeeds on top of https://github.com/bpmn-io/bpmn-js/commit/c4206a4d31baf71caced240377eafe7f478e1599 but fails one commit later in the history (https://github.com/bpmn-io/bpmn-js/commit/bb9dc16cace353ccfb2e67a85e248ae91faaf962).

__Expected Behavior__

DI is correctly serialized.

__Environment__

 - Browser: any
 - OS: any
 - Library version: https://github.com/bpmn-io/bpmn-js/commit/bb9dc16cace353ccfb2e67a85e248ae91faaf962

**Comment by nikku** [comment]
Thanks for opening this issue. I'll have a look.

**Comment by nikku** [comment]
Easy fix. We accidentally broke this via https://github.com/bpmn-io/bpmn-js/commit/bb9dc16cace353ccfb2e67a85e248ae91faaf962#diff-dc6b2f2490723717034ccc2a20ba8e375f76fd64f6c4130357268a1b7ea01b0dR115.

**Comment by nikku** [comment]
We would have detected this one easily, _if_ we did run the latest trunk against our [integration test suite](https://github.com/bpmn-io/bpmn-js-integration).
