### ISSUE TITLE
Moving one element removes incoming flows of another element   

### ISSUE THREAD

**Issue by Makatumba** [bpmn-io/bpmn-js#1547]
__Describe the Bug__

__Steps to Reproduce__

1.  create two elements of the same type
2.  put the first element on the flow of the second element
3.  move the first element along the second flow

This issue can be reproduce on [demo.bpmn.io](https://demo.bpmn.io/new):

![bpmn-js](https://user-images.githubusercontent.com/16556148/144842065-924311d7-2d30-4e74-af1e-26e99dc0d762.gif)

__Expected Behavior__

- both elements keep their connections

__Environment__

 - Browser: [Chrome 95]
 - OS: [Windows 10]
 - Library version: [v8.8.2]

**Comment by nikku** [comment]
Could you elaborate what you expect here?

An _end event_ cannot have outgoing flows, hence, as you drop it on the connection the following happens: The outgoing connection (illegal) is not being created.
