### ISSUE TITLE
Builds based on `master` are broken due to incompatible diagram-js version

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js#1558]
__Describe the Bug__

Our CI on branches targeting `master` is currently broken, cf. [this build](https://github.com/bpmn-io/bpmn-js/runs/4725608553?check_suite_focus=true#step:6:18).

It's working fine locally though.

__Steps to Reproduce__

1. Checkout [this build](https://github.com/bpmn-io/bpmn-js/runs/4725608553?check_suite_focus=true#step:6:18)
2. See the build is failing on 25 broken test cases

__Expected Behavior__

Make CI work again.

__Environment__

 - Browser: not specified
 - OS: discovered on Linux & Mac, Windows seem to work fine.
 - Library version: `master`

**Comment by pinussilvestrus** [comment]
Seems like we are using a not yet supported diagram-js version (8.0.0): https://github.com/bpmn-io/bpmn-js/runs/4725608553?check_suite_focus=true#step:6:18

That throws errors due to unsupported API in Canvas#setRootElement. Maybe our `wiredeps` script is broken.

Cf. [this information](https://github.com/bpmn-io/bpmn-js/runs/4725608553?check_suite_focus=true#step:6:18) it is using diagram-js@8, although it shouldn't because of breaking changes.

**Comment by pinussilvestrus** [comment]
We are good on `develop` because we already added the necessary API updates, cf. https://github.com/bpmn-io/bpmn-js/commit/4e08a1c703e71866ef1b11d2196daa2374a618ec

**Comment by pinussilvestrus** [comment]
Seems like we don't properly skip the `wiredeps` task on `master` as expected. It works on [Windows though](https://github.com/bpmn-io/bpmn-js/runs/4725608596?check_suite_focus=true#step:6:3), maybe something breaks with the environment variables.

**Comment by pinussilvestrus** [comment]
So it seems like it is intended behavior that we [fall back to `diagram-js#develop`](https://github.com/bpmn-io/bpmn-js/blob/develop/tasks/wiredeps#L22) on any branch except `master`. In simple `push` builds, it's almost impossible to detect that `master` was the base branch. 

What we could do is to introduce a flag that can be used inside commit messages to skip wiredeps, e.g.

```vim
fix: fix a bug

[SKIP_WIREDEPS]
```

**Comment by pinussilvestrus** [comment]
@barmac @nikku do you have any thoughts about this one?

**Comment by nikku** [comment]
I shared [an alternative to consider](https://github.com/bpmn-io/bpmn-js/pull/1559#issuecomment-1008822534).

We should keep in mind that the current `develop` rework in bpmn-js is fairly un-usual and our current approach was not built with that in mind. We shall aim to make master the new stable, i.e. simply release a new bpmn-js alpha some day, soon.

**Comment by pinussilvestrus** [comment]
We decided to fix it by creating an alpha release: https://github.com/bpmn-io/bpmn-js/pull/1559
We can close this issue once the release is done.
/cc @marstamm

**Comment by marstamm** [comment]
Release is done: https://github.com/bpmn-io/bpmn-js/releases/tag/v9.0.0-alpha.0

**Comment by pinussilvestrus** [comment]
[Looks good](https://github.com/bpmn-io/bpmn-js/pull/1557), thanks @marstamm!
