### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation  On Console

### ISSUE THREAD

**Issue by 1664017494** [bpmn-io/bpmn-js#1561]
Unable to preventDefault inside passive event listener invocation  On Console

int develop environment,  move the canvas will has 
![image](https://user-images.githubusercontent.com/57864571/148635127-b9f8800d-c893-4f1b-8789-0759b178540b.png)

toSolve:

![bpmn-js控制台报错](https://user-images.githubusercontent.com/57864571/148635056-91b7b377-ab16-4439-9b21-305d742f338b.png)

change the  'event.preventDefault' or remove it ,

**Comment by pinussilvestrus** [comment]
Can you maybe use our [bug issue template](https://github.com/bpmn-io/bpmn-js/issues/new?assignees=&labels=bug&template=BUG_REPORT.md) to give further information? Thank you!

**Comment by pinussilvestrus** [comment]
I'm closing this due to incomplete information. Feel free to reopen.
