### ISSUE TITLE
Why can't the value of process's ID start with a number?  When the ID of the process is a number, rendering will fail

### ISSUE THREAD

**Issue by loongcaser** [bpmn-io/bpmn-js#1562]
Why can't the value of process's ID start with a number?  When the ID of the process is a number, rendering will fail

__Environment__
 - Browser: [e.g. Chrome 75.0.3770.100（正式版本）]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]
 - bpmn-js: [e.g. 7.5.0]

**Comment by barmac** [comment]
According to the specification, IDs have to be valid QNames and a QName cannot start with a number. If your BPMN contains "id" which starts with a number, it's a broken diagram. Cf. https://en.wikipedia.org/wiki/QName

**Comment by barmac** [comment]
BTW the error emitted by the modeler explicitly mentions the ID problem:
```
unparsable content <bpmn:process> detected
	line: 2
	column: 2
	nested error: illegal ID <2>
```

**Comment by loongcaser** [comment]
Thank you very much
