### ISSUE TITLE
Diagram jumps wrapping process in pool

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1565]
__Describe the Bug__

![capture gstW3T_optimized](https://user-images.githubusercontent.com/58601/149092385-c30308a4-e70a-4d70-bb26-4d71cd154ad6.gif)

__Steps to Reproduce__

1. model process
2. wrap in pool
3. __See diagram jump__

__Expected Behavior__

Diagram stays in current viewport.

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: `bpmn-js@develop`

**Comment by marstamm** [comment]
Root cause: 

When replacing the root element, we reset the viewport, even when it's not a plane change: https://github.com/bpmn-io/bpmn-js/blob/4e08a1c703e71866ef1b11d2196daa2374a618ec/lib/features/drilldown/DrilldownCentering.js#L14
