### ISSUE TITLE
Can not drill down after collapsing process using `undo`

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/bpmn-js#1569]
__Describe the Bug__

When I undo a expand operation, the Drilldown overlays get messed up. This Bug was introduced with the update to diagram-js@8

![Recording 2022-01-13 at 11 00 30](https://user-images.githubusercontent.com/21984219/149308587-f5332a18-8546-46f1-b9b4-782c514678b1.gif)

__Steps to Reproduce__

1. Open https://github.com/bpmn-io/bpmn-js/blob/bd20db3aba83072214585700c181761a9358e7a5/test/spec/features/drilldown/nested-subprocesses.bpmn or Model a Process with more than 2 layers
2. Expand a subprocess
3. Ctrl+Z
4. The Drilldown Buttons disapear or are on the wrong plane

__Expected Behavior__

The Drilldown overlays are on the correct plane

__Environment__

 - Browser: Chrome 90
 - OS: Linux
 - Library version: develop

**Comment by nikku** [comment]
Best bugs are no bugs! :)
