### ISSUE TITLE
Drag leads to connection errors

### ISSUE THREAD

**Issue by ys1121** [bpmn-io/bpmn-js#1577]
__Describe the Bug__
Drag leads to connection errors

__Steps to Reproduce__

![cazgy-ztg4z](https://user-images.githubusercontent.com/35028530/149933056-dee687fe-bf7c-4783-bd07-94056721a010.gif)

__Expected Behavior__

__Environment__

 - Browser: Microsoft Edge 97
 - OS: Windows10
 - Library version: 7.4.0

**Comment by pinussilvestrus** [comment]
Thanks for reporting! Can you explain in which cases you need to model such stacked tasks?

![image](https://user-images.githubusercontent.com/9433996/149934190-4d430a47-a11c-4cec-bcfe-0b0c0ebdb118.png)

**Comment by ys1121** [comment]
The figure shows the operation that can reproduce the problem. In our usage scenario, we need to draw a large number of task nodes. In this case, there will be a certain chance of wiring errors.

**Comment by nikku** [comment]
Please share more information:

* If possible, concrete steps to reproduce
* Error message (printed in DEV tools) + What happened before the error
