### ISSUE TITLE
bpmn-js dependency min-dom references security-issue flagged domify version

### ISSUE THREAD

**Issue by jafz** [bpmn-io/bpmn-js#1591]
This is a dependency tree issue, when running our project that uses bpmn-io through code vulnerability scans.

bpmn-io version 8.9.1 references min-io 3.1.3 (which is also in this repo). min-io references domify in ^1.3.1. The domify versions up to 1.4.0 have an XSS via prototype pollution security issue, that was fixed ~9 months ago with 1.4.1.

We can require domify to be ^1.4.1 in our package.json, so a workaround exists. However, I'm not certain if you'd not like to not depend on versions that have issues.

I am not sure if the bug belongs to you, as min-io would need to change first if you don't want to add domify as a direct dependency. Or whether it belongs here b/c our dependency is not min-io, but bpmn-io.
Or whether the overall idea is to depend on the lowest third-party lib version that you can use, feature/code-wise, irrespective of flagged issues in them.

**Comment by nikku** [comment]
Thanks for opening this issue. We'll check and get back to you.

To better understand, does this not auto-fix with `npm audit fix`?

Min-dom and domify both adhere to semantic versioning so that shall be picked up automatically, right?

**Comment by jafz** [comment]
Thanks, I didn't even think of that.
So, doing a new package.json with just bpmn-js, I seem to be packaging domify in version 1.4.1.
But a npm audit fix still doesn't fix this on our large project - we'd have to regenerate the lock file, I guess.

I'm now assuming that it's standard to rely on npm to fix the dependencies, so I'll just close this issue?
Correct me if I'm wrong, of course. I'm rather new to package mgmt with node.
