### ISSUE TITLE
About labels  </bpmndi:BPMNEdge>

### ISSUE THREAD

**Issue by chenaichenet** [bpmn-io/bpmn-js#1603]
When I regenerate the XML and there is a child tag < DC: boundaries >, a parent node tag < bpmndi: bpmnlabel > will be added. And the tag (< bpmndi: bpmnlabel >) is not defined during generation. Is it correct, or is there any method to avoid the generation of the tag.
The case is as follows, which is part of the newly generated XML file:
`                        <bpmndi:BPMNEdge id="line_3_di" bpmnElement="line_3" name="flow_5---flow_6">
                                <di:waypoint x="924" y="44" />
                                <di:waypoint x="1144" y="44" />
                                <bpmndi:BPMNLabel>
                                        <dc:Bounds x="997" y="19" width="74" height="14" />
                                </bpmndi:BPMNLabel>
                        </bpmndi:BPMNEdge>`

The label style I need should be as follows:

`                        <bpmndi:BPMNEdge id="line_3_di" bpmnElement="line_3" name="flow_5---flow_6">
                                <di:waypoint x="924" y="44" />
                                <di:waypoint x="1144" y="44" />
                        </bpmndi:BPMNEdge>`

The extra label should be under this label:

`<bpmndi:BPMNShape id="flow_5_di" bpmnElement="flow_5">
                                <dc:Bounds x="900" y="20" width="48" height="48" />
                        </bpmndi:BPMNShape>`

**Comment by nikku** [comment]
Thanks for opening this issue. Could you update it to [match one of our issue templates](https://github.com/bpmn-io/bpmn-js/issues/new/choose)? I'm not sure if you ask a question or would like to report a bug.

Also, what do you refer to as "re-generate the XML"? What do you start with, how do you _regenerate_?

Please provide us with the full steps (and resources, i.e. an example diagram) if you want us to reproduce a bug.

**Comment by houzhonghu** [comment]
Hello, first of all, thank you for your reply. I mentioned above that issues is a participant in the same project. The current situation is like this. In the Java environment, use dom4j to generate xml, and finally use bpmn to parse the XML file and display the nodes and connection.
By fetching the relevant data from the database, generating XML, and parsing it with bpmn, the first request (ie an empty file) is feasible and everything works fine.
But when the file exists, get the original location information from the old file, save it to the new file, and regenerate the XML, there will be several more nodes named </bpmndi:BPMNEdge>, I can't be sure this is a bug Or a technical problem, or a dom4j problem.

**Comment by nikku** [comment]
Unfortunately I cannot dive into it at this stage. Event after your explanation it is not clear how our library is part of the issue, and how I can reproduce it.

**Comment by chenaichenet** [comment]
Thank you for your reply. The problem here has been solved. It is brought when the front end passes parameters.
