### ISSUE TITLE
Creating groups inside collapsed sub-processes breaks BPMN export

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1606]
__Describe the Bug__

If I create a group inside a collapsed sub-process and save the result a warning shows on re-import:

```
unresolved reference <CategoryValue_01k5toe>
```

__Steps to Reproduce__

1. Model an embedded, collapsed sub-process and navigate to it
2. Add a group to the collapsed sub-process
3. Save the diagram
4. Re-import the diagram
5. __See the warning above `unresolved reference <CategoryValue_01k5toe>`__

__Expected Behavior__

Modeling groups does work without warnings.

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: v9.0.1

----

![image](https://user-images.githubusercontent.com/58601/154928284-a2c61a19-dd32-44d0-82b0-ac4c9b9534a0.png)

![image](https://user-images.githubusercontent.com/58601/154928464-2b3838de-133c-4a9c-9f6f-73226211a050.png)

**Comment by marstamm** [comment]
I cannot reproduce this issue. Can you share the exported XML?

![Recording 2022-02-21 at 10 46 25](https://user-images.githubusercontent.com/21984219/154929736-bdeb187b-8122-4166-b0c1-767097833e28.gif)

**Comment by marstamm** [comment]
Never mind, I can reproduce it. It's in the warnings in the promise
