### ISSUE TITLE
Custom rules, move element lines and disappear Unresolved

### ISSUE THREAD

**Issue by jonyshi** [bpmn-io/bpmn-js#1613]
__Describe the Bug__

After customizing the rule, the drag element connection is lost?

my code 

https://forum.bpmn.io/t/custom-rules-move-element-lines-and-disappear/7285

Online example:

https://codesandbox.io/s/bpm-costom-rules-rsmfhq?file=/src/rules/CustomRules.js

__Steps to Reproduce__

1. After I expanded the custom rule, the mobile element connection is lost. Do you need your help? Thank you very much!!!

__Environment__

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
Thanks for opening this issue. 

The reason that the connection disappears is that a sequence flow is not allowed between data stores.

In between data stores only associations and data associations are allowed. What is not allowed is cleaned up upon modeling.
