### ISSUE TITLE
Support auto layout

### ISSUE THREAD

**Issue by wormtql** [bpmn-io/bpmn-js#1615]
__Is your feature request related to a problem? Please describe.__

I have an application which generates bpmns, but without layout information.
Although currently there is `bpmn-auto-layout` available, in my test it does not support multiple process.
Is it possible to do an enhanced version of auto layout?

__Describe the solution you'd like__

I wish to auto layout multiple process bpmns.
It doesn't need to be beautifully layouted.

__Describe alternatives you've considered__

__Additional context__

**Comment by nikku** [comment]
We'll likely not offer automatic layout capabilities at the core of this library.

Did you open a feature request in `bpmn-auto-layout`?

Closing this as won't fix.
