### ISSUE TITLE
Sequence flow label left hanging when a subprocess is collapsed

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1617]
__Describe the Bug__

Given there is an expanded subprocess with a labeled sequence flow inside, when I collapse the subprocess, the label is left out hanging. The label is not present when I drill down and disappears when I move it in the process diagram.

https://user-images.githubusercontent.com/28307541/158175224-484937c9-669a-4e1c-a9e5-a3a6a9f52789.mov

__Steps to Reproduce__

1. Create a subprocess with a labeled sequence flow inside
2. Collapse subprocess

__Expected Behavior__

Label is moved to the collapsed subprocess diagram.

__Environment__

 - Browser: Chrome 98
 - OS: MacOS
 - Library version: most recent (demo.bpmn.io and Camunda Modeler nightly from 9. March)

**Comment by marstamm** [comment]
After ~1 hour of coming up with unsatisfying solutions, I found the actual code we should change:

https://github.com/bpmn-io/bpmn-js/blob/e41442b393f6acad8a38d1d812967e956c9ea47c/lib/features/ordering/BpmnOrderingProvider.js#L134

There is no reason to use the labelTarget as reference for the root, we can just use `newParent` to find the root. Yes, this allows labels to be on different root elements than the labelTarget, but this is only an intermediate step during moving and is not possible to achieve through normal modeling.
