### ISSUE TITLE
Synergic use of deep linking with multi-diagram plugin

### ISSUE THREAD

**Issue by Ichigo85** [bpmn-io/bpmn-js#1622]
__Is your feature request related to a problem? Please describe__

Good morning. I developed years ago a multi-diagram plugin which creates "global subprocesses" (as defined on "Fundamentals of Business Process Management" book, p. 101) and allows to navigate between them. Now i saw, with the next release of bpmn-js and  Camunda Modeler 5.0, that you worked on deep linking for subprocesses, which is strictly connected (but different) to my work.

I made a picture of what is working now.

As you see at the end of the animation, the deep linking overlay for the subprocess is lost, and I don't understand why.

__Describe the solution you'd like__

What I want is that these functionalities could work together, navigating between multiple processes AND subprocesses inside the same BPMN.

__Describe alternatives you've considered__

Another consideration would be to integrate my work on bpmn-js. My old pull request about this work was not accepted years ago.

__Additional context__
![DeepLinking MultiD](https://user-images.githubusercontent.com/27808087/158993088-cd5dab32-1bf0-40b2-afab-3adde3d3d7fc.gif)

You can check my plugin, updated for the latest modeler alpha 5.0, on [this branch](https://github.com/sharedchains/camunda-modeler-plugin-multidiagram/tree/feature/modeler-5.0), you can clone the branch in the resources/plugins directory of your Camunda Modeler 5.0 instance.

Here is the BPMN of the animation, so you can use it.
[TestMultidiagram.bpmn.txt](https://github.com/bpmn-io/bpmn-js-examples/files/8304021/TestMultidiagram.bpmn.txt)

**Comment by marstamm** [comment]
I'll take a look :eyes:

**Comment by marstamm** [comment]
I can confirm that his is a problem with our implementation:

https://github.com/bpmn-io/bpmn-js/blob/fb6c6495701e693e76c89d97cf05d96a0c7e5c35/lib/features/drilldown/DrilldownOverlayBehavior.js#L83

We add the initial overlays on `import.done`. However, this event is only fired when `viewer.importXML` is called and not for `viewer.open`. The fix is to listen to `import.render.complete` instead or fire `import.done` every time

**Comment by barmac** [comment]
OK so then we can confirm that this is a bug in bpmn-js. Thanks for looking into this @marstamm

**Comment by Ichigo85** [comment]
Hello @marstamm, thank you for your reply! So, if I am right, the first solution competes to bpmn-js, the second is on my plugin, right?
If you confirm that `import.render.complete` will be the solution, I'll wait for the next release :) thank you!

**Comment by marstamm** [comment]
Hi @Ichigo85 ,

This is a bug in bpmn-js, so we should take care of firing the correct events in the core. I will fix it before the stable release.

You could fire the `import.done` event yourself as a quick fix, but I do not recommend it. It could lead to unexpected side-effects if we decide to implement it in the core.

**Comment by marstamm** [comment]
merged with 574a674381d6449b509396b6d17c4ca94674ea1c
