### ISSUE TITLE
Provide typings as a library like @types/bpmn-js

### ISSUE THREAD

**Issue by rasoulMrz** [bpmn-io/bpmn-js#1628]
As bpmn-js is a large and complex library, using this library without typing information is really a pain! 
With the current js lib, you won't know what methods or properties you can use! so you can not take full advantage of the library!

Apart from improving usability, using the current js lib in typescript produces lots of compile erros in imports, so we need to use 'ts-ignores' all over the source codes!

with these in mind that would be nice if you provide typings in a library like `@types/bpmn-js` as other libs like 'lodash' or 'moment' do :)

**Comment by pinussilvestrus** [comment]
Thanks for opening the issue and for your feedback. There are already lots of discussions around this topic, e.g. in https://github.com/bpmn-io/bpmn-js/issues/1002. Currently, we have no plans to deliver types for `bpmn-js` and `diagram-js`, that might change in the future though. 

I close this issue as a duplicate. Feel free to provide your feedback [in the other issue](https://github.com/bpmn-io/bpmn-js/issues/1002). Let's bundle the discussions in one place / issue. 👍

**Comment by nikku** [comment]
> Apart from improving usability, using the current js lib in typescript produces lots of compile erros in imports, so we need to use 'ts-ignores' all over the source codes!

Maybe an example where typescript errors as you use it would be interesting here.

I get already fairly detailed typed feedback, as I use the library:

![capture aKxlhy_optimized](https://user-images.githubusercontent.com/58601/161442249-aac8cec3-1a61-4f82-9466-732d14a9ed13.gif)

But there may be a lot of places where there is bugs, and we shall fix these bugs with better doc comments.
