### ISSUE TITLE
`Label` property exists after clearing the name

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/bpmn-js#1637]
__Describe the Bug__

When I remove the Label of a Task, the di still has the property `label: null`. This causes issues with other tools, e.g. with linting:

![Recording 2022-04-22 at 10 13 44](https://user-images.githubusercontent.com/21984219/164674929-c8e344a5-71d1-4cab-8611-b4cd5ef87a02.gif)

__Steps to Reproduce__

1. Remove the label of a Task
2. `di.label` exists and is `null`

__Expected Behavior__

`di.label` does not exist

__Additional Context__

This was introduced with support for embedded label DIs: https://github.com/bpmn-io/bpmn-js/issues/1540

Cf. [discussion in the forum](https://forum.bpmn.io/t/clearing-labels-results-in-errors-during-bpmnlint-run/7497)

__Environment__

 - Browser: Chrome 100
 - OS: Ubuntu
 - Library version: master

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1638.
