### ISSUE TITLE
Allow to import collapsed subprocesses through API (similar to`importXML`)

### ISSUE THREAD

**Issue by rajgoel** [bpmn-io/bpmn-js#1641]
__Is your feature request related to a problem? Please describe.__

Currently it is possible to use `importXML`to load a full process model. However, there is no possibility (afaik) to load a partial model that is used to populate a subprocess.

__Describe the solution you'd like__

It would be great to have a function like `importSubProcessXML` that allows to populate the details of a collapsed subprocess. 

__Describe alternatives you've considered__

As suggested by @philippfromme  in https://forum.bpmn.io/t/import-subprocesses/7522/2 the details of subprocesses could be manually copied using the Camunda Model. However, I am searching for a way to programmatically achieve this. @nikku suggested to file an issue.

__Additional context__

In my particular use case I want to populate collapsed custom subprocesses as described here: https://forum.bpmn.io/t/programmatically-populate-collapsed-subprocess/7504/2. The problem is that the details of these subprocesses are prone to changes and cumbersome to include by adding elements line-by-line. Loading the subprocess details from a file and inserting them would be much more convenient. 

Furthermore, such a feature would also be helpful for anyone dealing with a complex process landscape in which subprocesses are modelled in independently.  An  `importSubProcessXML` function would allow to create integrated models from these subprocess-models automatically.

**Comment by rajgoel** [comment]
I just realised that both problems I mentioned above had the same cause. In the code 
```javascript
const element = targetElementRegistry.getAll().find(function(el) {
  // determine target element
  return el.id == target_id;
});
```
should be replaced by
```javascript
// paste tree
const element = targetElementRegistry.getAll().find(function(el) {
  // determine plane element to paste children
  return el.id == target_id + '_plane';
});
```
Then, the sketch of the solution should work.

**Comment by philippfromme** [comment]
> Apparently, something appears to still be wrong when copy/pasting event-subprocesses with non-interrupting start events which also appears to be an issue in https://demo.bpmn.io/new (see #1696).

I've commented on the issue you mentioned: https://github.com/bpmn-io/bpmn-js/issues/1696

**Comment by rajgoel** [comment]
Just uploaded a module that provide this functionality: https://github.com/bpmn-os/bpmn-js-subprocess-importer

Only problem is that `moddleExtensions` are not yet supported ([#1](https://github.com/bpmn-os/bpmn-js-subprocess-importer/issues/1)), because I haven't found a way to pass them to the temporary modeller required to import the XML.

**Comment by rajgoel** [comment]
The `moddleExtensions` can now be set allowing to import subprocess with cutom extensions.

**Comment by nikku** [comment]
:tada:

**Comment by nikku** [comment]
@rajgoel Consider adding your extension to the [bpmn.io awesome list](https://github.com/bpmn-io/awesome-bpmn-io) if you want others to pick it up.
