### ISSUE TITLE
`setColor` should always set the external label to "stroke" color

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js#1653]
__Describe the Bug__

When setting the color of elements with external labels, the external label is set to the "fill" color instead of the "stroke" color. This is different to the color set for embedded labels. This raises a UX concern, because of the color being so light.

⚠️ This happens if color is applied to label specifically (not when applied to target shape). 

__Steps to Reproduce__

1. select an external label 
2. use `modeling.setColor` API to change the color of the selection
3. observe external label is set to the fill color:

<img width="539" alt="Screenshot 2022-05-18 at 16 30 58" src="https://user-images.githubusercontent.com/25825387/169068231-1b495b39-b003-4dd4-a4f8-6722a688987c.png">

**Optional:** can be tested in Camunda Modeler with selection tool and Edit -> Set color :

https://user-images.githubusercontent.com/25825387/169325524-f91870f7-c0e5-4b43-999f-4045eeeb2697.mov

__Expected Behavior__

External labels should be set to the "stroke" color, as seen in the embedded labels

__Environment__
 - Library version: latest

**Comment by smbea** [comment]
This happens in [SetColorHandler](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/cmd/SetColorHandler.js). This is because when setting the color of a multi element selection, the external label is considered as a standalone element. For a single element, only the shape is selected and the label color is derived from it.

**Comment by nikku** [comment]
> warning This only happens if color is applied to selection of element + element label.

From what I found this also happens when you apply on the label itself.

**Comment by smbea** [comment]
Yes, I will update correctly @nikku
