### ISSUE TITLE
Resizing the text box of an text annotation below the constraints makes the canvas unusable

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/bpmn-js#1657]
__Describe the Bug__

Resizing the text box of an text annotation below the constraints (min height of 10px) creates _total madness_ on the canvas.
See below video to see what happens.

__Steps to Reproduce__

1. Create a text annotation
2. Write in some text
3. Resize the text box so it is too small for the text
4. The text disappears (and no matter how the box is resized, it is gone)
5. As long as the box is too small, the canvas goes mad (as the CommandStack is broken, see console)
    - Context pads appear randomly in different locations, you can not drag things, text boxes open in random places...
6. Resizing the text box to fit the text again resolves it

https://user-images.githubusercontent.com/56470362/169487504-04f107d0-c0e9-479b-9515-1b0a4f26ce14.mov

__Expected Behavior__

Annotation text boxes shouldn't be allowed to be resized below the constraints, and resizing below the constraints (for example if model loaded from external resource) should not break the canvas/command stack

__Environment__

Please complete the following information:

 - Browser: Brave 1.36.119 / Chromium: 99.0.4844.83
 - Library version: Latest bpmn-io/bpmn-js#develop with bpmn-io/diagram-js#select-hover-states as of May 20th 2022, run in Karma debugger. Does not happen in latest stable (on bpmn.io demo)

**Comment by nikku** [comment]
Can you reproduce this on demo.bpmn.io?

**Comment by christian-konrad** [comment]
@nikku Does not happen in latest stable (on demo.bpmn.io)

**Comment by nikku** [comment]
Thanks. We'd need to further investigate it / root cuase it then.

**Comment by nikku** [comment]
I cannot reproduce this locally (Chrome 100) that is:

![capture BiI5sU_optimized](https://user-images.githubusercontent.com/58601/169525790-4cab9b24-2e13-45f8-a071-1b413a283981.gif)

Please try to reproduce this on Chrome or Firefox to see if it is an actual browser issue.

**Comment by nikku** [comment]
@christian-konrad Please double-check if / how you can reproduce this reliably.

If we cannot reproduce it reliably then we have to close the issue.

**Comment by pinussilvestrus** [comment]
Any updates on this one @christian-konrad? If not, I'd like to close this one until it pops up again.

**Comment by christian-konrad** [comment]
> Any updates on this one @christian-konrad? If not, I'd like to close this one until it pops up again.

We can close it until we stumble upon it again 👍
