### ISSUE TITLE
Associations should Snap to Flow

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/bpmn-js#1660]
__Describe the Bug__

Associations should Snap to Connection
![Recording 2022-05-20 at 15 32 22](https://user-images.githubusercontent.com/21984219/169538899-2290f3dc-9d41-41b2-ab34-5e6e63d79f21.gif)

__Steps to Reproduce__

1. Connect a Association to a Flow
3. It is misaligned 

__Expected Behavior__

It snaps to the Line

__Environment__

 - Browser: Chrome 101
 - OS: Ubuntu
 - Library version: dev

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/diagram-js/pull/646.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/b158addcc8f46ecbc9210b6b569823686547a323.
