### ISSUE TITLE
When I use BpmnViewer.importXML, a scroll bar appears in the window, and this problem also exists in the official website test.

### ISSUE THREAD

**Issue by L1yp** [bpmn-io/bpmn-js#1662]
__Describe the Bug__

__Steps to Reproduce__

1. open [url](https://demo.bpmn.io/)
2. create a bpmn file and export to local driver
3. refresh [url](https://demo.bpmn.io/)
4. import a bpmn file

![image](https://user-images.githubusercontent.com/22633943/169674261-f65e1d48-1f6b-46d4-8994-c70b9944f570.png)

__Expected Behavior__

__Environment__

 - Browser: [Chrome 100.0.4896.75]
 - OS: [e.g. Windows 11]
 - Library version: [e.g. 9.1.0]

**Comment by pinussilvestrus** [comment]
Thanks for reporting! I can reproduce this[ in the demo](https://demo.bpmn.io/s/start). However, I'm not able to reproduce this locally on the current `develop` branch. 

Are you able to share how you saw the problem when using the viewer? E.g. [via Codesandbox](https://codesandbox.io/s/bpmn-js-starter-m3kex).

**Comment by L1yp** [comment]
> Thanks for reporting! I can reproduce this[ in the demo](https://demo.bpmn.io/s/start). However, I'm not able to reproduce this locally on the current `develop` branch.

I'm sorry it took so long to reply to you.

Thanks. I saw 
```css
html,body {
  margin:0;
  padding:0
}
```
 in your code and solved the problem.👍
