### ISSUE TITLE
Changing task type clears draft changes in the node name

### ISSUE THREAD

**Issue by HanselIdes** [bpmn-io/bpmn-js#1670]
__Describe the Bug__

Changing task type clears draft changes in the node name

__Steps to Reproduce__

1. Change the name of a node (DO NOT hit "Return")
2. Change the type of node

https://user-images.githubusercontent.com/17521551/171350597-66171f8a-1243-4980-b554-d40a1cd38400.mov

__Expected Behavior__

Changes are saved automatically

__Environment__

 - Browser: Version 101.0.4951.54 (Official Build) (x86_64)
 - OS: macOS Monterey v 12.3.1
 - Library version: Whatever is on https://modeler.cloud.camunda.io/

**Comment by barmac** [comment]
This needs to be fixed in https://github.com/bpmn-io/bpmn-js-connectors-extension/issues/40

**Comment by MaxTru** [comment]
Sorry for the confusion. As @barmac pointed, let's use https://github.com/bpmn-io/bpmn-js-connectors-extension/issues/40 for tracking this.

**Comment by nikku** [comment]
@HanselIdes this is not a bpmn-js issue. I've opened it in the web modeler: https://github.com/camunda/web-modeler/issues/1390. We're also tracking it up stream (https://github.com/bpmn-io/bpmn-js-connectors-extension/issues/40) so I think we're cool.

**Comment by HanselIdes** [comment]
Sure, that works for me
