### ISSUE TITLE
Multi-instance toggle loop then toggle Parallel or Sequential XML label No updates

### ISSUE THREAD

**Issue by ChaominRuan** [bpmn-io/bpmn-js#1673]
__Describe the Bug__

![GIF 2022-6-7 19-50-50](https://user-images.githubusercontent.com/61787903/172374025-61f23e34-b199-4e67-bddd-ec7a3aafdb92.gif)

__Steps to Reproduce__

1. Create Task
2. Add loop multi-instance
3. toggle Parallel or Sequential

__Expected Behavior__

XML  label： <bpmn:multiInstanceLoopCharacteristics /> or  <bpmn:multiInstanceLoopCharacteristics isSequential="true" />

__Environment__

 - Library version: 9.1.0

**Comment by nikku** [comment]
@smbea Could you have a look at this? Seems to be related to a recent multi-instance loop fix we've shipped with v9.x.
