### ISSUE TITLE
Transforming a Call Activity into a SubProcess does not resize the Shape

### ISSUE THREAD

**Issue by pihme** [bpmn-io/bpmn-js#1687]
__Describe the Bug__

There is a certain edit sequence which is a little confusing because it leads to what seems like a dead end. 

__Steps to Reproduce__

1. Create Camunda 8 BPMN diagram
2. Create a task
3. Use wrench symbol to turn the task into a call activity
4. Now observe, that the wrench menu has additional entries (which is already a bit confusing): sub-process collapsed, sub-process expanded
5. Use wrench symbol to turn the call activity into an expanded sub process
6. Now you end up with an element that visually looks like a task. But when opening the wrench menu, it only allows me to change it into an event subprocess. So I cannot go back to turn it into a call activity, and I reached a dead end.

![image](https://user-images.githubusercontent.com/14032870/175896702-5ef66d70-3a26-4f44-8e55-91dc429e4acb.png)

**Hints:** 
* I was unable to reproduce this exactly on [demo.bpmn.io](https://demo.bpmn.io/new)
* Was able to reproduce it in current web modeler 
* Was able to reproduce it in desktop modeler 5.0.0

__Expected Behavior__

* after step 3, I don't expect additional entries to appear in the wrench menu. Especially since it seems that the collapsed sub process is not fully supported UI wise in either desktop or web modeler. 
* When I use the wrench symbol to change the type of an element, I expect that I can use the same wrench symbol to change the type back

__Environment__

 - Browser: Firefox
 - OS: Ubuntu 21.04
 - Library version: Whatever is used by current web modeler and desktop modeler 5.0.0

**Comment by pinussilvestrus** [comment]
@marstamm is this related to https://github.com/bpmn-io/bpmn-js/issues/1688?

**Comment by pinussilvestrus** [comment]
Moving this to backlog then.

**Comment by philippfromme** [comment]
Fixed by https://github.com/bpmn-io/bpmn-js/pull/1720.
