### ISSUE TITLE
I can create a collapsed sub process, but cannot do anything useful with it

### ISSUE THREAD

**Issue by pihme** [bpmn-io/bpmn-js#1688]
__Describe the Bug__
In desktop and web modeler I can create a collapsed sub process, but then I cannot do anything useful with it.

__Steps to Reproduce__

1. Create Camunda 8 BPMN diagram
2. Create task
3. Use wrench menu to turn it into a call activity (this adds additional entries to the wrench menu)
4. Use wrench menu to turn it into a collapsed sub process
5. Maybe there is a trick I am missing, but in dedktop and web modeler, I don't see a way to do anything useful with it.

**Hints**

* Works great in https://demo.bpmn.io/new where I have this arrow to go into the details
* Doesn't work in current web modeler or in desktop modeler version 5.0.0

__Expected Behavior__
* Either I cannot reach that state, or
* I can navigate into the collapsed sub proces and edit it

__Environment__

 - Browser: Firefox
 - OS: Ubuntu 21.04
 - Library version: Desktop Modeler 5.0.0, current web modeler

----

Depends on https://github.com/camunda/camunda-bpmn-js/pull/139

**Comment by christian-konrad** [comment]
Additionally to that, you can not convert a task into an expanded subprocesses in the Web Modeler with the wrench action; you need to convert it to a call activity, first. This needs to be fixed, too.

**Comment by marstamm** [comment]
As long as Cloud does not support collapsed subprocesses, I think it should work like it did with previous modeler releases.

This means that you can model collapsed subprocesses (for non-execution or compatibility usecases) and expand them, but can't collapse subprocesses. It is a bug that the expand option is not available in cloud modeler, which will be addressed in https://github.com/camunda/camunda-bpmn-js/pull/139

![Recording 2022-07-06 at 13 32 04](https://user-images.githubusercontent.com/21984219/177540905-3c2be33e-9e44-4735-845f-b6698289027e.gif)

**Comment by nikku** [comment]
@marstamm What is the status of this issue? I do not see any PR referencing it.

**Comment by marstamm** [comment]
This was an issue in camunda-bpmn-js and was released as v0.16.0 and modeler 5.2.0
