### ISSUE TITLE
bundle bpmn-js as webjar

### ISSUE THREAD

**Issue by zerounix** [bpmn-io/bpmn-js#169]
it should be possible to use bpmn-js as a webjar in JSF or different maven build environments.

I already bundled a lib here: https://github.com/zerounix/webjar-bpmn-js

The webjar bundles 2 Versions, 
- the bpmn-viewer -
  i build that with you example project: https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-bower-bundle and added a grunt browserify:uglify task to it, so i get the minified and non minified version
- the bpmn-modeler which i took from your demo page

Could you please review the webjar project especially the pom.xml (licensce etc.)

In the next step it would be cool, if these versions, i manually assembled, build in a bpmn-js github project, so the webjar can take it from there.

So we can download 4 artefacts:
- bpmn-js-viewer.js and bpmn-js-viewer.min.js (bundled with the zoom and scroll dependencies)
- bpmn-js-modeler.js and bpmn-js-modeler.min.js

regards,
Daniel

**Comment by Nikku** [comment]
I have two of questions:

* Should both modules contain the full sources (including external libs) or only bpmn-js and the other core libraries?

* Could we uses [bower-bpmn-js](https://github.com/bpmn-io/bower-bpmn-js) as a starting point for the packaging-as-webjar?

**Comment by Nikku** [comment]
One way to build the webjar-bpmn-js project can be that it pulls bpmn-js via npm and builds the artifacts itself. This can easily be established similar to [custom-bower-bundle](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-bower-bundle).

I am happy to provide you with an example of how to do it.

**Comment by zerounix** [comment]
i would not bundle the full depencies in bpmn-js, just the included diagram-js libs. jquery-mousewheel etc. can be downloaded via webjars again. i would take care of this via maven see https://github.com/zerounix/webjar-bpmn-js/blob/master/pom.xml the dependencies section.

i will check the bower project and come back.

**Comment by zerounix** [comment]
I think the bower-bpmn-js project would be my bpmn-js-viewer, yes.

could you please provide me an example how to do that npm pull?

**Comment by zerounix** [comment]
Hi Nico,

so if i coild get the assets into npm i could use this maven plugin i just found https://github.com/mulesoft/npm-maven-plugin

**Comment by zerounix** [comment]
Hi,

i had a chat with the guy from the webjars project and rebuild my webjar project according to his advice.

One thing still bugs me a litte, is that i could not find a prebuild modeler asset on github. So i downloaded it from demo.bpmn.io/vendor/bpmn-js/bpmn.min.js.

Do you have that anywhere prebuild?

I will submit the webjar now, if thats ok for you?

greets,
Daniel

**Comment by Nikku** [comment]
Is it possible to republish a webjars bundle under a different name in the future?

I had a closer look into the webjars topic today. Before we can actually support this we would need to 

* publish the modeler via bower (get it via a proper build artifact), cf. #154
* add the navigation modules to the viewer and/or publish a separate viewer + navigation distro

We will resolve these issues somewhere in the future. I'd love to wait and publish the webjar based on proper build artifacts.

**Comment by zerounix** [comment]
That is ok for me. It is still possible to have minor versions of webjars, like 0.7.0-0.

Do you have an idea when there will be these artefacts?

We will wait and deploy the artefact to our company nexus till then.

**Comment by Nikku** [comment]
We provide (viewer + navigation) packages and the modeler prebundled with our next release via [bower-bpmn-js](https://github.com/bpmn-io/bower-bpmn-js). 

Are you ok with the webjar project to the bpmn-io organization?
I'd love to make you the maintainer of this project, too since you have been the one initiating it and using it.

As said, we would provide the complete tested and bundled files with every release. There should not be much work involved with publishing the webjars project.

**Comment by zerounix** [comment]
That's totally ok for me. Just let me know when to do anything.

**Comment by Nikku** [comment]
You received an invitation the bpmn-io organization as the maintainer of [webjar-bpmn-js](https://github.com/bpmn-io/webjar-bpmn-js). 

I added two issues that reflect the remaining work todo.

A complete webjar bundle including the viewer+navigation + modeler will ship with the next version of bpmn-js.
