### ISSUE TITLE
Unnecessary scrollbar appears on pages that include bpmn.js

### ISSUE THREAD

**Issue by OmranAbazid** [bpmn-io/bpmn-js#1692]
__Describe the Bug__

There is an unnecessary scrollbar appearing on pages that include bpmn.js

This is caused by a weird svg element on the page named: 'helper-svg'
![Screenshot 2022-07-06 at 11 40 43 AM](https://user-images.githubusercontent.com/9063094/177521256-4944ca08-7000-4b19-a770-6f78a23ed726.png)

__Steps to Reproduce__

1. Go to https://demo.bpmn.io/s/start (preferably on Windows)
2. You will see a scrollbar as shown: 

![image](https://user-images.githubusercontent.com/9063094/177520884-0b64b45e-a495-43a9-ab49-38d22ef34a1e.png)

__Expected Behavior__

No scrollbar should appear

__Environment__

 - Browser: Chrome, 103
 - OS: Windows 11
 - Library version: 9.2.2

---

Depends on https://github.com/bpmn-io/diagram-js/pull/657

**Comment by nikku** [comment]
Thanks for opening this issue. Weird element indeed.

Fixed upstream via https://github.com/bpmn-io/diagram-js/pull/657

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/5a75bab2fc5b893b147f8d50d79484522eaaebab.
