### ISSUE TITLE
Copy/paste of event-subprocess turns non-interrupting message start event to untyped start event

### ISSUE THREAD

**Issue by rajgoel** [bpmn-io/bpmn-js#1696]
__Describe the Bug__

When copy/pasting an event-subprocess on [demo.bpmn.io](https://demo.bpmn.io/new) the type of the start event is not correctly copied.

After copying and before pasting the modeller shows:

![Copy](https://user-images.githubusercontent.com/4448455/178283898-9824497d-cc56-4c80-987d-aaea06527438.png)

After pasting the modeller shows:

![Paste](https://user-images.githubusercontent.com/4448455/178284106-7675e82d-cde7-4586-908b-17022946b6f6.png)

__Steps to Reproduce__

1. Create an event-subprocess in https://demo.bpmn.io/new 
2. Change start event to non-interrupting message start event 
3. Select event-subprocess and press CTRL-C
4. Press CTRL-V and click 

__Expected Behavior__

The type of the start event should be the same as in the original event-subprocess.

__Environment__

 - Browser: FF101
 - OS: Ubuntu 18.04
 - Library version: https://demo.bpmn.io/new on July 11, 2022

**Comment by rajgoel** [comment]
Interestingly, copying a non-interrupting start event into an existing event-subprocess appears to work as expected in the demo modeller.

**Comment by philippfromme** [comment]
Hey, thanks for creating this issue. I've looked into it and it seems to be an issue with [BpmnRules](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/rules/BpmnRules.js#L670). The start event gets replaced by a blank start event after it was pasted because of the rules assume it was pasted onto the process even though it's a child of the sub-process.

**Comment by rajgoel** [comment]
Just tried out this fix  https://github.com/bpmn-io/bpmn-js/commit/71416249d50cf54f261a92e22965f1d99bbe18f3 by @barmac and it appears to solve the issue.

**Comment by philippfromme** [comment]
> Just tried out this fix [7141624](https://github.com/bpmn-io/bpmn-js/commit/71416249d50cf54f261a92e22965f1d99bbe18f3) by @barmac and it appears to solve the issue.

I'm currently working on this. Expect this to be fixed very soon.

**Comment by philippfromme** [comment]
Fixed by https://github.com/bpmn-io/bpmn-js/pull/1699
