### ISSUE TITLE
Resizing Group Using Space Tool Breaks Application

### ISSUE THREAD

**Issue by emaveric** [bpmn-io/bpmn-js#1705]
__Describe the Bug__

__Steps to Reproduce__

1. Create new bpmn diagram on https://demo.bpmn.io/
2. Add group
3. Activate space tool and use on group
4. Move group with space tool up
5. Space tool stuck and can be dropped only after 2 clicks
6. After drop all elements can't move
[](url)

__Expected Behavior__

Space tool don't stuck and elements can move

__Environment__

 - Browser: Chrome 101, Yandex browser 21.2
 - OS: Mac and Win 10
 - Library version: v9.3.0
[](url)

**Comment by emaveric** [comment]
https://user-images.githubusercontent.com/49570281/184382317-54b6ba29-1387-4c1c-b590-f1d2e5c902e6.mov

**Comment by pinussilvestrus** [comment]
Seems like errors are occuring when one tries to resize a group below the min-height. I see these errors in the Chrome Dev Tools logs:

```
unhandled error in event listener Error: width and height cannot be less than 10px
    at hh.execute (ResizeShapeHandler.js:50:11)
    at CommandStack.js:415:31
    at rm._atomicDo (CommandStack.js:377:5)
    at rm._internalExecute (CommandStack.js:408:8)
    at rm.execute (CommandStack.js:153:8)
    at Oh.resizeShape (Modeling.js:445:22)
    at SpaceToolHandler.js:81:20
    at b (index.esm.js:145:16)
    at fh.resizeShapes (SpaceToolHandler.js:78:3)
```

**Comment by pinussilvestrus** [comment]
Sounds like a nice spring cleaning topic 👍

**Comment by philippfromme** [comment]
We may be missing the minimum dimensions for group elements.
