### ISSUE TITLE
Drag the node position. The arrow of the line is hidden behind the node

### ISSUE THREAD

**Issue by Aifomy** [bpmn-io/bpmn-js#1732]
__Describe the Bug__

Drag the node position. The arrow of the line is hidden behind the node

__Steps to Reproduce__
1.Initialize a start node, drag another node A, and connect the start node to node A with a line
2. Drag the position of node A multiple times.
3. The arrows of the lines are occasionally hidden under node A.

![image](https://user-images.githubusercontent.com/38654496/187574040-fa2ea229-dbd9-46b4-a134-ba44400ce6a2.png)
![image](https://user-images.githubusercontent.com/38654496/187574087-f39e982e-2742-415c-9eb4-62d7a5b1fd48.png)

**Comment by nikku** [comment]
@Aifomy Thanks for opening this bug.

Unfortunately we cannot help you with custom modelers built on top of the bpmn-io tooling, _unless_ you provide us sufficient ways to reproduce it (i.e. a code sandbox).

Are you able to reproduce your issue in stock bpmn-js, i.e. https://demo.bpmn.io/s/start?

I was not so I assume this is a bug in some of the extensions you provided.

**Comment by pinussilvestrus** [comment]
@Aifomy any updates on this one?
