### ISSUE TITLE
`modeling#setColor` sets color on BPMNPlane

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1734]
__Describe the Bug__

`bpmn-in-color` extensions can be used only on BPMNShapes, BPMNEdges, and BPMNLabels. The `modeling#setColor` allows to set color on any DI element though.

Cf. https://github.com/bpmn-io/bpmn-js-integration/runs/8151588491?check_suite_focus=true#step:6:350

__Steps to Reproduce__

At https://demo.bpmn.io/s/start, open the devtools, and paste the following commands:

```javascript
const { modeler } = bpmnio
const elements = modeler.get('elementRegistry').getAll()
modeler.get('modeling').setColor(elements, { fill: 'black', stroke: 'white' })
elements[0].di.$attr
{background-color: '#000000', border-color: '#ffffff', stroke: '#ffffff', fill: '#000000'}
```

Notice that process' DI contains invalid attributes.

__Expected Behavior__

The handler should ignore DI elements which cannot have colors.

__Environment__

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
Good one. You'd like to fix it right away? Otherwise let's move it to backlog and mark as `spring cleaning`.

**Comment by barmac** [comment]
Not sure. Let's move it to the backlog for now.
