### ISSUE TITLE
Connector icon is not being displayed 

### ISSUE THREAD

**Issue by Hafflgav** [bpmn-io/bpmn-js#1739]
__Describe the Bug__
There is an issue displaying the connector icon. 

__Steps to Reproduce__

1. Create a connector in Web Modeler 
2. Apply it to a service task
(p.s. you can make it visible by resizing the picture) 
![image](https://user-images.githubusercontent.com/30292227/190349937-04f6115f-41fd-4902-afb8-d32e4764168d.png)
https://user-images.githubusercontent.com/30292227/190350074-5d015b00-831a-408e-89ef-f0fafb89b033.mp4

__Expected Behavior__
Icon is visible right away without resizing it. 

__Environment__
 - Browser: Chrome 105.0.5195.102 
 - OS: MacOS 12.5.1
 - Library version: Camunda 8 SaaS

**Comment by nikku** [comment]
Please raise this with operate! They need to upgrade to the latest camunda-bpmn-js version, specifically bump https://github.com/bpmn-io/element-templates-icons-renderer.

**Comment by Hafflgav** [comment]
Thanks for chiming in @nikku, is this also valid for the video which shows the issues in Web Modeler?

**Comment by nikku** [comment]
Happy to dive into the web modeler issue if you provide me with the template that is broken.

**Comment by francav** [comment]
@nikku This is the template in use when the issue was found: https://github.com/francav/hey-duedate/blob/c8-connector/c8-connector/element-templates/template-connector.json

**Comment by Hafflgav** [comment]
Thanks @nikku and @francav, 
I will create two additional ones 👍

**Comment by nikku** [comment]
For context: We did not enforce an icon size / re-scaled for 8.0 (operate). 

For 8.1+ we do enforce the icon size consistently, across the whole tool stack. @francav if you'd like to stay backwards compatible with the template you have to re-scale the icon manually to 18x18 pixel (cf. [documentation](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/defining-templates/#icons)).

**Comment by francav** [comment]
Great, thanks @nikku
