### ISSUE TITLE
Is the bpmn2:documentation tag available?

### ISSUE THREAD

**Issue by shellmann** [bpmn-io/bpmn-js#174]
Hi, I was wondering if the bpmn2:documentation tag for the elements is available in the online modeler?

**Comment by nikku** [comment]
Yes it is. What would you like to do with it?

**Comment by shellmann** [comment]
I would like to use it. Can you tell me where to find this feature?

**Comment by nikku** [comment]
Would you like to 

* read stuff from the documentation tag?
* write stuff to the documentation tag?
* display overlays based on the documentation tag?

You can find a complete example of how to use the documentation tag to read, display and write documentation tag based meta data in the [bpmn-js-embedded-comments](https://github.com/bpmn-io/bpmn-js-embedded-comments) example application.

Feel free to reopen this issue if you have any concrete questions.

**Comment by shellmann** [comment]
Ah ok, thanks. I would like to write stuff to the documentation tag. I thought this is implemented within http://demo.bpmn.io, but that's not the case, right?
I tried to set up the project on my own, but I get some error.

Doesn't matter, I will stay to the camunda modeler within eclipse.


...:bpmn-js user$ grunt --version
grunt-cli v0.1.13

module.js:340
    throw err;
          ^
Error: Cannot find module 'inherits'
...

**Comment by nikku** [comment]
Simply populating a documentation tag with custom content is not implemented in the demo as of yet.
