### ISSUE TITLE
Token Simulation

### ISSUE THREAD

**Issue by beckonline** [bpmn-io/bpmn-js#175]
Would it be possible to create a token simulation example?

Thanks

**Comment by nikku** [comment]
What are your requirements to "token simulation"?

The feature is not implemented yet. I personally consider it something interesting for the future to look into thought.

**Comment by Florian79** [comment]
but is there an equivalent for the previous Executor.js
https://github.com/camunda/camunda-bpmn.js/blob/master/src/bpmn/Executor.js

**Comment by martinschimak** [comment]
As you @nikku ask for requirements, I would like to be able to 'explain' process models by showing small animations of certain pathes choosen by me. So I imagine to be able to 'feed' process path information into bpmn-js and as a consequence get the path animated step by step without intervening any further. It should be possible to influence the animation speed and turn on/off repetition.

As an enhancement, I would like to be able to stop at certain defined points and pop up further explanation oriented overlays for a definable amount of time, after which the animation continues.

**Comment by berndruecker** [comment]
This is comparable to the TOken Simulator once written by students from Thomas Allweyer in Swing (you can run that yourself here: https://svn.camunda.com/training/ca020%20-%20Praxiskurs%20BPMN/Tokentool/ - use your LDAP credentials). Quite nice actually!

**Comment by vkatushenok** [comment]
Requested during the training again

**Comment by ngarimalla** [comment]
I am not able to access the code in  https://svn.camunda.com/training/ca020%20-%20Praxiskurs%20BPMN/Tokentool/ . Can someone please help? We are looking for a token simulator code on top of  bpmn-js. Thank you in advance!

**Comment by berndruecker** [comment]
That tokentool was an old implementation using Java Swing. Will not help you and is deprecated anyway. Feel free to build something on top of bpmn-js and share :)

**Comment by philippfromme** [comment]
This is now in the making. https://github.com/bpmn-io/bpmn-js-token-simulation
