### ISSUE TITLE
Double click event not firing reliably every time

### ISSUE THREAD

**Issue by 04756** [bpmn-io/bpmn-js#1753]
__Describe the Bug__

This issue has been discussed in the forum: https://forum.bpmn.io/t/element-dblclick-is-not-work-fluently/8121

I change the stroke color when the element be selected, but it will make dblclick hard to trigger. May be the reason is the “selection.changed” did not finish in the first click, and when I secondly click the same element it will trigger “selection.changed” again. Then it makes a conflict. I wonder how to solve it? Thanks!

https://codesandbox.io/s/eloquent-darkness-tg8cwz?file=%2Fsrc%2Findex.js:610-1002

__Steps to Reproduce__

1.  Try dbclick to connect
2. Check the console. There may be no console output every time dbclick connects.

__Expected Behavior__

The console has log when I db click the connection, and the color of connection changes with my action.

(Hope this issue can be fixed in version 8.x, thanks! : ))

__Environment__

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 10]

**Comment by barmac** [comment]
The code you shared updates the XML each time the color is changed. This causes the elements to be redrawn and thus can lead to problems with click events. If you want to color selected elements in the UI only, use CSS for this. Check out this codesandbox: https://codesandbox.io/s/affectionate-wildflower-usznl6?file=/src/index.js

**Comment by 04756** [comment]
> The code you shared updates the XML each time the color is changed. This causes the elements to be redrawn and thus can lead to problems with click events. If you want to color selected elements in the UI only, use CSS for this. Check out this codesandbox: https://codesandbox.io/s/affectionate-wildflower-usznl6?file=/src/index.js

Hi, thanks for your help! But this codesandbox does not change the color of the marker, could you help me to change the whole connection color include the marker when it is selected. Now, I only know change the marker color via rewrite the drawConnection method, but this way need to trigger the connection redraw manually when the selection collection changed.

**Comment by 04756** [comment]
And I hope you can re-consider to fix this issue. In my own opinion, it is still issue when I have different connection color initially, the !important hacker attribute will cause the modeling.setColor not work as expected.
