### ISSUE TITLE
Space tool resizes empty pool vertically

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1769]
__Describe the Bug__

An empty pool has a dedicated, fixed height shape to distinguish it from lanes / expanded pools. Using the space tool it gets resized however:

![capture SiJdcQ_optimized](https://user-images.githubusercontent.com/58601/201333134-d400f316-8fa1-4de2-a48a-d10d1a7938bf.gif)

__Steps to Reproduce__

1. Model an empty pool
2. Use space tool on top of empty pool

(Can be reproduced on https://demo.bpmn.io/s/application-processing).

__Expected Behavior__

Empty pool does not resize (vertically).

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: v10.x, https://demo.bpmn.io

**Comment by MaverickDe** [comment]
Hi, can I get assigned to this issue, Thanks

**Comment by nikku** [comment]
@MaverickDe If you're interested go ahead and file a PR.

**Comment by jyzib** [comment]
Hi, can I get assigned to this issue, Thanks

**Comment by nikku** [comment]
@jyzib You don't need to be assigned. If you want to contribute, please open a PR that fixes this issue (or attempts a fix).

**Comment by hkupitz** [comment]
I have a fix ready for the space-tool behavior, but I wonder if it _generally_ should be impossible to resize an empty pool vertically.

The bug description by @nikku says:

> An empty pool has a dedicated, fixed height shape to distinguish it from lanes / expanded pools. Using the space tool it gets resized however:

Maybe I am misunderstanding this, but should the following be possible or not?

![emptypool](https://github.com/bpmn-io/bpmn-js/assets/27265759/4b970d48-442e-4f41-bff6-b1e25117eadf)

**Comment by nikku** [comment]
@hkupitz That is an interesting question. I'd argue: A default size empty pool makes it simpler to recognize it and not confuse it with a lane. So :+1: from my side.

**Comment by hkupitz** [comment]
I think using the spacing tool along the x-axis should be allowed as empty pools quite often stretch along another accompanied pools:

![spacetool_yaxis_disabled](https://github.com/bpmn-io/bpmn-js/assets/27265759/5c7ef6b5-c2f1-43b4-9cb5-8ab43a1ec256)

When disabling both axes, this leads to - in my opinion - unexpected behavior:

![spacetool_fully_disabled](https://github.com/bpmn-io/bpmn-js/assets/27265759/6cf0036a-3020-4781-a6f2-32c767222cb6)

What do you think, @nikku?

**Comment by nikku** [comment]
100% agreed.
