### ISSUE TITLE
Problem: overlapping connections make it very hard to work with bendpoints

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#177]
It is currently not very comfortable to edit bendpoints on overlapping connections

![image](https://cloud.githubusercontent.com/assets/3829733/5915836/b87338dc-a60a-11e4-955c-cfe6b75ab0ac.png)

**Comment by ISO50** [comment]
Is this also an issue if both connections does not have the same source and target nodes?

**Comment by nikku** [comment]
Fixed with recent release.

A user can select a connection to make sure the edit handles are accessible (always on top).
