### ISSUE TITLE
The default startEvent node cannot be connected to the callActivity node in a straight line 

### ISSUE THREAD

**Issue by ChaominRuan** [bpmn-io/bpmn-js#1774]
__Describe the Bug__

When creating a new process in bpmn or camunda there is a default startEvent node, 
which is not connected to the callActivity node in a straight line

![1](https://user-images.githubusercontent.com/61787903/202188569-f60e94db-6ebc-497a-9097-a887ac1031f1.gif)

__Steps to Reproduce__

1. Create a new process, **do not move the default startEvent node**
2. Drag a callActivity node and drop it when it is aligned with the startEvent node display
3. Connecting the startEvent node to the callActivity node
4. We will find that they cannot join a straight line when connecting

This does not happen if the default startEvent node is moved, I only found this with the callActivity node and not with the others.

**The default startEvent node coordinates are x="156" y="81"**
```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" id="Definitions_16seury" targetNamespace="http://bpmn.io/schema/bpmn" exporter="bpmn-js (https://demo.bpmn.io)" exporterVersion="10.2.1">
  <bpmn:process id="Process_0qet8w8" isExecutable="false">
    <bpmn:startEvent id="StartEvent_1gu8un6" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_0qet8w8">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1gu8un6">
        <dc:Bounds x="156" y="81" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

__Expected Behavior__

Expect to be able to connect a straight line
![image](https://user-images.githubusercontent.com/61787903/202338379-bcbb36ab-5f14-4bdf-a588-c4c30a7bb6d3.png)

__Environment__

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
I can reproduce this. Seems like the initial diagram start event position is one pixel of, vertically.

**Comment by nikku** [comment]
Addressed with recent demo deployment.
