### ISSUE TITLE
Integrate new poupMenu

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js#1775]
__What should we do?__

Integrate the new popupMenu in replace and align/distribute menus.

__Why should we do it?__

To improve look and feel of popup menu and prepare for replace anything.

**Comment by philippfromme** [comment]
_Change element_ and _Align and distribute_ works for me. ✔️

**Comment by christian-konrad** [comment]
I'd go for `Align and distribute` as well

**Comment by christian-konrad** [comment]
![Bildschirmfoto 2022-11-17 um 11 03 02](https://user-images.githubusercontent.com/56470362/202416835-0e804eea-619b-45cc-98e6-6dd70ef69440.png)

Maybe improving tooltips in the future could also help here (cf. Miro)

**Comment by philippfromme** [comment]
I agree with @christian-konrad. I guess, the alignment and distribution icons can be understood without a title.

**Comment by nikku** [comment]
No titel is fine. Same for the color picker.
