### ISSUE TITLE
I can draw a connection from and to the same element

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#178]
AT:
- source and target of the connection are the same element
- proper auto layouting for this kind of connections exist

**Comment by adi64** [comment]
I'd like to extend the modeler to be able to model self-loops. Extending the rules was trivial, thanks to the extensible nature of bpmn-io.

It seems as if the layouting part is on the backlog -- could someone maybe point me in the right direction? Maybe it's easy enough so I can contribute (or at least hack something for my need) :)

**Comment by nikku** [comment]
Essentially you'd need to extend [`ManhattanLayout`](https://github.com/bpmn-io/diagram-js/blob/master/lib/layout/ManhattanLayout.js) to support circular (back-to-self) connections.

Debug into [`#repairConnection`](https://github.com/bpmn-io/diagram-js/blob/master/lib/layout/ManhattanLayout.js#L213) to see how it is invoked during modeling.

**Comment by nikku** [comment]
Adressed via https://waffle.io/bpmn-io/tasks/cards/5b4616b5cf90730011b55003.
