### ISSUE TITLE
trying to update attributes of different subprocesses's elements

### ISSUE THREAD

**Issue by samarthvaish** [bpmn-io/bpmn-js#1781]
__Describe the Bug__
I have a list of elements that are present in different subprocess 
suppose that subProcess 1 contains element1 and element2,  subprocess 2 contains element 3 and element 4
subProcess 1 
- element 1
- element 2

subProcess 2
- element 3
- element 4

and I have a list of elements to update their attributes
list = [element 1, element 2, element 3, element 4]

I used modeling.updateProperties() method inside for loop to update their attributes.

after updating their attributes when I get the XML only the elements of the last subprocess in the list get updated (in this case last subprocess is subProcess 2  and attributes of element 3 and element 4  are updated.).

__CODE__

here is the code:-
```javascript
import Modeler from "bpmn-js/lib/Modeler";
// create modeler
const _modeler = new Modeler({ container: '#container', propertiesPanel: { parent: '#properties' } });

// list of BPMN element object that are present in different subprocesses
const elements_list = [ [element_object , {"attribute_name": "value"}] , ....]

// updating their attribute
for(let i = 0; i < elements_list .length; i++){
             const modeling = _modeler .get('modeling');
            modeling.updateProperties(elements_list[i][0], elements_list[i][1]);
}

// get the updated XML 
_modeler.saveXML({ format: true }).then({ xml } => console.log(xml));
```
__Steps to Reproduce__

1. get the list of elements that are present in different subprocesses.
2. update their properties with modeling.updateProperties(element_object, {attribute_name : "value"}) inside for loop.
3. get the updated XML from modeler.
4. check XML if all the element's attributes are updated.

__Expected Behavior__
all the element's attributes should be updated.

__Environment__

 - Browser: Chrome  version - 107.0.5304.108
 - OS:  Windows 10
 - Library version: bpmn-js 7.3.0

**Comment by nikku** [comment]
@samarthvaish Looks like it could be fairly straight forward for you to create a code sandbox that reproduces your issue. Would you do that? Otherwise we have a hard time to dig into this report.

There is no good reason why what you describe _should not_ work.

**Comment by nikku** [comment]
Closing this due to lack of feedback.
