### ISSUE TITLE
Improve auto layouting and connection bend points

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#179]
Situation:
- I manually adjust the connection of a flow and a task (see image)
![image](https://cloud.githubusercontent.com/assets/3829733/5916344/76f4aeda-a610-11e4-9c96-9e7da6679f00.png)

- then I move the task downwards

Problem
- I want my connection point to stay the same, but it is readjusted to the middle

![image](https://cloud.githubusercontent.com/assets/3829733/5916398/02903720-a611-11e4-993c-7cf787d55f93.png)

**Comment by gimbel** [comment]
Hint: This is a specific observation which struck me, but I am unsure of the general solution to this problem

**Comment by nikku** [comment]
Going to fix this as part of #249
