### ISSUE TITLE
connection `bpmn:Association` will disconnect after moving shape

### ISSUE THREAD

**Issue by Vinsea** [bpmn-io/bpmn-js#1792]
__Describe the Bug__
the connection of type `bpmn:Association` will disconnect after move shape

__Steps to Reproduce__

1. add a rules:
  ```js
  this.addRule(['connection.create', 'connection.reconnect'], 1500, function(context) {
     if(source/target is dataobjectref){
        return { type: bpmn:bpmn:Association }
    }
  })
  ```
3. connect a dataobjet and a shape
4. move shape

![2022-12-12 11 47 36](https://user-images.githubusercontent.com/25002974/206958127-17e857c9-26b8-41e6-a590-e01499ab89ed.gif)

__Expected Behavior__

connection still exist

__Environment__

 - Browser: Chrome 107
 - OS: mac
 - Library version: 
   - bpmnjs: 9.3.2
   - diagramjs: 8.9.0

__My Solution__
I found out it will work when connection source is not `dataObject` , so I add a rule:
```js
this.addRule(['connection.create', 'connection.reconnect'], 1500, function (context) {
            const source = context.source;
            if (is(source, 'bpmn:DataObjectReference')) {
                return false;
            }
})

**Comment by nikku** [comment]
@Vinsea The element you have to test against is the `bpmn:DataObjectReference` indeed.

`bpmn:DataObject` is a non-visual element, represented visually through `bpmn:DataObjectReference`.

**Comment by Vinsea** [comment]
@nikku sorry I didnt write right, Im sure do test on `bpmn:DataObjectReference`, this is my codes:

### custom palette
```js
assign(actions, {
    'create.data-object': createAction(
      'bpmn:DataObjectReference', 'data-object', 'bpmn-icon-data-object'
    ),
}
```

### custom rules
```js
function canConnect(source, target) {

  if (source.type === 'bpmn:DataObjectReference' || target.type === 'bpmn:DataObjectReference') {
    return { type: 'bpmn:Association' };
  }

}
```

### my solution
```js
this.addRule(['connection.create', 'connection.reconnect'], 1500, function (context) {
    const source = context.source;
    if (is(source, 'bpmn:DataObjectReference')) {
        return false;
    }
})
```

you can see this problem if you start connect from `DataObjectReference`
