### ISSUE TITLE
Add create to palette

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js#1798]
__What should we do?__

Add a "create anything" entry to the palette which provides a menu with all possible elements.

What it should look like (but with bpmn elements):
<img width="568" alt="Screenshot 2023-01-10 at 16 38 45" src="https://user-images.githubusercontent.com/25825387/211595187-1285eb72-67c9-452a-941d-382065dd39b9.png">

 __To do:__
- [ ] Add entry to palette 
- [ ] Add create menu entries provider

__Why should we do it?__

To support create anything, see https://github.com/bpmn-io/bpmn-js/issues/1627

**Comment by nikku** [comment]
> But (edge case) does it make sense if the canvas is empty?

I think it does, because a diagram must always contain at least one process, and that is the one wrapped in the pool. We'd otherwise end up with empty pools in process diagrams (not containing expanded participants). We don't support such things yet.
