### ISSUE TITLE
Popup menu should support no element selected

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js#1799]
__Is your feature request related to a problem? Please describe.__

The popup menu is only able to open if an element is provided (the selected element). With the addition of ["create anything"](https://github.com/bpmn-io/bpmn-js/issues/1798), we want to open the popup menu in a general way, with no contextual element.

__Describe the solution you'd like__

The `element` parameter should be optional in `popupMenu.open` (not throw an error) and the element check could be done in popup menu providers (in `getEntries` or `getPopupMenuEntries`) instead. 

__Describe alternatives you've considered__

Attach the popup to the canvas root

__Additional context__

See https://github.com/bpmn-io/bpmn-js/issues/1798

**Comment by nikku** [comment]
The way [element template chooser](https://github.com/bpmn-io/element-template-chooser) solves this is to attach the popup to the canvas root. Not sure if reworking our popup menu infrastructure (with potential breaking changes) is necessary here?

**Comment by nikku** [comment]
Could you assess if it would be a major breaking change? If so I'd rather keep the notion of "popup menus are added onto elements", which may be "global elements".

**Comment by nikku** [comment]
Let's park or close this issue in that case. 

No need to invest if we can just show the menu on root elements instead.
