### ISSUE TITLE
Add append to contextPad

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js#1801]
__What should we do?__

Add a "append anything" entry to the palette which provides a menu with all possible elements.

What it should look like:
<img src="https://user-images.githubusercontent.com/25825387/210820799-c3751f4d-5b98-4121-9373-2339db0d1e16.png" width="400"/>

 __To do:__
- [ ] Add entry to context pad 
- [ ] Add append menu entries provider

__Why should we do it?__

To support create anything, see https://github.com/bpmn-io/bpmn-js/issues/1627

**Comment by nikku** [comment]
If done properly this closes the following issues:

* https://github.com/bpmn-io/bpmn-js/issues/1621
* https://github.com/bpmn-io/bpmn-js-connectors-extension/issues/31
* https://github.com/camunda/camunda-modeler/issues/2004
* https://github.com/bpmn-io/bpmn-js/issues/1731
* https://github.com/bpmn-io/bpmn-js-connectors-extension/issues/54

**Comment by barmac** [comment]
How about we fake the initial cursor position based on the button position? That could mimic the mouse interaction. Still, it looks good enough as we don't aim for keyboard-only modeling at the moment.

**Comment by nikku** [comment]
Also interesting: Why does it work so smoothly in the prototype?

**Comment by nikku** [comment]
> Behaviour of catch events vs (interrupting) boundary events

I'm aware of that case and would keep it as is.

> Maybe makes sense for event subprocess. Does it make sense for end event?

We could go either way about this, but we should be consistent: Either we show the menu for _all_ flow elements (end, event-sub + others) or only others. Intuitively I'd not show for both (end, event-sub) for now.

Also: Should we show it for elements where the context pad is conclusive? Event-based gateway is such a candidate.

**Comment by barmac** [comment]
I was surprised to learn that we cannot add text annotation via the append menu. Perhaps that could make sense even for event subprocesses and end events.

**Comment by nikku** [comment]
> I was surprised to learn that we cannot add text annotation via the append menu. Perhaps that could make sense even for event subprocesses and end events.

Let's log this as a follow up, too. Makes sense to annotate from there, too.

**Comment by barmac** [comment]
> > I was surprised to learn that we cannot add text annotation via the append menu. Perhaps that could make sense even for event subprocesses and end events.
> 
> Let's log this as a follow up, too. Makes sense to annotate from there, too.

Created as https://github.com/bpmn-io/bpmn-js/issues/1806
