### ISSUE TITLE
Add keyboard shortcuts for create

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js#1814]
### What should we do?

Add a shortcut for opening the create menu ('n', 'N') and ('a', 'A') when no selection.

**Requirements:**
- allow to trigger palette by entry id

### Why should we do it?

As part of the replace anything epic, see https://github.com/bpmn-io/bpmn-js/issues/1627

**Comment by nikku** [comment]
Additional detail:

* Append shortcut should work like create shortcut if no selection exists

**Comment by nikku** [comment]
Yes, that is my suggestion, and what's implemented [on the prototype](https://bpmn-io.github.io/bpmn-js-connectors-extension/?aa=1):

![capture 0Wyngz_optimized](https://user-images.githubusercontent.com/58601/214041815-1d5c4bd9-c41a-4d88-97b6-8d00b35b380f.gif)
