### ISSUE TITLE
Zoom Scroll is to fast using the track pad

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#182]
This appears to be an issue on MacOSX. Zoom Scroll works fine on Windows and Linux.

**Comment by ISO50** [comment]
As far as I know the website can't use the gestures directly so trackpad navigation would be:
* click + move  to meve around the canvas
* 2 finger drag up/down will zoom

**Comment by ISO50** [comment]
Closed.
Feel free to reopen if more information about usage of raw trackpad events on Mac is available.
