### ISSUE TITLE
11.2.0 Unable to delete 'append element' in content-pad and unable to delete 'create element' in palette

### ISSUE THREAD

**Issue by zxiaozhou** [bpmn-io/bpmn-js#1837]
### Describe the Bug

11.2.0 Unable to delete 'append element' in content-pad and unable to delete 'create element' in palette

### Steps to Reproduce

1. CustomContextPadProvider and create fundtion getContextPadEntries 
2. change getContextPadEntries entries,bug not found append element entry

### Expected Behavior

<img width="1046" alt="iShot_2023-02-07_11 30 06" src="https://user-images.githubusercontent.com/62740686/217141657-416db1c1-a445-4856-983a-e8a9b0f5c69e.png">

### Environment

 - Browser: [e.g. IE 11, Chrome 69] 80
 - OS: [e.g. Windows 7] mac os
 - Library version: [e.g. 2.0.0] bpmn js 11.2.0

**Comment by nikku** [comment]
`Create/append anything` is a new feature that [ships with `bpmn-js@11.2.0`](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#1120).

It is contained in it's [own module](https://github.com/bpmn-io/bpmn-js/tree/develop/lib/features/create-append-anything) so it should be in principle fairly easy to get rid of it, again:

* Do not use [`Modeler`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/Modeler.js) but rely on [`BaseModeler`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/BaseModeler.js). Pick only the modules you actually need (excluding `create-append-anything`).
* Create a `ContextPadProvider` that removes the entry (again)

Could you share how your `ContextPadProvider` looks like that you're `console.log` available entries with?

**Comment by zxiaozhou** [comment]
@nikku Thank you very much，I rewrote modeler。
