### ISSUE TITLE
Redo shortcut `CTRL+Y` does not work on German keyboard layout

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1842]
### Describe the Bug

I cannot use the `CTRL+Y` shortcut on Windows / Linux anymore to trigger redo.

### Steps to Reproduce

1. Open https://demo.bpmn.io/s/start
2. Perform change
3. `CTRL+Z` + `CTRL+Y`
4. Observe undo works, while redo does not

### Expected Behavior

Redo shortcut works.

### Environment

 - Browser: Chrome 110
 - OS: Linux, Windows
 - Library version: 11.3.0

**Comment by nikku** [comment]
Broke with [bpmn-js@11.0.0](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#1100).

**Comment by nikku** [comment]
Root causing this:

* `diagram-js < 11` we intercepted both `key` (actual key) and `keyCode` / `which` (physical key). We had a workaround in place for German keyboards and removed it with `11.0.0`.
* What we have now in place is a behavior where physical keys, depending on the keyboard shortcut registration order, overrule actual keys, so both `y` and `KeyZ` on German keyboards will trigger `undo` (https://github.com/bpmn-io/diagram-js/commit/ff861b022fb80e1f658ef7d6129516143bbca872#r100581210).

**Comment by philippfromme** [comment]
@nikku What's the way forward here? Implementing the solution you proposed?

**Comment by philippfromme** [comment]
I can reproduce the issue. Using a German keyboard layout:

German keyboard produces `"z", "KeyY"` for <kbd>Z</kbd> and `"y", "KeyZ"` for <kbd>Y</kbd>
Englisch keyboard produces `"y", "KeyY"` for <kbd>Z</kbd> and `"z", "KeyZ"` for <kbd>Y</kbd>

As a result when pressing `Y` the undo listener matches.

> A proper solution would likely value actual keys over physical keys:
> 
> * We first process bindings against actual keys
> * _THEN_ we process bindings against physical keys (in case actual keys did not trigger a change yet)

That's what we have to do. Or drop `code` alltogether.

**Comment by philippfromme** [comment]
@nikku Do you want to go ahead and prototype the solution or should I give it a try?

**Comment by nikku** [comment]
@philippfromme I've sketched an alternative:

> The alternative:
> 
> * Don't bind physical keys at all (only actual keys)
> * Potentially make it extensible (i.e. allow to specify additional keys for special keyboard layouts; but even then these can be mapped as actual keys, not physical keys)

If we ever want to support non latin keyboards (where users expect undo to be triggered on the [physical `KeyY` position](https://github.com/camunda/camunda-modeler/issues/2724) we'd need to build that, one way or the other). What would be your preference?

**Comment by philippfromme** [comment]
It sounds like the alternative would be to right approach in the long term so why don't we just implement that instead of wasting time on an intermediate fix?

**Comment by nikku** [comment]
If I understand you correctly (https://github.com/bpmn-io/bpmn-js/issues/1842#issuecomment-1430935689) you second the alternative I sketched.

I#ll go ahead and remove the physical key fix then. We can then (potentially, some day in the future), add support for shortcut customization / physical key positions.

**Comment by philippfromme** [comment]
> I#ll go ahead and remove the physical key fix then. We can then (potentially, some day in the future), add support for shortcut customization / physical key positions.

👍🏻

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/530b61ec371e7e6b2c9b435ba0399e4d0930f441.
