### ISSUE TITLE
Migrate to lodash 3.0.0

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#185]
Lodash is our utility library. They recently published version 3.0.0 that adds better modularity (áka browserify support) and performance improvements. 

For our libraries a migration would have the  benefit of providing only the utilities we actually need. 

For users it means less stuff to download and thus faster diagram rendering.

## Migration Path

1. Bump project dependency versions
2. Use lodash utilities instead of global `_` variable.

## Checklist

* [x] migrate moddle
* [x] migrate moddle-xml
* [x] migrate bpmn-moddle
* [x] migrate diagram-js
* [x] migrate bpmn-js

## Additional Tasks

* [ ] bundle required parts of lodash instead of relying on `window._` in the bower bundle.

**Comment by nikku** [comment]
[Lodash 3 release notes](https://github.com/lodash/lodash/releases/tag/3.0.0)

**Comment by nikku** [comment]
Also interesting: Is it actually worth exposing lodash and sax globally in the bower bundle?

It may be easier for developers to just load them bundled via our modeler/viewer dist files. This allows us to remove / replace them  more easily in the future, too.

**Comment by meyerdan** [comment]
Does "exposing lodash and sax globally" mean that they would bind to `window._` ?

**Comment by nikku** [comment]
Yes. __Either__ we bind lodash to the window and require users to explicitly include it (as a whole) in the page via another script tag. __Or__ we use only the parts we actually need but leave it as an internal dependency.

Any thoughts about that from your side?

**Comment by meyerdan** [comment]
I agree: I think it is smart to encapsulate it as an internal dependency. This way

* users do not have to include it,
* users can use a different version of lodash inside their application,
* we can exchange them more easily in he future (as you write above).

so +1 for encapsulating it as an internal dependency.
