### ISSUE TITLE
Replace `css.escape` with native `CSS.escape()`

### ISSUE THREAD

**Issue by thetric** [bpmn-io/bpmn-js#1850]
### What should we do?

`css.escape` should not be necessary anymore as most browsers (95% global usage according to https://caniuse.com/mdn-api_css_escape) support `CSS.escape` (https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape).
I'm not sure about this project's browser support as it is nowhere documented. The only drawback is the loss of Internet Explorer support which is somewhat retired (https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549).

Affected code: https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/replace-preview/BpmnReplacePreview.js

### Why should we do it?

Reduce (CommonJS) dependencies and embrace standard APIs.

**Comment by nikku** [comment]
We don't support IE anymore since bpmn-js@10. Given the fact that `CSS.escape`can be trivially polyfilled, let's do this.

Do you mind contributing this?

**Comment by thetric** [comment]
Sure. I can do this 👍
