### ISSUE TITLE
ASCII Art / UTF Diagramme Output Similar to PlantUML 

### ISSUE THREAD

**Issue by SylvianHemus** [bpmn-io/bpmn-js#1856]
### Is your feature request related to a problem? Please describe.

I usually am working in an environment without a gui.  BPMN-js does not seem to currently support the ability to output to Ascii/UTF-8 instead of an image file

### Describe the solution you'd like

Implement ASCII / UTF-8 output instead of images

Provide a to-do list for me / my team to implement (we don't know the internals of your codebase)

### Describe alternatives you've considered

I can support image viewing in the framebuffer, but this is not ideal.  

I'd rather not use PlantUML since strict UML is a bit bloated  

### Additional context 

I am using [Kroki](https://github.com/yuzutech/kroki) with emacs org-mode - ob-kroki - to generate BPMN images with code blocks

**Comment by nikku** [comment]
I guess you're asking a question here. In this case our [forum](https://forum.bpmn.io/) is the right place. I guess it makes sense to raise that in the forum. Maybe a community member knows more.

I'm not aware of an ASCII rendering of BPMN.

**Comment by nikku** [comment]
Please use our existing issue template if you have a feature request.

**Comment by nikku** [comment]
> Implement ASCII / UTF-8 output instead of images

Not sure what you mean by that / how this tool should help. Do you seek a BPMN to ASCII art converter? That should already exist (cf. Kroki). 

I cannot at the moment not envision how maintaining a diagram as ASCII art, if that is what you imply will be useful. You can try to convince us, of course. Still not sure at this stage what you think this tool does, and how any kind of support for ASCII would help you and/or benefit our users.

**Comment by nikku** [comment]
> It could be useful to us if you would kindly do the needful and explain how we could program this using your existing codebase.

This is exactly what the forum is for. To answer your questions. Cf. https://github.com/bpmn-io/bpmn-js/issues/1856#issuecomment-1452417114.

-----

If you mirror the question in our forum ("how to build an ASCII art exporter for bpmn-js" then I'm happy to provide you pointers there.

As you indicated you're not willing to share additional details on how you plan to use such thing; consider at least the basics:

* What is the format you desire to output to? (I guess it is what kroki can read? ->  share a link)
* Should it be roundtrip capable? (you model in bpmn-js -> output ASCII art, transform ASCII art to BPMN so you can modify your processes again)

If you do that then you'll (1) receive more helpful pointers / feedback and (2) maybe a community member with domain knowledge can contribute.
