### ISSUE TITLE
Update BPMN Font to full BPMN support

### ISSUE THREAD

**Issue by ISO50** [bpmn-io/bpmn-js#186]
For the context pad we need following elements:

* All Event Types
* All Gateway Types
* All Task Types + call activity

In addition  we need for the palette:

* ~~Pool~~
* ~~Lane~~
* ~~Connections~~
* (see #222)

## Details

Update the [bpmn-font](https://github.com/bpmn-io/bpmn-font) project to include the icons based on the given [example diagram](https://github.com/bpmn-io/bpmn-font/blob/master/resources/all-elements.bpmn).

We need the following icons:

* [x] __for events__: only the icon markers
* [x] __for gateways__: gateway + marker inside
* [x] __for activities__: only markers
* [x] __subprocess/transaction/adhoc__: _????_

A [how to build fonts](https://github.com/bpmn-io/bpmn-font/blob/master/docs/HOWTO.md) is attached.

## Requirements

* [x] font must look good at 20px size pixels
* [x] font sources must be provided as SVG to the project

## Other

* [x] font is updated in bpmn-js/assets + app
* [x] font example screenshot is updated on bpmn-font project page

**Comment by gimbel** [comment]
Pool, Lane and Connections should be moved to a separate issue, since they are not critical for this milestone

**Comment by ISO50** [comment]
Rendering of the font on Linux  looks to soft. Will increase stroke size need to update all elements.
* [ ] events
* [ ] gateway
* [ ] tasks

**Comment by ISO50** [comment]
New icon font has landed.

* [x] Test OS X - normal
* [x] Test OS X - Retina
* [ ]  Test Linux
* [x] Test Windows 7 IE and Firefox
* [ ] Bundle new font to dist folder and add a new Image of all contained icons.

Even if the updated font is a step forward I would like to increase the font size from 20px to 21px or 22px as Windows seems to apply less interpolation to the icons.

**Comment by gimbel** [comment]
looks great on my machine ;)

**Comment by ISO50** [comment]
As another improvement we could increase the outer stroke of end events. That would help to distinguish them from normal events.
