### ISSUE TITLE
Allow `create-append-anything` to be easily disabled

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js#1862]
### Is your feature request related to a problem? Please describe.

There is currently ways to remove the `create-append-anything` feature (see [forum](https://forum.bpmn.io/t/disable-popupmenu-for-palette-and-contextpad/8782/6)). But they require some effort or aren't super straightforward.

We should provide a way to easily remove `create-append-anything`.

### Describe the solution you'd like

Extract `create-append-anything` to separate extension.

- [x] Create new extension and release - https://github.com/bpmn-io/bpmn-js-create-append-anything
- [x] Remove from `bpmn-js` and release as breaking change - https://github.com/bpmn-io/bpmn-js/pull/1873
- [ ] Add it to [awesome list](https://github.com/bpmn-io/awesome-bpmn-io) - https://github.com/bpmn-io/awesome-bpmn-io/pull/21

### Describe alternatives you've considered

Don't ship it with default Modeler. Users have to explicitly add it if they want to use it.

### Additional context

There have been around 4 (or more) questions on how to disable this feature. It is clear that not all users want this.

**Comment by nikku** [comment]
What about the alternative: Making it an external module (an extension)? Would fit nicely into our existing story, too.

**Comment by nikku** [comment]
> A completely separate extension would be basically the connectors extension, right?

Exactly.

If possible we should keep the core lean. The readme ("related") and/or our [awesome list](https://github.com/bpmn-io/awesome-bpmn-io) are places to discover these additional helpful extensions.
