### ISSUE TITLE
Translation behavior of contextPad buttons is inconsistent

### ISSUE THREAD

**Issue by siaikin** [bpmn-io/bpmn-js#1865]
### Describe the Bug

Missing title parameter.

* https://github.com/bpmn-io/bpmn-js/blob/cc6a40aa69f74cef991e59d851ca89531508d4a8/lib/features/context-pad/ContextPadProvider.js#L405
* https://github.com/bpmn-io/bpmn-js/blob/cc6a40aa69f74cef991e59d851ca89531508d4a8/lib/features/context-pad/ContextPadProvider.js#L421
* https://github.com/bpmn-io/bpmn-js/blob/cc6a40aa69f74cef991e59d851ca89531508d4a8/lib/features/context-pad/ContextPadProvider.js#L474

### Steps to Reproduce

1. do this
2. do that

### Environment

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
Not sure exactly what you need. Translating of "append text annotation" happens through the [`appendAction`](https://github.com/bpmn-io/bpmn-js/blob/cc6a40aa69f74cef991e59d851ca89531508d4a8/lib/features/context-pad/ContextPadProvider.js#L190).

**Comment by siaikin** [comment]
> Not sure exactly what you need. Translating of "append text annotation" happens through the [`appendAction`](https://github.com/bpmn-io/bpmn-js/blob/cc6a40aa69f74cef991e59d851ca89531508d4a8/lib/features/context-pad/ContextPadProvider.js#L190).

not exactly.

https://github.com/bpmn-io/bpmn-js/blob/cc6a40aa69f74cef991e59d851ca89531508d4a8/lib/features/context-pad/ContextPadProvider.js#L188
https://github.com/bpmn-io/bpmn-js/blob/cc6a40aa69f74cef991e59d851ca89531508d4a8/lib/features/context-pad/ContextPadProvider.js#L303

i can also control translating by passing in `title` parameter.

my question is translating behavior is Inconsistent. both have simple text also have text template.

**Comment by siaikin** [comment]
I just found out while writing the translation module that TextAnnotation couldn't be translated with simple text matching like the other elements.

Then I noticed that **missing**(or be designed so ?) the third arguments when adding TextAnnotation.

If you think this is not an issus, then I believe this is the design.
