### ISSUE TITLE
Package `lezer-feel` is duplicated in a user's bundle

### ISSUE THREAD

**Issue by boris-petrov** [bpmn-io/bpmn-js#1869]
### Describe the Bug

Using `bpmn.js` for the past few weeks has caused `lezer-feel` to be duplicated in a user's bundle. `@bpmn-io/feel-lint` depends on `lezer-feel` `^0.15.0`. `@bpmn-io/variable-resolver` depends on version `github:marstamm/lezer-feel#decouple-context-format`. `feelers` depends on `^0.16.2`. There's a few more. All of these cause the package to be bundled multiple times (by webpack for example) because it uses different "major" versions (0.x are considered major).

### Steps to Reproduce

Install and use `bpmn.js`.

### Expected Behavior

No duplicated packages in the bundle.

### Environment

N/A.

**Comment by barmac** [comment]
This is not the case anymore.

**Comment by boris-petrov** [comment]
@barmac are you sure? Using the latest versions (as of now) still leads to the same thing - three versions of `lezer-feel`. Version `1.0.2` requested by `@bpmn-io/feel-lint` (and others). Version 0.16.2 requested by `feelers` (in turn requested by a bunch of stuff from `@bpmn-io`). Version `1.2.0` requested by `feelin` (and others). What else are you seeing?

**Comment by barmac** [comment]
I checked `@bpmn-io/feel-lint` and `@bpmn-io/variable-resolver` of which both depend on ^1, so there is no dependency on GitHub repository anymore. 

However, indeed `feelers` depends on v0.16.2. On the other hand though, bpmn-js does not use that project. Feel free to suggest an update in the respective repository: https://github.com/bpmn-io/feelers

**Comment by boris-petrov** [comment]
@barmac you're right, sorry, I didn't correctly update my dependencies. Now the only problem is `feelers`, yes, which is a transitive dependency from `camunda-bpmn-js`. I will open an issue in `feelers` as you suggest, thank you.
