### ISSUE TITLE
 How do I change the width and height of the task node

### ISSUE THREAD

**Issue by wangzongming** [bpmn-io/bpmn-js#1879]
Hi!
I want the task node to be square, so I need to change the width of the element to do that.
But I looked for a long time for a way, and I couldn’t find it.
Can someone help me with this? 
Thank you very much.

**Comment by wangzongming** [comment]
> @wangzongming Please reach out for questions [in our forum](https://forum.bpmn.io/). It looks like you [already did](https://forum.bpmn.io/t/how-do-i-change-the-width-and-height-of-the-task-node/9025)?
> 
> Spam posting on multiple channels won't get you an answer quicker. Thanks for your understanding!

那请问有解决方案吗？

**Comment by philippfromme** [comment]
> Is there a solution?

Find out in the [forum](https://forum.bpmn.io/). 😉
