### ISSUE TITLE
如果我不使用官方提供的bpmn-js-properties-panel实现属性扩展，还需要描述文件吗？If I don't use the official bpmn-js-properties-panel to implement the property extension, do I still need a description file?

### ISSUE THREAD

**Issue by Lands-1203** [bpmn-io/bpmn-js#1889]
demo: https://github.com/Lands-1203/bpmn-react-antd
属性面板是使用antd开发的，可以直接使用updatePropertiesAPI向节点添加属性，为什么还需要一个json文件呢?
The properties panel is developed using antd, and we can use updatePropertiesAPI to add attributes to nodes directly. Why do you need a json file?
描述文件：Description file：
![image](https://user-images.githubusercontent.com/61341868/231432893-cb42da4a-5523-451c-ade0-bc85c34bac6c.png)

**Comment by barmac** [comment]
This seems to be a question related to the usage of bpmn-js and not a bug report. Feel free to post a thread on the forums: https://forum.bpmn.io/
