### ISSUE TITLE
Missing attachedToRef attribute if deleting name of a pasted bounary event

### ISSUE THREAD

**Issue by tonny1983** [bpmn-io/bpmn-js#1895]
### Describe the Bug

The `attachedToRef` attribute is missing when pasting a bounary event and deleting the name in the panel then.

### Steps to Reproduce

1. Createa process with one boundary event with name as follows:

![截屏2023-04-20 17 16 29](https://user-images.githubusercontent.com/8895687/233320235-d0fddec1-625b-4164-a984-3ace3f669caa.png)

the code of the event is:
```xml
<bpmn:boundaryEvent id="Event_0v3948t" name="abcd" attachedToRef="Activity_1d4m834">
  <bpmn:outgoing>Flow_12etd6a</bpmn:outgoing>
  <bpmn:timerEventDefinition id="TimerEventDefinition_0rsaxd4" />
</bpmn:boundaryEvent>
```
 
2. Now copy the timer boundary event and paste it to the second user task:
![截屏2023-04-20 17 19 43](https://user-images.githubusercontent.com/8895687/233320694-09fc4ecf-6abd-4600-8f29-38436c60056a.png)

the code of the two events is:
```xml
<bpmn:boundaryEvent id="Event_0v3948t" name="abcd" attachedToRef="Activity_1d4m834">
  <bpmn:outgoing>Flow_12etd6a</bpmn:outgoing>
  <bpmn:timerEventDefinition id="TimerEventDefinition_0rsaxd4" />
</bpmn:boundaryEvent>
<bpmn:boundaryEvent id="Event_1ibx7aw" name="abcd" attachedToRef="Activity_1jxg4s0">
  <bpmn:timerEventDefinition id="TimerEventDefinition_0e5vbfw" />
</bpmn:boundaryEvent>
```

3. Delete the name field in panel and the result is:
![截屏2023-04-20 17 26 56](https://user-images.githubusercontent.com/8895687/233322778-2aa30a25-5bc7-4395-af7b-6792f59fa7f2.png)

the code of the two events is:
```xml
<bpmn:boundaryEvent id="Event_0v3948t" name="abcd" attachedToRef="Activity_1d4m834">
  <bpmn:outgoing>Flow_12etd6a</bpmn:outgoing>
  <bpmn:timerEventDefinition id="TimerEventDefinition_0rsaxd4" />
</bpmn:boundaryEvent>
<bpmn:boundaryEvent id="Event_1ibx7aw">
  <bpmn:timerEventDefinition id="TimerEventDefinition_0e5vbfw" />
</bpmn:boundaryEvent>
```

Obviously, the `attachedToRef` has gone together with the `name` attribute.

### Expected Behavior

`attachedToRef` should not be missing.

### Environment

 - Browser: Firefox 112.0.1 
 - OS: MacOs
 - Library version: 12.1.0

**Comment by smbea** [comment]
I tracked down that while copying and pasting the boundary event, the label shape is attributed a "host" too, which should only be the case for the event shape. This then checks [this condition](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/attach-support/AttachSupport.js#L267), which it shouldn't. This problem is only present with copy/paste.

I haven't quite figured out where/when this assignment happens though.
