### ISSUE TITLE
Incorrect encoding of & character during export

### ISSUE THREAD

**Issue by Dr4K4n** [bpmn-io/bpmn-js#190]
When i create a model where the description of some element contains for instance an '&'-characeter. I'm able to save the model, but when I reopen it, bpmn.io complains about the file not being valid. When i remove the '&' character from the .bpmn file by hand, I'm able to open the file again.

**Comment by nikku** [comment]
Looks like we do not properly encode `&`.

**Comment by nikku** [comment]
Will be fixed in our next modeler release.

**Comment by Dr4K4n** [comment]
Great, thank you very much!
