### ISSUE TITLE
unparsable content </bpmn:task> detected; this may indicate an invalid BPMN 2.0 diagram file

### ISSUE THREAD

**Issue by egorTriceps** [bpmn-io/bpmn-js#1907]
### Describe the Bug

```xml
unparsable content </bpmn:task> detected; this may indicate an invalid BPMN 2.0 diagram file
	line: 46
	column: 6
	nested error: closing tag mismatch
```

when opening the file, it gives this error

### Environment

 - Browser: [ Chrome 69]
 - OS: [ Windows 10]

**Comment by nikku** [comment]
@egorTriceps I have a number of questions:

* How did this error happen?
* What is the diagram that triggers this error?
* How can we help yoU?

**Comment by egorTriceps** [comment]
[Заявка на потребность.zip](https://github.com/bpmn-io/bpmn-js/files/11465026/default.zip)
in each line where "name =" is written, incomprehensible characters are written

**Comment by nikku** [comment]
How can we reproduce your issue? Do you create this broken diagram using our tooling (i.e. https://demo.bpmn.io?

**Comment by egorTriceps** [comment]
@nikku Yes

**Comment by egorTriceps** [comment]
I saved the file through the demo version of the site, after that I could not upload this file to the site

**Comment by nikku** [comment]
We need concrete steps to reproduce. So if you'd try again, on a small file, to reproduce the issue and report back what you found, that would be amazing.

We'll otherwise not be able to help you.

**Comment by barmac** [comment]
I tried Russian keyboard on my Mac but couldn't reproduce the issue.

**Comment by egorTriceps** [comment]
How can I restore the table?

**Comment by barmac** [comment]
Perhaps this helps: https://stackoverflow.com/questions/43108359/how-to-remove-all-special-characters-in-linux-text

I am closing this issue as we cannot reproduce the problem.
