### ISSUE TITLE
Follow html pattern for icon loading

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js#1918]
### What should we do?

Replace instances where we use "embedded icons" and replace it with html, like https://github.com/bpmn-io/bpmn-js-create-append-anything/pull/7

### Why should we do it?

To establish a single pattern and be consistent across our stack

**Comment by smbea** [comment]
The instances of "embedded icons" in bpmn-js are the align and distribute icons. The icons that are rendered with the popup menu can't be changed as easily.

Firstly we need to allow html in `diagram-js` popup menu component, which we currently don't.

Then there is challenge with using `htm`'s `html....` utility. In previous cases, we would pass `html: "<div>some html string</div>"`, and we would `domify` it and add it to the tree. With popup menu, I'm having trouble rendering this in the `htm` context.

**Comment by nikku** [comment]
What keeps us from [using `dangerouslySetInnerHTML`](https://github.com/preactjs/preact/issues/29)? I believe it should work with `htm`, too?
