### ISSUE TITLE
I can morph BPMN elements (events)

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#192]
AT:
* BPMN elements can be changed among each other (e.g. from service task to script task or from message event to signal event)
* Not every element can be changed to anything, the following "groups" apply
 * Start Events --> all allowed event definitions, throwing or catching
 * Intermediate Events --> all allowed event definitions, throwing or catching
 * End Events --> all allowed event definitions, throwing or catching

**Comment by ISO50** [comment]
Rendering of the font on Linux  looks to soft. Will increase stroke size need to update all elements.
* [ ] events
* [ ] gateway
* [ ] tasks
