### ISSUE TITLE
Replace menu doesn't show the corresponding non-interrupting element

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js#1923]
### Describe the Bug

The replace menu does not show the option to replace by the corresponding non-interrupting element.

### Steps to Reproduce

1. select a "message start event"
2. open replace menu
3. see that "non-interrupting message start event" is not present
4. interrupting "message start event" still appears as an option

~~This happens in Camunda Modeler but not in the demo (see bello). For this reason, I believe this is a bug with the [UnlinkTemplateReplaceProvider](https://github.com/bpmn-io/bpmn-js-create-append-anything/blob/main/lib/element-templates/unlink-templates/UnlinkTemplateReplaceProvider.js) in this extension.~~ This element is also missing in `bpmn-js`.

<div>
<img width="300" alt="Screenshot 2023-05-19 at 11 11 52" src="https://github.com/bpmn-io/bpmn-js-create-append-anything/assets/25825387/90e1ff09-04e1-4d00-800d-4df93bf740c0">

<img width="300" alt="Screenshot 2023-05-19 at 11 11 52" src="https://github.com/bpmn-io/bpmn-js-create-append-anything/assets/25825387/5b3a5402-069c-4a98-890d-3ce90c7b1dd2">
</div>

### Expected Behavior

* The "non-interrupting" should appear as option
* The duplicate of the selected element should not appear

### Environment

 - Library version: latest

**Comment by nikku** [comment]
Released with v13.2.1 :tada:
