### ISSUE TITLE
undo cannot work

### ISSUE THREAD

**Issue by hexiaokang** [bpmn-io/bpmn-js#1933]
### Describe the Bug

Why I calling the undo command when using bpmn-js V9.0.3 cannot undo the added task nodes, and I have tried the latest V13 version but it cannot be undone. But when I downgrade to V6, calling undo can be undone normally.

### Steps to Reproduce

1. add task node
2. click undo

### Environment

 - Browser: chrome, Version 115.0.5790.114, (arm64)
 - OS: macOS V12.0
 - Library version: 9.0.3

**Comment by philippfromme** [comment]
Where exactly do you click undo? Please provide more information about your setup. Undo is working in all versions of bpmn-js including the latest.

**Comment by hexiaokang** [comment]
> Where exactly do you click undo? Please provide more information about your setup. Undo is working in all versions of bpmn-js including the latest.

step:
1、import BpmnModeler from 'bpmn-js/lib/Modeler'
2、bpmn init
<img width="587" alt="image" src="https://github.com/bpmn-io/bpmn-js/assets/16911432/e8c9b618-92a6-471b-b565-0dc2524fab1d">

3、handle undo click
<img width="460" alt="image" src="https://github.com/bpmn-io/bpmn-js/assets/16911432/ae8475ea-884a-4a2c-903f-7cbff45da03f">


version:
<img width="1391" alt="image" src="https://github.com/bpmn-io/bpmn-js/assets/16911432/824a3da0-aa67-4cb7-aceb-953916f52521">

**Comment by philippfromme** [comment]
What customizations are you using? Any additional modules?

**Comment by hexiaokang** [comment]
> What customizations are you using? Any additional modules?

I had solved, that is  affected by my business data, thanks!
