### ISSUE TITLE
Problems with references after copying default sequence flow elements

### ISSUE THREAD

**Issue by ChaominRuan** [bpmn-io/bpmn-js#1935]
### Describe the Bug

After setting the sequence flow to be the default sequence flow and using the shortcut key to copy the element, you will find that the element business object default property becomes **enumerable** and there is a circular reference. Importing a diagram, or switching the sequence flow to the default sequence flow after a normal element's default property is not enumerable.

as shown below :

![20230801201123](https://github.com/bpmn-io/bpmn-js/assets/61787903/bde68cb2-7976-44ec-a883-91c5ce5c3818)

### 
1. Create a start event, gateway and end event element.
2. Connect them, with the flow between the gateway and end event set to the default flow.
3. Select the gateway and end event element and copy it.

[ code example in stackblitz](https://stackblitz.com/edit/web-platform-co27xm?file=script.js) and [run](https://web-platform-co27xm.stackblitz.io/)

### Expected Behavior

When copied, the default properties of a business object should be **no enumerable**. This avoids unexpected problems, e.g. TypeError: Converting circular structure to JSON when using JSON.stringify.

### Environment

 - Browser: [e.g. IE 11, Chrome 110]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

**Comment by philippfromme** [comment]
The behavior you're observing is correct. We're not talking about a simple object here. Every model element is an instance of [Base](https://github.com/bpmn-io/moddle/blob/master/lib/base.js). When using `JSON.stringify` you have to make sure the references are handled. You can see an example here: https://github.com/nikku/bpmn-js-copy-paste-example

**Comment by ChaominRuan** [comment]
> The behavior you're observing is correct. We're not talking about a simple object here. Every model element is an instance of [Base](https://github.com/bpmn-io/moddle/blob/master/lib/base.js). When using `JSON.stringify` you have to make sure the references are handled. You can see an example here: https://github.com/nikku/bpmn-js-copy-paste-example

I found this problem exactly when I was using the example you mentioned!
https://github.com/nikku/bpmn-js-copy-paste-example/blob/master/test/copy-paste.js#L45 `JSON.stringify(tree)` is used here.

In the model it's using defineProperty: https://github.com/bpmn-io/moddle/blob/master/lib/properties.js#L51,
but in BpmnCopyPaste.js it's mounted directly on the object's property https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/copy-paste/BpmnCopyPaste.js#L111
So there's this problem.

**Comment by philippfromme** [comment]
Closed by https://github.com/bpmn-io/bpmn-js/commit/ca65cde02c37a5c9db1a121fc3b6edbdc35a3f60.
