### ISSUE TITLE
API to move and zoom to specific elements

### ISSUE THREAD

**Issue by EloProf** [bpmn-io/bpmn-js#195]
My current use-case of your library can involve very large diagrams with a lot of tasks. Because of this I am currently using your navigated viewer because otherwise you wouldn't be able to see anything in most diagrams.

This helped the issue a bit, but I would like to have some easier navigation. I would like to have a list of all tasks that will move and zoom the diagram to the position of the task in the diagram on mouseover or click.

I have looked for some documentation but unfortunately i couldn't find any. I also tried to take a look into the source but unfortunately i couldn't find a good way to hook in there.

Is there a way to achieve this? If not, then I would like to make a feature request for it.

**Comment by nikku** [comment]
To summarize your feature request:

* Given a number of model elements
* Zoom into the diagram so that all of them are visible

Is that correct?

**Comment by EloProf** [comment]
Yeah, that is pretty much it. And it would probably be nice if the center of the view area would me moved to the center of the element group. If there is only one element you want to go to, then it will be centered.

Another thing that should be accounted for is zoom level. For example if you want to show only one element then it shouldn't maximize that element to fill the whole view area alone.

**Comment by nikku** [comment]
I'm closing this as we will not implement this as part of the CORE any time soon.

**Comment by victors1681** [comment]
is there any way to accomplish this??

**Comment by nikku** [comment]
Not using public API. You can use the elements position along with the existing canvas scrolling APIs. You'd end up with something along those lines: 

```javascript
var element; // diagram element to scroll to

var viewbox = canvas.viewbox();

var box = getBoundingBox(element);

var newViewbox = {
  x: (box.x + box.width/2) - viewbox.outer.width/2,
  y: (box.y + box.height/2) - viewbox.outer.height/2,
  width: viewbox.outer.width,
  height: viewbox.outer.height
};

canvas.viewbox(newViewbox);

canvas.zoom(viewbox.scale);
```

Please ask questions [in our forum](https://forum.bpmn.io/).
