### ISSUE TITLE
Not accounting for negative coordinates

### ISSUE THREAD

**Issue by EloProf** [bpmn-io/bpmn-js#196]
I am not sure if this belongs in here or diagram-js, so perhabs this needs to be moved.

Currently the package doesn't respect negative coordinates for elements:
I took the pizza-collaboration.bpmn example file and changed line 136 to
```
<dc:Bounds height="294.0" width="1044.0" x="-1.0" y="-1.0"/>
```
This results in the following rendering in the viewer with `canvas.zoom('fit-viewport')`:
![diagramjs_bug](https://cloud.githubusercontent.com/assets/7925129/6363698/afb46934-bc9c-11e4-9f81-4d501efe0e88.jpg)

**Comment by nikku** [comment]
We have updated the `zoom('fit-viewport')` behavior in our next release. It will always try to display the whole diagram (independent on where `(0,0)` is.

You may achieve the same behavior via `canvas.viewbox(canvas.viewbox().inner)` for large diagrams (see [here](https://github.com/bpmn-io/diagram-js/commit/350a0e44b00116ebf2ae36f47ff3058e22690c99#diff-de3dfbb232d33f623c8e3072a4d0bdc9R515)).
