### ISSUE TITLE
Boundary event detached when moved by keyboard arrow keys

### ISSUE THREAD

**Issue by rambo-bertelsmann** [bpmn-io/bpmn-js#1961]
### Describe the Bug

When an attached boundary event is moved using the keyboard arrow keys, it is expected to remain attached. Currently, the boundary is detached when moved with arrow keys.

### Steps to Reproduce

1. Go to https://demo.bpmn.io/new
2. Drag a task onto the canvas.
3. Drag a boundary event on top of the task.
4. Click on the boundary event and press the "right" arrow key on your keyboard.
5. Click on the task and drag it to the right side.

### Actual Behavior

Boundary event is no longer attached to the task.

### Expected Behavior

The boundary event is still attached to the task, moving slightly to the right within the task hitbox.

### Environment

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
I believe this is a duplicate of https://github.com/bpmn-io/bpmn-js/issues/1961?

**Comment by smbea** [comment]
Did you mean https://github.com/bpmn-io/bpmn-js/issues/1876 @nikku ? You linked the same issue 🙂

I think it is and we can mark it as such, since there was no new activity here.

**Comment by nikku** [comment]
Yes, updated.

**Comment by rambo-bertelsmann** [comment]
@smbea yes, it is the same as #1803.

**Comment by rambo-bertelsmann** [comment]
This is duplicated. I am closing this and tracking it in #1803.
