### ISSUE TITLE
Fix post-release job

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1979]
### What should we do?

Fix post-release job which fails since automatic release was introduced. It fails to read the tag which breaks the pipeline.

Cf. https://github.com/bpmn-io/bpmn-js/actions/runs/6557498817/job/17809291824

### Why should we do it?

Our CI should work.

**Comment by marstamm** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1980

**Comment by barmac** [comment]
It's still broken 🤡 : https://github.com/bpmn-io/bpmn-js/actions/runs/6574289199/job/17859110100

**Comment by barmac** [comment]
OK perhaps now: https://github.com/bpmn-io/bpmn-js/pull/1982

Too bad GitHub Actions don't validate outputs and inputs.
