### ISSUE TITLE
Participant Multiplicity Marker Not Centered

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1990]
### Describe the Bug

Becomes move obvious when the participant is very small.

![image](https://github.com/bpmn-io/bpmn-js/assets/7633572/5278eced-f1d0-4a33-8100-8292eb5cc35d)

### Steps to Reproduce

1. Create a collapsed participant with multiplicity
2. Marker not centered

### Expected Behavior

Marker centered

### Environment

 - Library version: 12.5.0

**Comment by barmac** [comment]
I can reproduce this:

![image](https://github.com/bpmn-io/bpmn-js/assets/28307541/ef9e230f-2112-4a60-91c2-02e0e1a52537)
