### ISSUE TITLE
Better customise the `browse to marketplace` icon in the context pad

### ISSUE THREAD

**Issue by marcellobarile** [bpmn-io/bpmn-js#1991]
### Is your feature request related to a problem? Please describe.

With https://github.com/camunda/web-modeler/issues/6064 we have added a new browse marketplace icon to the header of the contextual menus of the diagram (append element, change element, select template). However, in our first iteration, it doesn't follow completely the design specs (e.g. it misses the hover state).

Moreover, we might need to apply some `Carbon-like` style to it.

We tried playing around with the CSS but the result was hideous (see https://github.com/camunda/web-modeler/issues/6175)

### Describe the solution you'd like

It would be nice to be able to apply a theme to the context pad (e.g. to let it resemble a bit more the Carbon components).

### Additional context

![image](https://github.com/bpmn-io/bpmn-js/assets/1809476/988275a1-b85d-45dc-aeeb-8d0558ee94c1)

![image](https://github.com/bpmn-io/bpmn-js/assets/1809476/0a1529f2-d1e6-4798-8ed2-09ffbd7b34b3)

**Comment by barmac** [comment]
Hi,
regarding the hover state, this can probably be fixed via CSS in the application. Can you please explain what parts of the popup menu you'd need to change? A drawing of the desired changes would be great.

**Comment by barmac** [comment]
My assumption right now is that we can help styling without changes to the core library. So if we are to change anything in the core, we need to know what exactly cannot be done at the moment.

**Comment by nikku** [comment]
@marcellobarile Happy to re-visit the styling together.

We don't want to theme the core ("make it work like carbon").

Closing this issue as there is no immediate concrete work item for us.
