### ISSUE TITLE
Custom added elements cannot preview append on hover

### ISSUE THREAD

**Issue by zxuanhong** [bpmn-io/bpmn-js#1999]
### Describe the Bug

1. Custom added elements cannot preview append on hover
<img width="759" alt="image" src="https://github.com/bpmn-io/bpmn-js/assets/62740686/17307707-b1ee-4cce-81e7-dc0fd977dfac">
<img width="831" alt="image" src="https://github.com/bpmn-io/bpmn-js/assets/62740686/98a254d1-1b19-4094-87f1-3543b0b8bb99">

### Environment

 - Browser: [e.g. IE 11, Chrome 69]  chrome101
 - OS: [e.g. Windows 7] mac
 - Library version: [e.g. 2.0.0] 15.0

**Comment by philippfromme** [comment]
This is not a bug. In your custom provider you must specify for each entry what happens on click, drag and hover. Check out the implementation here: https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/context-pad/ContextPadProvider.js#L282
