### ISSUE TITLE
Grey rectangular appears when moving connection segments

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#2002]
### Describe the Bug

A grey rectangular appears when moving connection segments:

https://github.com/bpmn-io/bpmn-js/assets/28307541/49f4510b-4c12-4a74-bd49-db93f57ebf15

### Steps to Reproduce

1. Create a connection
2. Move segment

### Expected Behavior

There should be no funny rectangular when dragging.

### Environment

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: v15.0.0

**Comment by barmac** [comment]
I discovered this while reviewing https://github.com/bpmn-io/dmn-js/pull/800, so it may be either in diagram-js or copied over from bpmn-js to the dmn-js PR.

**Comment by smbea** [comment]
The removal of the selection line is intentional. The funny rectagular thing is not though

**Comment by barmac** [comment]
Thanks for clarification. Then, we only need to fix the rectangular thing.

**Comment by barmac** [comment]
I will reword the issue to talk about the rectangular only.

**Comment by smbea** [comment]
Ok so this is actually unrelated to the selection changes. It comes from [this commit](https://github.com/bpmn-io/diagram-js/commit/0941c37892c28b8d2c58be41a5d90e47948d54d9#diff-682322eea3bdf2a0256e2e37fb5a12ac5c9744f340488edcb053b4dbe8f57137R296), which related to the preview feature. If I comment that out, it works.

I don't exactly know what this is affecting. @philippfromme how can i safely fix this without breaking something else? 😅

**Comment by philippfromme** [comment]
I will look into this.

**Comment by philippfromme** [comment]
Same issue when moving bendpoints. Seems affect all other components using `djs-dragging`.

![image](https://github.com/bpmn-io/bpmn-js/assets/7633572/01e395c9-7f3f-4d03-9b43-efa37aa6253a)

**Comment by philippfromme** [comment]
Fixed by https://github.com/bpmn-io/bpmn-js/pull/2016.
