### ISSUE TITLE
Append preview gets stuck and doesn't dissapear

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js#2004]
### Describe the Bug

I found a case where append preview gets stuck and doesn't disappear:

https://github.com/bpmn-io/bpmn-js/assets/25825387/9575acad-8eba-4a49-a178-0dcfd549de82

Maybe this is an edge case, I only experienced it in this scenario.

### Steps to Reproduce

1. move task out of subprocess
2. click on "append task" in context pad

### Expected Behavior

Append preview should disappear after adding or moving mouse away.

### Environment

 - Library version: v15.0.0

**Comment by philippfromme** [comment]
Fixed by https://github.com/bpmn-io/bpmn-js/pull/2016.
