### ISSUE TITLE
Gateway types are not rendering with NavigatedViewer

### ISSUE THREAD

**Issue by ana-max** [bpmn-io/bpmn-js#2020]
When I use Modeler, Gateway types are displayed.
![изображение](https://github.com/bpmn-io/bpmn-js/assets/42715111/79563d80-3bf1-4879-b4ea-c119fc91ff6d)

But it doesn't work that way with NavigatedViewer.
![изображение](https://github.com/bpmn-io/bpmn-js/assets/42715111/ff2cce38-f13e-41d0-ba37-338ed2313619)

### Steps to Reproduce

1. Use `new Modeler`
2. Use `new NavigatedViewer`
3. See the difference

### Expected Behavior

Gateway types must be displayed in every case.

### Environment

 - Browser: Chrome 119.0.6045.106
 - OS: Windows 11
 - Library version: 13.0.5

**Comment by nikku** [comment]
Please share a diagram that allows us to reproduce your issue.

**Comment by ana-max** [comment]
@nikku 

https://github.com/Citeck/ecos-offers/blob/master/src/main/resources/app/artifacts/process/bpmn/offer-candidate-process.bpmn.xml

**Comment by nikku** [comment]
I cannot reproduce your issue with the example diagram provided, and bpmn-js@15.1.0.

----

Note that the marker may also be hidden via the `BPMNDI#isMarkerVisible` property, cf. [BPMN Spec, page 373](https://www.omg.org/spec/BPMN/2.0/PDF):

![image](https://github.com/bpmn-io/bpmn-js/assets/58601/c83adf7f-7902-40e3-8082-479cbc198d2d)

**Comment by ana-max** [comment]
That is exactly what I've missed! Thank you! It works now.
