### ISSUE TITLE
Type errors in BpmnRenderUtil.d.ts

### ISSUE THREAD

**Issue by syedgaian** [bpmn-io/bpmn-js#2028]
type Shape is not defined and imported in the file which is being used in some methods in file.

I am importing a method from this file when I am trying to implement a custom renderer in a web based modeler built on anular framework, whole application is breaking , because Shape is not defined, can you please look into this.

import { getRoundRectPath } from 'bpmn-js/lib/draw/BpmnRenderUtil'; 
this is import where it is failing

### Steps to Reproduce

1. do this
2. do that

### Environment

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: linux-ubuntu
 - Library version: latest- 15.1.3

**Comment by marstamm** [comment]
Hi @syedgaian ,

Thanks for reporting this. To help you better, could you provide:

1. Angular version.
2. Any additional dependencies/configurations.
3. Details on the custom renderer.
4. Steps to reproduce.

Also, if possible, could you share a [Codesandbox](https://codesandbox.io/) link for us to inspect the issue directly?

Appreciate your assistance!

**Comment by syedgaian** [comment]
Hi @marstamm 
Thanks for responding
Angular version : 16.2.0
additionally I am using : diagram-js - 12.8.0 apart from this angular related dependencies

steps to reproduce :

import { getRoundRectPath } from 'bpmn-js/lib/draw/BpmnRenderUtil';
 I am trying to import some methods from 'bpmn-js/lib/draw/BpmnRenderUtil' file it is breaking in this point

There are few methods in this file which are using a type 'Shape' , but it is not been imported anywhere in this file, it is breaking because it is not able to resolve this type

these are the methods :- 

/**
 * Get width and height from element or overrides.
 *
 * @param bounds
 * @param overrides
 *
 * @returns
 */
export function getBounds(bounds: Dimensions | Rect | Shape, overrides?: any): Dimensions;

/**
 * Get width from element or overrides.
 *
 * @param bounds
 * @param overrides
 *
 * @returns
 */
export function getWidth(bounds: Dimensions | Rect | Shape, overrides?: any): number;

/**
 * Get height from element or overrides.
 *
 * @param bounds
 * @param overrides
 *
 * @returns
 */
export function getHeight(bounds: Dimensions | Rect | Shape, overrides?: any): number;

these are the only type definitions available in the file:-

export type ModdleElement = any;
export type Element = any;
export type ShapeLike = any;
type Dimensions = import('diagram-js/lib/util/Types').Dimensions;
type Rect = import('diagram-js/lib/util/Types').Rect;

There is no type definition for shape in the file

**Comment by marstamm** [comment]
I see, seems like we use `Shape` instead of `ShapeLike` in some JSDoc comments. https://github.com/bpmn-io/bpmn-js/pull/2036 should fix this issue.

Note that only the JSDoc is broken, not the functionality itself

**Comment by marstamm** [comment]
Fix released as [v15.2.2](https://github.com/bpmn-io/bpmn-js/commit/460125a6038e980cce05962a80721fbf75bbdcb4)
