### ISSUE TITLE
SubProcess Activity change name in subProcess view causing unwanted label attribute to XML di node

### ISSUE THREAD

**Issue by zeus6379** [bpmn-io/bpmn-js#2033]
### Describe the Bug

same issue in both bpmnjs and camunda modeler app.

when change subProcess`s name in subProcess view,  <bpmndi:BPMNPlane> node in xml add unwanted label attribute, cause deployment of the process failed.
<img width="2055" alt="image" src="https://github.com/bpmn-io/bpmn-js/assets/5676756/191169be-b522-4f65-a3ed-11fe7a3317da">

<img width="889" alt="image" src="https://github.com/bpmn-io/bpmn-js/assets/5676756/d7325fcc-a56d-4cd3-80da-29d013c942b9">

bpmn source file here, subProcess activity ID 「Activity_0ds7evi」: 
[定期合规披露.bpmn.zip](https://github.com/bpmn-io/bpmn-js/files/13471302/bpmn.zip)

### Steps to Reproduce

1. enter modeler subProcess view
2. use modeler dbclick to change subProcess name
3. or use properties panel to change subProcess name
4. check xml source and unwanted attrs 「label="[object object]"」

### Environment

https://demo.bpmn.io

**Comment by nikku** [comment]
Please provide full context, including the bpmn-js version you're using.

**Comment by zeus6379** [comment]
you can use my bpmn file reproduce it on https://demo.bpmn.io/new, same issue on official Camunda Modeler https://camunda.com/download/modeler/

**Comment by zeus6379** [comment]
> Please provide full context, including the bpmn-js version you're using.
you can use my bpmn file reproduce it on https://demo.bpmn.io/new, same issue on official Camunda Modeler https://camunda.com/download/modeler/

**Comment by nikku** [comment]
I can reproduce your issue with Camunda Modeler v5.17.0. Thanks for reporting.
