### ISSUE TITLE
Maximum call stack size exceeded while dragging a sub-process node

### ISSUE THREAD

**Issue by shaansriv** [bpmn-io/bpmn-js#2045]
When a subprocess is expanded, then on selecting entire node and then dragging it, the cursor changes to hand sign and the screen hangs, console shows error for **Maximum Call Size Exceeded**.
bpmn-js version being used: **"7.0.3"**

**Error**:
![image](https://github.com/bpmn-io/bpmn-js/assets/153165775/9dcf25e1-2026-449d-92fe-32d2754e7160)

### Steps to Reproduce

1. Expand any subprocess
2. Select entire node
3. Drag it in any direction
4. Again try to click anything on the screen after dragging

### Expected Behavior
It should be dragged and after being dragged it should behave normally, but instead the website hangs.

### Environment

 - Browser: Chrome
 - OS: Windows 10
 - Library version: (bpmn-js): 7.3.0

**Comment by nikku** [comment]
Please try to reproduce this with a recent bpmn-js version. We're now at 16.0.0 and don't support version 7 anymore.

**Comment by nikku** [comment]
Closed due to missing information.
