### ISSUE TITLE
Allow text annotations to overlap with the borders of subprocesses and pools

### ISSUE THREAD

**Issue by CatalinaMoisuc** [bpmn-io/bpmn-js#2049]
### Context

Transferred from: https://github.com/camunda/web-modeler/issues/7213.
cc @till-stadtler

### Describe the problem that you are trying to solve

When adding or moving text annotations in a subprocess or a pool, it can happen that the border of the subprocess or pool is shifted. For me, this is often an undesired effect. 

Text annotations can become hidden behind subprocesses.

This behavior of text annotations can lead to subprocesses and pools that are larger than they need to be in regards to the relevant BPMN elements themselves.

### Describe the solution you'd like to see implemented

I would like text annotations to not affect the size of subprocesses or pools when adding or moving them around. This means they should be allowed to overlap with the borders of subprocesses and pools. (This already happens when the text annotation is "outside" the subprocess or pool. In this case, the text annotation becomes partially hidden. (This behavior is not consistent, regarding a text annotation being outside of a pool or not.))

Text annotations should always be visible, thus independent of the "scope" where they live in the XML (?).

I hope this change will allow BPMN processes to become more compact as it will be easier to shift text annotations to a desired location. Customers might choose to position text annotations outside of subprocesses or pools, which makes the BPMN process itself more compact, see below. Once this is implemented, a tool can be added to temporarily hide all text annotations to focus on the BPMN process itself.

To summarize, text annotations should be _always on top_ and not affect resizing of the containers they are in.

### Describe alternatives you've considered

Use ctrl + z to undo the undesired change.

### Additional Context

Adding a text annotation:
![new-text-annotation](https://github.com/camunda/web-modeler/assets/117343024/1cce255c-0936-4d56-a856-ab4dda0f9f63)

Moved the text annotation a bit to the right:
![moved-text-annotation](https://github.com/camunda/web-modeler/assets/117343024/be27a6ab-6081-4700-a078-25379a1ff1be)

Partially hidden text annotation:
![partially-hidden-text-annotation](https://github.com/camunda/web-modeler/assets/117343024/22da7a16-ce1b-4413-942c-741aa4dfd0f9)

I assume this requested handling of text annotations will lead the customers to design more compact in regards to relevant BPMN elements. Especially, if we implement a tool to temporarily hide text annotations. This way, text annotations do not heavily affect the size and compactness of the BPMN model.
![compact-model](https://github.com/camunda/web-modeler/assets/117343024/c222112e-a4cd-4f39-b326-46b71bb46916)

**Comment by nikku** [comment]
Let's have a quick user feedback. Happy to make text annotations labels, behavior wise.

**Comment by till-stadtler** [comment]
Hi @nikku,
I got one positive feedback for this FR from @barmac!
Until now, no other person has responded to my Camunda-internal user feedback request.

**Comment by nikku** [comment]
I think it is a safe bet to try out regardless.

**Comment by barmac** [comment]
I think it's fair to expect that text annotations are displayed on top of everything, and don't affect the flow elements containers bounds.

**Comment by nikku** [comment]
> I think it's fair to expect that text annotations are displayed on top of everything, and don't affect the flow elements containers bounds.

This is backed up by https://github.com/camunda/camunda-modeler/issues/4035.
