### ISSUE TITLE
Modelling Rules for event based Gateways 

### ISSUE THREAD

**Issue by ISO50** [bpmn-io/bpmn-js#206]
* Context menu for event based Gateways should only contain 
  * Catching Message Intermediate Event
  * Catching Timer Intermediate Event
  * Catching Condition Intermediate Event
  * Catching Timer Intermediate Event
  * Catching Signal Intermediate Event
  * Receive Task
* It should be allowed to connect the outgoing connections of an event based gateway only with:
  * Catching Message Intermediate Event
  * Catching Timer Intermediate Event
  * Catching Condition Intermediate Event
  * Catching Timer Intermediate Event
  * Receive Task

**Comment by gimbel** [comment]
![image](https://cloud.githubusercontent.com/assets/3829733/6439193/a25457b2-c0d0-11e4-8b27-b65f3f8b62e0.png)

**Comment by ISO50** [comment]
Closed by [225cbb9]
