### ISSUE TITLE
`elements.changed` event handler doesn't return an actual information about BPMN schema

### ISSUE THREAD

**Issue by corocoto** [bpmn-io/bpmn-js#2065]
### Describe the Bug

If you wrote text into `bpmn:Task` element and don't unfocussed from it, this BPMN node won't have its actual state. The main problem is that `elements.changed` event doesn't call at that moment (only after unfocusing from the element, if we're looking at the case with creating/editing text).

### Steps to Reproduce

1. Add event listener on 'elements.changed' event (`bpmnModeler.on('elements.changed', [event handler])`)
2. Add the opportunity to log some information from that listener, or add a debugger into its body
3. Create a simple BPMN schema (with two `bpmn:Task` elements, as example)
4. Write internal text for both elements, but don't unfocussed from the last one
5. See how many times the event handler has called

### Expected Behavior

Event listener of the `'elements.changed'` should be called after editing text. And the decision about calling shouldn't depend on the state of its element (focusing or unfocusing, etc.)

### Environment

 - Browser: Chrome v120
 - OS: MacOS 14.2
 - Library version: v16.3.0

**Comment by nikku** [comment]
@corocoto Please share with us a screen capture that provides additional context. If you seek to get an `elements.changed` event during direct editing (cf. below), then you'll see that this is not the case. It only _commits_ on unfocus, `ENTER` or another user action.

![capture 5Qu5Zk_optimized](https://github.com/bpmn-io/bpmn-js/assets/58601/a9d768c0-1758-4946-931a-01985768facc)

**Comment by corocoto** [comment]
@nikku, yeah, I suppose your screencast with shown scenario fully cover my case. 

But I have a small counter question. The scenario shown below will also not trigger the `elements.changed` event? (node's label creation process)

https://github.com/bpmn-io/bpmn-js/assets/37180024/d6ca95eb-4904-4ee6-a725-dc7ce5910cfc

And if it is, I would like to understand why the event didn't dispatch. I mean, I want to understand why it works so. Because for me, any manipulation with an element (including text editing) - is also refer to an element editing.

**Comment by nikku** [comment]
@corocoto Label editing, _unless commited_ is ephemeral. Hence it never reaches the underlying model, and no `elements.changed` is called.

If you build upon the change to happen please raise an issue and clearly lay out your use case.

**Comment by corocoto** [comment]
@nikku, I see. Thanks a lot for description of working process! It's really useful information that should to know.
