### ISSUE TITLE
CompensateBoundaryEventBehavior.js: fail 'shape.replace' event handler when the `targetElement` is undefined

### ISSUE THREAD

**Issue by Vovamzur** [bpmn-io/bpmn-js#2073]
### Describe the Bug

There is a bug while using bpmn-js-element-templates with bpmn-js@16.3.0 after removing an element template:

```
EventBus.js:437 unhandled error in event listener TypeError: Cannot read properties of undefined (reading 'type')
    at handleReplacement (CompensateBoundaryEventBehavior.js:101:1)
```

It is caused by calling https://github.com/bpmn-io/bpmn-js-element-templates/blob/main/src/element-templates/cmd/RemoveElementTemplateHandler.js#L46 without `hints.targetElement`

As we can see from line https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/behavior/CompensateBoundaryEventBehavior.js#L95 the `targetElement` could be undefined.

As solution, we could check it for undefined before getting properties like `targetElement.type` or `targetElement.eventDefinitionType` on 100,101,115 lines

### Steps to Reproduce

1. apply some element template
2. remove element template

### Expected Behavior

Element template is removed without errors

### Environment

 - Library version: 16.3.1
 - bpmn-js-element-templates: 1.10.0

**Comment by nikku** [comment]
I can reproduce this in the [`bpmn-js-element-templates`](https://github.com/bpmn-io/bpmn-js-element-templates) test environment:

* spin it up using `npm start`
* assign an element template to a compensation activity
* remove element template from a compensation activity

---

![capture uS3OzT_optimized](https://github.com/bpmn-io/bpmn-js/assets/58601/3e73aea3-e410-479f-9eaf-981338be894c)

**Comment by nikku** [comment]
We see these failures when updating the element template repository dependencies, too: https://github.com/bpmn-io/bpmn-js-element-templates/pull/40

**Comment by barmac** [comment]
This sounds critical :/

**Comment by barmac** [comment]
I had a closer look, and in the compensation PR I assumed that `targetElement` is set but it's only done when replacing via `bpmnReplace`. We should probably look at the `newData` property instead as it's set in the core diagram-js component.

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/2074
