### ISSUE TITLE
Parallel Multiple Events are rendered with fill

### ISSUE THREAD

**Issue by sombrek** [bpmn-io/bpmn-js#2085]
### Describe the Bug

Parallel Multiple Events are rendered with a filled trigger. This seems to be a recent regression.

![parallel-multiple-events](https://github.com/bpmn-io/bpmn-js/assets/150448993/e9761b36-ac62-4b8f-91db-60519bd31051)

### Steps to Reproduce

1. Open [test/fixtures/bpmn/draw/events.bpmn](https://github.com/bpmn-io/bpmn-js/blob/develop/test/fixtures/bpmn/draw/events.bpmn) in bpmn.io
2. View the parallel multiple events (those with a plus marker)

### Expected Behavior

The plus sign in these events should have no fill, per BPMN spec.

![parallel-multiple-events-correct](https://github.com/bpmn-io/bpmn-js/assets/150448993/571b19ee-0d4b-4c9c-ba90-cf6d4155bc9f)

### Environment

 - Library version: 16.3.2

**Comment by nikku** [comment]
We're happy to take a PR to improve this.
