### ISSUE TITLE
Handle Adding Vertical Lanes

### ISSUE THREAD

**Issue by sombrek** [bpmn-io/bpmn-js#2086]
### Is your feature request related to a problem? Please describe.

Adding vertical lanes to existing pools should be supported. Currently, new lanes are placed as if they were added to a horizontal pool, i.e.
- they leave space for the label on the left side of the pool
- they split vertical pools vertically
- they set `isHorizontal=true`

<details>
  <summary>Adding Issue Demonstration</summary>

![add-lane-vertical](https://github.com/bpmn-io/bpmn-js/assets/150448993/c5312df8-a89b-49c4-9603-e8c959947604)

</details>

### Describe the solution you'd like

Implement adding vertical lanes to existing pools and lanes by supporting that feature under the hood.
I think this can be done unintrusively without UI changes, by ensuring that lanes are always added horizontally/vertically according to their parent pool. The downside is that the icons will not match the actual action.

Splitting lanes will be implemented separately.

### Describe alternatives you've considered

Vertical variants of the "add lane" buttons could be introduced, but that would give the feature more exposure (i.e. less _under the hood_-ness as required by #507).

### Additional context

This is related to #507 and I would like to contribute the implementation.

**Comment by barmac** [comment]
I think this makes sense. We are happy to accept community contribution on this.
