### ISSUE TITLE
Redo/undo and Copy/Paste issue

### ISSUE THREAD

**Issue by EhsanValiGeeksltd** [bpmn-io/bpmn-js#2087]
if we load a xml through `ImportXml` function, Redo/undo and Copy/Paste work.
but if we change the DOM element and then create a new instance of BPMN js and ImportXml again, Copy/Paste and Reso/Undo do not work.

you can see the sample of the issue [here](https://jsfiddle.net/qmnvbo5L/2/)

1. Please go to the link
2. Check the Copy/Paste and Undo/Redo. That works.
3. Then press the Reload button, those functionalities do not work after change the DOM element

**Comment by nikku** [comment]
Please use the existing issue template or we'll not be able to help you.

**Comment by EhsanValiGeeksltd** [comment]
@nikku thanks for your response. I update the issue

**Comment by nikku** [comment]
From what I understand:

* You want to do undo/redo
* You create a new bpmn-js instance
* Undo/redo does not work across bpmn-js instances

Agreed. This is not a use-case we plan to support. 

Instead consider _why_ you need undo/redo across instances. Do you need more than once instance? If that is really the case, add a global keyboard / editing context, share the clipboard. These are options you have.

**Comment by nikku** [comment]
@EhsanValiGeeksltd There is always ways to "keep the DOM node" and or otherwise have persistent (cached) instances of sub-components. I'd ask you to look into how _a single instance of BpmnJS_ can be realized in your scenario. Cache it in a global variable, or pass it via context are two options.
