### ISSUE TITLE
The browser event is not disabled when adding a new task and adding a comment

### ISSUE THREAD

**Issue by shibaaboy** [bpmn-io/bpmn-js#2103]
### Describe the Bug

The browser event is not disabled when adding a new task and adding a comment

### Steps to Reproduce

1) add a task
2) press save hotkey
3) the browser save window is displayed

ITS ONLY FOR TASKS AND COMMENTS!

Added a video with sequential steps

[code for test](https://codesandbox.io/p/sandbox/recursing-sky-4r3gqn?file=%2Fsrc%2Ftest.js%3A3%2C26)

### Expected Behavior

Don't display the browser save window  for tasks and comments

### Environment

 - Browser: [Chrome 69]
 - OS: [macOs]
 - Library version: [e.g. 2.0.0]

**Comment by shibaaboy** [comment]
https://github.com/bpmn-io/bpmn-js/assets/43315031/0b91dfa0-0c16-4f73-8073-efbd6b9fae53

**Comment by shibaaboy** [comment]
Uploading 02484436-6bc5-4e70-9ba2-347a32f69ccc.mp4…

**Comment by shibaaboy** [comment]
https://github.com/bpmn-io/bpmn-js/assets/43315031/376fdf97-7cac-4434-a38e-b4128b594189

**Comment by philippfromme** [comment]
Why would you want to prevent that browser feature from working?

**Comment by shibaaboy** [comment]
I want to create a combination save (command + S) without using a browser dialog in my app

**Comment by miyuesc** [comment]
我也认为这种情况 (命令s) 应该由开发人员自己处理，而不是委托给bpmn-js.

**Comment by nikku** [comment]
@shibaaboy This should be handled by you.

You can consider to register a global `CTRL/CMD + S` key listener and `event.preventDefault()` it to prevent the browser default. Closing as `wontfix` for our tooling.
