### ISSUE TITLE
Can we add a dropdown in the Java class feature in the right panel?

### ISSUE THREAD

**Issue by vasugarggl** [bpmn-io/bpmn-js#2109]
### Is your feature request related to a problem? Please describe.

Can we add a dropdown in the Java class feature in the right panel?
as there could be wrong inputs I want a dropdown so that we can select direclty without making any mistake.

### Describe the solution you'd like

If possible, do write back.
I have added the screenshot below with the highlighted part on which we want to add the dropdown.
<img width="813" alt="Screenshot 2024-02-28 125745" src="https://github.com/bpmn-io/bpmn-js/assets/156659580/f89fade4-d1d6-4b7e-b7dc-95f5f82bf06d">

**Comment by nikku** [comment]
@vasugarggl I think you refer to an extension of the [bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel). 

Yes, that is possible, and we offer an [example for that](https://github.com/bpmn-io/bpmn-js-examples/tree/main/properties-panel-extension). 

You want to refer to the linked old version of the example as you use bpmn-js-properties-panel@0.x.

**Comment by suraj-G862** [comment]
hello , i am new to opensource. And i want to try to contribute. Can your please specify how to open that right side panel in your screenshot?

**Comment by nikku** [comment]
@suraj-G862 Not sure what you want to accomplish? What would you like to contribute?

**Comment by nikku** [comment]
Closing due to missing user feedback. As mentioned [before](https://github.com/bpmn-io/bpmn-js/issues/2109#issuecomment-1968392625) there is ways to customize the properties panel in the desired way.
