### ISSUE TITLE
Bug - Morph Options missing for End events

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#211]
The following events are missing:
    * termination (only the symbol)
    * end event (blanko)
    * signal

![image](https://cloud.githubusercontent.com/assets/3829733/6463375/f0fb65b8-c1b1-11e4-8b39-e9f2245987c2.png)

**Comment by gimbel** [comment]
End Event Blanko still missing, when morphed to another event

**Comment by gimbel** [comment]
![image](https://cloud.githubusercontent.com/assets/3829733/6466594/16e55d8a-c1c9-11e4-9838-48fe6ad84879.png)

**Comment by ISO50** [comment]
Old version in your browser cache? My menu has the entry.

**Comment by gimbel** [comment]
successfully tested
