### ISSUE TITLE
Vertically Auto-Place Elements

### ISSUE THREAD

**Issue by sombrek** [bpmn-io/bpmn-js#2110]
### Is your feature request related to a problem? Please describe.

Problem: Elements in vertical pools and lanes are auto-placed horizontally.

### Describe the solution you'd like

Auto-place elements within vertical containers vertically from top to bottom. Make Sequence and Message Flows match this direction.

In a more abstract way: The result model should look like a horizontally modeled process that was mirrored on the model axis from top-left to bottom-right.

![sample-auto-place](https://github.com/bpmn-io/bpmn-js/assets/150448993/73c85e2e-fdb9-4e99-b2ef-a7398909881d)

### Describe alternatives you've considered

Not implementing this feature. But I think it's worth now that layouting vertical containers is possible.

At the moment I don't see a way to make this work in general, i.e. for models without vertical pools. So I would limit this feature to the insides of vertical pools.

### Additional context

Related to #507

I would like to make a contribution.

**Comment by sombrek** [comment]
I might deviate from the system explained above when it comes to data objects/stores and text annotations.
Below please find the current horizontal behavior for reference and my suggestion on implementing data object and text annotation placement for vertical layouts.
Another tool I tried places both on the right side. For me, extending the model to the right _feels_ more correct.
Any strong opinions on your side?

![data-store-suggestion](https://github.com/bpmn-io/bpmn-js/assets/150448993/5b5daaeb-ab6c-4e70-9334-8f854a4621d2)

**Comment by barmac** [comment]
Hi,

I think it makes sense to append to the bottom for the flow elements in a vertical participant, but as you noticed artifacts should still take place to the top-right from an element. The behavior should not be present outside of vertical pools though. Feel free to tag me if you prepare a contribution.

**Comment by nikku** [comment]
Tagging as `pr welcome` and moving to `backlog`.
