### ISSUE TITLE
Some error messages are not internationalized

### ISSUE THREAD

**Issue by ChaominRuan** [bpmn-io/bpmn-js#2124]
### Is your feature request related to a problem? Please describe.

Should these error messages be added to add internationalization?

![image](https://github.com/bpmn-io/bpmn-js/assets/61787903/b6abc461-15fb-4802-b97c-bd0612b5fa7b)

### Describe the solution you'd like

If these error messages need to be internationalized, I can submit a PR.

**Comment by barmac** [comment]
Thanks for creating the issue. I agree that the messages should be internationalized.

**Comment by nikku** [comment]
We decided to not translate technical (and non-user facing) errors - https://github.com/bpmn-io/bpmn-js/pull/2137#issuecomment-2074367305.
