### ISSUE TITLE
Data Input Box is not rendering completely

### ISSUE THREAD

**Issue by Tri16** [bpmn-io/bpmn-js#2129]
Hi @falko 

I am trying to render a bpmn diagram with data input and output, but the image which is getting render is showing the data input box as half incomplete, pls help on this

xml string:

<?xml version="1.0" encoding="UTF-8"?>
  <definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="definitions_4158acd2-4b5c-4db6-9d2d-bd0b38f2ff94" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL">
    <process id="UserOnboardingandConnectionFlow" name="User Onboarding and Connection Flow" isExecutable="true">
      <startEvent id="START_EVENT_7" name="Start">
        <outgoing>sequenceFlow_bf883553-3345-48e8-b493-7dee0ad970aa</outgoing>
      </startEvent>
      <serviceTask id="COMMUNICATION_2" name="Landing Page Visit">
        <documentation id="documentation_37b88d97-a922-43ff-8805-e03a72b244ce">User lands on the platform's homepage.</documentation>
        <extensionElements>
          <camunda:properties>
            <camunda:property name="nodeType" value="COMMUNICATION" />
          </camunda:properties>
        </extensionElements>
        <incoming>sequenceFlow_bf883553-3345-48e8-b493-7dee0ad970aa</incoming>
        <outgoing>Flow_1gdt121</outgoing>
        <property id="Property_4869bbc9-fed8-4a32-a284-3211f01d9ead" name="__targetRef_placeholder" />
        <dataInputAssociation id="DataInputAssociation_f00c6a56-710a-424f-99f0-70f6968f1b44">
          <sourceRef>DataObjectReference_d8d3b829-ddca-4e28-83ba-c90b1be49354</sourceRef>
          <targetRef>Property_4869bbc9-fed8-4a32-a284-3211f01d9ead</targetRef>
        </dataInputAssociation>
        <dataOutputAssociation id="DataOutputAssociation_05de6327-827e-43ec-8a12-ed2cbd836864">
          <sourceRef>Property_4869bbc9-fed8-4a32-a284-3211f01d9ead</sourceRef>
          <targetRef>DataObjectReference_92edf2f1-9e7f-41ac-aa6e-27a9f2db1c41</targetRef>
        </dataOutputAssociation>
      </serviceTask>
      <sequenceFlow id="sequenceFlow_bf883553-3345-48e8-b493-7dee0ad970aa" sourceRef="START_EVENT_7" targetRef="COMMUNICATION_2" />
      <dataObject id="DataObject_5e85cd89-03b9-4f41-a000-f27a79f13f34" />
      <dataObjectReference id="DataObjectReference_d8d3b829-ddca-4e28-83ba-c90b1be49354" name="User Interest" dataObjectRef="DataObject_5e85cd89-03b9-4f41-a000-f27a79f13f34" />
      <dataObject id="DataObject_26483eda-b2e2-4714-9fba-6a88c42f8de7" />
      <dataObjectReference id="DataObjectReference_92edf2f1-9e7f-41ac-aa6e-27a9f2db1c41" name="Awareness of &#39;Spark&#39;" dataObjectRef="DataObject_26483eda-b2e2-4714-9fba-6a88c42f8de7" />
      <endEvent id="END_EVENT_1" name="End">
        <incoming>Flow_1gdt121</incoming>
      </endEvent>
      <sequenceFlow id="Flow_1gdt121" sourceRef="COMMUNICATION_2" targetRef="END_EVENT_1" />
    </process>
    <bpmndi:BPMNDiagram id="BPMNDiagram_62d11867-6bdf-4e0a-a5a4-25a6c8caebf8">
      <bpmndi:BPMNPlane id="BPMNPlane_2bcd8aa5-0475-4e96-bbff-dd0ea67e84ad" bpmnElement="UserOnboardingandConnectionFlow">
        <bpmndi:BPMNShape id="BPMNShape_565bf8a4-ca11-4c56-a10a-64d1fbcfafd9" bpmnElement="START_EVENT_7">
          <dc:Bounds x="100" y="100" width="36" height="36" />
        </bpmndi:BPMNShape>
        <bpmndi:BPMNShape id="BPMNShape_41803abb-960a-4e2a-8096-78b5f4b49234" bpmnElement="COMMUNICATION_2">
          <dc:Bounds x="186" y="78" width="100" height="80" />
        </bpmndi:BPMNShape>
        <bpmndi:BPMNShape id="DataObjectReference_d8d3b829-ddca-4e28-83ba-c90b1be49354_di" bpmnElement="DataObjectReference_d8d3b829-ddca-4e28-83ba-c90b1be49354">
          <dc:Bounds x="136" y="-22" width="36" height="50" />
        </bpmndi:BPMNShape>
        <bpmndi:BPMNShape id="DataObjectReference_92edf2f1-9e7f-41ac-aa6e-27a9f2db1c41_di" bpmnElement="DataObjectReference_92edf2f1-9e7f-41ac-aa6e-27a9f2db1c41">
          <dc:Bounds x="136" y="218" width="36" height="50" />
        </bpmndi:BPMNShape>
        <bpmndi:BPMNShape id="BPMNShape_93f8b832-38e1-413a-adb3-401b5d9a1576" bpmnElement="END_EVENT_1">
          <dc:Bounds x="382" y="100" width="36" height="36" />
          <bpmndi:BPMNLabel>
            <dc:Bounds x="390" y="136" width="20" height="14" />
          </bpmndi:BPMNLabel>
        </bpmndi:BPMNShape>
        <bpmndi:BPMNEdge id="DataInputAssociation_f00c6a56-710a-424f-99f0-70f6968f1b44_di" bpmnElement="DataInputAssociation_f00c6a56-710a-424f-99f0-70f6968f1b44">
          <di:waypoint x="154" y="28" />
          <di:waypoint x="236" y="78" />
        </bpmndi:BPMNEdge>
        <bpmndi:BPMNEdge id="DataOutputAssociation_05de6327-827e-43ec-8a12-ed2cbd836864_di" bpmnElement="DataOutputAssociation_05de6327-827e-43ec-8a12-ed2cbd836864">
          <di:waypoint x="236" y="158" />
          <di:waypoint x="154" y="218" />
        </bpmndi:BPMNEdge>
        <bpmndi:BPMNEdge id="BPMNEdge_c8f7f67a-afbb-47cc-bfda-4d731cf7afaf" bpmnElement="sequenceFlow_bf883553-3345-48e8-b493-7dee0ad970aa">
          <di:waypoint x="136" y="118" />
          <di:waypoint x="186" y="118" />
        </bpmndi:BPMNEdge>
        <bpmndi:BPMNEdge id="Flow_1gdt121_di" bpmnElement="Flow_1gdt121">
          <di:waypoint x="286" y="118" />
          <di:waypoint x="382" y="118" />
        </bpmndi:BPMNEdge>
      </bpmndi:BPMNPlane>
    </bpmndi:BPMNDiagram>
  </definitions>

![image](https://github.com/bpmn-io/bpmn-js/assets/106538459/02158753-5af7-403e-b89d-b4d99251615f)

**Comment by nikku** [comment]
@Tri16 As you did not use any of our provided [issue templates](https://github.com/bpmn-io/bpmn-js/issues/new/choose) I'm not sure if this is a bug, feature request or question (the latest one better to be [asked in our forums](https://forum.bpmn.io/)).

It looks like your diagram is simply not rendered fully, hence the data input is cut off. If you want us to look into this issue as a bug report, please update your issue: 

* Use the bug report template
* Provide _full_ steps to reproduce for us

Thanks! :sun_behind_small_cloud:
