### ISSUE TITLE
Bug - Morph of events following an event based gateway always remove sequence flows

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#213]
reproduce:
    * model an event based gateway
    * model a message event (catch)
    * connect event based gateway and message event
    * morph message event to timer event

problem
    * sequence flow is removed

expected
    * sequence flows are only removed if event is not allowed after an event based gateway (e.g. morph to message event throw)

**Comment by gimbel** [comment]
still not working for the following events
    * condition
    * signal

**Comment by ISO50** [comment]
Event Definitions are wrong:
https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/rules/ModelingRules.js#L52-L53

**Comment by gimbel** [comment]
Tested on stage: now I am completely unable to connect condition and signal events to the event based gateway

**Comment by gimbel** [comment]
Sucessfully tested now, sorry, caching problem
