### ISSUE TITLE
BPMN logo removal way from rendered image using bpmn-js library

### ISSUE THREAD

**Issue by Tri16** [bpmn-io/bpmn-js#2130]
Hi @nikku 

Can we remove bpmn.io logo from rendered image which is generated using bpmn-js library

![bpmnlogo](https://github.com/bpmn-io/bpmn-js/assets/106538459/7e809e17-849b-445a-95da-5ba604f9cce4)

**Comment by nikku** [comment]
Not permitted as per the [bpmn.io license](https://bpmn.io/license/).

**Comment by nikku** [comment]
@Tri16 This is not a place for your questions, our [forum is](https://forum.bpmn.io).
