### ISSUE TITLE
How to add create/append anything

### ISSUE THREAD

**Issue by Ken-Scofield** [bpmn-io/bpmn-js#2132]
### Describe the Bug
! missing "create elements" in palette, how to add it?

![no-create](https://github.com/bpmn-io/bpmn-js/assets/30038865/0e11ee6a-9433-4d94-9282-5a53eb0f3726)

**Comment by Ken-Scofield** [comment]
@nikku give some help, please!

**Comment by nikku** [comment]
Provided via [an extension](https://github.com/bpmn-io/bpmn-js-create-append-anything).

**Comment by Ken-Scofield** [comment]
> Provided via [an extension](https://github.com/bpmn-io/bpmn-js-create-append-anything).

thanks, boss!
