### ISSUE TITLE
Navigated viewer uses outdated outlines

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#2133]
### Describe the Bug

The outlines used by the navigated viewer are outdated.

Modeler:

![image](https://github.com/bpmn-io/bpmn-js/assets/7633572/1f6bb580-7f6b-435b-8f9f-9642beef9d27)

Navigated viewer:

![image](https://github.com/bpmn-io/bpmn-js/assets/7633572/10b7c753-6387-43df-8506-39e7514b3721)

### Expected Behavior

Outlines should look the same in all viewers.

### Environment

 - Library version: 17.2.1

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/2134.
