### ISSUE TITLE
Multi-selection in viewer causes black boxes

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#2135]
### Describe the Bug

As a user I'm embedding the viewer as recommended in the [starter project](https://github.com/bpmn-io/bpmn-js-examples/tree/main/starter). When I select elements no outline is shown, I can still react to selected events; this I expect.

However when I select more than one element a black box appears that hides the diagram:

![capture vSxTJn_optimized](https://github.com/bpmn-io/bpmn-js/assets/58601/b27e6796-31e9-4e8b-9218-7a679a0c712f)

### Steps to Reproduce

1. open [starter viewer example](https://cdn.statically.io/gh/bpmn-io/bpmn-js-examples/main/starter/viewer.html)
2. select more than one element using `SHIFT + click`
3. see black box appear

### Expected Behavior

* No black box appears
* (Alternative) Selection is not available for the viewer

### Environment

 - Browser: Chrome 110
 - OS: Linux
 - Library version: v14.0.0

**Comment by philippfromme** [comment]
I think that we need to be clear on what a viewer is. The default viewer in my opinion, should behave like viewing an SVG. No interactivity at all. I never liked the fact that you get selection behavior in the viewer. Now, there are use cases that need an _interactive_ viewer. In these cases, users need to include the required features and stylesheets as well.

**Comment by philippfromme** [comment]
There would still remain the problem of _interactive_ viewer and no selection outlines for connections. In the modeler selection is indicated by showing the bendpoints.

![image](https://github.com/bpmn-io/bpmn-js/assets/7633572/452b6b98-a888-44bf-9723-10d162737aba)

In an interactive viewer selecting connections should be indicated. We should have a solution for that.

**Comment by nikku** [comment]
No interactivity means that you cannot properly react to states in i.e. overlays. Hence the viewer would always offer basic interactivity, including hover and selection.

**Comment by philippfromme** [comment]
Overlays is a feature of an _interactive_ viewer, I'd say.

**Comment by barmac** [comment]
I'd say there are 4 ways to display diagram:

* Modeler
* NavigatedViewer
* Viewer with some interactivity
* Displaying result of Viewer.saveSVG

Otherwise we should rename the Viewer to Renderer, as that's what it is without any interactivity.

**Comment by nikku** [comment]
Thanks for https://github.com/bpmn-io/bpmn-js/issues/2135#issuecomment-2047268633 @barmac. I subscribe to it. Without interactivity the viewer is simply a renderer. 

You can roll your own barebones renderer if you so desire on top of the [`BaseViewer`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/BaseViewer.js) package.

**Comment by misiekhardcore** [comment]
When I open the starter project locally, the outline seems to work fine. In the example linked I can see that the issue occurs cause there are no `diagram-js` styles added

**Comment by philippfromme** [comment]
The selection and outline features are part of the both the viewer and the modeler. Unless we decide to remove it from the viewer I'd say you simply must include `diagram-js.css` for it to work properly.

But even then there are a couple of issues:

* connection outline not shown (we decided to not show connection outlines anymore since the bendpoints feature indicates selection, we could enable it in the viewer)
* selecting multiple elements always selects text (at least in the example)

**Comment by misiekhardcore** [comment]
After adding the missing `diagram-js.css` the selection visuals seem to be fixed, the issue with selecting text persists but maybe it should be handled in a separate issue?

**Comment by misiekhardcore** [comment]
Won't this require the `Outline` feature to now be aware of `selection` and `canvas`?

**Comment by nikku** [comment]
@misiekhardcore The purpose of the [outline feature](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/outline/Outline.js#L34) is to render an outline (around elements), to be styled based on selection and other state. It is an _optional_ feature in the toolbox.

Selection on the other hand is a more _core_ feature of the toolbox, and hence we want to keep it as minimal as possible. The way components plug into selection is through events, so we already loosely couple things (nothing breaks if selection ends up not being there, but it is, if you want to make _anything_ selectable):

```javascript
function MyComponent(eventBus) {
  
  eventBus.on('selection.changed', function({ newSelection, oldSelection }) {
    ...
  });
}
```

We _could_ consider to not move the SelectionOutline into the `outline` feature, but make it a dedicated concern ([standalone feature](https://github.com/bpmn-io/diagram-js/tree/develop/lib/features)). However, for me it conceptional fits into the "outline" bucket. 

What I propose is to add a `MultiSelectionOutline` component within the outline feature, rendering the (multi-selection) outline. 


----

What is also useful in terms of design is to clearly separate UI and non-UI components. As part of [bpmn-js-headless](https://github.com/bpmn-io/bpmn-js-headless) we investigated a way to make core bpmn-js available for headless use. This works as long as only non-UI components ("the business logic") is used, but breaks if components wildly mix UI and non-UI concerns. In this particular case, using [the actual selection](https://github.com/bpmn-io/bpmn-js-headless/blob/main/src/Modeler.js#L5C8-L5C23) (to do whatever, i.e. trigger an editor action afterwards) will blow up the headless tool, unless [explicitly detangled](https://github.com/bpmn-io/diagram-js/commit/5db35ec636b047bac30b56661518d88b5d029e4f). Another reason to make this change.

**Comment by misiekhardcore** [comment]
Okay, that brings some more light into the problem we want to fix. I personally like the idea of having a separate `MultiSelectOutline` feature to have a better granularity and allowing the user to decide what they need

**Comment by misiekhardcore** [comment]
So, I opened a PR, but should I open an issue in `diagram-js`? or opening a PR and relating it to this one is the correct way?
Also I do not really know how to test it out, how can I play with the changes I made?

**Comment by nikku** [comment]
You can link the PR in your comment, to establish the context. No other issue is needed, if the PR is self explainatory in what we want to accomplish, and why. It should provide a clear rationale, [along the lines of this](https://github.com/bpmn-io/bpmn-js/issues/2135#issuecomment-2446077605).

**Comment by misiekhardcore** [comment]
Okay, I understand, I also saw your comment on the PR, I will try to improve the description there.
Other, implementation related question:
I created a separate feature `lib/features/outline/MultiSelectionOutline.js` but I am thinking if we should't move the single selection outline from selection feature too?

**Comment by nikku** [comment]
@misiekhardcore Which single selection outline? 

Elements ("single selection") are selected through outline styling, using a `marker` (CSS class). Given your approach both concerns are already clearly separated:

* Once you got `selection` pulled in, then you can select elements, and react to that state changing (markers change)
* Once you got `outline` pulled in, then you see visual outlines for elements, single (selection, potentially hover), but also multi-element (during selection).

**Comment by misiekhardcore** [comment]
I have decided to create a[ separate issue](https://github.com/bpmn-io/diagram-js/issues/944) for moving multi-select outlines to a separate module as this won't fix the issue described here.
The core problem here is that svg `rect` gets the black fill by default and as long as we include the `diagram-js` css file, it works fine, because it has styles defined for the multi-select which are setting `fill: none` ([here](https://github.com/bpmn-io/diagram-js/blob/develop/assets/diagram-js.css#L107-L112)).
`bpmn-js` has no default styling for this

**Comment by nikku** [comment]
> Technically if user does not pull in the Outline feature, it will all work now, and if they did add the Outline feature, they should include the diagram-js styles right?

That is the resolution, and we'll ship the viewer without the outline. As a result the viewer will not depend on the external style sheet, which always has been our intention. Or do I miss anything? 

If I understood correctly, then https://github.com/bpmn-io/bpmn-js/pull/2253 and https://github.com/bpmn-io/diagram-js/pull/943 solve this issue, which was our intention.

**Comment by misiekhardcore** [comment]
> If I understood correctly, then https://github.com/bpmn-io/bpmn-js/pull/2253 and https://github.com/bpmn-io/diagram-js/pull/943 solve this issue, which was our intention.

Yes, exactly

**Comment by nikku** [comment]
Ok, moved this issue to `fixed upstream`. Let's close it once the linked PRs / issues are merged.
