### ISSUE TITLE
Append preview not cleaned up when deleting element through keyboard

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#2150]
### Describe the Bug

When deleting an element using the keyboard while there is a preview the preview doesn't get cleaned up.

![brave_acVJ3O7hd2](https://github.com/bpmn-io/bpmn-js/assets/7633572/4cf8e65d-e78e-4ff4-9392-8d45630a81fe)

### Steps to Reproduce

1. Show append preview through hover
2. Delete selected element through keyboard
3. Preview not cleaned up

### Expected Behavior

Preview always cleaned up.

### Environment

 - Library version: 17.3.0

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/2152.
