### ISSUE TITLE
Popup Menu positioning breaks inside "containing blocks"

### ISSUE THREAD

**Issue by deje1011** [bpmn-io/bpmn-js#2156]
Thanks for your work on this library! 
We are currently trying to integrate it but we are facing an issue when embedding a bpmn diagram in a dialog.
I'm not sure if the issue should be solved in bpmn-js or in diagram-js but I think it's a general problem with the positioning of popovers:

### Describe the Bug

If a diagram is nested within a "containing block" that is not full screen, the positioning of the popup menu breaks. 
Imagine the following DOM structure: 

```html
<div class="content" style="padding: 100px;">
    <div class="canvas">
        <!-- diagram is rendered here -->
    </div>
</div>
```

<details>
<summary>Screenshot</summary>

<img width="1728" alt="image" src="https://github.com/bpmn-io/diagram-js/assets/9350748/adf21856-6fcb-4ba9-b03c-79552441449b">
</details>

As long as there is no containing block around the diagram, this works as expected. But if we turn the `canvas` element into a [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block) by adding a `transform`, the fixed position of the popup-menu will be relative to the position of that container, instead of the entire document. 

```html
<div class="content" style="padding: 100px;">
    <div class="canvas" style="transform: scale(1)">
        <!-- diagram is rendered here -->
    </div>
</div>
```

Therefore, the popover menu will be offset to the right and to the bottom by `100px` (which is the offset of the `.canvas` element, caused by the padding on the `.content`). 

<details>
<summary>Screenshot</summary>

<img width="1728" alt="image" src="https://github.com/bpmn-io/diagram-js/assets/9350748/252d7998-e535-4e43-bd7a-afc421cfc337">
</details>

### Steps to Reproduce

1. Open https://demo.bpmn.io/s/start
2. Add `100px` of padding to the `.content` element
3. Add `transform: scale(1)` to the `.canvas` element
4. Open a popover menu

### Expected Behavior

The position of the popover should not be affected by this.

### Possible Solutions

I think this could be solved by either appending the popover menu to the body or by subtracting the offset of the closest containing block before applying the position to the popover-menu element.
What do you think?

### Environment

Please complete the following information:

 - Browser: Chrome 123
 - OS: MacOS 13.6
 - Library version: 14.4.2

**Comment by nikku** [comment]
@deje1011 I moved this over to bpmn-js. Will have a look and see if I can reproduce your issue.

**Comment by nikku** [comment]
Could you elaborate why you need a `transform` outside of the diagram in the first place?

**Comment by barmac** [comment]
Thanks for reporting this! I'd be happy to review a contribution providing a fix for this. It could probably use the `offsetParent` property for the positioning of the popup menus: https://polypane.app/blog/offset-parent-and-stacking-context-positioning-elements-in-all-three-dimensions/#how-to-find-the-offset-parent

**Comment by deje1011** [comment]
> Could you elaborate why you need a `transform` outside of the diagram in the first place? I'd be hesitant to support it.

Sure! In our case, the diagram is shown inside a dialog. And the dialog has an opening animation, which uses `transform` to scale the dialog while it fades in. 

There are some other css properties that can cause the same issue if they were to be used on the `.canvas`:
`transform`, `perspective`, `will-change: transform/perspective`, `filter`, `contain`, `container-type`, `backdrop-filter`.
https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block

And I'm afraid we can't use the `offsetParent` property to find the containing block because it doesn't work for some of those cases.
https://bpceee.github.io/posts/10

**Comment by nikku** [comment]
> Sure! In our case, the diagram is shown inside a dialog. And the dialog has an opening animation, which uses transform to scale the dialog while it fades in.

Pragmatic solution: Remove `transform` attribute when scale turns `1`?

**Comment by nikku** [comment]
@deje1011 I think you do yourself a favor to get rid of `transform: ...` on any standard HTML components. 

The other option is for us to move such `position: fixed` elements to the `document.body`, but then again that poses the risk to break custom integrations; in fact we were there before, and [reverted that change](https://github.com/bpmn-io/diagram-js/pull/728), again.

**Comment by nikku** [comment]
I'll close this as `wontfix`. It is an edge case, and your usage of `transform` will break any tools that do `position: fixed` inside a dialog. Workaround is available.
