### ISSUE TITLE
make the artifacts element support flowElements

### ISSUE THREAD

**Issue by evin2333** [bpmn-io/bpmn-js#2160]
I have customized an element custom:Group, which inherits bpmn:Group and contains a new property flowElements:FlowElements.
When I finished saving the data and reloading the xml, I found that the child element under this custom:Group was not rendering.

**Comment by nikku** [comment]
@evin2333 I checked against the BPMN 2.0 meta-model and found that `bpmn:Group` does not support `flowElements`. Am I mistaken?

We'll not accept any contributions to add custom extensions in the core. Instead I recommend you to build your custom version of our BPMN editor to support your extensions there.
