### ISSUE TITLE
Remove button is not displayed for external labels

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#2163]
### Describe the Bug

<img width="132" alt="image" src="https://github.com/bpmn-io/bpmn-js/assets/28307541/73900942-9bd1-471e-9558-6e3ce273e1b6">

### Steps to Reproduce

1. Select an external label
2. Only color picker is available

### Expected Behavior

The button should be displayed.

### Environment

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

---

Initially reported via https://github.com/camunda/improved-canvas/issues/66

**Comment by jarekdanielak** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/2201
