### ISSUE TITLE
'create' opinion cannot removed in palette entries

### ISSUE THREAD

**Issue by okankrdg** [bpmn-io/bpmn-js#2165]
### Describe the Bug

'create' cannot remove from palette entries and mot filtering

![Screenshot_74](https://github.com/bpmn-io/bpmn-js/assets/61060461/94b2b17b-7368-4267-92dd-b85cc4b1a687)

### Steps to Reproduce

1. do this
```
export function CustomPaletteProvider(palette) {
  palette.registerProvider(this);
}

CustomPaletteProvider.$inject = ['palette'];

CustomPaletteProvider.prototype.getPaletteEntries = function (element) {
  return function (entries) {
    console.log('entries', entries);
    delete entries['create'];
    return entries;
  };
};

export default {
  __init__: ['customPalette'],
  customPalette: ['type', CustomPaletteProvider],
};
```

2. do that
'create' anything opinion still see in palette but if you remove other opinion like hand-tool, correctly works.

### Expected Behavior

'create' must be removed in palette entries

### Environment

 - Browser:  edge 125
 - Library version: latest

**Comment by nikku** [comment]
@okankrdg Create/append anything is not part of the core since [`v12.0.0`](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#1200). Closing this request as invalid.

If you report bugs, be precise, establish the necessary context and we'll be able to help you.
