### ISSUE TITLE
HTML validation errors

### ISSUE THREAD

**Issue by boris-petrov** [bpmn-io/bpmn-js#2179]
### Describe the Bug

Using the newest version, I get a lot of errors from my HTML validator like `Duplicate ID “marker-dgx997t15d1210s2srnctq0ez”`. Indeed, in the HTML I see two of that ID (and all the rest that the validator complains about). I'm not sure which version introduced that but it's recent - in the past week or two. I guess the problem might be [here somewhere](https://github.com/bpmn-io/bpmn-js/blob/v17.8.0/lib/draw/BpmnRenderer.js#L172).

### Steps to Reproduce

Just render any diagram in the modeler.

### Expected Behavior

No HTML-validation errors.

### Environment

 - Browser: Any
 - OS: Linux
 - Library version: 17.8.0

----

Depends on https://github.com/bpmn-io/diagram-js/pull/909.

**Comment by nikku** [comment]
@marstamm Could be related to https://github.com/bpmn-io/bpmn-js/pull/2173?

**Comment by nikku** [comment]
I can verify the report during dragging; if we clone elements with an ID we must change the ID or duplicates will occur:

![image](https://github.com/bpmn-io/bpmn-js/assets/58601/351eeda1-0f0b-4e8f-bb84-3d430cf98cd4)

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/issues/2181.

**Comment by boris-petrov** [comment]
Hi, thanks for the quick fix and sorry I didn't provide enough detail. I tried updating to `diagram-js@14.7.1` but I still get the same errors. I've attached the HTML (as TXT as GitHub doesn't allow HTML) that results in the error. The duplicate ID is `marker-6cnzxp45vcldqdsc7bp8xadlw`. You can see it twice in the HTML. My code is as follows:

```html
  <div class="canvas"></div>
  <div class="properties"></div>
```

```typescript
    this.modeler = new BpmnModeler({
      container: $('.canvas').get(0)!,
      keyboard: {
        bindTo: document,
      },
      propertiesPanel: {
        parent: $('.properties').get(0),
      },
      bpmnRenderer: {
        defaultFillColor: 'var(--bs-body-bg)',
        defaultStrokeColor: 'var(--bs-body-color)',
      },
    });
```

Let me know if that helps or you need more information?

[bpmn-bug.txt](https://github.com/bpmn-io/bpmn-js/files/15486888/bpmn-bug.txt)

**Comment by marstamm** [comment]
The duplicated markers come from the minimap. Seems like it copies the SVG and only strips the root `defs`

**Comment by marstamm** [comment]
Correction, we simply clone everything in the `djs-visual` when we replicate the elements in the minimap: https://github.com/bpmn-io/diagram-js-minimap/blob/156bcaa2d64013a13f4c601c013bb466ab124eed/lib/Minimap.js#L741-L746

we need to strip or change the markers there

**Comment by marstamm** [comment]
Given the issues we are facing in multiple sections of our code, I'll also evaluate if there are other solutions than rendering as part of `djs-visual` container

**Comment by marstamm** [comment]
Discussed with @nikku today:

- The minimap blindly copying elements, even those with IDs, is a bug. We will fix this in the minimap repo
- A potential other solution for tyleable markers (https://github.com/camunda/camunda-modeler/issues/4307) would be to use `context-stroke` and `context-fill` on the markers. The browser support for these is not well-documented, we will follow-up on this
