### ISSUE TITLE
Bug: demo + modeler example: if editing text followed by saveXML, the new text is missing in the xml

### ISSUE THREAD

**Issue by c-antin** [bpmn-io/bpmn-js#2197]
### Describe the Bug

if editing text followed by saveXML, the new text is missing in the xml

### Steps to Reproduce

1. goto https://demo.bpmn.io/
2. append a task
3. double click to edit text
4. add text
5. click download xml button
6. re-import xml
7. observe missing text

### Expected Behavior

editing text should trigger change event.
Or is there a way to trigger change before saving xml?
Note: every non-text action (e.g. click on elements) seems to trigger change.

### Environment

 - Browser: Chrome 126
 - OS: Win 10
 - Library version: bpmn-js 17.8.3

**Comment by philippfromme** [comment]
Did you actually confirm the label editing though <kbd>Enter</kbd> or clicking outside of the element? If you don't do that before downloading the XML the label will be missing.

**Comment by philippfromme** [comment]
A screencast demonstrating your issue would be helpful.

**Comment by c-antin** [comment]
> Did you actually confirm the label editing though Enter or clicking outside of the element? If you don't do that before downloading the XML the label will be missing.

I was of the impression that editing text without clicking outside would be enough to register the change.
I guess it's more of an inconvenience than a bug, then?

**Comment by barmac** [comment]
I can reproduce the issue. However, I don't think it's likely that we look into this. If you want to solve it on your own, you can call [`modeler.get('directEditing').complete()`](https://github.com/bpmn-io/diagram-js-direct-editing/blob/main/lib/DirectEditing.js#L84) before `modeler.saveXML()` is executed.

**Comment by c-antin** [comment]
Thanks for pointing me to `directEditing`! Since `saveXML` is async, I save on `'commandStack.changed'`. So sadly calling `complete()` does not help here!
Do you think it's a good idea to listen for `keyup` and calling `complete()` then?

**Comment by barmac** [comment]
Have you tried to complete the direct editing when [`saveXML.start` event](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/BaseViewer.js#L419) is fired. This way you complete only once, and right before the XML serialization is performed.

For further questions regarding your project, please head to [the bpmn.io forum](https://forum.bpmn.io/).
