### ISSUE TITLE
ContextPadProvider d.ts file has wrong type difinition 

### ISSUE THREAD

**Issue by J4CKVVH173** [bpmn-io/bpmn-js#2203]
I installed bpmn-js via npm and wrote custom ContexPad. I extended my class by `bpmn-js/lib/features/context-pad/ContextPadProvider` and used constructor. ts said that there are 12 constructor's props (screenshot 1). But when i've tried to use the system - i've got an error. I did a research and found out that ContextPadProvider in ContextPadProvider.js file has extra prop (there are 13 constructor props in source js file - screenshot 2).
![image](https://github.com/bpmn-io/bpmn-js/assets/33596000/d1692526-5a3e-4bc6-ac5e-9e4a26e335b3)

![image](https://github.com/bpmn-io/bpmn-js/assets/33596000/fcd1a3b3-a6e8-44fb-98b4-9a01ff78602a)

**Comment by barmac** [comment]
Indeed, the typescript definition looks incomplete. Would you like to file a pull request which fixes the problem?

**Comment by J4CKVVH173** [comment]
i could but i can't find `d.ts` file into the repository. i checked that the lib in common has 'pure js files' but where is the `d.ts` i don't have any clue

**Comment by barmac** [comment]
The type declarations are [generated from JSDocs with bio-dts](https://github.com/bpmn-io/bpmn-js/blob/develop/package.json#L27). To fix the problem, you'd need to change the JSDoc of the constructor.

**Comment by J4CKVVH173** [comment]
done

**Comment by philippfromme** [comment]
Closed by https://github.com/bpmn-io/bpmn-js/pull/2204
