### ISSUE TITLE
Toggling Vertical Pool Changes Its Direction

### ISSUE THREAD

**Issue by sombrek** [bpmn-io/bpmn-js#2208]
### Describe the Bug

When a vertical pool is collapsed (or expanded) it becomes a horizontal pool.

### Steps to Reproduce

1. Select any vertical pool, e.g. in https://github.com/bpmn-io/bpmn-js/blob/develop/test/spec/features/modeling/lanes/participant-no-lane-vertical.bpmn
2. Change element: Empty pool/participant or Expanded pool participant.

### Expected Behavior

The vertical direction of the pool should be respected.
Moreover, the behavior should suite the vertical direction i.e. the height of the vertical pool should remain, only the width may shrink (for horizontal pools it's vice versa).

### Environment

 - Library version: 17.9.1

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/2211
