### ISSUE TITLE
Lane resize constraints do not work when resizing from bottom right corner with any lane but the lowest one

### ISSUE THREAD

**Issue by StefanLerch** [bpmn-io/bpmn-js#2209]
### Describe the Bug

The lane resize constraints do not work when using any lane except for the lowest one of the participant and using the bottom right corner of the lane.

![chrome_3YOVUbaBhp](https://github.com/user-attachments/assets/75d70756-09e7-4cf9-9495-6b43a7d7f238)

### Steps to Reproduce

1. Create a pool with at least two lanes
2. Insert an element into one of the lanes
3. Resize any but the lowest lane with the direction "se"

Result: The width of the lane can be decreased beyond the elements inside of it.

### Expected Behavior

The participant and therefore one of the lanes should always contain all elements. It should not be possible to decrease the x coordinate of a lane/participant beyond that of the elements inside of it.

### Environment

 - Browser: Chrome v127.0.6533.73
 - OS: Windows 11 Enterprise
 - Library version: 17.6.4, also [demo](https://demo.bpmn.io/new)

**Comment by barmac** [comment]
Thanks for reporting. I can reproduce this issue. I will move it to the backlog, but if you are interested in providing a pull request fixing this, we will be happy to review it.
