### ISSUE TITLE
How to dynamically change i18n

### ISSUE THREAD

**Issue by tony2y** [bpmn-io/bpmn-js#2212]
When initializing Modeler, a language has already been set. How can I dynamically switch the display language now? For example, en ->fr, fr ->en
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/797cf961-c104-4de4-bc61-2c15998f8bee">
@nikku

**Comment by barmac** [comment]
Hi,

GitHub issues are a place to file feature requests or bug reports. For usage guidance, please head over to the forums: https://forum.bpmn.io

**Comment by tony2y** [comment]
ok ! thanks!
