### ISSUE TITLE
Spacing tool enhancements

### ISSUE THREAD

**Issue by crobbins215** [bpmn-io/bpmn-js#2215]
### Is your feature request related to a problem? Please describe.

The current spacing tool in the C7 Desktop Modeler is very precise, which can result in unintentional movements. This often requires restarting the process of selecting the spacing tool. This issue occurs in the production environment and impacts all users.

### Describe the solution you'd like
Addition of separate functionalities for the spacing tool, including the ability to move just horizontally and the ability to move just vertically. These should be in addition to the current functionality of moving both vertically and horizontally.

### Describe alternatives you've considered
Currently, no alternatives within the C7 Desktop Modeler address this issue directly. Users must attempt to move the tool precisely or restart the process if an unintended movement occurs.

### Additional context
Adding separate functionalities for horizontal _and_ vertical movements in the spacing tool would streamline the workflow and save time for all users. There is no specific deadline for this feature, but its implementation would improve efficiency in the production environment.

Feature request - https://jira.camunda.com/browse/SUPPORT-22648

**Comment by nikku** [comment]
@crobbins215 As I understand the desire is to make space in both directions (horizontal _and_ vertical at the same time)?

**Comment by crobbins215** [comment]
This issue is about bug https://github.com/camunda/camunda-modeler/issues/4172

> Hi Calvin, so I understand the functionality depicted in the image below. However, if one of the tasks has an associated annotation and you attempt to move either horizontally or vertically, the annotation does not move with the associated task. As such, when you complete the move, you have to go back and move the annotations individually.

Will close this FR
