### ISSUE TITLE
Increase Colour picker options

### ISSUE THREAD

**Issue by crobbins215** [bpmn-io/bpmn-js#2216]
### Is your feature request related to a problem? Please describe.

The current colour options are limited to five colours. This limitation is insufficient for adequately representing the numerous stakeholders involved in a process. 

### Describe the solution you'd like

An expansion of the available colour palette. The inclusion of a typical Microsoft colour palette would be sufficient, offering a variety of initial 'Theme' and 'Standard' choices as well as the ability to create new colours under the 'More Colors' option or being able to pick a colour from a code.

### Additional context

Increasing the number of available colours would allow users to better represent more stakeholders in a process. There is no specific deadline for this feature, but its implementation would improve user representation.

Feature request https://jira.camunda.com/browse/SUPPORT-22607

**Comment by nikku** [comment]
@crobbins215 I believe this is a feature request for Camunda's modeling offering, right? If so, could you please re-open this report in [Camunda Modeler](https://github.com/camunda/camunda-modeler)? 

Under the hood the [color picker already supports custom colors](https://github.com/bpmn-io/bpmn-js-color-picker/blob/main/colors/ColorPopupProvider.js#L33), gotta solve "configuring of custom colors and storing them" within the context of the modeler.

**Comment by crobbins215** [comment]
> @crobbins215 I believe this is a feature request for Camunda's modeling offering, right? If so, could you please re-open this report in [Camunda Modeler](https://github.com/camunda/camunda-modeler)?
> 
> Under the hood the [color picker already supports custom colors](https://github.com/bpmn-io/bpmn-js-color-picker/blob/main/colors/ColorPopupProvider.js#L33), gotta solve "configuring of custom colors and storing them" within the context of the modeler.

I will close this and have logged the ticket under that repo https://github.com/camunda/camunda-modeler/issues/4465
