### ISSUE TITLE
Existing lane names make it impossible to read them when editing

### ISSUE THREAD

**Issue by wieteLueck** [bpmn-io/bpmn-js#2219]
### Describe the Bug

When changing the name of a pool lane, the text is displayed slightly shifted twice, new text is written above it and is not readable until the next ENTER. 
![image](https://github.com/user-attachments/assets/92e4588b-8203-427b-a0c9-55742d5dabfa)

### Steps to Reproduce

1. Create a pool/participant
2. Divide it into two lanes
3. Double click on one lane to change the name
4. Click somewhere else
5. Double click on the same lane to change the name again

### Expected Behavior

When completely overwriting the name of the lane, the old name should not be visible while writing the new one.
When editing the existing name, the “old” name should be edited and not shown twice.

### Environment

 - Browser: Microsoft Edge Version 127.0.2651.74
 - OS: Windows 11
 - Library version: 17.9.2, [demo.bpmn.io](https://demo.bpmn.io/) (latest)

**Comment by nikku** [comment]
@philippfromme Can you reproduce this on Edge (Windows 11)?

**Comment by barmac** [comment]
We are happy to accept external contributions!

**Comment by abdul99ahad** [comment]
This issue is fixed in https://github.com/bpmn-io/bpmn-js/pull/2224. 
Related Issue: https://github.com/camunda/camunda-modeler/issues/4477

@philippfromme Pls confirm if we can close this issue.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/2224.
