### ISSUE TITLE
Most of BPMN invisible after zooming - Chrome

### ISSUE THREAD

**Issue by ev-codes** [bpmn-io/bpmn-js#2222]
### Describe the Bug

After using the following, most of the BPMN diagram disappears when using Chrome. The subprocess blue icon is still visible.
- `bpmnViewer.get('canvas').zoom('fit-viewport');`
- `bpmnViewer.get('canvas').zoom('fit-viewport', true);`

### Steps to Reproduce

1. Find a BPMN file that contains a subprocess ([example](https://raw.githubusercontent.com/camunda/camunda-platform-tutorials/main/solutions/capital-market-exception-processing/Capital_Market_Trade_Exception_Remediation_Processing.bpmn))
2. Open the BPMN file using bpmn-js
3. Call `bpmnViewer.get('canvas').zoom('fit-viewport');`
4. Refresh the page
5. The following happens:
    - BPMN lines mostly disappear, except for the blue subprocess icon
    - SVG remains in the DOM, but size values are `NaN`
    - No console error logs appear

I tried to use the playground in the issue template, but I get BpmnJS unresolved errors.

For now, I provide the following screen recording. I can debug the playground a little more if needed 😄 

https://github.com/user-attachments/assets/3a5814cf-8491-40f5-8b1d-828c0b12b75f

### Expected Behavior

BPMN should:
- be fully visible
- be centered in the viewport

### Environment

 - Browser: Chrome 127
 - OS: macOS 14.6.1
 - Library version: 4.17.0 (and 4.5.0)

**Comment by ev-codes** [comment]
@barmac this is the bug we discussed that occurred on [Camunda's Public Marketplace](https://marketplace.camunda.com/en-US/apps/449343/trade-exception-remediation-processing).

The AppDirect theme used in the screen recording [can be found here](https://github.com/camunda/public-marketplace/tree/main).

**Comment by crobbins215** [comment]
I would love to get this sorted, for the latest blueprints its more obvious

**Comment by nikku** [comment]
@ev-codes How far did you get debugging this? Any errors in the logs? Is the SVG still in the DOM?

**Comment by barmac** [comment]
We found out in the tests was that the SVG was in the DOM but got `NaN` values for size etc. 
However, the exact command was `canvas.zoom('fit-viewport', true)` to trigger centering (https://github.com/bpmn-io/diagram-js/blob/develop/lib/core/Canvas.js#L1386).

**Comment by ev-codes** [comment]
@barmac thanks for responding! For context, I also tried with `canvas.zoom('fit-viewport');` and got the same behaviour.

@nikku in addition to @barmac 's [comment](https://github.com/bpmn-io/bpmn-js/issues/2222#issuecomment-2298162927):
- I did not see any console error logs
- Sometimes, when first accessing the page, the diagram is rendered correctly (see video in issue description). However, after refreshing the page, the diagram render issues recur.

**Comment by nikku** [comment]
@ev-codes How can I try this out myself?

**Comment by ev-codes** [comment]
@nikku to replicate the screen recording in the description, you can:
1. Clone https://github.com/camunda/public-marketplace/tree/main
2. [Uncomment this line](https://github.com/camunda/public-marketplace/blob/26c7710531ebb1bdbdd9d48cea4c25abb1bc896a/sourcecode/themes/Plaza_Camunda/content/macros/profile/profile-details-tab.html#L646)
3. [Start a local instance of Marketplace](https://github.com/camunda/public-marketplace/blob/26c7710531ebb1bdbdd9d48cea4c25abb1bc896a/README.md#run-locally)
4. [Open this link](http://localhost:3555/en-US/apps/449343/trade-exception-remediation-processing)

**Comment by ev-codes** [comment]
@nikku do you and the team need any more information?

I see the `needs more information` label is still there, so I wanted to confirm 😄

**Comment by nikku** [comment]
No more information needed. To proceed, two options:

* You debug the issue and figure out what is happening inside your application. Should be possible. Idea here: Use the developer console to check the actual DOM, if it exists (I assume), see what "moves it off the screen" or otherwise hides it.

* I find time to look into the issue based on your steps to reproduce. As of today I assume this is an application/integration issue, and we have limited capacity to support debugging users and their applications.

**Comment by barmac** [comment]
This issue includes a feature request: "As a library user, I want to make my diagram fit the viewport and be centered at the same time so that it looks good". The `canvas.zoom('fit-viewport', true)` call is neither documented nor typed in the TS declarations.

**Comment by ev-codes** [comment]
@nikku I'll take a closer look at this next week, thanks!

@barmac I'll try using [a forum solution it appears you wrote](https://forum.bpmn.io/t/how-to-center-the-bpmn-graph-in-the-viewer/3773/10) first. If that doesn't work for me, I'll write up a feature request ticket. Of course, feel free to create one if you'd like 😄

**Comment by ev-codes** [comment]
@nikku @barmac I believe this was an application integration-related bug, so I'm closing this issue.

I believe I fixed it by showing a containing div that was hidden.

It appears that in Chrome, this was causing some zero/null results when getting the SVG's bounding box. Firefox's SVG implementation does not seem to have this issue.

[Here's my fix PR](https://github.com/camunda/public-marketplace/pull/52) with some more context if anyone is curious 😄

**Comment by nikku** [comment]
Great for investigating, fixing, and following up on this PR. Indeed `hidden` elements will cause some browsers to not properly compute bounds, as `display: hidden` completely removes things from the render tree. 

Things must be `visibility: none` (good workaround), or fully visible (off canvas) to be measured.
