### ISSUE TITLE
 bpmn-js@17.9.2 package ContextPadProvider.d.ts constructor missing parameter "appendPreview" 

### ISSUE THREAD

**Issue by kingsley-s** [bpmn-io/bpmn-js#2228]
### Describe the Bug

custom contextPad ,inject appendPreview, error:Expected 12 arguments, but got 13
if can't implement appendView in super function, error: ContextPadProvider.js appendPreview.cleanUp() error

contruct super appendPreview error:  Expected 12 arguments, but got 13
<img width="742" alt="image" src="https://github.com/user-attachments/assets/e42f5e20-fc82-448b-959c-b0faf94ff5f6">
 ContextPadProvider.js error:
<img width="536" alt="image" src="https://github.com/user-attachments/assets/2bbda051-ff2d-4414-a64d-fe8fd352ad33">

### Expected Behavior

<img width="928" alt="image" src="https://github.com/user-attachments/assets/890d0a69-d706-4875-a5fc-f88bab2295b0">

### Environment

 - Browser: [ Chrome 126.0.6478.185]
 - OS: [mac os]
 - Library version: [17.9.2]

**Comment by nikku** [comment]
This should be fixed with recent versions of the library, cf. https://github.com/bpmn-io/bpmn-js/edit/develop/lib/features/context-pad/ContextPadProvider.js.

**Comment by nikku** [comment]
Closed via ad7303c4c2bad31cd4677679010d96960b5eadb6.
