### ISSUE TITLE
cannot read properties of undefinde (reading 'saveXML')

### ISSUE THREAD

**Issue by slhasadi** [bpmn-io/bpmn-js#2229]
### Describe the Bug
hi i use the bpmn modeler with react js and i have a problem with this when i want to save changed xml It shows me an error cannot read properties of undefinde (reading 'saveXML')

i found when i used setState in modeler.on("element.click") function this error has show and when unused this its hasnt error
### Steps to Reproduce

1. do this
2. do that

### Expected Behavior
![Untitledrrrr](https://github.com/user-attachments/assets/52abf670-899e-4318-ab0c-d328bf545281)
![Untitledrrrr222](https://github.com/user-attachments/assets/5eb1f7a5-ef05-41e9-8b3b-848d08bbbc3e)

### Environment

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Mac]
 - Library version: [e.g. 17.9.2]

**Comment by nikku** [comment]
This is an issue with how you embed bpmn-js into your React app. Cf. https://github.com/bpmn-io/react-bpmn for a simple example that does this properly, via refs.

**Comment by slhasadi** [comment]
> This is an issue with how you embed bpmn-js into your React app. Cf. https://github.com/bpmn-io/react-bpmn for a simple example that does this properly, via refs.

thanks for your answer but I have some custom components and I used bpmn modeler but  this repo just used bpmn viewer
