### ISSUE TITLE
Search blows up in huge diagram

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#2232]
### Describe the Bug

When I search a [huge diagram](https://stage-demo.bpmn.io/s/application-processing) then search blows up with the following error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at compareStrings (BpmnSearchProvider.js:155:1)
    at eval (BpmnSearchProvider.js:72:1)
    at Array.sort (<anonymous>)
    at BpmnSearchProvider.find (BpmnSearchProvider.js:70:1)
    at SearchPad._search (SearchPad.js:186:1)
    at HTMLDivElement.eval (SearchPad.js:156:1)
    at HTMLDivElement.eval (delegate.js:35:1)
```

### Steps to Reproduce

1. Open [huge diagram](https://stage-demo.bpmn.io/s/application-processing)
2. Search for `a`
3. __Observe error in console__

### Expected Behavior

Search gracefully handles search.

### Environment

 - Browser: Chrome 110
 - OS: Linux
 - Library version: v17.11.0 (stage demo)

**Comment by nikku** [comment]
As this is introduced by recent changes we should fix this. Moving to `ready`.

**Comment by philippfromme** [comment]
Oh oh. I'll have a look.

**Comment by philippfromme** [comment]
Search blows up when [`getLabel`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/util/LabelUtil.js#L225) returns undefined which happens with associations for example. A minimal diagram to reproduce is one with two associations:

![image](https://github.com/user-attachments/assets/0aca2316-8f2c-4fe9-a642-49bc571e098e)

**Comment by barmac** [comment]
I can reproduce it.

**Comment by philippfromme** [comment]
Fix incoming: https://github.com/bpmn-io/bpmn-js/pull/2234
