### ISSUE TITLE
Improve search in huge diagrams

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#2233]
### Is your feature request related to a problem? Please describe.

As a follow-up to https://github.com/bpmn-io/bpmn-js/pull/2187 I reviewed the new search in a [huge diagram](https://demo.bpmn.io/s/application-processing). What I found is that search may not be as useful anymore due to two core changes:

* We do not keep the existing viewport, but reset the viewport to `1` (standard zoom), as a result, on smaller screens and large diagrams the "search context" is gone
* We do no longer aggressively highlight the search results (with blue background). This leads to results being hardly visible in crowded diagrams.

#### Old search

![capture oczmuT_optimized](https://github.com/user-attachments/assets/bc5a8edd-2332-49cf-8ee2-c3b7e3260707)

#### New search

![capture sFEAwq_optimized](https://github.com/user-attachments/assets/cadc1cf2-7402-4126-85f6-9db9857a1f29)

### Describe the solution you'd like

* [ ] Viewport is kept when searching, to accommodate for user intend (do I want to have a quick overview ("find usages across the diagram", or "do I want to jump to a particular element")
* [ ] We re-introduce the background for search results, this can be done easily though CSS:
  ```css
  .djs-search-open .djs-outline {
    fill: var(--element-selected-outline-stroke-color) !important;
    fill-opacity: .1;
  }
  ```

### Describe alternatives you've considered

No real alternatives; I need to be able to understand the "context" in which a particular element is used, to learn if it is relevant for my intend.

### Additional context

None.

**Comment by philippfromme** [comment]
By keeping the viewport you mean the zoom level?

**Comment by barmac** [comment]
Minor thing:
I'd expect it to show the fragment around the found string.

Before:
![image](https://github.com/user-attachments/assets/c32ae707-5065-483d-a9ce-2c15b4585a8b)

After:
![image](https://github.com/user-attachments/assets/0a9b5871-f85d-4775-9904-3fed72593efc)

Ideal:
![image](https://github.com/user-attachments/assets/cac0c33c-8202-4c68-a737-9e712aeedcce)

**Comment by barmac** [comment]
One thing which is annoying but present in the old solution as well is that the position is reset when I hit SHIFT without any changes to the string.

https://github.com/user-attachments/assets/1c2e6a35-2d3f-4dbf-9ac4-06fbc3def6c3

**Comment by lmbateman** [comment]
Possible future enhancements: Indicate how many results there are, provide a control for users to click through them, and highlight results on the screen, as the browser search does. The first time I tried out the new search, I searched for "termin", saw a list of results in the dropdown, pressed Return, and was surprised that only one element was selected in the diagram. I see now that you can scroll through the dropdown, and the results in the diagram are selected in turn as you scroll, but making the control a bit more obvious might be helpful.

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/e24244a9-b780-43d9-8954-0c99519d82ed">

**Comment by barmac** [comment]
Perhaps it makes sense to have a separate bug issue for the lacking contrast? WDYT @nikku?

**Comment by nikku** [comment]
> Perhaps it makes sense to have a separate bug issue for the lacking contrast? WDYT @nikku?

Yes. I'm not sure which contrast you refer to, please create a separate issue.
