### ISSUE TITLE
modelling rules for event subprocesses

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#224]
1) context menu
    * event subprocesses do not allow to model any bpmn elements
    * context menu only contains
      * delete
      * connection (but association only)
      * morph
2) morph of start events inside an event subprocess
    * the following options are possible (if interrupting)
      * message, timer, condition, signal, error, escalation, compensation
    * the following options are possible (if non-interrupting)
      * message, timer, condition, signal, escalation

**Comment by pedesen** [comment]
Solved with #302
