### ISSUE TITLE
Need support for Angular 17 and 18

### ISSUE THREAD

**Issue by swethadmurthy2024** [bpmn-io/bpmn-js#2243]
### Describe the Bug

1) unable to load BPMN file while using angular 18.2.6
2) With Angular 7.3.9, I have to use "npm install --force", which is not the best practice.

Please provide support for Angular 17 and 18

**Comment by barmac** [comment]
Please check out the Angular example: https://github.com/bpmn-io/bpmn-js-example-angular

For the usage questions/problems, feel free to open a thread at https://forum.bpmn.io

**Comment by barmac** [comment]
I am closing this issue as it's not a bug in bpmn-js.
