### ISSUE TITLE
sequence flow stay red under certain conditions

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#225]
Steps to reproduce:
    * model start event
    * model gateway from context pad
    * morph gateway to event based gateway
    * model receive task from context pad of gateway
    * model conditional event also from context pad of gateway

Problem
    * one sequence flow is red, see image below

![image](https://cloud.githubusercontent.com/assets/3829733/6559113/feced7b4-c680-11e4-8d0f-76840c432581.png)

**Comment by gimbel** [comment]
I found another way to reporudce (similar steps as above)
![image](https://cloud.githubusercontent.com/assets/3829733/6598823/81558e68-c806-11e4-983c-e895a9f1998c.png)

**Comment by nikku** [comment]
I wonder whether this still occurs. We did some fixes on the touch interaction integration (which may have caused this).

**Comment by gimbel** [comment]
Not able to reproduce, I will close the ticket until we are able to do so.

Otherwise consider it fixed :)
