### ISSUE TITLE
When editing, it is likely to cause the loss of xml 'xmlns'

### ISSUE THREAD

**Issue by zxuanhong** [bpmn-io/bpmn-js#2261]
### Describe the Bug

1. If no attribute modification operation is performed after creating the model, it will result in the loss of the xml xmlns
2. video 

https://github.com/user-attachments/assets/db0ab75e-4bca-45da-aee5-a6f1814eb7ff

3. After adding elements and modifying properties, it returned to normal

https://github.com/user-attachments/assets/dccff907-24d4-4190-9ca1-611613bfc20d

### Environment

 - OS: [e.g. Windows 7] mac
 - Library version: [e.g. 2.0.0] camunda model

**Comment by nikku** [comment]
I apprechiate your video as steps to reproduce, could you also attach a human readable description? 

What `xmlns` do you expect to be there, for what reason? 

And why is it a bug that the namespace is _NOT_ there?

In which concrete way can I reproduce this on my machine?
