### ISSUE TITLE
Improve on auto layouting

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#227]
Change the way auto layouting works by making the one bendpoint connection marker the default if the two connected elements are not on the same axis.

---------

## Original Issue

This what I typically model behind any gateway
![image](https://cloud.githubusercontent.com/assets/3829733/6636347/8105564a-c96f-11e4-9251-e5186b4ccb16.png)

This is how I adjust the layout anytime
![image](https://cloud.githubusercontent.com/assets/3829733/6636362/98c5c0ee-c96f-11e4-8f98-45ade8f121bb.png)

The rule could be: if the following element is not snapped on the horizontal line with the gateway, the sequence flows are drawn from the upper/lower corner of the gateway

**Comment by gimbel** [comment]
This has nothing to do with tasks, the same holds true for events, that follow a gateway

**Comment by gimbel** [comment]
Another example which shows the desired behaviour independant from gateways

Current behaviour
![image](https://cloud.githubusercontent.com/assets/3829733/7855150/94da1566-051f-11e5-8afa-a8a8a724107d.png)

Intended behaviour
![image](https://cloud.githubusercontent.com/assets/3829733/7855158/a69753ae-051f-11e5-9a01-caafa95c8708.png)

**Comment by gimbel** [comment]
And another one for events

Current:
![image](https://cloud.githubusercontent.com/assets/3829733/7855175/d196690a-051f-11e5-9f4e-937536bc5771.png)

Intended

![image](https://cloud.githubusercontent.com/assets/3829733/7855184/e80b6d16-051f-11e5-985b-ffb872f7e6c2.png)

**Comment by nikku** [comment]
This is now configurable. We will ship with the originally specified behavior (outgoing top, bottom for gateways) and can easily change the behavior for others (tasks, events) in the future.
