### ISSUE TITLE
incorrect z-order of associations

### ISSUE THREAD

**Issue by ISO50** [bpmn-io/bpmn-js#230]
1. Create a flow node with an attached text-annotation
2. Create sub-process
2. Move Text-Annotation or the flow node to the subprocess
--> Association is hidden by the subprocess, if you mix step 1 and 2 the association is drawn correctly. This happens as we do not update the position in the SVG tree as the association does not change it parent.

**Comment by nikku** [comment]
We should probably simply move the association to the front after performing such an operation.
