### ISSUE TITLE
I can drop new elements on flows

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#232]
It should be possible for a user to insert an flow element in between two existing elements by dropping it from the palette onto the connecting flow.

* [x] new element from palette can be dropped on an existing flow `[S] ---> [E]`
* [x] this results into a new element `[N]` being added
* [x] the new element splits the flow into two flows resulting in `[S] --> [N] --> [E]`
* [x] During drop on a connection, visuals indicate whether inserting is allowed

#### Example

The following screencast shows _a possible_ behavior in action:

![droponflow](https://cloud.githubusercontent.com/assets/3829733/6863916/059a6004-d45a-11e4-8dc7-8b2a0289af9d.gif)

#### Specifications

* Once a user drops a flow node on a connection, rules check, whether dropping it is allowed
* A visual indication is shown on the target connection during dropping
* The diagram is updated after drop
* The feature is tested
* The feature can be undone

#### Help 

* We have the basic move interaction [already implemented](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/move/Move.js)
* The component checks [rules](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/rules/Rules.js) that define whether a certain modeling operation can be executed.
* To insert an element in between flows, existing functionality to [create elements](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/create/Create.js) and [connect them](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/connect/Connect.js) can be useful.

**Comment by ISO50** [comment]
@gimbel 
So after inserting the the element. 
The incoming connection should be equal to the existing one, and the outgoing connection should be a new one?

**Comment by nikku** [comment]
Yes, that is the idea. I am going to attach some more information later.
