### ISSUE TITLE
External label position changes during element morph

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#235]
Reproduce:

 * model a XOR gateway
 * add a label to the gateway 
 * move the label from bottom to top of gateway
 * morph the gateway to any other gateway (e.g. parallel)

Problem:
 * label position is changed to bottom again after morph

Expected:
 * label position does not change because of morph

**Comment by philippfromme** [comment]
This bug also causes labels on connections to be positioned at the center of the initial waypoints even after the waypoints changed.

Reproduce:

* model a connection
* change the waypoints of the connection by dragging it
* add a label

Problem:

* label position is at the center of the initial waypoints

Expected:

* label position is at the center of the current waypoints
