### ISSUE TITLE
I can use multi-select + space tool from the palette

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#244]
* [x] integrate space tool into the palette
* [x] integrate multi-select into the palette
* [x] create key bindings for space tool
* [x] create key bindings for multi select tool

**Comment by gimbel** [comment]
related to #243

**Comment by gimbel** [comment]
It would be nice to have some mouse-over-explanation in the palette, what the different modes are about.

**Comment by nikku** [comment]
Related to #264
