### ISSUE TITLE
Invesigate MIWG test suite result

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#245]

**Comment by falko** [comment]
Thttp://bpmn-miwg.github.io/bpmn-miwg-tools/

**Comment by nikku** [comment]
We will look into this at the beginning of the next milestone and possibly ship with a bug fix release depending on our review results.

**Comment by falko** [comment]
I'll need to test the Berlin demo with other participants starting from 
next week. I'll fix it manually in the files for now.

**Comment by gimbel** [comment]
I will close this one, since we have specific issues now
