### ISSUE TITLE
Viewer / Modeler modules should be replacable

### ISSUE THREAD

**Issue by adrobisch** [bpmn-io/bpmn-js#258]
For the initialization of a Modeler or Viewer, its currently only possible to define either the whole set of modules or some additional modules via the options object. The latter is not sufficient to change default behavior and the former requires to much knowledge about internals.

There should be a way to replace modules by name. e.g. 

```javascript
var options = {
  replaceModules: {
    "contextPadProvider": {...} 
  }
  ...
}
```

**Comment by nikku** [comment]
You can override diagram components by simply redefining them in override modules, i.e. modules that provide a interface compatible version of the service with the same name.

I added some documentation to the viewer and modeler entry points mentioning this option.

**Comment by nikku** [comment]
See [relevant docs section](https://github.com/bpmn-io/bpmn-js/commit/6b23d181d5db9fa2dd07500208b46080a4d4dd9b#diff-6a28cb13662494293351ba71b07c2a92R68)
