### ISSUE TITLE
Message flow not updating correctly after changing source

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/bpmn-js#267]
steps to reproduce it: 
- Create participant A and B.
- Create a start event and a task inside of A.
- Connect participant B to the task inside of A.
- Change the message flow start from participant B to the start event.

problem:
- The connection remains a message flow.

expected behavior
- The message flow should be replaced by a sequence flow.

**Comment by gimbel** [comment]
I was trying to reproduce this bug, but did not get what the *problem* and *expected behavior* would look like

**Comment by pedesen** [comment]
@gimbel I just added it to the description.
