### ISSUE TITLE
I can model a default flow

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#272]
Default Flow
 * a sequence flow following an exclusive or inclusive (XOR and OR) gateway can be morphed into a default flow
 * it is only possible to have one of the sequence flows following as default flow
   * so we should check somehow that no other default flows exist
 * it should also be possible to morph back to a normal sequence flow

Conditionale Flow
 * all flows following activities (subprocess, task, call activity) can be morphed into conditional flows
 * in the xml we have to add an empty expression (I guess?)

**Comment by gimbel** [comment]
![image](https://cloud.githubusercontent.com/assets/3829733/8800844/6761fbb4-2fb6-11e5-9258-f172958d603f.png)

**Comment by jblankendaal** [comment]
Hi, this is functionality I was looking for, any idea when it will be implemented? Very nice bpmn tool btw, I'm impressed!

**Comment by nikku** [comment]
We are planing to work on it in our next milestone.

**Comment by jblankendaal** [comment]
Great! Is there a due date (roughly...) for that milestone?

**Comment by nikku** [comment]
No due date, sorry!

**Comment by jblankendaal** [comment]
:-) Thanks, I'll keep an eye on it then.

**Comment by ricardomatias** [comment]
This issue will be used for the direct development of default flows and [issue#369](https://github.com/bpmn-io/bpmn-js/issues/369) for conditional flows.
