### ISSUE TITLE
Wrong connection between elements

### ISSUE THREAD

**Issue by ISO50** [bpmn-io/bpmn-js#274]
If modelling an element  from the context pad and drop it to another pool, the connection type  is an undirected Association. I would expect a Message Flow instead.

**Comment by ISO50** [comment]
![connection](https://cloud.githubusercontent.com/assets/6464494/7581787/58958062-f887-11e4-9ac1-7992dfe88a36.png)

**Comment by gimbel** [comment]
In this case a message flow is not allowed from a BPMN perspective

try the same with two tasks and you will get the expected behaviour

**Comment by ISO50** [comment]
👍
