### ISSUE TITLE
I can model activity markers (loop and MI)

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#275]
* [x] Using the attribute menu (#294) the following marker can be modeled: multi instance parallel, multi instance sequential, loop
* [x] Markers are exclusive
* [x] Interacting with the attribute toggles does not close the context pad

Depends on attribute menu (#294)

**Comment by pedesen** [comment]
Should it be possible to toggle the collapse state of SubProcesses via the attribute menu?

**Comment by gimbel** [comment]
Good point: I think the subprocess should not be in the marker menu at all, this is rather a morph
