### ISSUE TITLE
XML namespace declaration not preserved during roundtrip

### ISSUE THREAD

**Issue by falko** [bpmn-io/bpmn-js#278]
... for namespace prefix that is only used in attribute values.

See bpmn-miwg/bpmn-miwg-demos#16

Inputfile: [handle-invoice.bpmn](https://github.com/bpmn-miwg/bpmn-miwg-demos/blob/09cc16c62965e54c19306576fba702e7fe5085f1/2015-06-15-19-omg-technical-meeting-berlin/execution-demo/handle-invoice.bpmn)

**Comment by nikku** [comment]
This works now, as we correctly roundtrip manually added namespaces.
