### ISSUE TITLE
Conditional in sequence flows (and questions in general)

### ISSUE THREAD

**Issue by matehat** [bpmn-io/bpmn-js#281]
Hello,

Sorry to have to create an issue for this, but I can't find any good guidance on the matter anywhere.

If we have questions, like how to do X or Y, where should we go? some IRC chatroom? some mailing list?

Right now, I want to programmatically add a condition to a sequence flow. The documentation is lacking and browsing the code doesn't seem to go anywhere on this. 

Thanks

**Comment by matehat** [comment]
BTW, I know I can get to the sequence flow's `businessObject` by hooking onto `eventBus`'s `selection.changed` triggered event, but once I get there, I don't know how I can add a condition, and have that be reflected in the diagram (the little diamond shape).

**Comment by nikku** [comment]
A better place to ask these questions is our [project forum](https://forum.bpmn.io).

Regarding your actual issue: You would need to update the sequence flows `condition` property.

Use the `modeling.updateProperties()` method to do it in a way that plugs into the diagrams redo/undo cycle.

```javascript

bpmnjs.inject(function(elementRegistry, moddle, modeling) {
  var condition = moddle.create('bpmn:FormalExpression', { body: 'some-expression' });

  var connection = elementRegistry.get('someSequenceFlow');

  modeling.updateProperties(connection, {
    condition: condition
  });
});
```

**Comment by matehat** [comment]
Awesome, thanks for the link!

**Comment by matehat** [comment]
For the record, it's `conditionExpression` you need to update, not `condition`. Thanks again!
