### ISSUE TITLE
DI attributes with wrong namespace prefix

### ISSUE THREAD

**Issue by falko** [bpmn-io/bpmn-js#283]
The attributes BPMNDI:name and BPMNDI:resolution of  BPMNDiagram are prefixed with DI. These prefixes should just be omitted as the element BPMNDiagram is already in the correct namespace.

See bpmn-miwg/bpmn-miwg-demos#11

To reproduce perform a roundtrip with this file: [Fridge repair service.bpmn](https://github.com/bpmn-miwg/bpmn-miwg-demos/blob/c922bc97bfff04613bdcf7c1410f2a1747ca2f53/2015-06-15-19-omg-technical-meeting-berlin/hidden-attribute-interchange/Fridge%20repair%20service.bpmn)

Schema validation output:
diagram.bpmn:557: element BPMNDiagram: Schemas validity error : Element '{http://www.omg.org/spec/BPMN/20100524/DI}BPMNDiagram', attribute '{http://www.omg.org/spec/DD/20100524/DI}name': The attribute '{http://www.omg.org/spec/DD/20100524/DI}name' is not allowed.
diagram.bpmn:557: element BPMNDiagram: Schemas validity error : Element '{http://www.omg.org/spec/BPMN/20100524/DI}BPMNDiagram', attribute '{http://www.omg.org/spec/DD/20100524/DI}resolution': The attribute '{http://www.omg.org/spec/DD/20100524/DI}resolution' is not allowed.

**Comment by nikku** [comment]
Closed via bpmn-io/bpmn-moddle#31
