### ISSUE TITLE
Roundtrip removes mandatory source and target from relationship element

### ISSUE THREAD

**Issue by falko** [bpmn-io/bpmn-js#285]
6_bpmn.io_FridgeRepairService.bpmn:3: element relationship: Schemas validity error : Element '{http://www.omg.org/spec/BPMN/20100524/MODEL}relationship': Missing child element(s). Expected is ( {http://www.omg.org/spec/BPMN/20100524/MODEL}source ).

To reproduce perform roundtrip with this file: [5_Camunda_FridgeRepairService.bpmn](https://gist.github.com/falko/32256e9e3e8723495ced)

Here is the according portion of the XML Schema:
```xml
	<xsd:element name="relationship" type="tRelationship"/>
	<xsd:complexType name="tRelationship">
		<xsd:complexContent>
			<xsd:extension base="tBaseElement">
				<xsd:sequence>
					<xsd:element name="source" type="xsd:QName" minOccurs="1" maxOccurs="unbounded"/>
					<xsd:element name="target" type="xsd:QName" minOccurs="1" maxOccurs="unbounded"/>
				</xsd:sequence>
				<xsd:attribute name="type" type="xsd:string" use="required"/>
				<xsd:attribute name="direction" type="tRelationshipDirection"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>	
```

**Comment by nikku** [comment]
Closed via bpmn-io/bpmn-moddle@4c146a75b34553c3cd0277a39aac8266345dc23e
