### ISSUE TITLE
SVG export contains Resizer

### ISSUE THREAD

**Issue by ISO50** [bpmn-io/bpmn-js#286]
I can't reproduce it all the time but I have cases where the SVG contains classes like: 'djs-resizer', 'djs-resizer-ne'. That causes to render an ugly version of the resizer anchors.

Should remove elements matching the selectors on exported SVG or unselect all elements before export.

**Comment by nikku** [comment]
Resizers are drawn on a different SVG layer nowadays. This should resolve the issue.
