### ISSUE TITLE
It is possible to visually drag elements outside of pools using multi select

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#288]
reproduce:
- see forum post https://forum.bpmn.io/t/i-can-move-elements-out-of-pools-by-multi-selection/149

**Comment by nikku** [comment]
Actually this is not a bug but a feature. You never really dropped the element outside the pool. It just looks like you did.

Rather than rejecting such a modeling operation we should work on the auto-expand for pools (and other containers, c.f. #263).

That would pretty much fix the issue.

**Comment by gimbel** [comment]
agreed

**Comment by pedesen** [comment]
Related to #353, resolved via https://github.com/bpmn-io/bpmn-js/commit/857454bbc13bb6f83221c256ef0dd54d7cfe9fed
