### ISSUE TITLE
FlowNodes outside laneSets not being rendered

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#300]
Lane sets have kinda week semantics in BPMN 2.0.

Currently we assume that all flow nodes need to be _inside_ a laneSet. Consequently we do not draw them if lane sets are added just for fun. 

This is something we should probably adjust.

See [this diagram](https://forum.bpmn.io/uploads/default/original/1X/2ee7a65d8150e9b0405c19b1af0c24ed92f6a3a5.bpmn). 

[`BpmnTreeWalker#L310`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/import/BpmnTreeWalker.js#L310) is the reason for the current behavior.

**Comment by falko** [comment]
I completely agree. Lanes are just an additional partitioning of the process, which does not have an effect on the semantics. Thus, it should not dominate the rendering. However, I'll also talk to the tool vendors that produced this model to see if they can fix their export.

**Comment by nikku** [comment]
This is not an issue anymore.
