### ISSUE TITLE
Simplify setup instructions

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#318]
Our setup instructions are slightly to complicated and outdated. Most of our dependencies are stable enough to be pulled via npm in the correct versions.

That said, a simple setup could consist of _only_

* diagram-js
* bpmn-js
* bpmn-moddle

Simplifying our setup instructions would allow users to get started with the project more easily.

**Comment by ricardomatias** [comment]
Mac OS X should also be mentioned within the instructions.
