### ISSUE TITLE
Allow editing of hidden BPMN properties via properties panel

### ISSUE THREAD

**Issue by linudaar** [bpmn-io/bpmn-js#324]
Hi, I am watching your project and I like it very much. Looking forward to see it maturing.

Here is an Idea/Feature Request:

User Story
As a BPMN modeler ...
... I'd like to have a possibility to add bpmn-compliant properties to BPMN items (such as activities, sequenceFlows,...)
... So that I can execute the resulting BPMN file after I finished modelling by any process engine that can interpret standard BPMN. 

Acceptance Criteria
* I can add implementation property to userTask and serviceTask
* I can add conditionExpression property to sequenceFlow
* I can add script and scriptFormat properties to scriptTask
* I can add gatewayDirection property to gateways
* I can add ioSpecification, dataInputAssociations and dataOutputAssociation to userTask and serviceTask (KISS for the beginning: plain xml)

Solution Proposal
The goal of adding additional properties to BPMN items in order to make the model executable can be achieved by introducing a dialog for key-value-pairs (e.g. "`<userTask implementation=foobar .../>`") and innerXML (e.g. `<serviceTask><ioSpecification>...</ioSpecification>...</serviceTask>`). This would do it for a while ...

BR

**Comment by nikku** [comment]
Looks like this is being addressed by [bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel), right? We are going to ship that properties panel in the next month(s).

I am leaving this open as a reminder.

**Comment by linudaar** [comment]
Great to hear that! Can I already see it in action (or, instructions on how to install it locally?)

**Comment by meyerdan** [comment]
Yes:
https://github.com/bpmn-io/bpmn-js-examples/tree/properties-panel/properties-panel

**Comment by linudaar** [comment]
Looks nice, thanks. 
I appreciate the fact that you have "providers" as I will have to write my own provider for a few properties.

**Comment by dalestone** [comment]
Looking good! This is one feature I am looking forward to having.

How would I go about adding custom properties to display in the panel? I guess I need to write my own provider as mentioned by @linudaar 

Also is there much functionality left to add or will this be merged into the master branch of the modeler soon?

Thanks.

**Comment by nikku** [comment]
Soon.

**Comment by nikku** [comment]
Closing this. The [bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel) is mostly feature complete with the latest release.
