### ISSUE TITLE
Boundary Event label is not moved on selection move

### ISSUE THREAD

**Issue by adrobisch** [bpmn-io/bpmn-js#326]
Not sure if this is intended behavior or not but at least it feels strange (tested on http://demo.bpmn.io/new) :

**GIVEN**:
Diagram with boundary event

**WHEN**:
Select all elements (Ctrl + A) and
move selection to right

**THEN**:
Boundary event label remains at old position instead of being updated relative to the event.

**Comment by nikku** [comment]
This is a bug. Thanks for the report :grinning:.
