### ISSUE TITLE
Update position of connection labels

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#331]
The position of connection labels should be updated either when moving one of the connected elements or when moving bend points of the connection itself.

#### Scope

* [x] update label position on connection segment move
* [x] update label position on adding a bendpoint
* [x] update label position on moving a bendpoint
* [x] set new label position when label is out of connection bounds

* [x] update label position reconnect start/end
* [x] update label position moving shapes
* [x] update label position on update waypoints

**Comment by aars** [comment]
:+1:

**Comment by Fundamentalistic** [comment]
Good day. bpmn-js doesn`t updat label position when I change waypoints

**Comment by nikku** [comment]
@Fundamentalistic Please create a new issue, reference this one and provide clear steps to reproduce. Thank you.
