### ISSUE TITLE
Re-think message flows layout between participants

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/bpmn-js#333]
At the moment when you move around a participant that is connected with a message flow to a smaller participant, the message flow keeps the smaller's participant anchor point into account for the message's flow layouting.

An improvement could be having the sequence flow stay put till it has to move, because it's reaching the limit of one of the participant's bounds.

**Comment by nikku** [comment]
Fixed? Otherwise we'd need to add some additional info (i.e. pictures) if we would like to understand what is behind this in two month.

**Comment by ricardomatias** [comment]
Solved in [bpmn-io/diagram-js/issues/110](https://github.com/bpmn-io/diagram-js/issues/110).
