### ISSUE TITLE
Use Github for *.bpmn files revision control and storage

### ISSUE THREAD

**Issue by tormi** [bpmn-io/bpmn-js#342]
It would be very useful to have an option to use Github repo for *.bpmn files revision control and storage.

**Comment by nikku** [comment]
This issue seems to be off topic because this library does not store any diagrams.

**Comment by tormi** [comment]
Sry, I've filed this issue against demo.bpmn.io. Draw.io can use dropbox google drive etc as file storage and I thought this could be useful here as well. But of course I can load a *.bpmn from my local repo and sync it with github after modifications using demo.bpmn.io or chrome client. Thanks anyway.

**Comment by nikku** [comment]
Yea, will keep this in mind once the demo gets the ability to save files to some external place.
