### ISSUE TITLE
Provide a callback or promise to BpmnTreeWalker.handleDefinitions()

### ISSUE THREAD

**Issue by kenda** [bpmn-io/bpmn-js#350]
I'm using the BpmnTreeWalker to parse and handle some BPMN stuff which works quite well. But after parsing and handling the definitions, I want to do some other things that require the promise that the walker really finished. I'm using the module in the same way the [Importer.js](https://github.com/bpmn-io/bpmn-js/blob/master/lib/import/Importer.js) does. So as far as I can see there is no clean way at the moment to ensure that handleDefinitions() really finished. This may also belong to #237.

**Comment by nikku** [comment]
The `BpmnTreeWalker` is synchronous. Simply call it and wait for its completion.

See [Importer.js#L49](https://github.com/bpmn-io/bpmn-js/blob/master/lib/import/Importer.js#L49) for how it is being used in a synchronous way.

**Comment by kenda** [comment]
Figured out this was an issue with an asynchronous call inside the visitor.element function. Sorry for that.

**Comment by nikku** [comment]
Good to hear you could figure this out.
