### ISSUE TITLE
Zooming while creating element should keep the element under the cursor

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/bpmn-js#355]
When creating an element (f.ex from the palette) if the canvas is zoomed in/out, the wrong matrix is applied to the element's positioning, resulting in the element NOT being under the cursor.

**Comment by vladimirskatusenoks** [comment]
This makes it very hard to work with large diagrams.

Example usage scenario:

1. Zoom in
2. Initiate connection
3. Zoom out and navigate to the target element
4. Click on target.

Connection still being created correctly, however, visual feedback is incorrect.

Relates to #474, #481, #394

**Comment by vladimirskatusenoks** [comment]
Scrolling canvas results in similar effect.

By the look of it, the issue is in [Dragging.js](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/dragging/Dragging.js).
