### ISSUE TITLE
How to get bpmn-js distribution without any package manager?

### ISSUE THREAD

**Issue by arapoport** [bpmn-io/bpmn-js#360]
Hi,

I could not find any downloads for your releases. Are the package managers the only way to get bpmn-js? How to integrate bpmn-js in a project, that does not use npm or bower?

Thanks!

**Comment by nikku** [comment]
You can simply download the [prebuild distribution](https://github.com/bpmn-io/bower-bpmn-js/tree/master/dist) or download the [seed project](https://github.com/bpmn-io/bpmn-js-seed/archive/master.zip) that contains bpmn-js embedded in a web page.
