### ISSUE TITLE
Boundary events are always visually on top

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#361]
Steps to reproduce:
- create a task with a boundary event
- create a sub process
- move the sub process over the task

problem:
- the task is visually behind the sub process, but the boundary event is in front

expected behavior:
- both task and boundary event should be visually behind the sub process

Rework of the BpmnOrderingProvider is required to solve this issue.

**Comment by nikku** [comment]
Unfortunately implementing this behavior is not trivial.

**Comment by nikku** [comment]
We won't act on this anytime soon; we accept PRs though!
