### ISSUE TITLE
Select multiple elements in OSX (cmd-click)

### ISSUE THREAD

**Issue by elnin0815** [bpmn-io/bpmn-js#363]
ctrl-click is mapped to a right-click by OSX by default. It's currently not possible to select multiple elements by clicking on them.
The standard key-mouseclick combination on OSX would be cmd-click.

**Comment by pedesen** [comment]
Hi, we changed the keybinding for multi selection to shift-click in this commit: https://github.com/bpmn-io/diagram-js/commit/cb53254fd8924ce24db6e53c3404bc65554c9855
