### ISSUE TITLE
Remove jsdoc from the build

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#378]
Now that we have our awesome hidden docs, we should get rid of JSDOC entirely in our projects.

__Reason:__ JsDoc is not needed anymore and regularly causes issues for people that do not have JAVA installed (or JAVA_HOME configured).

Cf. [forum thread](https://forum.bpmn.io/t/build-failure-with-jsdoc-on-ubuntu/307).

Projects to check:

* bpmn-js
* diagram-js
* bpmn-moddle
* moddle
* moddle-xml

**Comment by DrummerHead** [comment]
I'd be interested to get a hold of those awesome hidden docs you're talking about :)
