### ISSUE TITLE
Connection Layout lost for data associations and normal assiciations

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#380]
Reproduce:
- connect data object to a task
- add a bendpoint to the data association
- move data object or task

Problem
- connection is re-layouted and bendpoint is lost

Expected
- bendpoint is not lost and connection behaves similar to sequence flow

Hint:
I see two solutions:
- data associations behave like normal flows (except for initial layouting) -> preferred
- bendpoints cannot be added to data associations

**Comment by pedesen** [comment]
The same behavior appears for text annotations / associations.
