### ISSUE TITLE
Moving one dockingpoint over another deletes both

### ISSUE THREAD

**Issue by nkoehring** [bpmn-io/bpmn-js#383]
When dragging one docking point over another docking point, the other one is moving, too. Doesn't work always. Easiest way to reproduce is to take the target docking of the first connection in the bpmn.io demo (/s/start) and drag it over its source docking.

![bendpoint-gone](https://cloud.githubusercontent.com/assets/58601/15387896/b01a838e-1daf-11e6-95cf-68f9de7b2495.gif)

__Solution__

* [ ] moving over the other bendpoint keeps the other one and removes the moved one

**Comment by hoferch91** [comment]
Closing through 7d9f7d899f8751ef85d521ea324b31b080ba902b in diagram-js
