### ISSUE TITLE
Flows not being correctly cropped

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/bpmn-js#386]
**before**:
![after](https://cloud.githubusercontent.com/assets/8850708/10506294/551c3be2-7316-11e5-9eaa-819e310c1234.png)

**after**:
![before](https://cloud.githubusercontent.com/assets/8850708/10506293/53fd0dc2-7316-11e5-96df-4ce66b370cdb.png)

**Comment by nikku** [comment]
Fixed with bpmn-js `v0.16.0`.
