### ISSUE TITLE
I can copy + paste on a diagram

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#391]
Users should be able to copy and paste on the diagram.

* [ ] decide if a current selection can be copied
* [ ] decide if a selection can be pasted into a target selection
* [ ] create copy of selection, including `businessObject` and add these elements to the target (_Note_: this has to maintain the source element order)

Work on [diagram-js#123](bpmn-io/diagram-js#123) should lay the general foundations for this issue.

See also:

* [forum thread](https://forum.bpmn.io/t/how-to-implement-copy-paste-feature-on-diagram-elements/312)
* bpmn-io/diagram-js#123

**Comment by adrobisch** [comment]
Should not this belong to https://github.com/bpmn-io/diagram-js ? I would like to work on this, but not under bpmn-js license.

**Comment by nikku** [comment]
You are absolutely right. The foundations should be part of [diagram-js](https://github.com/bpmn-io/diagram-js) and editors such as bpmn-js should hook into some parts of the copy-and-paste process.

I added the diagram-js issue [#123](bpmn-io/diagram-js#123) there. We are happy to get pull requests on this.

**Comment by adrobisch** [comment]
Thanks! I will see what I can do ;-).

**Comment by samur-vonq** [comment]
1+
