### ISSUE TITLE
Cannot create sequence / message flows in huge diagrams

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#394]
I cannot always connect elements that are really far away.

* if I zoom out, the zoom restrictions do not allow me to create a connection anymore
* if I stay zoomed in, the second element is not accessible (we'd need to implement scrolling-while dragging for this to work)

**Comment by nikku** [comment]
Gets fixed via #474

**Comment by gimbel** [comment]
We can close this issue once #474 is completed

**Comment by vladimirskatusenoks** [comment]
As a workaround/approach see [this comment](https://github.com/bpmn-io/bpmn-js/issues/355#issuecomment-210396984).

**Comment by pedesen** [comment]
Resolved with https://github.com/bpmn-io/bpmn-js/commit/1923a6bdda4972d86d8f21c760be03fe6d31d996.
