### ISSUE TITLE
Context pad reaches outside browser window

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#395]
Often times the context pad is to long for the current editor selection.

That makes it impossible to select elements farther down (see screenshot):

![image001](https://cloud.githubusercontent.com/assets/58601/10658173/aed428a6-7894-11e5-82b4-57e3562238b6.png)

Possible solutions:
* [Reduce size of context-pad](https://forum.bpmn.io/t/shorter-context-menu/252/4)
* Make context pad pop up (if there is more space upwards)
* Make context pad scrollable

**Comment by berndruecker** [comment]
I think this was fixed already (probably in another issue)

**Comment by nikku** [comment]
Closed via #414

**Comment by gimbel** [comment]
should we close this ticket too?

**Comment by nikku** [comment]
:cake:
