### ISSUE TITLE
Expand parent element when appending new element

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#405]
Problem: If we are modeling inside a pool/lane/sub process and try to append a new element inside of it (from the context pad) close to the border, the parent is not adequately expanded (see animation). So far this behavior is generally intended, because if we move an existing element outside its parent, it should not expand (and it should drop the element outside of it). But In the case of appending, it is obvious that the user wants the parent element to be expanded.

![auto-expand](https://cloud.githubusercontent.com/assets/2543743/10877100/69968290-8143-11e5-9b16-5bcef0adca34.gif)

Possible solution: If and only if an element is appended (from the context pad) to an existing element, the parent should be expanded, even if the new element is placed far outside its parent.

Hint: This should only affect appending but not moving operations.

**Comment by nikku** [comment]
Closing this in favor of https://github.com/bpmn-io/bpmn-js/issues/560.
