### ISSUE TITLE
Question: What do you think about extending with ERD and FSM?

### ISSUE THREAD

**Issue by dumblob** [bpmn-io/bpmn-js#406]
First, thank you for such an awesome product. I really like it's simplicity, clean environment, responsiveness and embeddability.

Now, I was assigned to an issue of "merging" BPMN 2.0, ERD (Entity Relationship Diagram) and FSM (Finite State Machine) diagrams to one environment. Because FSM and ERD are way simpler than BPMN, I decided to use an existing BPMN library/tool and add the ERD and FSM functionality. Unfortunately, I don't know internals of bpmn-js well enough to be able to estimate how much effort it would take e.g. to add those few new elements ERD and FSM contains (rectangle with label and attributes, nice curves with labels for FSM, connection lines for ERD rectangles having cardinality and label and different endings, etc.) in a way, that they're manually editable (adding elements using just JS code is not enough).

How much time or effort might that take to you, professinals working on bpmn-js every day? Or would you rather choose a different approach?

**Comment by nikku** [comment]
Our [project forum](https://forum.bpmn.io) might be a better place to discuss these kinds of questions.

My approach on this would be as follows:

As a first step towards a combined modeler I'd create modelers for ERD and FSM modeling notations. I am not 100% into these. You'd need to implement modeling rules, layouting, graphics and an export format.

The second step would be to mix all that stuff together.

It is feasible and quite experimental to do this. Whether it is worth the effort or not depends on what you want to achieve in detail.
