### ISSUE TITLE
I can't modify the component Id

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/bpmn-js#407]
I'm using bpmn.io 0.12 and when I update the Id, it crashes:

Error: gfx is undefined
[99]</ElementRegistry.prototype.add@http://localhost:9000/bower_components/bpmn-js/dist/bpmn-modeler.js:19667:3
[99]</ElementRegistry.prototype.updateId@http://localhost:9000/bower_components/bpmn-js/dist/bpmn-modeler.js:19720:3
[41]</UpdatePropertiesHandler.prototype.execute@http://localhost:9000/bower_components/bpmn-js/dist/bpmn-modeler.js:6259:5
[95]</CommandStack.prototype._internalExecute@http://localhost:9000/bower_components/bpmn-js/dist/bpmn-modeler.js:18556:21
[95]</CommandStack.prototype.execute@http://localhost:9000/bower_components/bpmn-js/dist/bpmn-modeler.js:18325:3
[22]</Modeling.prototype.updateProperties@http://localhost:9000/bower_components/bpmn-js/dist/bpmn-modeler.js:4567:1

But when I change for example the "name", it DOES work !.

I'm doing what's explained at https://forum.bpmn.io/t/edit-id-attribute-of-element/96/4

**Comment by nikku** [comment]
Make sure you assign an actual id, i.e. not `null` or `undefined`.

Could you publish some pieces of your solution that allow me to reproduce your issue?

**Comment by rbatllet** [comment]
If I save the same id without changes:

-The sequenceFlowElement object have these properties:

<img width="588" alt="screen shot 2015-11-10 at 20 33 25" src="https://cloud.githubusercontent.com/assets/3993987/11073337/7c44776e-87ea-11e5-8f16-d9f93a799728.png">

My function to update the id is:
    function writePropertyByName(sequenceFlowElement, modeling, propertyName, value) {
      var item = {};
      item[propertyName] = value;
      modeling.updateProperties(sequenceFlowElement, item);
    }

And then the message error is "Error: element with id StartEvent_1 already added":

<img width="651" alt="screen shot 2015-11-10 at 20 38 38" src="https://cloud.githubusercontent.com/assets/3993987/11073494/26284d3c-87eb-11e5-961f-af64b6574928.png">

**Comment by rbatllet** [comment]
If I save a different Id (The original Id is "StartEvent_1") with the new value "StartEvent_XXX":

-The sequenceFlowElement object have these properties:

<img width="652" alt="screen shot 2015-11-10 at 20 43 29" src="https://cloud.githubusercontent.com/assets/3993987/11073616/bb0a73e4-87eb-11e5-95fd-3d6c2eda6e09.png">

And then the message error is "Error: gfx is undefined":
<img width="647" alt="screen shot 2015-11-10 at 20 44 06" src="https://cloud.githubusercontent.com/assets/3993987/11073636/d7d1c7f2-87eb-11e5-9f82-1b3d6d5b2524.png">

**Comment by nikku** [comment]
Could you paste the lines of code you are using to update the sequence flow id?

**Comment by rbatllet** [comment]
```function writePropertyByName(sequenceFlowElement, modeling, propertyName, value) {
var item = {};
item[propertyName] = value;
modeling.updateProperties(sequenceFlowElement, item);
}```

```var viewer = new BpmnModeler({container: canvas });
var sequenceFlowElement = viewer.get('elementRegistry').get('StartEvent_1');
var modeling = viewer.get('modeling');
writePropertyByName(sequenceFlowElement, modeling, 'id', 'StartEvent_XXX');```

**Comment by nikku** [comment]
Your error message indicates that the element is not part of the diagram anymore.

I cannot reproduce your findings on `bpmn-js@v0.12.0`. Plus, we got a [test case](https://github.com/bpmn-io/bpmn-js/blob/master/test/spec/features/modeling/UpdatePropertiesSpec.js#L121) for exactly your scenario, too.
