### ISSUE TITLE
Improve on canvas move for diagrams with large pools/lanes/subprocesses

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/bpmn-js#412]
We should allow the user to move a participant with lanes, if he starts a dragging operation with a lane.

**Comment by nikku** [comment]
Additional Idea: what about moving canvas instead of dragging whenever an element is bigger than the current viewport? It is something we could try to implement to see how it feels.

**Comment by nikku** [comment]
Additional Idea: Implement a Hand Tool (including keyboard shortcut) to help out in these kinds of situations.

**Comment by nikku** [comment]
__And__: We have the same issue with huge sub-processes, too.

**Comment by nikku** [comment]
Alternative: Moving canvas when dragging lane instead (#427).

**Comment by gimbel** [comment]
Alternative Idea: Pools and Lanes can only be selected and dragged by their header. All the rest is like moving the canvas. Subprocesses stay as they are
