### ISSUE TITLE
unable to select very short sequence flow

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#413]
this is especially harmfuly in case of editing the conditions of flows following a gateway

![image](https://cloud.githubusercontent.com/assets/3829733/11209155/c6ca4c84-8d1f-11e5-8ee5-8b524eebb792.png)

**Comment by ingorichtsmeier** [comment]
If the yellow box appears, the seqence flow should be selected, too. Then you are able to edit the properties of the sequence flow.
