### ISSUE TITLE
Morph menu is positioned outside of window

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#414]
User keep reporting that they have trouble with the morph menu being "longer" than their screen

![image](https://cloud.githubusercontent.com/assets/3829733/11211034/bb209912-8d2c-11e5-9c0d-1a2fe1b2e28a.png)

**Comment by nikku** [comment]
What are possible solutions for this problem?

**Comment by berndruecker** [comment]
There were already proposals to remove the text from the icons and only show them as tooltip. That way you would only need approx 2 lines for all items making the problem much smaller

**Comment by berndruecker** [comment]
PS: I already stumbled over this a couple of times as well :-)
