### ISSUE TITLE
Allow mouse wheel zoom to be disabled

### ISSUE THREAD

**Issue by zeropaper** [bpmn-io/bpmn-js#416]
In the Camunda blog, we did integrate bpmn.io to render diagrams (viewer only).
When a visitor scrolls on the page and reaches the diagram, if the cursor is over the diagram, the scrolloing stops and the diagram will be zoomed.

As discussed, enabling / disabling could be a switch in order to allow to the delegation of zoom control.

#### Hints

* [Canvas](https://github.com/bpmn-io/diagram-js/blob/master/lib/core/Canvas.js#L85) is already responding to external configuration.
* Mouse wheel interaction is implemented [here](https://github.com/bpmn-io/diagram-js/blob/master/lib/navigation/zoomscroll/ZoomScroll.js#L27)

**Comment by gimbel** [comment]
Just to add some more info on this one: Scroll down in this blogpost and the problem should be clear...
http://blog.camunda.org/post/2015/11/escalation-events-7.4/

**Comment by janstuemmel** [comment]
I added a quick hack on my forked diagram-js repository for this. You can pass a option 'disableZoomScroll=false' to disable the zoom on scroll. But I think its better to 'not-inject' the zoom feature in Modeler or NavigatedViewer class. 

https://github.com/janstuemmel/diagram-js/commit/80f4380ec405a7964989951b48ef1cf2ed3d0129#diff-b23da129e21c2fd054c7f3ee73617779

**Comment by nikku** [comment]
To give a few details on this one:

Along with the initial configuration it should be possible to enable / disable the zoom feature programmatically. Users could use this to implement stuff like _Only allow zoom/scrolling of the document focus is on the diagram_.

So an improved way of implementing this would be the following:

* initial enabled / disabled state can be configured via `config.zoomScroll.disabled` or the like
* API to toggle the activation manually via `zoomScroll.setEnabled(true|false)` is provided

Removing the zoom feature all together is a fun solution as well, if users never need zoom. We could look into that at some point in the future, too.

**Comment by RasPelikan** [comment]
We used an CSS-based approach and added an user-hint how to activate zooming/scrolling:
```html
<div ng-class="{'bpmnIOActivatorHintVisible': bpmnIOInactive, 'bpmnIOActivatorHintHidden': !bpmnIOInactive}">
	The process-diagram is disabled. Click it to enable zooming and scrolling!
</div>
<div class="diagram-pane" ng-class="{'bpmnIOInactive': bpmnIOInactive, 'bpmnIOActive': !bpmnIOInactive}"
	ng-click="activateBpmnIo()" cam-widget-bpmn-viewer
	diagram-data="processXml" control="control">
</div>
```
where CSS is:
```css
.bpmnIOInactive {
	cursor: pointer;
	background-color: #f0f0f0;
}

.bpmnIOInactive * {
	pointer-events: none;
}

.bpmnIOActive {
}

.bpmnIOActivatorHintVisible {
	position: absolute;
	color: black;
	z-index: 10;
	margin: 10px;
	padding: 2px;
	padding-left: 10px;
	padding-right: 10px;
	border-radius: 5px;
	background-color: white;
	opacity: 0.8;
}

.bpmnIOActivatorHintHidden {
	display: none;
}
```
The property `$scope.bpmnIOInactive` and the function `$scope.activateBpmnIo()` is defined in the surrounding directive:
```javascript
    scope: {
        bpmnIOInactive: '='
    };
    link: ($scope, element) =>  {
            $scope.activateBpmnIo = () => { $scope.bpmnIOInactive = false; }
            $scope.clickDidHitBpmnIo = (receiver, element) => {
                // this function checks whether any element of the bpmnIO viewer
                // (including zoom-in, zoom-out and reset-zoom) was hit
                if (element == null) {
                    return false;
                }
                if (receiver === element) {
                    return true;
                }
                var children = element.childNodes;
                for (var i = 0; i < children.length; ++i) {
                    var child = children[i];
                    if ($scope.clickDidHitBpmnIo(receiver, child)) {
                        return true;
                    }
                }
                return false;
            }

            var diagramPane = element.find('.diagram-pane');
            var bpmnIoElement = diagramPane.get(0);

            angular.element(document).bind('mousedown', function(event) {
                var receiver = document.elementFromPoint(event.clientX, event.clientY);
                if (receiver.nodeType == 3) { // Opera
                    receiver = receiver.parentNode;
                }

                if (!$scope.clickDidHitBpmnIo(receiver, bpmnIoElement)) {
                    $scope.bpmnIOInactive = true;
                    $scope.$apply(); // update binding since we are outside of AngularJS' view
                }
            });
    }
```
The only disadvantage of this solution is that for IE it requires v11 (see http://caniuse.com/#feat=pointer-events).

**Comment by nikku** [comment]
Fixed via #67.

It is now possible to toggle the zoomScroll activation via API.

**Comment by santosguilherme** [comment]
@nikku, how to disable mouse wheel scroll?

**Comment by nikku** [comment]
You can now toggle it via `ZoomScroll#toggle` or disable it per default via the `zoomScroll.enabled = false`.

**Comment by nikku** [comment]
See linked issue (I fixed the link).

**Comment by santosguilherme** [comment]
Thanks.
