### ISSUE TITLE
Missing BPMN 2.0 diagrams (collaboration, choreography, conversation)

### ISSUE THREAD

**Issue by dumblob** [bpmn-io/bpmn-js#418]
If I'm not mistaken, bpmn-js currently supports only BPMN 2.0 process diagram. The BPMN 2.0 specification though describes three more very important diagrams - collaboration, choreography, and conversation. I'm particularly interested especially in conversation and choreography.

Are there any plans to implement these **editable** diagrams as well? I didn't find anything in the kanban board, nor here in issues nor in the [project roadmap](http://bpmn.io/roadmap/), nor in the forum.

**Comment by nikku** [comment]
Collaboration diagrams work out of the box already (every diagram containing a participant is treated as one). Conversation and choreography diagrams are out of scope for this project at the moment.

If you plan to these diagrams, get in touch with us via [our forums](https://forum.bpmn.io). We accept pull requests.
