### ISSUE TITLE
ID is not released if element gets removed

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#421]
* [x] remove an element
* [x] assign element id to another element
* [x] id should be assignable

Related to camunda/camunda-modeler#97

**Comment by vladimirskatusenoks** [comment]
There is more to it.
Another related scenario:
- create new diagram
- rename 'StartEvent_1' -> 'StartEvent_2'
- create another start event
- rename it to 'StartEvent_1'

result: context pad for second start event gets sort of attached to first element and other actions start to break modeler
