### ISSUE TITLE
Move canvas when dragging a Lane

### ISSUE THREAD

**Issue by klajmajk** [bpmn-io/bpmn-js#427]
When diagrams get a bit bigger with Pools and Lanes user has to move the view only by dragging the canvas outside the Pool (those including Lanes) this tends to be very uncomfortable.

**Comment by nikku** [comment]
We will be working on a solution for this issue in the next month(s). Thanks for reporting.

**Comment by nikku** [comment]
Fixed with newly integrated Hand Tool
