### ISSUE TITLE
Refactor BpmnReplace

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#428]
- [x] Separate replace functionality from menu functionality
- [x] Let rules disallow replacement operations #426

**Comment by gimbel** [comment]
Should this issue have a milestone?

**Comment by barmac** [comment]
This is a quite unexpected behaviour of the bot since my branch is related to https://github.com/bpmn-io/diagram-js/pull/431 and its issue within `diagram-js`.
