### ISSUE TITLE
Let the user mark arrows as event path

### ISSUE THREAD

**Issue by dns2utf8** [bpmn-io/bpmn-js#432]
Hi all

I currently do not know how to draw a line between two event gateways that looks diffrent from regular lines.

Is it possible to make them dotted or choose manually?

Regards

**Comment by nikku** [comment]
This library is a BPMN 2.0 rendering toolkit. That said, you need to apply some voodoo magic to draw non-BPMN things on the canvas. Still perfectly doable.

If you simply want to draw a line between two elements, use `canvas.getLayer('someLayer')` to get hold on the underlying SVG layer. Use it to draw anything that ins interesting for you.

I think our [forum](https://forum.bpmn.io) is better suited for these kinds of questions.
