### ISSUE TITLE
Combine incoming -> outgoing sequence flow when deleting element

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#433]
When deleting an element with only one incoming / outgoing sequence flow:

* [ ] combine both flows to one before deleting the element

#### Screenshot

![image001](https://cloud.githubusercontent.com/assets/58601/11846273/39413700-a418-11e5-9290-66bd105fd075.png)

After the gateway got deleted the flow should still exist.

**Comment by berndruecker** [comment]
best keep the incoming flow name/expresion
