### ISSUE TITLE
Camunda modeler can't open bpmn diagram after specifying camunda:out tag of call activity

### ISSUE THREAD

**Issue by jsuleder** [bpmn-io/bpmn-js#436]
I tried to specify ingoing and outgoing variables of a call activity in my bpmn diagramm. After saving I can't open it with the modeler any more giving an error: 

**Ooops, we could not display this diagram!**
*Do you believe "diagram-name.bpmn" is valid BPMN or DMN diagram?
If so, please consult our forum or file an issue in our issue tracker.*

*Unbound namespace prefix: "camunda:out"
Line: 137
Column: 39
Char: >*

Here's my call activity: 
``` XML
135 <callActivity completionQuantity="1" id="sid-theid" isForCompensation="false" name="thename" startQuantity="1">
136   <extensionElements>
137       <camunda:in variables="all" />
138       <camunda:out variables = "all" />
139    </extensionElements>
140    <incoming>sid-D4E2FC7A-BCEC-46F3-A2FE-F837D1AE9760</incoming>
141    <outgoing>sid-369CB00F-6B89-4096-AA9F-FDBC4FF75FA9</outgoing>
142 </callActivity>
```
I followed this tutorial https://docs.camunda.org/manual/7.4/reference/bpmn20/subprocesses/call-activity/.

I am using Camunda Modeler in Version 0.34.0 (0.34.0)

**Comment by jsuleder** [comment]
Made a stupid mistake and and forgot to insert **xmlns:camunda="http://camunda.org/schema/1.0/bpmn"** in the xml header. 
I created the diagram with signavio and forgot to add it. Sorry for the inconvenience.

**Comment by nikku** [comment]
Glad you could find the error yourself ;-).

**Comment by leolux** [comment]
The correct name of the namespaces is documented here: https://docs.camunda.org/manual/7.4/reference/bpmn20/custom-extensions/extension-elements
