### ISSUE TITLE
Boundary event drawing problems on imported Activities

### ISSUE THREAD

**Issue by pfolthof** [bpmn-io/bpmn-js#437]
Dragging a boundary event (intermediate throw event) on an existing activity (loaded from BPMN), the boundary event is overlapped by the activity.

Also, when a sequence flow is drawn from the boundary event to the owning activity, the sequence flow is invisible or shown as a very short arrow within the boundary event and cannot be modified.

**Comment by nikku** [comment]
When creating a bug report, please add the necessary steps that allow us to reproduce the problem.

This can include:

* What did you do?
* Which environment?
* Which input (BPMN 2.0 XML, ...)

Thanks!

**Comment by pfolthof** [comment]
Yes, you can reproduce this on demo.bpmn.io. Simply click on 'try it', which opens the 'choose recipe' flow, drag the boundary event on the activity and you'll see that it will be drawn behind the activity.

Then, if you draw an arrow from the boundary event back to the activity, you'll notice that the arrow is within the boundary event and it is impossible to re-layout it.

**Comment by nikku** [comment]
Aaahh, nice finding. We will look into the issue as part of our next milestone. Thanks for reporting!
