### ISSUE TITLE
Take the liberty of ask next, please could provide 'demo.bpmn.io' demo download, thank you very much

### ISSUE THREAD

**Issue by CheneyLiu** [bpmn-io/bpmn-js#440]

**Comment by nikku** [comment]
We will not provide a download link to the demo. You can check out [the modeler example](https://github.com/bpmn-io/bpmn-js-examples/tree/modeler) that offers the same stuff though.

**Comment by akuckartz** [comment]
@nikku Visiting that link resulted in a 404 error page.

**Comment by pfolthof** [comment]
https://github.com/bpmn-io/bpmn-js-examples/tree/master/modeler

**Comment by CheneyLiu** [comment]
Thinks
