### ISSUE TITLE
Morph to default flow should remove condition

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#441]
* [ ] The flow condition should be removed when a flow is morphed into the default flow.
* [ ] The default flow should be removed when adding a condition.

Via [forum topic](https://forum.bpmn.io/t/436).

**Comment by oumayma-ltaief** [comment]
hello @nikku can you please explain why do this change is considered as a bug? is it a known rule in bpmn standard? I'm suprised to force such reset to the condition or default flow setting.

**Comment by nikku** [comment]
@oumayma-ltaief What exactly does not work as you'd expect it here?
