### ISSUE TITLE
Question: Lodash 4.0.0 compatibility?

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/bpmn-js#448]
Is there any future plans to make it compatible with Lodash 4.0.0. 

There's a lot of changes in the new version:

https://github.com/lodash/lodash/wiki/Changelog

**Comment by nikku** [comment]
What needs to be done to make it 4.0.0 compatible?

We do not have any specific plans to do it.

**Comment by rbatllet** [comment]
For example several methods has been removed:

Removed _.support
Removed _.findWhere in favor of _.find with iteratee shorthand
Removed _.where in favor of _.filter with iteratee shorthand
Removed _.pluck in favor of _.map with iteratee shorthand

And several aliases as well:
_.all, _.any, _.backflow, _.callback, _.collect, _.compose, _.contains, _.detect, _.foldl, _.foldr, _.include, _.inject, _.methods, _.object, _.#run, _.select, & _.unique

**Comment by nikku** [comment]
Feel free to look into these things and provide a PR for lodash 4 compatibility.

**Comment by rbatllet** [comment]
The compatibility will be done this way:
- `Use the alternative methods` removed in lodash 4.0.0 (for example _.map instead of ._pluck)

- `Avoid using the removed aliases`.

**Comment by nikku** [comment]
Will you provide a PR for this?

**Comment by nikku** [comment]
Closing this for now. If we update to Lodash 4 we must do that for all of our projects.

If you'd like to contribute and speed up the process, file a PR ;-).

**Comment by beeman** [comment]
@nikku I'm currently in the process of implementing bpmn-js into our app and I am now running into the issue that we need to downgrade our app to use lodash 3 to work with bpmn-js.

> If we update to Lodash 4 we must do that for all of our projects.

Is this still the same list of applications that are listed in issue https://github.com/bpmn-io/bpmn-js/issues/185 ?

Any more things to consider? I might give it a go upgrading it, but it would be good to get a better idea of what it involves.

**Comment by nikku** [comment]
How do you build your application? It should not be necessary to downgrade the app to use lodash 4.

**Comment by beeman** [comment]
Thanks for your reply @nikku.

I am using Angular CLI (currently Angular 2) and include it there using a requiere statement. 

When I initially includes bpmn-js I had lodash 4 in my app but this gave error message (I don't have the errors at hand right now, but they referred to lodash not being found).

Are you suggesting I can use both versions of lodash or should I do something else to get it working?

**Comment by beeman** [comment]
This is the snippet that I use to include it in my Angular component:

```
// FIXME: Create TypeScript definitions to use 'import { x } from y' syntax
const BpmnModeler = require('bpmn-js/lib/Modeler')
const propertiesPanelModule = require('bpmn-js-properties-panel')
const propertiesProviderModule = require('bpmn-js-properties-panel/lib/provider/camunda')
const camundaModdleDescriptor = require('camunda-bpmn-moddle/resources/camunda.json')
```

**Comment by nikku** [comment]
> Are you suggesting I can use both versions of lodash or should I do something else to get it working?

Yes, that is the way CommonJS / npm works at least.
