### ISSUE TITLE
Caret jumps to end while typing

### ISSUE THREAD

**Issue by leolux** [bpmn-io/bpmn-js#457]
I am struggling with a strange bug: The caret always jumps to the right end of the textfield while typing text into it. The time window before the caret jumps to the end is only about one second. This makes it very hard to write text before the end of the line.

Did anyone had such a problem before? I am running windows 10 and use eclipse for deploying my processes. And I have the native hook activated in eclipse (http://help.eclipse.org/juno/topic/org.eclipse.platform.doc.user/images/Image209_workspace.png). Deactivating the native hook didn't solve the problem.

**Comment by leolux** [comment]
The problem occurs on every textfield found at the right side of the modeler.

**Comment by nikku** [comment]
Are you talking about [this bug](https://github.com/camunda/camunda-modeler/issues/101)?

Please file Camunda Modeler related bugs in the [camunda-modeler GitHub project](https://github.com/camunda/camunda-modeler).

**Comment by nikku** [comment]
The respective bug will be fixed in the next version of the modeler.
