### ISSUE TITLE
[Request/Enquiry] Can we use the modeler & viewer in an enterprise application?

### ISSUE THREAD

**Issue by aseemflowingly** [bpmn-io/bpmn-js#463]
I have looked at the license and I want to know if there is a one time fee or cost which can be paid to have the modeler included in an enterprise SaaS application, without the following requirement:

> "The source code responsible for displaying the bpmn.io logo (two green cogwheels in
> a box) that links back to http://bpmn.io as part of rendered diagrams MUST NOT be
> removed or changed. When this software is being used in a website or application,
> the logo must stay fully visible and not visually overlapped by other elements.”

Can I get some contact details to discuss this?

**Comment by nikku** [comment]
See [our statement regarding this](https://forum.bpmn.io/t/license-questions/85/7).

**Comment by aseemflowingly** [comment]
Ah ok, thanks!
