### ISSUE TITLE
When remove element bpmn:SequenceFlow, event 'shape.remove' receives wrong element

### ISSUE THREAD

**Issue by santosguilherme** [bpmn-io/bpmn-js#465]
When i remove a 'bpmn:SequenceFlow' element and delete event ( 'shape.remove' ) receives label's element and not the element 'bpmn:SequenceFlow'.

As a workaround, the attribute 'businessObject' of element received in the event, this object contains the correct element.

The code snippet :

**Element deleted**: "SequenceFlow_133ens9"

**Code**:
```
eventBus.on('shape.remove', function (elem) {
       console.log(elem.element.id);
});
```
**Console show**: "SequenceFlow_133ens9_label"

It's a bug?

**Comment by pedesen** [comment]
Actually it is not a bug, but a misunderstanding. diagram-js is making a distinction between shapes and connections. This is why the `shape.remove` is fired only for the label in this case. You should either listen to the `connection.remove` or `elements.changed` event.

**Comment by santosguilherme** [comment]
ok, thanks for the explanation.
