### ISSUE TITLE
Localization Support (Different Language)

### ISSUE THREAD

**Issue by havid0707** [bpmn-io/bpmn-js#466]
There does not exists one way to localize the modeler UI without directly modifying the source code at this moment. 

Please help to make it easy to plug-in additional languages.

**Comment by nikku** [comment]
We accept pull-requests for that.

See [this forum topic](https://forum.bpmn.io/t/modeler-localization/255) for a discussion.

**Comment by nikku** [comment]
Closed via bpmn-io/bpmn-js#491.
