### ISSUE TITLE
Sequence flows aren't properly rendered after roundtrip

### ISSUE THREAD

**Issue by easterwood** [bpmn-io/bpmn-js#468]
Hi,

first of all the bpmn-js is great. No export of SVGs/PNGs are necessary. That's fine. Unfortunately the rendering results of the sequence flows looks chaotic if I use a different tool then the camunda modeler, e.g. the Yaoqjang BPMN Editor. The reason why I use  Yaoqjang BPMN Editor is that it has features like cut'n'paste or layout features. 

1. What is the reason for that?
2. Our you going to improve the sequence flow rendering?
3. Can I use existing SVGs/PNGs in the camunda cockpit application?

Here is an example of how it looks after rendering with bpmn-js:
![2016-02-10 07_52_25-camunda modeler](https://cloud.githubusercontent.com/assets/7085240/12940978/63985a9c-cfce-11e5-9ec1-4acc557f9718.png)

And this image shows how it looks in the  Yaoqjang BPMN Editor:
![yaoqjang modeler](https://cloud.githubusercontent.com/assets/7085240/12940992/79c368fc-cfce-11e5-8e90-afcf26c1c730.png)

**Comment by ricardomatias** [comment]
Hello @easterwood, we would need to check out the XML to understand why this is happening. The problem you're having has to do with the way the diagram is defined on the XML and not with our sequence flow's rendering. For the last point, you have to head over to the [camunda forums](https://groups.google.com/forum/#!forum/camunda-bpm-dev).

**Comment by nikku** [comment]
We cannot reproduce your changes without an example diagram.

Feel free to provide the diagram and we are happy to reopen this issue.
