### ISSUE TITLE
Failed to save nested namespace document (Bizagi export)

### ISSUE THREAD

**Issue by dbremer-tonn** [bpmn-io/bpmn-js#469]
I encountered some problem with the new camunda modeler (0.34.0) and an existing bpmn file we've got from some customer. Opening the bpmn file works flawless, layout is fine. Doing some changes to the bpmn model and saving it will break the bpmn file completely and its not possible to open it again with the modeler. I have attached the bpmn file in question. 

[Diagramm  1.bpmn.zip](https://github.com/bpmn-io/bpmn-js/files/126706/Diagramm.1.bpmn.zip).

Gets fixed via bpmn-io/bpmn-moddle#40.

**Comment by nikku** [comment]
Thanks for your bug report.

Could you attach a screenshot of the diagram in Bizagi so that we are able to compare the visual representation?

**Comment by nikku** [comment]
Just saw that the diagram contains nested namespaces:

```xml
  <BPMNDiagram id="Diagram_b33f18e3-e624-4003-9ca6-1b8fbeb99b9d" xmlns="http://www.omg.org/spec/BPMN/20100524/DI">
```

bpmn-js seems to export these differently. It puts namespaces on the document root but forgets to add the `bpmndi` prefix to `BPMNDiagram`.

This is a import / export bug.

**Comment by nikku** [comment]
Could you provide us with a trimmed down diagram (i.e. single task) Bizagi export? That helps us to fix this issue once we got time to do so.

**Comment by dbremer-tonn** [comment]
Unfortunately I don't have access to bizagi modeler. This example bpmn was given by one of our clients.

**Comment by nikku** [comment]
If you get hold on a very simple diagram, come back to us. As said it would help us a lot reproducing this bug and eventually fixing it. Thanks in advance!

**Comment by dbremer-tonn** [comment]
Thanx to our client I can provide 2 simple example bpmn files from bizagi, including PNGs for proper rendering.
I hope this will help.

[bizagi.zip](https://github.com/bpmn-io/bpmn-js/files/138190/bizagi.zip)

**Comment by nikku** [comment]
Thanks! I added a failing test case with the diagram you provided.
