### ISSUE TITLE
Automatically resize Text Annotation to fit contents

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#472]
There exist special editing rules for text annotation fields:

* [ ] text box grows horizontally as user types (+ max-width _?_)
* [x] text box grows vertically as user inputs new lines

After editing, the text annotation should automatically resize to accommodate the whole content.

That means:

* [ ] respect whitespace
* [x] respect line breaks
* [x] shrink / expand if needed

**Comment by nikku** [comment]
Closes camunda/camunda-modeler#155

**Comment by vkatushenok** [comment]
@hoferch91 There are couple of issues:
- Updating through properties panel does not update (using modeler).

>  text annotation should automatically resize to accommodate the whole content

- Not sure if this has been discussed and limited to some a particular area... @nikku? In this case, scrolling inside the text area should be available.
- Sometimes, entering text and hovering/zooming auto-expands label to some uncertain size:

![annotation](https://cloud.githubusercontent.com/assets/2331533/14853617/8d47c530-0c8c-11e6-8b33-4f0e8b7eab75.gif)

**Comment by hoferch91** [comment]
@vkatushenok 
I've fixed the scrolling problem and the positioning problem (gif below) with the commits c6d8860,  	 17a6695 and e7d65c1.

![positioningproblem](https://cloud.githubusercontent.com/assets/11477689/14913020/52503d0c-0e00-11e6-9136-0e551a1f2d48.gif)

For the other problems you mentioned I've created separate issues  #528 and #527  that I'm working on now.

**Comment by nikku** [comment]
We are going to rework this.
