### ISSUE TITLE
Import failed with "unquoted attribute value" message

### ISSUE THREAD

**Issue by nilei** [bpmn-io/bpmn-js#473]
Dears, 

I have uploaded a BPMN file to demo.bpmn.io from Yaoqiang that we use and successfully executed as example file. Unf. it failed to upload in demo.bpmn.io with a message saying that on line 78 we have an unquoted attribute value. 

As I cannot upload BPMN file here, this is the link: https://sourceforge.net/projects/bpmn/files/Examples/

It's the Async_ReceiveTask.bpmn file.

Cheers, Nils

**Comment by nikku** [comment]
Please use our [project forum](https://forum.bpmn.io) for these kinds of help requests (diagram not readable / wrong rendering and so on). You can easily upload a BPMN diagram there. We are happy to look into whether this is a bug and open a respective bug ticket for it.

Putting diagrams archived in `.zip` files onto some web page is really not the best way to share your diagrams.
