### ISSUE TITLE
Text layouting broken if diagram invisible during import.

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#476]
Text does not get properly layouted, if the diagram is imported onto an invisible element.

The result looks like this (see [forum thread](https://forum.bpmn.io/t/wrapping-text-in-viewer/539)):

![image](https://cloud.githubusercontent.com/assets/58601/13390796/e7dcb9cc-ded0-11e5-81cd-f87bd30dbe5e.png)
#### Possible Solutions
- defer label import / text layouting until diagram is imported?
- make sure element is visible during import

**Comment by nikku** [comment]
[Another forum thread](https://forum.bpmn.io/t/labeltext-show-wrong-position-after-export/559) regarding this.

**Comment by akkie** [comment]
I've stumbled over the same issue. We use dmn-js in a React context and even if I import the XML in the [componentDidMount](https://facebook.github.io/react/docs/react-component.html) lifecycle method, it can be the case that the container isn't visible in the DOM. Currently I use a timeout from 500ms to work around this issue.

So I'm not sure if your "make sure element is visible during import" solution would work in a React context.

**Comment by nikku** [comment]
Yes, there is ways to accomplish this. In general, React will keep elements in the DOM as long as possible. So if you do not deliberately allow your users to change the app, you should be O.K.

**Comment by nikku** [comment]
Will be addressed by https://github.com/bpmn-io/diagram-js/issues/205.

**Comment by akkie** [comment]
@nikku Issue https://github.com/bpmn-io/diagram-js/issues/205 is fixed. So I think this can also be fixed because it works now as expected in my case.

**Comment by nikku** [comment]
Thanks.
