### ISSUE TITLE
Allow to change Intermediate Events to Boundary Events

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#478]
* [x] Attach an intermediate event to a task to change it to a boundary event by dropping onto a task / sub-process border.
* [x] only works for some of catching and unspecified event definitions
* [ ] Keeps outgoing connections (if allowed)

**Comment by martinschimak** [comment]
This is what I mean - but in case you do that I would also allow it "the other way round": Change a boundary event into an intermediate event by dropping it onto a sequence flow - here I would also just keep the outgoing connections. 

Furthermore, I would allow the intermediate event in the context menu of a task / sub-process to be used to create a **new** boundary event by dropping it onto the task / sub-process' border. Probably this second thought is worth a separate issue.

**Comment by felideon** [comment]
+1 on this feature

**Comment by gimbel** [comment]
related to #518

**Comment by nikku** [comment]
Adresses https://github.com/camunda/camunda-modeler/issues/239.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1041.
