### ISSUE TITLE
Sub Process expanded when moving out elements

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#480]
When moving Task + Boundary Event + attached Task out of a Sub-Process the sub-process gets expanded. It should not, as all elements were moved out of it.

![subprocess-bug](https://cloud.githubusercontent.com/assets/58601/13453176/3eeba326-e04e-11e5-8c41-6732ed6cd79c.gif)

**Comment by philippfromme** [comment]
This bug appears for all boundary events that have at least one outgoing sequence flow.

**Comment by ricardomatias** [comment]
Move outgoing connections from attachers move with them
