### ISSUE TITLE
Scroll when dragging to diagram borders

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#481]
When dragging to the diagram borders, the canvas should scroll, allowing users to reach _out of view_ areas of the canvas.

Should address #394 along with global connect tool #474.

**Comment by ricardomatias** [comment]
Should aim to have the same kind of behavior as the canvas moving that can be done with the keyboard.

Should listen to the dragging events of the tools/elements where we intend to use this feature with.
