### ISSUE TITLE
Create new Boundary Event on Task from the tasks Context Pad

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#482]
It should be possible to create a new Boundary Event on a task from the tasks context pad by dragging an intermediate event from the context pad onto the task itself:

![boundary](https://cloud.githubusercontent.com/assets/58601/13453812/485d4d74-e053-11e5-86ea-a7bc5dc8812f.gif)

This _does not_ depend on #467 (proper sequence flow loop layouting).

**Comment by allinsonmota** [comment]
Hi @nikku can i do this? or not yet? Create new Boundary Event on Task from the tasks Context Pad

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/issues/742.
