### ISSUE TITLE
Allow DataStore to be modeled in between Participants

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#483]
- User can create DataStore in between participants/pools
- DataStore is still wired correctly in the underlying BPMN 2.0 document

Related to [Forum discussion](https://forum.bpmn.io/t/data-stores-to-share-data-in-between-processes-pools/469/13).

**Comment by felideon** [comment]
I don't get it. If the DataStore reference is dragged onto the canvas, how would the underlying XML know which pool to "wire it" to?

**Comment by nikku** [comment]
Yea, that is the issue and the reason why we did not implement that (yet). 

Looking into how user use our tool, we see that DataStores are often used to synchronize data between processes. And the way the BPMN reflects that (having the same data store many times drawn on the diagram) is not intuitive for the majority of users. You can read a little bit of discussion about this [here](https://forum.bpmn.io/t/data-stores-to-share-data-in-between-processes-pools/469/13).

DataStores between pools would not be 100% BPMN 2.0 compliant. They would certainly ease a users understanding of what is going on though, as users do not see these stores as replicated thingies but singletons (Excel spread sheet, database, a rack).

**Comment by nikku** [comment]
Released with `bpmn-js@2.0.0`.
