### ISSUE TITLE
Can't position any comment inside of an expanded subprocess

### ISSUE THREAD

**Issue by dumblob** [bpmn-io/bpmn-js#487]
It's impossible to add comment positioned inside of an expanded subprocess. It's only possible to position comment outside of the expanded subprocess even if it's a comment of an object inside of the expanded subprocess.

**Comment by vladimirskatusenoks** [comment]
Could you please provide some examples (screenshots and/or diagram) that could demonstrate this issue.

**Comment by dumblob** [comment]
I'm unable to reproduce it any more. I'm closing it then. If it should occur in the future, I'll reopen this issue.

**Comment by vladimirskatusenoks** [comment]
Sure, thanks!
