### ISSUE TITLE
Indicate elements hidden behind sub-processes / participants

### ISSUE THREAD

**Issue by dumblob** [bpmn-io/bpmn-js#488]
Currently expanded subprocess background is not transparent and has white background. This is an issue as some objects sometimes overlap (at least temporarily). I believe a transparent background would be a better choice.

**Comment by vladimirskatusenoks** [comment]
Hi,

Thank you for a thought. 

Could you share example diagram and screenshot(s) that would demonstrate an issue with current background and benefits of making background transparent.

**Comment by dumblob** [comment]
Hi @vladimirskatusenoks, just take a look at the screenshot below (of course, the example is wrong from the point of view of the BPMN 2.0 standard, but that's not the point).

One doesn't know what's under the subprocess which is very inconvenient while shuffling and arranging objects (in other words while working with Camunda modeler). It's also quite confusing when selecting something, because one doesn't see what everything is going to be selected.

Except for this confusion, after some time one doesn't even know which particular object will appear under or above this subprocess. Actually, this order might change over time (especially when dealing with edge triggers).

![2016-03-15-230121_1680x1050 0 0_imlib2_grab](https://cloud.githubusercontent.com/assets/2451044/13795949/44c56438-eb04-11e5-9383-8050b12d1a85.png)

![2016-03-15-230128_1680x1050 0 0_imlib2_grab](https://cloud.githubusercontent.com/assets/2451044/13795950/44cc9f28-eb04-11e5-8e12-ff5a11b7d8ac.png)

![2016-03-15-231513_1680x1050 0 0_imlib2_grab](https://cloud.githubusercontent.com/assets/2451044/13795935/287fd650-eb04-11e5-9f55-981b836e44fb.png)

![2016-03-15-231531_1680x1050 0 0_imlib2_grab](https://cloud.githubusercontent.com/assets/2451044/13795934/287f0c2a-eb04-11e5-9138-55b5d8040923.png)

**Comment by nikku** [comment]
Let me jump onto the discussion real quick here.

It makes no sense to make the expanded sub-process transparent. From the BPMN 2.0 standpoint containment (i.e. whether an element is _inside_ an expanded sub-process or not) is VERY important.

Another issue is how to indicate whether an element is currently hidden by a container (expanded sub-process or participant). We are going to give container elements (SubProcess / Participant) a slight transparency so that elements hidden by them are still visible.

**Comment by nikku** [comment]
Example screenshot: 

![image](https://cloud.githubusercontent.com/assets/58601/13809093/69761272-eb69-11e5-8258-7eb670516017.png)

**Comment by dumblob** [comment]
>We are going to give container elements (SubProcess / Participant) a slight transparency so that elements hidden by them are still visible.

Sounds and looks reasonable. Please do the same for pools and swim lanes, because as you can see on the last two screenshots I've posted, the arrow link between a data store and the expanded subprocess is behind it. In this case, I would actually rather consider making pools and swim lanes **always** under all other objects in the canvas to prevent overlapping.

**Comment by nikku** [comment]
The last two pictures you posted are known issues. Read [this forum post](https://forum.bpmn.io/t/553/3) for details.

**Comment by dumblob** [comment]
>The last two pictures you posted are known issues. Read this forum post for details.

Thanks @nikku for pointing me to an already [existing issue](https://github.com/camunda/camunda-modeler/issues/183). Does it though really happen only with Data Store objects?
