### ISSUE TITLE
Unable to upload bpmn file

### ISSUE THREAD

**Issue by shaneeardley** [bpmn-io/bpmn-js#489]
Unable to upload the attached file, the file is generated by IBM blueworks live, and as far as i can tell it is a valid BPMN 2.0 file. 

[James Dean Getting Started Process.bpmn_rename.txt](https://github.com/bpmn-io/bpmn-js/files/161387/James.Dean.Getting.Started.Process.bpmn_rename.txt)

**Comment by nikku** [comment]
Please be a bit more specific when filing bug reports:

* What is the problem (specific)?
* What did you try?
* What was the (unexpected) outcome (error message, ...)?

**Comment by shaneeardley** [comment]
Sorry about that, reading it now i was pretty vague.

Basically, as soon as i try and upload the file to open and edit it in bpmn.io, i get an error saying that the file cannot be opened(I've attached a screenshot of the error). 

![error](https://cloud.githubusercontent.com/assets/17704173/13593490/492309f0-e504-11e5-94e2-5bcba5ffdf18.png)

**Comment by vladimirskatusenoks** [comment]
Hi,

We are not yet familiar with IBM tools.

Could you please supply full export package (e.g. like described [here](https://www.blueworkslive.com/scr/docs/bwl/topics/export_print.html)) from the tool you are using, as it appears some referenced files are missing.

**Comment by shaneeardley** [comment]
Hi there,

I just tried to import the bpmn file as there wasnt an option to import the package,

I've attached the full package exported from them:

[James Dean Getting Started Process.zip.txt](https://github.com/bpmn-io/bpmn-js/files/167232/James.Dean.Getting.Started.Process.zip.txt)

**Comment by vladimirskatusenoks** [comment]
Thank you for details.

There are several issues with the way files are generated in the package and support in the Camunda Modeler:
- there is no 'bpmndi:BPMNDiagram' defined, which is required to correctly display and edit BPMN diagrams
- we currently do not support multi-file diagrams/definitions

Currently, there are no plans to support/cater for these cases.
