### ISSUE TITLE
Associating a data object reference populates the activities property instead of data input

### ISSUE THREAD

**Issue by nilei** [bpmn-io/bpmn-js#492]
According to the BPMN spec on page 150, 191 and especially 223 a data input association is used fill the data input of e.g. an activity. In the latest version online on bpmn.io, drawing an association from a data object reference to an activity creates an activity property instead of an activity data input.

This seems to be wrong and against the spec to me.

Please see the attached file (remove .txt).

Cheers, Nils
[diagram (3).bpmn.txt](https://github.com/bpmn-io/bpmn-js/files/172931/diagram.3.bpmn.txt)

**Comment by nilei** [comment]
To be explicit, I consider the following to be WRONG:

`    <bpmn:task id="Task_04wbhtb" name="Get responsible subsidiary">
      <bpmn:incoming>SequenceFlow_0jd7gxh</bpmn:incoming>
      <bpmn:outgoing>SequenceFlow_102a57d</bpmn:outgoing>
      <bpmn:property id="Property_19hjjo1" name="__targetRef_placeholder" />
      <bpmn:dataInputAssociation id="DataInputAssociation_04ff9py">
        <bpmn:sourceRef>DataObjectReference_0ockpaj</bpmn:sourceRef>
        <bpmn:targetRef>Property_19hjjo1</bpmn:targetRef>
      </bpmn:dataInputAssociation>
    </bpmn:task>
    <bpmn:dataObjectReference id="DataObjectReference_0ockpaj" name="Cancellation [unconfirmed]" dataObjectRef="DataObject_13hvbuq" />
    <bpmn:dataObject id="DataObject_13hvbuq" />`

It should result into this instead:

`    <bpmn:task id="Task_04wbhtb" name="Get responsible subsidiary">
      <bpmn:incoming>SequenceFlow_0jd7gxh</bpmn:incoming>
      <bpmn:outgoing>SequenceFlow_102a57d</bpmn:outgoing>
      <bpmn:ioSpecification>
        <bpmn:dataInput id="DataInput_04wbhtb_5" isCollection="false" name="Data Object"/>
        <bpmn:inputSet>
          <bpmn:dataInputRefs>DataInput_04wbhtb_5</bpmn:dataInputRefs>
        </bpmn:inputSet>
        <bpmn:outputSet/>
      </bpmn:ioSpecification>
      <bpmn:dataInputAssociation id="DataInputAssociation_04ff9py">
        <bpmn:sourceRef>DataObjectReference_0ockpaj</bpmn:sourceRef>
        <bpmn:targetRef>DataInput_04wbhtb_5</bpmn:targetRef>
      </bpmn:dataInputAssociation>
    </bpmn:task>
    <bpmn:dataObjectReference id="DataObjectReference_0ockpaj" name="Cancellation [unconfirmed]" dataObjectRef="DataObject_13hvbuq" />
    <bpmn:dataObject id="DataObject_13hvbuq" />`

Cheers, Nils

**Comment by nilei** [comment]
The same counts for data output associations.

**Comment by nikku** [comment]
It may be wrong according to the spec text. It is not wrong according to the underlying BPMN 2.0 meta-model. When implementing data-associations we had to do a trade of:

* We wanted to support data associations (visually).
* According to the BPMN 2.0 standard `targetRef` is mandatory.
* The correct implementation comes with a huge boilerplate (`InputSet`, ...), in practice that gets much more complicated than in your example.
* We wanted to produce valid BPMN 2.0 XML.
* We wanted to keep the implementation as simple as possible.

As a result of that we decided to not support `InputSet` and friends. What we did instead is implement a simple workaround via the `__targetRef_placeholder` property.

We do not plan to change anything about this in the future. That said we are happy to accept a pull request that contributes correct serialization of data associations and management of the necessary boilerplate.

Please talk to us [on our forums](https://forum.bpmn.io/c/developers/contributing) if you plan to contribute.

**Comment by nilei** [comment]
Hi @nikku, may you explain this workaround a little more? I don't get the idea... 

Cheers, Nils

**Comment by nilei** [comment]
And could you also point me to the place in the spec where I can find all the boilerplates you mentioned? I want to fully understand what you mean before I start contributing anything worse ;-)

Cheers, Nils
