### ISSUE TITLE
Support BPMN in color (read shape, connection and label color information)

### ISSUE THREAD

**Issue by jobburg** [bpmn-io/bpmn-js#494]
It would be nice if you guys added the function to import/export shapes with color attributes like border color for reading purposes at large diagrams. This would be a suggested integration:

`<bpmndi:BPMNLabel color:color="#000000">`

Related BPMN vendor extension: [bpmn-in-color](https://github.com/bpmn-miwg/bpmn-in-color).

**Comment by nikku** [comment]
Support for this should be built via the [bpmn-in-color](https://github.com/bpmn-miwg/bpmn-in-color) vendor extension.

We accept PRs for this.

**Comment by vkatushenok** [comment]
N.B. Here is an example based on the proposal: https://github.com/bpmn-io/bpmn-js-in-color

**Comment by ricardomatias** [comment]
Implemented with the latest [release](https://github.com/bpmn-io/bpmn-js/releases/tag/v0.19.0)
