### ISSUE TITLE
BPMN Viewer got an error in Bootstrap Tab.

### ISSUE THREAD

**Issue by solenovex** [bpmn-io/bpmn-js#498]
![err](https://cloud.githubusercontent.com/assets/3320194/13944665/074e64ae-f042-11e5-8de0-a802f9754ea1.jpg)
`

<div class="tab-content">
    <div></div>
    <div>...</div>
    <div>...</div>
    <div>...</div>
    <div role="tabpanel" class="tab-pane" id="approval">
        <bpmn process-name="销售合同审批"></bpmn> 
    </div>
</div>`

The text for each nodes were moved to the right a little bit.
This **just **happens in bootstrap tab, it was ok in other elements. (I use angularjs 1.5).

Could you please tell me how to fix that?
Thank you.

**Comment by nikku** [comment]
You are running into #476. Make sure the diagram is visible during import.

**Comment by solenovex** [comment]
Thank you very much!!!
