### ISSUE TITLE
gateway.default is not cleared when sequence flow is removed

### ISSUE THREAD

**Issue by adbre** [bpmn-io/bpmn-js#505]
**Steps to reproduce**

1. Create a gateway
2. Create a task
3. Create a sequence flow from the gateway to the task
4. Make the sequence flow default
5. Delete the sequence flow

Expected

- gateway.default property is empty

Actual

- gateway.default property still refers to the removed sequence flow

**Consequences**
Continuing the steps above

6. Create a (new) sequence flow from the gateway to the task
7. Make the sequence flow default

Now an exception is thrown because element.changed is fired with a undefined task, which the events handler did not expect.

`app.min.js:9 Uncaught TypeError: Cannot read property 'id' of undefined`

A protection against this is implemented in bpmn-io/diagram-js#154
Please note that it will not solve this issue, it will only protect against the unhandled exception.

**Solutions**
I am not that confident where the most appropriate place for a fix should be implemented.
Connections is created by diagram-js and the default property is managed by bpmn-js, and I don't know which event is appropriate to use for this.

I'd be happy to provide you with a pull request if given some hints to where a fix should be implemented (what events to listen for).

**Comment by vladimirskatusenoks** [comment]
Thank you for reporting the issue.

It is better to hook into `connection.delete` event and handle BPMN specifics in bpmn-js project.

Thank you for pointing out to the issue details
