### ISSUE TITLE
Always show full data association

### ISSUE THREAD

**Issue by martinschimak** [bpmn-io/bpmn-js#506]
When connecting a data store with an element in a different pool, the data association is most of the time partly hidden beneath one of the pools. See:

![c4ee6d7dec873d9918987757a961aec4ee7ff2b3](https://cloud.githubusercontent.com/assets/1680911/14323633/8fe8330e-fc21-11e5-9870-ef3904805413.png)

If possible this should be resolved even sooner than https://github.com/camunda/camunda-modeler/issues/183 can probably be dealt with, because it's currently one of the most annoying issues when using the modeler in real life.

**Comment by hoferch91** [comment]
![screenshot from 2016-04-14 13-51-13](https://cloud.githubusercontent.com/assets/11477689/14527132/214fe874-0248-11e6-8093-28a58c1b8fa0.png)

The same problem occurs with sub-processes in combination with DataObjectReferences.
