### ISSUE TITLE
Collapsed Subprocess shows itself in the context pad

### ISSUE THREAD

**Issue by janstuemmel** [bpmn-io/bpmn-js#509]
![image](https://cloud.githubusercontent.com/assets/7893682/14494561/bbb39914-018b-11e6-9d0e-ba40e70d61fb.png)

**Comment by gimbel** [comment]
@janstuemmel Feel free to fix this in the current milestone!

**Comment by janstuemmel** [comment]
Ref. bpmn-io/bpmn-js#247
