### ISSUE TITLE
Connection on boundary events changes/breaks on dragging

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#511]
Reproduce:
- model a boundary event with at least one outgoing sequence flow
- select elements
- move vertically

Problem:
- waypoints of sequence flow change

Expected:
- waypoints of sequence flow do not change

![honeycam 2016-04-18 14-10-15](https://cloud.githubusercontent.com/assets/7633572/14603985/7f650fda-0571-11e6-8ee2-4b2cafb38dae.gif)

**Comment by nikku** [comment]
Failing test case added (see above).

**Comment by nikku** [comment]
Restored failing test case via https://github.com/bpmn-io/bpmn-js/commit/9282cdb5a8fecf6c50614d8e76c05c57ebcfa4b4. This is still an issue.

**Comment by nikku** [comment]
My bad; attachers are already correctly added to move closure. 

Not an issue anymore 🍷.
