### ISSUE TITLE
Enhance linking from / to external documents (inter diagram / resource)

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#52]
Process diagrams are often coupled with external documents through links. To support that use case, we must be able to
- link documents from diagram elements
- link diagram elements from external documents

We should investigate that use case and provide the functionality as a plug-in for the viewer.
#### Scenarios

For bpmn elements
- A user can follow click a link to an external descriptive document
- A user can add an external document (stored as meta-data in the bpmn 2.0 file)

For external documents
- A user can provide a link to a bpmn diagram with an element or a list of elements highlighted

**Comment by andyboeh** [comment]
I would really appreciate that feature. My use-case is as follows:

We use DokuWiki as a communication platform and quality management system. There is a DokuWiki-PlugIn that embeds bpmn-js into DokuWiki. It would be very nice to be able to link process steps to Wiki pages.

I'm thinking of working around this by using, e.g., an overlay to link to the desired page. Any other ideas?

**Comment by nikku** [comment]
This sounds like a great scope for a side project. 

We don't plan to add such functionality to the bpmn-js CORE though.

**Comment by MLNW** [comment]
Since I got here via my favorite search engine I'll leave a hint how to accomplish this:

Create an extension like so:
```json
{
  "name": "Link",
  "uri": "http://schema/bpmn/link",
  "prefix": "link",
  "xml": {
    "tagAlias": "lowerCase"
  },
  "types": [
    {
      "name": "Internal",
      "superClass": ["Element"],
      "properties": [
        {
          "name": "href",
          "isAttr": true,
          "type": "String"
        }
      ]
    }
  ],
  "emumerations": [],
  "associations": []
}
```

Add `xmlns:link="http://schema/bpmn/link"` to the `<bpmn2:definitions>` tag in a diagram you want to add links to. Then add your links to an element, e.g.:

```xml
    ...
    <bpmn2:subProcess id="PMPR" name="PMPR">
      <bpmn2:extensionElements>
        <link:internal href="/processes/spr?subprocess=PMPR" />
      </bpmn2:extensionElements>
    ...
```

Now you can check if an element contains a link extension and react on that, e.g., on `root.set`:

```typescript
// Check if the element references a link that should be opened instead
const extensionElements = event.element?.businessObject?.extensionElements?.values;
if (extensionElements) {
  const links = extensionElements.filter(
    (element: { $type: string }) => element.$type === 'link:internal'
  );
  if (links.length === 1) {
    navigationInProgress = true;
    goto(links[0].href, { state: { ...history.state } });
  }
}
```

**Comment by nikku** [comment]
@MLNW Awesome contribution.

As this is requested once in a while would you like to contribute an [example](https://github.com/bpmn-io/bpmn-js-examples) how to add it (and use it)?

We'd otherwise look into picking it up, one day.

**Comment by MLNW** [comment]
@nikku At this moment I sadly do not have the capacity to do so. If someone else wants to use my comment as the basis for an example, go ahead 🚀
