### ISSUE TITLE
Provide pre-packaged version of modeler + properties-panel

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#520]
Requested **a lot** in the forum.

**Comment by IdeaSolutionsOnline** [comment]
this would be great any ideia when we will have it

**Comment by nikku** [comment]
Not on our immediate roadmap. Add you :+1: to indicate you need this.

**Comment by nikku** [comment]
We will not do this, as part of this project.

**Comment by momofant** [comment]
I spend several hours trying to follow the pipelines in the forum. But still didn't get the integrated library. It would be so great to have it pre-packaged.
