### ISSUE TITLE
Editing Textarea does not scale if zooming

### ISSUE THREAD

**Issue by hoferch91** [bpmn-io/bpmn-js#527]
The direct-editing textarea should be adapted to the current scale. This includes:
- [ ] font-size should adapt to zooming, increase/decrease if one has zoomed in/out
- [ ] size of bpmn-element should be calculated upon the scale. Up to now,  there appears the current problem: 

![zoomproblem](https://cloud.githubusercontent.com/assets/11477689/14912592/9683d306-0dfd-11e6-8dc2-b4e4e1873c61.gif)
- [x] textarea should have a minimum size, when zoomlevel << 1

**Comment by hoferch91** [comment]
Open problems:
*[ ] the resizing-dimensions are currently too large 
*[ ] when editing the label of a connection, the position of the textarea is wrong

**Comment by pedesen** [comment]
@philippfromme Can we close this? Do we want to have a textarea minimum size, when zoomlevel < 1?

**Comment by nikku** [comment]
@philippfromme Can we close this?

**Comment by philippfromme** [comment]
I'll close this. Text editing now scales with zoom.
