### ISSUE TITLE
I can model a pool with MI marker

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#533]
In BPMN it is possible to mark a pool as multi instance (at least the marker looks like the parallel multi instance marker)

Should work for both, collapsed and expanded pools

**Comment by rajgoel** [comment]
:+1:  Would be nice to have this implemented

**Comment by nikku** [comment]
We accept contributions for this feature.

**Comment by nikku** [comment]
We'll not implement this any time soon, unless we receive a contribution for this feature.

**Comment by LinqLover** [comment]
Please reopen, I'd love to have this feature, too!
Relevant thread: https://forum.bpmn.io/t/multi-instance-pool/3990/13

---

I started investigating how the other menu items for pools are implemented and found this line:
https://github.com/bpmn-io/bpmn-js/blob/d252ba2b9b4d3186443fb5d7b63c5c6d10e64935/lib/features/replace/ReplaceOptions.js#L802
However, neither this repository nor entire GitHub provides a definition of `replace-with-expanded-pool`. Can you give me any pointer on how and where this symbol is resolved eventually? Conceptionally, I would try to implement a `toggle-multiple-instance-pool` besides `replace-with-expanded-pool`, but I have no idea where to start. :-)

**Comment by azeghers** [comment]
Hi LinqLover,

Glad to see that you're taking interest in this feature.
If you wish to implement it yourself, I would guide you to [this file](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/popup-menu/ReplaceMenuProvider.js), where you'll find [conditions](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/popup-menu/ReplaceMenuProvider.js#L251-L278) to add entries to a context menu.
You would then have to create a handler specific to participants, somewhere at the bottom of the file.
Feel free to reach out if you have additional questions.

**Comment by LinqLover** [comment]
Thanks for the pointers. I'll take a look at them when I have more time again. Just to clarify: I'm not actually eager to implement this, someone else would probably be much more efficient at it. :)

Btw: We just found out that bpmn.io also appears not to support multiple instance data object, see https://bpmtips.com/bpmn-miwg-demonstration-2018-nearly-everything-you-always-wanted-to-know-about-data-objects-but-were-afraid-to-ask/#:~:text=collection, is this correct? :-)

**Comment by azeghers** [comment]
Understood, I'll take care of it and keep you updated on the results.
As for your side note, we are supporting collection markers for data objects as of [v7.5.0](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md) of bpmn-js, so there you go :smile:

**Comment by nikku** [comment]
![capture LfucGg_optimized](https://user-images.githubusercontent.com/58601/101243467-dfd8ff00-3700-11eb-8240-05282c85efe5.gif)

**Comment by LinqLover** [comment]
Great, when will these changes arrive at bpmn.io? :-)

**Comment by nikku** [comment]
With the next releas :wink:
