### ISSUE TITLE
Add minimap

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/bpmn-js#535]
Minimap is its own separate module.

- [x] Create container which should be always on top of the diagram
  - [x] Add mirroring svg group
  - [x] Mirroring svg group should fit the whole diagram (init)
- [x] Add overlay (svg rect) inside mirroring frame (svg group)
  - [x] Overlay size is according to viewport
  - [x] Make it draggable. Moving it moves the diagram's viewport.
  - [x] Make it clickable. Clicking it sets the diagram's viewport.

__TODO__

* [x] Ensure compatibility with Internet Explorer 11
* [x] Ensure compatibility with Edge
* [x] Extract into library [`diagram-js-minimap`](https://github.com/bpmn-io/diagram-js-minimap)
* [x] Add example for using it in `bpmn-js-examples`

**Comment by philippfromme** [comment]
TODO

* for now we don't want this to be part of bpmn-js, move feature into its own repository
* no tests yet

**Comment by philippfromme** [comment]
For review:

* [Minimap Implementation](https://github.com/bpmn-io/diagram-js-minimap)
* [bpmn-js Example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/minimap)

**Comment by philippfromme** [comment]
For review:

* added [open/close/toggle](https://github.com/bpmn-io/diagram-js-minimap/issues/2)
