### ISSUE TITLE
Rules added via RuleProvider ignored by Connect

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#536]
### Problem

Rules added by diagram-js's `RuleProvider` are irgnored when using diagram-js's `Connect` to create a new connection. By calling

```
modeling.connect(source, target);
```

without the third parameter set the object returned from my rule is effectively thrown away which causes bpmn-js's `Modeling` to always use a default connection or the one provided by bpmn-js's `BpmnRules`.

In my case I wanted to add a rule for custom connections via `RuleProvider` without touching `BpmnRules` but since the information is thrown away my rule was beeing ignored.

### Possible Fix

A simple change to

```
modeling.connect(source, target, typeof canExecute === 'object' && canExecute);
```

fixed this. Now in

```
Modeling.prototype.connect = function(source, target, attrs) {

  // ...

  if (!attrs) {
    attrs = bpmnRules.canConnect(source, target) || { type: 'bpmn:Association' };
  }

  // ...
};
```

`attrs` is not undefined if my rule returned an object like `{ type: 'custom:connection }` and thereby is not ignored anymore.

**Comment by nikku** [comment]
Can you add a PR + test cases for this?
