### ISSUE TITLE
Error trying to install with JSPM

### ISSUE THREAD

**Issue by calbertts** [bpmn-io/bpmn-js#537]
Hi,

I've been trying to install this package with JSPM but I'm getting this error:

`err  Error locating github:Nikku/Snap.svg/archive/v0.3.0-browserify.tar.gz.`

Not sure if you used to have an archive that isn't available anymore.

Any ideas?

**Comment by vkatushenok** [comment]
Hi,

We currently support only `npm` and `bower` packages.

The package you are referring above is [available](https://github.com/Nikku/Snap.svg/archive/v0.3.0-browserify.tar.gz)

Make sure `JSPM` can actually handle [this kind of dependencies](https://github.com/bpmn-io/diagram-js/blob/master/package.json#L59)

Cheers,
Vladimir

**Comment by calbertts** [comment]
Just for future references:

https://github.com/jspm/jspm-cli/issues/1787

**Comment by vkatushenok** [comment]
@calbertts Thanks!
