### ISSUE TITLE
Sequenceflow overlaps gateway

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#546]
Steps to reproduce:

![screencast1](https://cloud.githubusercontent.com/assets/3829733/15320771/9448725c-1c32-11e6-8283-6e06480ecc91.gif)

Hints:
- only occured with gateways
- can be fixed by moving the connection again or reimport

**Comment by nikku** [comment]
This is something we cannot easily fix unless we get rid of SnapSVG (https://github.com/bpmn-io/diagram-js/issues/50).
