### ISSUE TITLE
Adjust label position with changed connection (non-segment dragging)

### ISSUE THREAD

**Issue by janstuemmel** [bpmn-io/bpmn-js#547]
- [ ] should move label, if out of connection bounds
- [ ] should move label if reconnecting
- [ ] should move label if dragging bendpoint

Referenced to #331

**Comment by vkatushenok** [comment]
Here is some [relevant post](https://forum.bpmn.io/t/adjust-label-when-connection-has-modified/746) in the forum.

**Comment by nikku** [comment]
Gonna be closed with #331.
