### ISSUE TITLE
Tooltip hides the text that is currently entered

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#548]
__Problem:__

When editing text labels (e.g. of tasks) the tooltip for linefeed is often above the text being entered which makes typing quite difficult, because you cannot see what you type

![screencast1](https://cloud.githubusercontent.com/assets/3829733/15323676/865f5578-1c43-11e6-87c5-41b870acf57b.gif)

__Possible solutions:__

* tooltip does not stay, but goes away after time
* tooltip can be hidden by user ("do not show this tooltip anymore")
* tooltip is not placed above the text but next to it

**Comment by nikku** [comment]
We are using the native browser facility for tooltips here. That means we got only two options here:

* Display the tooltip (with the current behavior)
* Remove the tooltip alltogether

Anything else means lots of implementation efford.

**Comment by gimbel** [comment]
Maybe it makes sense to think in the following direction:

All shortcuts are documented at the same place (e.g. in the help menu). Then it would feel easier to remove the tooltip which is described above.

**Comment by pedesen** [comment]
We should remove the tooltip, because "Shift + Enter" for a new line is a widespread shortcut found in many tools or web apps.

I created a module specific ticket for that: https://github.com/bpmn-io/diagram-js-direct-editing/issues/3
