### ISSUE TITLE
Rework label handling

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#549]
There is lots of room for improvements with regards to label editing. 

#### Sub Tasks

* [ ] same size text on diagram and during direct editing (gives the user very good feedback on how the text looks layouted)
* [ ] better editing experience for `TextAnnotation`
      * [ ] automatically expand the direct editing field based on contents
      * [ ] do not remove manual new lines
* [ ] update label dimensions (post editing)
      * [ ] adjust label box to actual text size
      * [ ] remove label outline (would allow labels to be less intrusive, i.e. when modeling in crowded diagrams)
* [ ] improve on inline tooltip #548

**Comment by hoferch91** [comment]
Editable html-elements might be an approach. 
Checkout: https://jsfiddle.net/v3142yna/2/
