### ISSUE TITLE
How to draw dashed arrow?

### ISSUE THREAD

**Issue by jkufner** [bpmn-io/bpmn-js#551]
There is an image on project home page:

![http://bpmn.io/assets/img/model.png](http://bpmn.io/assets/img/model.png)

How to draw the vertical dashed arrow? There is no obvious way to do it at http://demo.bpmn.io/ -- if it is not possible, then is should not be at the first screenshot; if it is possible, then it is very well hidden feature. One way or another, something is not right :)

**Comment by philippfromme** [comment]
Hi,

the dashed arrow is called 'Message Flow'. It is used to communicate between pools (see https://camunda.org/bpmn/reference/). You can model it easily using the context pad.

![ezgif com-crop](https://cloud.githubusercontent.com/assets/7633572/15466462/132805aa-20da-11e6-818d-3255b812f709.gif)

**Comment by jkufner** [comment]
Thank you. It looks very logical now, but it was very hard to discover. Actualy, it took me very long to find the "collapsed pool" to create the correct target for the arrow. I was thinking what would help in my begginings, and I found two things:

  1. Link BPMN reference from the editor. I completely missed the BPMN reference document you linked and it is extremely helpful. There are some links in bottom right corner, the "BPMN reference" link would be helpful there.

  2. Palette (the left toolbar) shows only basic variants of the elements, more specialized variants are available after clicking the wrench icon at the element in the diagram. This makes it hard to see, what is on the menu and where each specialized element is available. I'm sure it is easy for someone with a good knowledge of BPMN and some experience with this editor, but it is significant obstacle when starting. What do you think about a two level palette? The content of the submenu would be the same as the popup menu after clicking the wrench icon:

    ![screenshot](https://cloud.githubusercontent.com/assets/16572/15467665/03fbcb24-20e0-11e6-8cef-7edcf7d3c6c8.png)

**Comment by vintprox** [comment]
> 2. Palette (the left toolbar) shows only basic variants of the elements, more specialized variants are available after clicking the wrench icon at the element in the diagram. This makes it hard to see, what is on the menu and where each specialized element is available. I'm sure it is easy for someone with a good knowledge of BPMN and some experience with this editor, but it is significant obstacle when starting. What do you think about a two level palette? The content of the submenu would be the same as the popup menu after clicking the wrench icon:

Wow, I like the idea with two-level palette.
