### ISSUE TITLE
Tasks are very very small

### ISSUE THREAD

**Issue by nilei** [bpmn-io/bpmn-js#552]
When importing my BPMN into the bpmn.io editor I am receiving very very small task elements.
[test.bpmn.txt](https://github.com/bpmn-io/bpmn-js/files/276384/test.bpmn.txt)

**Comment by nikku** [comment]
How are tasks very small? They are as big as defined in the DI section of the BPMN 2.0 XML:

![image](https://cloud.githubusercontent.com/assets/58601/16224358/03d5caf4-37a2-11e6-8b59-e121b384a440.png)
