### ISSUE TITLE
When copying pools, I cannot connect tasks with messageflow.

### ISSUE THREAD

**Issue by klajmajk** [bpmn-io/bpmn-js#553]
Sequence flow is drawn instead of messageflow. Please see the picture.

Reproduction of the bug:

1. I created pool with one start event and one task.
2. Then I copied the whole thing
3. Then I tried to connect the tasks and bpmnio created sequenceflow (which is overlapped by the second poll) instead of messageflow. (Please see the picture)

![bpmn_io_bug](https://cloud.githubusercontent.com/assets/2862151/15472197/2fa5be82-20fa-11e6-8e10-37495bc4b92a.JPG)

**Comment by gimbel** [comment]
Good catch, I was able to reproduce. We will take a closer look in our next milestone and decide what we are going to do.

**Comment by gimbel** [comment]
Saving and re-importing such a diagramm results in many errors

**Comment by philippfromme** [comment]
Furthermore it is not possible to connect the pools via message flow after copy-paste. 

When 2 participants are modeled by hand they both belong to a different process so they are connected via message flow.

If 1 participant is copied and pasted both of them belong to the same process so they are connected via sequence flow. This is not the desired behavior.

**Comment by ricardomatias** [comment]
This has been fixed with camunda/camunda-modeler#297
