### ISSUE TITLE
Copy/paste does not work correctly for event sub-processes

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/bpmn-js#555]
![event-sub](https://cloud.githubusercontent.com/assets/2331533/15508513/0da3f7d2-21d0-11e6-8c70-139a408cf077.gif)

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/b43cff1ec2e2aed7d7ad45e90b8ba489ec7633a2
