### ISSUE TITLE
Add modifier for space tool to restrict adding space only to the current participant

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/bpmn-js#557]
On the screenshot below, would like to add space to the right of the cursor but only for the bottom participant.
![screen shot 2016-05-25 at 09 19 01](https://cloud.githubusercontent.com/assets/2331533/15531318/0cbd5c20-225a-11e6-9adf-fa91a4fdc8b3.png)

__Tasks__

* [ ] Perform space tool locally if _secondary modified_ is pressed
* [ ] Show which element is the target of the space operation if modifier is pressed during space preview

**Comment by nikku** [comment]
__Interaction Demo__

![foo](https://user-images.githubusercontent.com/58601/33994050-543ef43e-e0d9-11e7-8525-2f43a59da7b2.gif)

__Notes__

This does not provide a preview to the user yet, whether the local or global space tool is being used.

**Comment by nikku** [comment]
This is definitely something we'd like to have, someday maybe.

**Comment by nikku** [comment]
See https://github.com/bpmn-io/diagram-js/commit/148a87c575802db97de8a83d139cbf21ddaa79a1 for working demo.

**Comment by hkupitz** [comment]
Is there any reason the commit by @nikku hasn't been merged yet? Anything that is missing?

This feature would make my day-to-day life so much easier and I'd assume I'm not the only one.

**Comment by hkupitz** [comment]
Thanks for looking into it. I've just briefly played around with the local space-tool and it's a game changer for me personally, working with multiple pools in one diagram quite often. ❤

**Comment by nikku** [comment]
@hkupitz unfortunately this did not make it into our last planning rounds.

Tagged with `spring cleaning`, I hope we'll be able to follow up via that route.

**Comment by nikku** [comment]
You can update the diagram-js feature branch to the latest diagram-js version, and create a pull request for it.

**Comment by nikku** [comment]
In addition we'd need test cases to verify that the feature works (cf. [space tool tests](https://github.com/bpmn-io/diagram-js/blob/develop/test/spec/features/space-tool/SpaceToolSpec.js#L640)).

**Comment by hkupitz** [comment]
I've rebased the newest commits of `diagram-js/develop` onto the feature branch.

Still I'm wrapping my head around how I can simulate pressing the secondary modifier key (Shift) for the respective test(s). [hasSecondaryModifier()](https://github.com/bpmn-io/diagram-js/blob/768a5bae26ff36a525958762738c8a6cec6e376d/lib/util/Mouse.js#L81) goes by the `MouseEvent`, which in case of manually holding down Shift has the `shiftKey` flag set to true. How can I programmatically trigger this in the test case?

**Comment by hkupitz** [comment]
@nikku Any hints or pointers?
