### ISSUE TITLE
Element layout assistance (equal distance)

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#563]
**Observation:** People usually want to model elements in the same distance to each other.

We could give them some assistance in doing so.

#### Advanced Snapping
- I.e. like sketch (cf. https://github.com/bpmn-io/bpmn-js/issues/181)

#### Placeholder / Position on Add

  ![add-helper](https://cloud.githubusercontent.com/assets/58601/15665260/4dd46898-270a-11e6-97ed-7fe14077313b.png)

#### Alignment Helpers

- Distribute selection (horizontal / vertical....) https://github.com/bpmn-io/diagram-js/issues/172

#### Automatic Placement

- element is placed to pre-defined position on click; this takes layout rules into account

**Comment by nikku** [comment]
I think we can close this ticket once https://github.com/bpmn-io/diagram-js/issues/172 is implemented. Should solve the issues for the time being.

**Comment by nikku** [comment]
Closing this as https://github.com/bpmn-io/diagram-js/issues/172 is implemented.

**Comment by nikku** [comment]
We can do better 😉 .

**Comment by nikku** [comment]
![auto-place](https://user-images.githubusercontent.com/58601/33783059-5fd92184-dc5b-11e7-842d-9d2083e08530.gif)

**Comment by nikku** [comment]
This also addresses https://github.com/bpmn-io/bpmn-js/issues/560.

**Comment by nikku** [comment]
![auto-place](https://user-images.githubusercontent.com/58601/33799698-109b0eee-dd31-11e7-9f26-2a22a4027ce7.gif)

**Comment by philippfromme** [comment]
Don't know if this is related to auto-placement but when you add 3 tasks the third connection is not being cropped correctly.

![foobar](https://user-images.githubusercontent.com/7633572/33837517-da981168-de8c-11e7-90d6-eada5fb821a3.gif)

**Comment by philippfromme** [comment]
This feature would be much better if there was a preview of what would happen if used auto-place. Right now it feels like I have to learn the way it works through fiddling around, especially when I don't know the code.

**Comment by philippfromme** [comment]
For example in this case:

![foobar](https://user-images.githubusercontent.com/7633572/33838303-679fbaa0-de8f-11e7-8a84-b53083373e63.gif)

I would expect the task to be placed below the bottom one. As a user `MAX_HORIZONTAL_DISTANCE` would seem like magic to me. It would feel like sometimes it works and sometimes not. This might lead to a lot of users using auto-place in situations where they expect something else to happen.

**Comment by nikku** [comment]
The general rational for the implementation (in the order of mentioning):

* drop auto placed elements as close to the source as possible (that's why `MAX_HORIZONTAL_DISTANCE` is in place)
* in complex setups (such as the one you've screencasted) just work with a sensible default => users should rather use manual placement in these case anyway
* be simple and predictable

Especially for cases such as layouting / auto placement there is _always_ room for improvement. The question is, how far we'd like to go here.

**Comment by nikku** [comment]
The example you've mentioned regarding the cropping is not related to auto-placement but to our intersection algorithm.

**Comment by nikku** [comment]
Boundary handling could be improved, too: 

![image](https://user-images.githubusercontent.com/58601/33847090-bbb38fb2-dea9-11e7-9752-929f2113fc7b.png)

**Comment by nikku** [comment]
Incorporating [your feedback](https://github.com/bpmn-io/bpmn-js/issues/563#issuecomment-350756442) I've removed the `MAX_HORIZONTAL_DISTANCE` handling via https://github.com/bpmn-io/bpmn-js/commit/4d52d5284de5fad52dceca86859286de24a616c2.

This leads to this interesting effect now:

![foo](https://user-images.githubusercontent.com/58601/33848450-13e1af26-deae-11e7-9e52-f8c98d3ba273.gif)

I'd argue the placed element should be closer to the actual source element. Otherwise we may risk people don't find the placed element on the screen.

**Comment by philippfromme** [comment]
At least I found a reliable way to reproduce the cropping bug. 🍾

**Comment by philippfromme** [comment]
Regarding `MAX_HORIZONTAL_DISTANCE` one or the other way we have to make an assumption about how users would expect auto-place to work. I think we should get more feedback.

**Comment by nikku** [comment]
Added the ability to opt out of autoPlace via bootstrap configuration (https://github.com/bpmn-io/bpmn-js/commit/86d1ee92fa3e4117da45f574accd7689efe1a307).

**Comment by nikku** [comment]
Added basic auto placement for boundary events via https://github.com/bpmn-io/bpmn-js/commit/b4dd4f9bf9337867904a69cbb8e0f9d86033dfcb.
