### ISSUE TITLE
Cant' morph ad-hoc subprocess into event subprocess

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#572]
Context pad entry is there but turning an ad-hoc subprocess into an event process is not possible. Either remove context pad entry or make operation possible.

![ezgif com-crop](https://cloud.githubusercontent.com/assets/7633572/16033324/a9b4a798-320b-11e6-8dc4-79f3aaef082c.gif)

Implementation Hints:
- Create failing test case first (see [existing test cases](https://github.com/bpmn-io/bpmn-js/blob/master/test/spec/features/replace/BpmnReplaceSpec.js)).
- [`ContextPadProvider`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/context-pad/ContextPadProvider.js) is responsible for showing the replace menu.

**Comment by ricardomatias** [comment]
Cannot reproduce it anymore.
