### ISSUE TITLE
Can't select any tool

### ISSUE THREAD

**Issue by pankovivan** [bpmn-io/bpmn-js#573]
No hover color, when I try select tool. As result, I can't select any element tool.

![animation](https://cloud.githubusercontent.com/assets/19933221/16049555/910db9a8-3271-11e6-86e9-43a5cb8f653e.gif)

I have IE 11, in Chrome - no problem.

**Comment by pankovivan** [comment]
Looks like I found the reason, problem with property `pointer-events`. But in IE11 it should work.
http://stackoverflow.com/questions/17441810/pointer-events-none-does-not-work-in-ie9-and-ie10

**Comment by vkatushenok** [comment]
Tested in IE 11.0.9600.17416 (Windows 8.1), http://demo.bpmn.io and everything looks fine.

Closing for now.
