### ISSUE TITLE
Fix message flow layout on participant resize

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#574]
Existing message flows should not break/relayout on participant resize, unless their docking points got _resized away_.

Cf. [forum thread](https://forum.bpmn.io/t/resizing-of-pools-moves-outgoing-message-flows/738).

__Example Interaction__

![image](https://cloud.githubusercontent.com/assets/58601/16073301/923d4b9e-32e5-11e6-8e80-d27720f56e19.png)

**Comment by martinschimak** [comment]
Many thx for opening this issue.

1) This is breaking on "move" actions, too. 

2) Let me add my personal point of view on the rules for the underlying algorithm. In my mind, 

* Message flow's source and target points connected to a flow symbol should *always stick* at the exact border point of the flow symbol at which they have been connected before. Move and Resize Actions should *not change those points* by default but prefer a cornered line to connect the points.

(Reason: Typically I have a very good (readability) reason to connect a flow at a very specific position. When I move some objects, I would get a few cornered message flows, which would not be as harmful as changed connections points. Furthermore I can then decide to move/resize a communicating participant, too, which would typically give me straight message flows again, at least if I find the correct position for the flows.)

* Just message flow's source and target points connected to a participant's border should stay at the x-coordinate of the drawing area as long as it is possible to re-connect the message flow to the participant at this x-coordinate.

(Reason: Here it typically does not matter at which point the message flow is connected, and in particular straight lines should remain straight. Therefore the message flows should "float" along the participant's border)

**Comment by martinschimak** [comment]
I updated my previous comment. Please reread, if you already have read it before. Thx.
