### ISSUE TITLE
Morphing collapsed subprocess into expanded should make children visible

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/bpmn-js#575]
* expand does not show children
* on reimport of expanded diagram, children are visible though

![1](https://cloud.githubusercontent.com/assets/2331533/16074941/10842b4c-32ed-11e6-8b02-0f89791ed91e.gif)
![2](https://cloud.githubusercontent.com/assets/2331533/16074942/1084e456-32ed-11e6-8b0f-eb99251e0f31.gif)

N.B. #510 should make children invisible on morph back

**Comment by hoferch91** [comment]
State of progress:
functionality: replacing collapsed with expanded shows children
	       replacing expanded with collapsed hides children
tests: both ways are tested, missing functionality is also tested
TODO: 
      -make sure that all children are covered by the parent shape(already tested)
      -labels without a content should not be displayed

**Comment by nikku** [comment]
See review comments on feature branch.

Test cases verifying this works with bpmn-js would be cool, too.
