### ISSUE TITLE
Select specific elements through pressOn on palette-symboles

### ISSUE THREAD

**Issue by hoferch91** [bpmn-io/bpmn-js#577]
A first idea to reach specific elements through the palette easier could be, to provide on a long mousedown (pressOn) a small horizontal menu with the possible selectable elements (comparing to the screw-wrench). After opening up the menu, the selection itself should be done through mouseup.

The sequence of usage should be comparable to the selection of an umlaut on the smartphone.

Chrome-Demo: https://plnkr.co/edit/fgsAIqqyx2vjkLW5lA2X?p=preview

NOTE:
* current behaviour of palette should not change
* pressOn-menu contains only the specializations of the element, icons have the same size as the palette

**Comment by nikku** [comment]
We decided to implement direct replace menu open as an alternative. See https://github.com/camunda/camunda-modeler/issues/327. 

Let's talk whether we still want this.

**Comment by hoferch91** [comment]
Not necessary due to [camunda/camunda-modeler#327](https://github.com/camunda/camunda-modeler/issues/327).
