### ISSUE TITLE
Replace events when moved outside event sub process

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#583]
Some events (error, escalation and compensation start events) are not allowed outside an event sub process. We should consider replacing them the same way as non-interrupting start events get replaced.

![foo](https://cloud.githubusercontent.com/assets/2543743/16555201/b9327c18-41d3-11e6-9b33-1393ab45fa5c.gif)

**Comment by nikku** [comment]
You got a complete list of events for which that behavior should apply?
