### ISSUE TITLE
Cursor doesn't change on tool activation via keyboard shortcut

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#584]
When using keyboard shortcuts to activate a tool (hand tool, space tool...) the cursor changes to default and only changes to tool cursor after moving it.

**Comment by nikku** [comment]
Fixed by https://github.com/bpmn-io/diagram-js/issues/136

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/2cb18c92ccf7624b143a1e0f956780340468c955.
