### ISSUE TITLE
Simplify svg for escalation events

### ISSUE THREAD

**Issue by enedelko** [bpmn-io/bpmn-js#592]
I have noticed that your code uses curves to render Escalation events. 

Please consider correction of PathMap.js to make sure that instead of

d="m 18,19.98 c -2.808,2.382 -5.616,4.764 -8.424,7.146 2.808,-6.589333 5.616,-13.178667 8.424,-19.768 2.463,6.589333 4.926,13.178667 7.389,19.768 -2.463,-2.382 -4.926,-4.764 -7.389,-7.146 z"

the path would look like this

d="m 18 20 l -8 7 l 8 -20 l 8 20 l -8 -7 z"

**Comment by pedesen** [comment]
You're right, thanks! Saves us a few bytes :smiley_cat:
