### ISSUE TITLE
Bundling bpmn-js with browserify: issues with snapsvg / eve?

### ISSUE THREAD

**Issue by frhd** [bpmn-io/bpmn-js#60]
When bundling bpmn-js with browserify and loading the javascript file in the browser, I get the following error:

<pre>
/**
 * @class ClassPlugin
 *
 * Extends snapsvg with methods to add and remove classes
 */
Snap.plugin(function (Snap, Element, Paper, global) {
 ^^^
<b>(Uncaught TypeError:undefined is not a function)</b>

  function split(str) {
    return str.split(/\s+/);
  }
</pre>

I've spent some hours digging around, but no luck yet. [https://github.com/adobe-webplatform/Snap.svg/pull/170](https://github.com/adobe-webplatform/Snap.svg/pull/170) didnt resolve this issue for me.

Any ideas?

**Comment by dovidkopel** [comment]
I'm having an issue with this. I am trying to using bpmn-js but I want to customize some things. Like you do in the custom-elements example. In this case I just want to remove some items from the palette. I see how to do this when building with grunt but not with bower.

If there is a simple way to make that change please let me know.

**Comment by nikku** [comment]
Please create a new issue if you have a particular problem.
