### ISSUE TITLE
Text annotation should automatically fit its content vertically

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#600]
The size of the text annotation should automatically increase and decrease height based on the content.

Hint: the resizing should react on all external changes of the element's name (e.g. properties panel).

![text-annotation](https://cloud.githubusercontent.com/assets/2543743/17396236/c018085a-5a32-11e6-8a99-2ccea3140484.png)

![selection_086](https://cloud.githubusercontent.com/assets/2543743/25182336/8e7358e2-2514-11e7-9f39-84e19ca169bb.png)

---

Related to [SUPPORT-3243](https://app.camunda.com/jira/browse/SUPPORT-3243), related to (but not required by) [SUPPORT-2604](https://app.camunda.com/jira/browse/SUPPORT-2604).

**Comment by vkatushenok** [comment]
There is related issue in the Modeler - https://github.com/camunda/camunda-modeler/issues/155.

**Comment by nikku** [comment]
Reverted these changes via https://github.com/bpmn-io/bpmn-js/issues/635 as they break a lot of stuff (https://github.com/bpmn-io/bpmn-js/issues/628, https://github.com/bpmn-io/bpmn-js/issues/634). 

A proper fix needs to take into account importing and integrate correctly into the diagram-js undo / redo infrastructure.

**Comment by mschoe** [comment]
requested in support [SUPPORT-3243](https://app.camunda.com/jira/browse/SUPPORT-3243).

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/issues/472.
