### ISSUE TITLE
Vertical distribution freeze model with boundary event

### ISSUE THREAD

**Issue by Zelldon** [bpmn-io/bpmn-js#605]
**Short description**:
After boundary event with outgoing sequence flow is added to the model and the vertical distribution is used the model can't be edit anymore. The activities can't be moved.

![freeze](https://cloud.githubusercontent.com/assets/2758593/17623688/8fe3cd66-60a1-11e6-8e79-dcc3e6368705.png)

**How to reproduce:**

 * Create Process with Task
 * add Boundary Event to the Task
 * add outgoing sequence flow to Boundary event to an End Event
 * mark all activities
 * use the vertical distribution
 -> Model will freezed

**AT:**

 * after vertical distribution model is not freezed

**Comment by nikku** [comment]
@Zelldon Would be cool if you could attach the diagram you are using, too.

**Comment by Zelldon** [comment]
Hey I created a new model for that:

[freeze.zip](https://github.com/bpmn-io/bpmn-js/files/415571/freeze.zip)

It seems that the boundary event should be a timer boundary event so the freeze will come along.

Greets,
Chris
