### ISSUE TITLE
Align annotation text annotation editing and display

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/bpmn-js#607]
Be consistent in editing and displaying annotation test.
- [x] Text annotation text is rendered from top-left
- [x] Text annotation direct editing is carried out from top-left
---

See also [SUPPORT-2604](https://app.camunda.com/jira/browse/SUPPORT-2604).

**Comment by nikku** [comment]
Closed with latest release.

**Comment by nikku** [comment]
Changed to align text-annotation rendering and editing.

**Comment by pedesen** [comment]
This gets addressed in #600.

**Comment by pedesen** [comment]
Closed with https://github.com/bpmn-io/bpmn-js/commit/a53562e1d5ff37b91ad1e70d1069c15308802389
