### ISSUE TITLE
Creating a collaboration leads to multiple unused claimed ids in model

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#608]
When creating a collaboration by creating a participant multiple ids are claimed but never used.

Berfore:

![before](https://cloud.githubusercontent.com/assets/7633572/17857555/79ea43a8-6882-11e6-8ddb-e9913e809fef.png)

After:

![after](https://cloud.githubusercontent.com/assets/7633572/17857562/810a68de-6882-11e6-904e-d6912372da22.png)

After the collaboration was created there should only be one process id claimed. Instead there are three, two of them unused.

**Comment by philippfromme** [comment]
When creating the new element from the palette IDs are claimed already for a new process element that serves as temporary parent for participant. Later this element is replaced by the already existing process but IDs are not unclaimed.

**Comment by nikku** [comment]
Maybe related to https://github.com/bpmn-io/bpmn-js/issues/1161.

**Comment by nikku** [comment]
We generally do not unclaim IDs when removing elements. This is something we got to look into, some day, maybe :wink:

**Comment by philippfromme** [comment]
> some day, maybe

Maybe, baby.

**Comment by philippfromme** [comment]
Deleting shapes/connections only unclaims the IDs of the shape/connection. Nested IDs (e.g. process ID) are not unclaimed.

**Comment by nikku** [comment]
@philippfromme is this issue fixed via https://github.com/bpmn-io/bpmn-js/commit/fe11c2ee78000449ba20412c99be30be95bf776d? If that is the case, let us close it and close the related https://github.com/camunda/camunda-modeler/issues/1503 issue, too.

**Comment by philippfromme** [comment]
This is __not__ fixed. Thes numbers that are assigned true are not unclaimed due to the IDs are generated. DI element IDs are also not unclaimed. We could decide that this is not an issue. The main issue was that we didn't unclaim IDs like `StartEvent_1` in certain cases. That has now been fixed.

**Comment by nikku** [comment]
We concluded that this is not a problem anymore. With https://github.com/bpmn-io/bpmn-js/commit/fe11c2ee78000449ba20412c99be30be95bf776d being merged all IDs that can be edited by the user are and _should be_ properly unclaimed.
