### ISSUE TITLE
create community-feature-repo for auto-layouting

### ISSUE THREAD

**Issue by hoferch91** [bpmn-io/bpmn-js#611]

**Comment by berndruecker** [comment]
yeah :-) :+1:

**Comment by gimbel** [comment]
there should be a readme and an example how to use it

we could also think of a blogpost on the bpmn.io blog

**Comment by hoferch91** [comment]
yes, I’m working on that. I've created a repository, that will give an idea about required preconditions how to use it in its readme. 
https://github.com/bpmn-io/bpmn-js-auto-layout
