### ISSUE TITLE
Label position changes when editing text externally

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#613]
When editing text externally, e.g. using properties panel or undo/redo, the position changes slightly on each change.

![label_move](https://cloud.githubusercontent.com/assets/2543743/18380847/a5a535de-7679-11e6-8e7b-c75ab7d0a8e8.gif)

**Comment by rbatllet** [comment]
Any idea when this bug will be fixed?

**Comment by rmondejar** [comment]
After some tests, we discovered this problem only happens with Firefox, but with Chrome it works well. Take that in consideration to reproduce the error.
