### ISSUE TITLE
I can add conditions on conditional events

### ISSUE THREAD

**Issue by Zelldon** [bpmn-io/bpmn-js#615]
I can model conditional events and **add conditions** (like on conditional sequence flows) in the property panel.

AT:
 * on intermediate, boundary and start Event-Subprocesses I can add conditions on conditional events

 Should look like this:
```
      <bpmn:conditionalEventDefinition>
        <bpmn:condition xsi:type="bpmn:tFormalExpression">${false}</bpmn:condition>
      </bpmn:conditionalEventDefinition>
```

Related to [CAM-6602](https://app.camunda.com/jira/browse/CAM-6602).

**Comment by pedesen** [comment]
moved to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/211
