### ISSUE TITLE
Names are not shown after horizontal and vertical distribution

### ISSUE THREAD

**Issue by Zelldon** [bpmn-io/bpmn-js#616]
**Problem:**
The labels/names of the activities are not shown in the modeler. If a new label will be created the name is set in the XML but not in the diagram.

**Method to reproduce:**
After modeling the following diagram the horizontal and vertical scaling must be used.
When a activity is now labeled, the label/name is not shown in the diagram.
![namingfails](https://cloud.githubusercontent.com/assets/2758593/18944104/c49af9f6-8623-11e6-8586-93abeb65a0b5.png)

**Modeler Version:**
1.2.1

Attached also an example model file
[namingFails.zip](https://github.com/bpmn-io/bpmn-js/files/499963/namingFails.zip)

**Comment by Zelldon** [comment]
Forgot to mention the error does not appear in the modeler logs. But there are 2 errors and 1 warning in the dev mode (F12), see the following screenshot.


![screenshot](https://cloud.githubusercontent.com/assets/2758593/18944345/427dcfe6-8625-11e6-9c2c-7212c273deac.jpg)

**Comment by ricardomatias** [comment]
I get the following errors when I open your diagram with the latest version of the modeler (1.3):
![img-2016-09-30-110103](https://cloud.githubusercontent.com/assets/8850708/18986472/3fc6b8f2-86fd-11e6-8a7f-084b55e76a48.png)

**Comment by Zelldon** [comment]
Hey Ricardo,

it seems that this problem is fixed on the latest version.
I will close the ticket.

Thanks,
Chris
