### ISSUE TITLE
how can i save bpmn but not gatewayDirection

### ISSUE THREAD

**Issue by huazi111** [bpmn-io/bpmn-js#617]
i use properties-panel-extenstions  after i save the xml but not thi gatewayDirection like this

```
<bpmn2:exclusiveGateway id="ExclusiveGateway_172sl2h"> 
```
but i want that 

```
<exclusiveGateway id="sid-5134932A-1863-4FFA-BB3C-A4B4078B11A9" gatewayDirection="Converging">
```

**Comment by nikku** [comment]
`gatewayDirection` is not maintained by this library and we do not plan to add it as a feature, too.
