### ISSUE TITLE
Mobile navigation

### ISSUE THREAD

**Issue by John0x** [bpmn-io/bpmn-js#622]
Good morning,

is bpmn-js supposed to support mobile devices? I tried to use it with ionic 2 and had a lot of problems. One of them is that alot of events like the element.click don't fire accurately. Another one is that I get alot of the "Unable to preventDefault inside passive event listener due to target being treated as passive" errors.

**Comment by nikku** [comment]
It should work on mobile, it is not our main priority though. It wouldn't surprise me if you encounter some issues.

You can help us by tracing down the stuff you encounter and filing them as individual bug reports.
