### ISSUE TITLE
Unable to preventDefault

### ISSUE THREAD

**Issue by John0x** [bpmn-io/bpmn-js#624]
Hey, I've bundeled the bpmn-js modeler (newest version) with bower and integrated it into my ionic 2 (angular 2) app.
Every time I move an element I get the following error:
````
Unable to preventDefault inside passive event listener due to target being treated as passive
````

The elements do move without problems but I guess the error still has some impact?

**Comment by nikku** [comment]
This is not an error but a warning. Google and the corresponding link to [this Chrome status](https://www.chromestatus.com/features/5093566007214080) will tell you more. 

For you as a user, this warning should not have any impact.
