### ISSUE TITLE
Selecting an element via TOUCH does not work correctly

### ISSUE THREAD

**Issue by John0x** [bpmn-io/bpmn-js#625]
Hey, I've bundeled the bpmn-js modeler (newest version) with bower and integrated it into my ionic 2 (angular 2) app.
It is hard to click on an element because the bounding box does not seem to work. I have to click multiple times to select an element.
Dragging (Holding down over the element) though works fine.

**Comment by nikku** [comment]
Thanks for the bug report. Mobile support is not the best right now. At some point we'll revise it.

**Comment by nikku** [comment]
Duplicate of https://github.com/bpmn-io/bpmn-js/issues/449.
