### ISSUE TITLE
External Gateway label not rendered as typed

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#632]
Working towards a more intuitive label editing experience, external labels should always render as they are typed.

This is not the case in certain situations:

![image](https://cloud.githubusercontent.com/assets/58601/20518455/8e103882-b09f-11e6-94c4-4c73f62eaeb2.png)

**Comment by pedesen** [comment]
Fixed with https://github.com/bpmn-io/bpmn-js/commit/e797d9c1423493ceb67c0c5e4a68cadb47e5a582.
