### ISSUE TITLE
how can I use colorRenderer with BpmnViewer

### ISSUE THREAD

**Issue by ravitdx** [bpmn-io/bpmn-js#633]
Hi,

I have to change the color of each type of the element accordingly like **'bpmn:Lane','bpmn:StartEvent','bpmn:Task'** .So how can I use colorRenderer with Bpmnviewer so that I can set colors each element. My code is same as in **simple-commonjs** example

**Comment by nikku** [comment]
Please ask these kind of questions in our [project forum](https://forum.bpmn.io).
