### ISSUE TITLE
Notifications stay after mouse leaving it

### ISSUE THREAD

**Issue by MitjaMIKLAV** [bpmn-io/bpmn-js#637]
Hi.

I have a problem - if i hover mouse over the connect arrows and start dragging it,
notification with text "Connect using Sequence/MessageFlow or Association" stays
in canvas permanently. I need to save drawing and reopen it that the notification disappears.

Any idea how can I fix this?

Image with problem:
![image](https://cloud.githubusercontent.com/assets/6469320/20850735/1e302612-b8dd-11e6-8253-0dc09738f84a.png)

**Comment by nikku** [comment]
Which browser do you use?
