### ISSUE TITLE
Cannot move Participant + Data Association

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#638]
A selection with participants + data association cannot be moved:

![foo](https://cloud.githubusercontent.com/assets/58601/20902640/47e378a8-bb38-11e6-9c00-ab57b1fbe69f.gif)

__Example Diagram__

[association.bpmn.txt](https://github.com/bpmn-io/bpmn-js/files/632289/association.bpmn.txt)

**Comment by ricardomatias** [comment]
Cannot move elements if the association is selected, f.ex:

![638-association](https://cloud.githubusercontent.com/assets/8850708/21221252/fc2854f6-c2bc-11e6-80c8-3edff3920f3d.gif)

**Comment by nikku** [comment]
Fixed with additional rule tweeking.
