### ISSUE TITLE
SVG markers disappearing when multiple BPMN viewers are on the same page

### ISSUE THREAD

**Issue by vpanfilov** [bpmn-io/bpmn-js#639]
There is a problem with SVG markers rendering when multiple instances of BPMN viewers or modelers are loaded on the same page. For example, I am using several bpmn-js modelers in Bootstrap 3 Tabs component and SVG markers are rendered inconsistently in various browsers:

- IE 11 displays SVG markers in all tabs;
- Firefox displays SVG markers in first tab ONLY;
- Markers can randomly appear/disappear on switching tabs in Chrome.

In my opinion, this behaviour is caused by duplicated markers IDs in `<defs>` sections of multiple `<svg>` elements.

Steps to reproduce:

1. Use this simple HTML file (need **pizza-collaboration.bpmn** in the same folder);
2. Click "Toggle" button in Firefox or Chrome multiple times.

```html
<html>
	<head>
	<script src="https://cdn.rawgit.com/bpmn-io/bower-bpmn-js/v0.18.4/dist/bpmn-viewer.js"></script>
	</head>
	<style type="text/css">
		.canvas {
			width: 100%;
			height: 90%;
		}
	</style>
	<body>
		<button onclick="toggleDisplay('canvas1', 'canvas2')">Toggle</button>
		<div id="canvas1" class="canvas"></div>
		<div id="canvas2" class="canvas"></div>
	</body>
	<script>
	  var viewer1 = new BpmnJS({ container: '#canvas1' });
	  var viewer2 = new BpmnJS({ container: '#canvas2' });
	
	  var xhr = new XMLHttpRequest();

	  xhr.onreadystatechange = function() {
		if (xhr.readyState === 4) {
		  viewer1.importXML(xhr.response);
		  viewer2.importXML(xhr.response);
		}
	  };

	  xhr.open('GET', 'pizza-collaboration.bpmn', true);
	  xhr.send(null);
	  
	  function toggleDisplay(id1, id2) {
	    el1 = document.getElementById(id1);
		el2 = document.getElementById(id2);
		el1.style.display = (el1.style.display == 'none') ? 'block' : 'none';
		el2.style.display = (el1.style.display == 'none') ? 'block' : 'none';
	  }
	</script>
</html>
```

**Comment by nikku** [comment]
Thanks for the bug report.

**Comment by vpanfilov** [comment]
At the moment, I use a workaround to mitigate this problem:

1. Create SVG element at the beginning of the page with all needed markers;
```html
<svg id="svgMarkerWorkaround">
  <defs>
    <marker id="sequenceflow-end" viewBox="0 0 20 20" refX="11" refY="10" markerWidth="10" markerHeight="10" orient="auto">
      <path d="M 1 5 L 11 10 L 1 15 Z" style="fill: black; stroke-width: 1px; stroke-linecap: round; stroke-dasharray: 10000, 1;">
      </path>
    </marker>
  </defs>
</svg>
```

2. Apply some CSS styles:
```css
#svgMarkerWorkaround {
  position: absolute;
  width: 1px;
  height: 1px;
}

.djs-container > svg > defs {
  display:none;
}
```

This temporarily solution seems to be working in all main browsers.

**Comment by vpanfilov** [comment]
@nikku,  you can close this issue (https://github.com/bpmn-io/bpmn-js/pull/709).
