### ISSUE TITLE
XPDL support

### ISSUE THREAD

**Issue by phackwer** [bpmn-io/bpmn-js#641]
Greetings,

Would it be possible to add the XPDL file format support? This BPMN file format is not a standard - ccouldn't find documentation for it, making the graphic unusable on WFMC Engines.

Best way probably would be writing a XPDL importer/exporter feature, so no code would have to be changed

The XPDL standard covers graphical things like size, position, icon, etc.

http://www.wfmc.org/standards/xpdl

**Comment by vkatushenok** [comment]
Hi,

We are focusing on [BPMN 2.0 standard from OMG](http://www.omg.org/spec/BPMN/2.0/) features support and not going to look into XPDL in the nearest future.

Please check out the documentation docs from the link above for more information regarding the standard (e.g. graphics support).
