### ISSUE TITLE
Feature request: official viewer and editor for Google Drive

### ISSUE THREAD

**Issue by bretdabaker** [bpmn-io/bpmn-js#642]
I am using http://demo.bpmn.io heavily to document processes in my company, we store and share our documents on Google Drive so right now we have to download the drawings as `.svg` and `.bpmn` and upload to Google Drive. Every time I want to edit the drawings I have to download the `.bpmn` and edit using the demo site. 

This is tedious but compared with doing the drawings on draw.io it's still 100 times easier and faster. It would be great if someone can turn the js app into a Google Drive app.

**Comment by nikku** [comment]
Would you like to contribute?

**Comment by naringas** [comment]
I have made a very rudimentary viewer for bpmn XML files based on (the excelent) bpmn-js
https://github.com/naringas/bpmn-drive
My plan is to add an editor eventually... All what's really needed is to integrate the drive api and the bpmn-js code (and a place to host the app)

**Comment by nikku** [comment]
Thanks for your contribution. 

Closing this issue, as you've implemented a running prototype.
