### ISSUE TITLE
Overlays not being rendered if width is below a certain value

### ISSUE THREAD

**Issue by veluria** [bpmn-io/bpmn-js#643]
I'm rendering a BPMN diagram in a div and I'm using `canvas.zoom('fit-viewport');` to make it fit to the div's size. The diagram is quite huge, but it's still readable in this state. I'm also adding multiple overlays to the diagram:

    overlays.add('SomeTask', {
        position: {
            bottom: 0,
            right: 0
        },
        html: `<a href="..." class="btn btn-danger">${count}</div>`
    });

![screenshot from 2016-12-22 11-18-10](https://cloud.githubusercontent.com/assets/1119538/21422546/707814ec-c838-11e6-9a91-fcce62c77c9b.png)

These are rendered just fine *if* I have the browser window maxed out, but not when the width is below ~1600-1700px. Is there anything I can do so they still get rendered?  

![screenshot from 2016-12-22 11-18-38](https://cloud.githubusercontent.com/assets/1119538/21422547/7078273e-c838-11e6-8a52-e6f4c76ecdac.png)

**Comment by nikku** [comment]
Configure the minimal zoom level for which overlays are being displayed via the `show.minZoom` property:

```javascript
overlays.add('foo', {
  ...,
  show: {
    minZoom: 0.1,
    maxZoom: 5.0
  }
});
```

Cf. [`Overlays` service](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/overlays/Overlays.js).

**Comment by nikku** [comment]
Nope. Could be documented [here](https://github.com/bpmn-io/bpmn-js-examples/tree/master/overlays) though.
