### ISSUE TITLE
Standard License?

### ISSUE THREAD

**Issue by chrisjlee** [bpmn-io/bpmn-js#649]
Is there any particular reason for this Custom License? Was it based on MIT?

Is there any interest to move toward a more standardized license? E.g. move toward a license that requires attribution? E.g. http://choosealicense.com/licenses/ or https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_.28original_.22BSD_License.22.29

I'm trying to get this approved for use at my company (an enterprise) i work for and they might have an issue with your license with the legal dept at my workplace.

**Comment by akuckartz** [comment]
:+1:

**Comment by nikku** [comment]
We have no plan to switch to a standard license in the near future.

Please read [this forum thread](https://forum.bpmn.io/t/license-questions/85) for an explaination _why_ we chose the non-standard license. The BSD 4 clause license is, as mentioned in the Wikipedia link "controversial" and will probably not serve our use case.

**Comment by chrisjlee** [comment]
Thanks.
