### ISSUE TITLE
Move code base to ES2015

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#652]
We should discuss whether we'd like to gradually move our code base to ES2015 to ensure future safety.

__Aspects__

* [ ] Use ES2015 import / export (https://github.com/bpmn-io/bpmn-js/issues/651)

__Related__

* [x] Migrate to min-dash (https://github.com/bpmn-io/diagram-js/issues/234)

**Comment by chrisjlee** [comment]
Has there been any thought which bundler to use for packaging bpmn?

**Comment by nikku** [comment]
Rollup has better tree-shaking. That is why I used rollup for my initial spike a few month ago. Webpack 2 should offer tree-shaking though, too, so no real preference here.

The metric for deciding should be:

* bundling speed
* bundle size
* incremental bundling / testing support?

**Comment by nikku** [comment]
If you'd like to contribute, try to get an understanding about our current setup in bpmn-js, including testing (`npm run dev`).

**Comment by chrisjlee** [comment]
Here are some more broad metrics using a test project: https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016

I'll try to dig into metrics as per this project.

**Comment by nikku** [comment]
A little experiment to switch over diagram-js (the bpmn-js core) [showed some promising results](https://gist.github.com/nikku/b903a06d1e095b93f0dd9af640cdcee8).

As of today webpack@3 with module collapsing and lodash optimization could be the way to go.

**Comment by nikku** [comment]
We'll drop lodash as our utility library all together in favor of [min-dash](https://github.com/bpmn-io/diagram-js/issues/234).

**Comment by nikku** [comment]
This will be addressed via https://github.com/bpmn-io/bpmn-js/pull/779. We don't plan to perform any other short term improvements beyond this point.
