### ISSUE TITLE
How to add additional modules when you initialize modeler  ?

### ISSUE THREAD

**Issue by Syedgit** [bpmn-io/bpmn-js#653]
I have created custom.js using bpmn-js bower bundle now for element templates i need to initiate additional modules and elementTemplates. Below additional modules (propertiesPanelModule,propertiesProviderModule,elementTemplates and moduleExtensions) are coming undefined client side. What is right approach to invoke these modules using modeler ? 

modelerCtrl.js
```

 var BpmnViewer = window.BpmnJS;
    var bpmnModeler = new BpmnViewer({
      container: '#canvas',
     keyboard: {bindTo: document},
      propertiesPanel:{
        parent: '#js-properties-panel'
      },    
    additionalModules: [
       propertiesPanelModule,
        propertiesProviderModule
    ],
    elementTemplates: templates,
    moddleExtensions: {camunda: camundaModdleDescriptor},
    });
```

bpmn-viewer-custom.js
```

var BpmnViewer = require('bpmn-js/lib/Modeler');

var camundaModdleDescriptor = require('camunda-bpmn-moddle/resources/camunda');

var templates = require('../resources/element-templates/javaClass.json');

var additionalModules = [
	require('bpmn-js-properties-panel'),

	// 1. require camunda provider instead of the bpmn one (!)
	require('bpmn-js-properties-panel/lib/provider/camunda')
];

BpmnViewer.prototype._modules = BpmnViewer.prototype._modules.concat(additionalModules);

// 2. include camunda moddle descriptor
BpmnViewer.prototype._moddleExtensions = { camunda: camundaModdleDescriptor }

module.exports = BpmnViewer
```;

**Comment by nikku** [comment]
Your code snippet should work as expected.

Is this related to [this forum post](https://forum.bpmn.io/t/how-to-add-element-template-to-diagram-using-modeler/1269/3)?

**Comment by nikku** [comment]
The pattern for extending a bundle is described in our [custom-bower-bundle example](https://github.com/bpmn-io/bpmn-js-examples/blob/master/custom-bower-bundle/index.js).
