### ISSUE TITLE
Cannot add a descriptive text on a gateway variant

### ISSUE THREAD

**Issue by gabiudrescu** [bpmn-io/bpmn-js#654]
I'm trying to map a flow with exclusive gateways but it seems when using bpmn.io I'm not able to add descriptive text on each branch of the flow:

![image](https://cloud.githubusercontent.com/assets/5156054/21976331/00bff31c-dbda-11e6-8d47-6a7b7f1a9dfc.png)

is it a bug or is it a feature?

**Comment by nikku** [comment]
Did you try to double click the flow?

**Comment by gabiudrescu** [comment]
yup, I did. it seems this functionality is not working with this extension: https://chrome.google.com/webstore/detail/bpmnio/hhikcjnalmkhinbomccdibaolelcpjli?utm_source=chrome-app-launcher-info-dialog

but I assume I either don't have the latest version or this is not supported by you.

on http://demo.bpmn.io/s/start it works with double click.

**Comment by nikku** [comment]
Thanks for investigating.
