### ISSUE TITLE
Make the viewer attachable

### ISSUE THREAD

**Issue by akkie** [bpmn-io/bpmn-js#655]
If I create an instance of the viewer then it will be automatically attached to the DOM. It would be nice if the viewer could be instantiated first and then later attached to the DOM. This would be great when using the viewer in a React context were the DOM isn't always available.

This could be made configurable. So if I set the `container` option then it will be automatically attached. Otherwise the user must attach it by itself.

The same functionality already exists for the [properties panel](https://github.com/bpmn-io/bpmn-js-properties-panel#dynamic-attachdetach).

**Comment by nikku** [comment]
Sounds like a good addition. Would you like to create a PR (including test cases) for this?

**Comment by akkie** [comment]
@nikku Sure, but I stumbled over an issue. There exists an default option for the viewer which says that the viewer should be attached to the body if no `container` option was given. So to not break backward compatibility, we should introduce an extra option, which allows to not attach the viewer automatically. Something like `attachAuomatically`. If backwards compatibility is not needed, then I would remove the default container option. Which solution would you prefer?

**Comment by nikku** [comment]
I'm not sure whether users are actually using that option in production because of missing control.

I'd rather get rid of it than working around it and mention the breaking change with our next release.

**Comment by akkie** [comment]
:+1:

**Comment by akkie** [comment]
@nikku I've created the pull request
