### ISSUE TITLE
Highlight an active task

### ISSUE THREAD

**Issue by jisqaqov** [bpmn-io/bpmn-js#657]
Good day. Could you consider a new feature to highlight an active task node in process diagram.

**Comment by nikku** [comment]
What is the _active_ task for you?

**Comment by jisqaqov** [comment]
I mean active node. If the process is still active, it has an active task node. I need to highlight it. In addition, i want to highlight completed tasks too, in gray color for instance.

**Comment by nikku** [comment]
This is a modeling tool, not a run-time platform. As such, there does not exist an _active task_ as you describe it.
