### ISSUE TITLE
Angular 2/ Typescript

### ISSUE THREAD

**Issue by jisqaqov** [bpmn-io/bpmn-js#658]
Good day. Could you move integrate library with angular 2 or typescript.

**Comment by nikku** [comment]
You are welcome to contribute and discuss this concern in our [forums](https://forum.bpmn.io/).

**Comment by chrisjlee** [comment]
@jisqaqov Someone prototyped an angular2/typescript project. It's being discussed here:  https://forum.bpmn.io/t/bpmn-js-with-angular2-and-webpack/1291
