### ISSUE TITLE
I can reopen a collapsed pool again

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/bpmn-js#659]
And all the contents is back.

If you store the content in an extension element while collapsing, you can bring it back when you expand the pool again.

**Comment by nikku** [comment]
Would be a workaround for https://github.com/camunda/camunda-modeler/issues/509, too.

**Comment by nikku** [comment]
Closing this in favor of https://github.com/bpmn-io/bpmn-js/issues/736.
