### ISSUE TITLE
startEvent/EndEvent losing position.

### ISSUE THREAD

**Issue by albertoVieiraNeto** [bpmn-io/bpmn-js#661]
I just donwloaded the Quick start and was testing when a realized that after the diagram was created and saved, when i tried to load again both startEvent and EndEvent would go to the top left corner of the screen.

this problem also occurs when using the demo: http://demo.bpmn.io/new

steps:
Create  a new diagram.
move the startEvent anywere on the screen
save
load 

note that the start event stays a the top left corner

this would not be a problem if the whole diagram also moved.

is this a bug or i missed something?

**Comment by nikku** [comment]
I cannot reproduce your findings, so... you probably missed something.

**Comment by nikku** [comment]
![image](https://cloud.githubusercontent.com/assets/58601/22732597/0339a080-edef-11e6-9869-b44762619341.png)

**Comment by albertoVieiraNeto** [comment]
very strange i tested on another 2 computers, and worked, maybe something with my development machine.

![image](https://cloud.githubusercontent.com/assets/25618042/22733815/84dd575e-edda-11e6-9fd1-38cb1968b64a.png)
