### ISSUE TITLE
Chrome print.

### ISSUE THREAD

**Issue by sabski** [bpmn-io/bpmn-js#663]
Hello, when i try to print a diagram generated by bpmn-js it appears cropped, any ideas how to resolve the issue ? 
http://imgur.com/a/V6RB6

**Comment by pedesen** [comment]
Apparently the diagram is too wide for the paper. Is using the landscape format an option? Otherwise bpmn-js provides a way to zoom out. Does that help you?

**Comment by sabski** [comment]
Yes i tried using `canvas.zoom('fit-viewport');` With the hopes that the diagram will properly fit the screen.
Sadly landscape is not an option.

**Comment by pedesen** [comment]
What you could do is to define a fixed width for the canvas container in the html like this:

```html
<div id="canvas" style="width: 400px"></div>
```

Then use the zoom function to fit the viewport and you end up like this:

![selection_075](https://cloud.githubusercontent.com/assets/2543743/23014723/68bee126-f430-11e6-90ba-e9afe8026818.png)

**Comment by pedesen** [comment]
Closed due to inactivity. If you still have questions, feel free to comment on this issue.
