### ISSUE TITLE
Getting viewbox when detached from container results in error (Firefox)

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/bpmn-js#665]
Steps to reproduce:
- Setup `modeler` example from [example](https://github.com/bpmn-io/bpmn-js-examples).
- Set `modeler` instance to global variable `m`
- Detach container and get viewbox: 
```
var child = document.getElementById('js-canvas');
document.getElementById('js-drop-zone').removeChild(child);
m.get('canvas').viewbox();
```
> "[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: http://localhost:9013/index.js :: [118]</Canvas.prototype.viewbox :: line 19808"  data: no]"
- Attach child back and get viewbox:
```
document.getElementById('js-drop-zone').appendChild(child);
m.get('canvas').viewbox();
```
> Object { x: 0, y: 0, width: 1349, height: 365, scale: 1, inner: Object, outer: Object }

_N.B. This return normal object in Chrome:_
> Object {x: 0, y: 0, width: 0, height: 0, scale: 1…}

**Comment by nikku** [comment]
We cannot easily fix this. You need to make sure to call `viewbox` when the diagram is actually detached.

As you can see, Chrome returns an empty view box (with width, height set to `0`), too.

**Comment by vkatushenok** [comment]
Here is related [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=612118).
