### ISSUE TITLE
Undo drop onto sequence flow during move results in 3 seperate undo operations

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#667]
For the user this is one operation, we should group those three operations so they can be undone at once.

![drop-onto-flow-undo](https://cloud.githubusercontent.com/assets/7633572/23357079/89df1786-fcdc-11e6-81b2-5d2f7220d812.gif)

**Comment by nikku** [comment]
Yep, to properly function, the drop on flow needs to be called within a `postExecute` callback, not inside a drag event listener [as done currently](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/behavior/DropOnFlowBehavior.js#L78).
