### ISSUE TITLE
BPMN does not render correctly Chrome - Version 57.0.2987.98 (64-bit)

### ISSUE THREAD

**Issue by rohitghatol** [bpmn-io/bpmn-js#671]
I have Observed that following page does not render correctly on Chrome Version 57.0.2987.98 (64-bit). I have also tried it on older version of Chrome where it renders fine (Chrome Version 56.0.2924.87 (64-bit)).

http://demo.bpmn.io/s/start

Can any one else confirm that BPMN 2.0 Diagrams are broken on Latest Chrome?

Chrome Version 56.0.2924.87 (64-bit).
![chrome-bpmn-01 before](https://cloud.githubusercontent.com/assets/899864/23841179/a8d02036-0768-11e7-939f-7ef13dd223b9.png)

Chrome Version 57.0.2987.98 (64-bit)
<img width="1237" alt="chrome-bpmn-02 after" src="https://cloud.githubusercontent.com/assets/899864/23841178/a8cf2f50-0768-11e7-8757-85c723240bc0.png">

**Comment by nikku** [comment]
I can confirm that. Was working on Chrome 56.

**Comment by yleider** [comment]
+1

**Comment by pkings** [comment]
I have the same problem.

**Comment by nikku** [comment]
This is a bug in [Chromium/Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=701075&q=component%3ABlink%3ESVG%20transform&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).

**Comment by nikku** [comment]
We shipped a patched version with a workaround.

**Comment by lpgera** [comment]
The workaround works for events and gateways, but the names of the lanes and participants are still not rendered correctly:

![image](https://cloud.githubusercontent.com/assets/3627084/24092254/6c09bd7a-0d4d-11e7-80c7-cdf775d0e9a9.png)

Chrome: 57.0.2987.110 (Official Build) (64-bit)
bpmn-js: v0.20.4

**Comment by vkatushenok** [comment]
@lpgera Thanks for reporting, still an issue.

**Comment by vkatushenok** [comment]
As per [this comment](https://github.com/bpmn-io/bpmn-js/issues/673#issuecomment-287470720), resizing does not work, too.

**Comment by vkatushenok** [comment]
@philippfromme LGTM
