### ISSUE TITLE
Modeler freezes when moving task with annotation outside of sub-process

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/bpmn-js#677]
What are the steps to reproduce your problem? 
1. create new diagram
2. add expanded subprocess
3. add task to that subprocess
4. add text annotation to that task, but place it out of subprocess
5. move service task out of subprocess
6. delete subprocess ---> now connection between task and annotation magically disappers (bug 1)
7. link existing text annotation to task again.
8. try to move text annotation -> JS error (bug 2)

![kapture 2017-04-11 at 10 43 50](https://cloud.githubusercontent.com/assets/2331533/24900323/cc9c8174-1ea3-11e7-896f-53c0d3492771.gif)

**Comment by nikku** [comment]
This does not look like an appropriate fix (cf. [comments on the commit](https://github.com/bpmn-io/diagram-js/commit/8094d39a24a9c757149945013ed0bdb487ca9fdd)).

It [breaks bpmn-js](https://travis-ci.org/bpmn-io/bpmn-js/builds/223124308), too.

**Comment by nikku** [comment]
Reverted and reopened.
