### ISSUE TITLE
element.changed dosent works on undo

### ISSUE THREAD

**Issue by molikh** [bpmn-io/bpmn-js#679]
i implemented undo and redo button on my page.
`    $scope.undo = function () {
        modeler.get("commandStack").undo();
    }`

   ` $scope.redo = function () {
        modeler.get("commandStack").redo();
    }`
i want to update when ever elment changes (ajax update);
so i used this for that: 
`modeler.on("element.changed", function (event) {
        var element = event.element;
        console.log(element, "Changed")
    });`
it works fine with redo **but doent works with undo**

**Comment by nikku** [comment]
Can't reproduce your changes (cf. 	fcb40bc).

Please provide us with a test case to reproduce this bug via our prepackaged bundle or some other way.
