### ISSUE TITLE
As a user, I can control the TextAnnotation size during direct editing

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#681]
...so I do not need to resize manually after a direct editing step.

### Features

__In edit mode:__

* The edit box has exactly the same dimensions (width and height) as the view box
* The text overflows the text annotation vertically: show vertical scroll bars in edit box
* The user can resize the edit box manually (width and height).
* When the user inserts a line which is longer than the edit box, the text is split to the next line. No automatic resize.
* Mouse wheel scrolling should be possible (see https://github.com/bpmn-io/bpmn-js/issues/680) 

__When exiting edit mode:__

* The view box of the text annotation changes its dimensions to the ones of the edit box (width and height).
* The text should align top left and overflow to the bottom (user can manually adjust)

### Additional Aspects

* When in edit mode: when the user inserts more lines than the height of the edit box -> automatic resize (height).
* When in edit mode: when the user resizes the edit box horizontally which results in more lines: show scroll bars in edit box

**Comment by mburke84** [comment]
Linked to [SUPPORT-3243](https://app.camunda.com/jira/browse/SUPPORT-3243)
