### ISSUE TITLE
Link document to file

### ISSUE THREAD

**Issue by proxteam** [bpmn-io/bpmn-js#682]
Hello,

I use the Win32 camunda modeler and display the bpmn using bpmn-js. I would like to create an document-element "DataObjectReference" in the Win32 camunda modeler and store the link to the real document, such that I can click on the document and the referenced document gets loaded in bpmn-js viewer.

How could I achieve this?

Best regards,
Olivier

**Comment by nikku** [comment]
Please file an issue in the [Camunda Modeler](https://github.com/camunda/camunda-modeler), if you request a Camunda Modeler feature.
