### ISSUE TITLE
Association missing between data object and text annotation

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#687]
Steps to reproduce:
* Create data object
* Create text annotation from the context pad of the data object

Problem:
* A association between data object and text annotation is missing and can't be created manually

Expected behavior
* An undirected association should be automatically created after adding the text annotation
* It should be possible to connect data objects / data stores and text annotations manually

![selection_092](https://cloud.githubusercontent.com/assets/2543743/26097035/7b7b7728-3a23-11e7-9a36-98d4f6cd4074.png)

See forum thread: https://forum.camunda.org/t/problem-with-text-annotation-of-a-data-object/3623

**Comment by nikku** [comment]
Please be more specific: Which type should the connecting edge have?

**Comment by pedesen** [comment]
Updated title and description.
