### ISSUE TITLE
Convert BPMN to SVG headless

### ISSUE THREAD

**Issue by ScalaWilliam** [bpmn-io/bpmn-js#689]
Hi I'd like to render BPMN to SVG in the command line so that it could be automated, eg:

```javascript
$ bpmn-to-svg -i file.bpmn -o file.svg
```

However, bpmn-js documentation indicates that it only works in a browser environment.

I tried using jsdom to simulate a browser environment but it's missing a layout renderer, so I get errors like this:

```
TypeError: contentNode.getBBox is not a function
    at Modeler.Viewer.saveSVG (/home/william/Projects/gitlookout/node_modules/bpmn-js/lib/Viewer.js:238:26)
```

On the other hand PhantomJS is doable but will take more time to set up an automated process.

**Comment by nikku** [comment]
You are correct with all your observations.

A few pointers:

* bpmn-js is not ment to be a BPMN to SVG conversion util
* it is not ment to work on jsdom (jsdom does not offer SVG support as far as I am concerned)
* using a headless browser would be the right approach
