### ISSUE TITLE
Global variable BpmnJS overwiriting

### ISSUE THREAD

**Issue by vangsscf** [bpmn-io/bpmn-js#692]
Seems like both Modeler and Viewer defines a global variable named BpmnJS, and when you try to import both with bower one overwrite the other. Because of that I can't use both on the same page. Could I be missing something?

**Comment by philippfromme** [comment]
As a quick fix you could do this, I guess:

```html
<script src="bower_components/bpmn-js/dist/bpmn-modeler.js"></script>
<script>
var BpmnModeler = window.BpmnJS;
</script>
<script src="bower_components/bpmn-js/dist/bpmn-viewer.js"></script>
<script>
var BpmnViewer = window.BpmnJS;
</script>
```

Haven't tested it but should work.
