### ISSUE TITLE
Property loses ID when copy-pasting a DataInputAssociation

### ISSUE THREAD

**Issue by StrohMax** [bpmn-io/bpmn-js#693]
**Reproduction steps:**

1. Create a diagram with a task
2. Create a DataObject (File or Database)
3. Connect the DataObject with the task using DataInputAssociation
4. Mark the task, the association and the DataObject with the lasso tool
5. Copy the marked objects (using Ctrl +C)
6. Paste them onto a valid position (using Ctrl + V)
7. Look at the XML-File (alternatively save the diagram and try to reopen it)

Alternatively put the elements (task, association and DataObject) into a pool/participant and copy&paste the whole pool.

**Actual result:**

- Looking at the XML, the ID of the Property is missing
- Because of that, the DataInputAssociation doesn't have a targetRef
- Because of that, the Camunda Modeler throws a warning in the log, that there's an unresolved reference <undefined>

Here is the part of my "broken" XML of the pasted elements:
`
<bpmn:task id="Task_1ukgpnz">
      <bpmn:incoming>SequenceFlow_03gaa5t</bpmn:incoming>
      <bpmn:property name="__targetRef_placeholder" />
      <bpmn:dataInputAssociation id="DataInputAssociation_1p677js">
            <bpmn:sourceRef>DataStoreReference_0msp5mm</bpmn:sourceRef>
      </bpmn:dataInputAssociation>
</bpmn:task>
`
![lost-property-id-when-copypasting](https://user-images.githubusercontent.com/29775599/27686339-a3a8dc1e-5cd2-11e7-9a64-688e4935f835.PNG)

**Comment by meyerdan** [comment]
@philippfromme do you think that this could be fixed with #686

**Comment by nikku** [comment]
This is still broken with the latest version of bpmn-js.

The reported warning is: 

```
unresolved reference <undefined>
```

Copy source XML:

```xml
<bpmn:task id="Task_0xz5wwx">
      <bpmn:property id="Property_076blo3" name="__targetRef_placeholder" />
      <bpmn:dataInputAssociation id="DataInputAssociation_0k2cizy">
        <bpmn:sourceRef>DataStoreReference_08hud7g</bpmn:sourceRef>
        <bpmn:targetRef>Property_076blo3</bpmn:targetRef>
      </bpmn:dataInputAssociation>
    </bpmn:task>
    <bpmn:dataStoreReference id="DataStoreReference_08hud7g" />
```

Pasted XML: 
```xml
    <bpmn:task id="Task_1lewsbz">
      <bpmn:property name="__targetRef_placeholder" />
      <bpmn:dataInputAssociation />
      <bpmn:dataInputAssociation id="DataInputAssociation_0iezjb6">
        <bpmn:sourceRef>DataStoreReference_0bxh935</bpmn:sourceRef>
        <bpmn:targetRef>undefined</bpmn:targetRef>
      </bpmn:dataInputAssociation>
    </bpmn:task>
    <bpmn:dataStoreReference id="DataStoreReference_0bxh935" />
```

Observation:

* DataInputAssociation is pasted twice
* The property placeholder is not correctly wired

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/cd24b27768bfd97f3cc1411ee19dd4718146ffb2.

**Comment by philippfromme** [comment]
Man, you're too fast. I was about to close this ticket.

**Comment by nikku** [comment]
🥇
