### ISSUE TITLE
I can snap existing elements on sequence flows

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#695]
Current behavior:
![bla](https://user-images.githubusercontent.com/2543743/28211985-b1f5b0a2-689f-11e7-891e-a81718e04716.gif)

**Comment by hanbar** [comment]
Please, is it possible to disable this behavior? We have diagrams with lots of connected tasks and the custommer is confused when dropping a task over a flow and suddenly this flow connects it. Thank in advance!

**Comment by nikku** [comment]
Please do not necro bump old issues. Create a new issue, explain your use case and we will get the discussions started.
