### ISSUE TITLE
Fix external label size

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#701]
Size of external label for some reason includes a lot of padding at the top

<img width="168" alt="3be3e4ef5414fea954a675c083a9e6dd" src="https://user-images.githubusercontent.com/7633572/28817667-3e5477b0-76a9-11e7-845b-40e73bf605b1.png">
<img width="162" alt="5f86e812fa878b89f0c7863677069961" src="https://user-images.githubusercontent.com/7633572/28817669-3f34bfc8-76a9-11e7-851a-bb0c6b48157f.png">

**Comment by nikku** [comment]
Not an issue anymore with recent label changes:

![image](https://user-images.githubusercontent.com/58601/45943711-bf24a300-bfe7-11e8-98a7-d6f5dd6a2561.png)
