### ISSUE TITLE
bpmn-js Error while creating new BpmnViewer()

### ISSUE THREAD

**Issue by JigneshPithva59** [bpmn-io/bpmn-js#704]
Hi,

I am trying to integrate BPMN viewer i my angular2 application.
I am referring [https://github.com/bpmn-io/bpmn-js-examples/tree/master/simple-commonjs]. 
But I am getting following error on creating BpmnViewer object. 
> var viewer = new BpmnViewer({ container: '#canvas' });

![image](https://user-images.githubusercontent.com/30984798/29252425-b64d0b80-8084-11e7-8027-4036fb3fc467.png)

As shown in image at line #23, I am creating BpmnViewer Object.
The downloaded github example is working fine, but the same code in my project is not working, I don't know what is the exact issue

Thanks,
Jignesh Pithva.

------

**Comment by nikku** [comment]
Please be more precise about what is not working and why:

* How do you integrate with AngularJS?
* How do you integrate with TypeScript?
