### ISSUE TITLE
Align open rectangle of TextAnnotation based on Association direction

### ISSUE THREAD

**Issue by jfastnacht** [bpmn-io/bpmn-js#705]
The TextAnnotation open rectangle should align with the direction of the Association.

BPMN Spec. 2.0.2, p. 69:
> A Text Annotation is an open rectangle that MUST be drawn with a solid single line (as seen in Figure 8.16).

![image](https://user-images.githubusercontent.com/6183607/29410997-5fc6a24a-8353-11e7-9b0b-a863e8526d35.png)

The "as seen in" could be interpreted as it has to be on the left-hand side following the figure, but the text leaves that open.

**Camunda-Modeler**
![image](https://user-images.githubusercontent.com/6183607/29410864-d0e34c54-8352-11e7-87a6-cc4e8c0dc3e2.png)

**MS Visio 2016**
![image](https://user-images.githubusercontent.com/6183607/29410890-e8e9a1b8-8352-11e7-9503-ad4555246cdb.png)

**Comment by nikku** [comment]
I personally don't see enough gain in the MS Visio 2016 version to justify the implementation effort.

**Comment by sbaghdadi** [comment]
+1 i would like to see this feature. A nice UI is a sign of well developed software. This effort is worth to have.

**Comment by nikku** [comment]
Properly sized text annotations don't look all that bad:

![image](https://user-images.githubusercontent.com/58601/32718209-acc9df8c-c85c-11e7-982b-e0909fafa49a.png)

Closing this issue as we have no intention to implement this any time, soo.
