### ISSUE TITLE
Use <foreignObject> SVG element for labels

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#707]
[\<foreignObject\>](https://developer.mozilla.org/en/docs/Web/SVG/Element/foreignObject) on MDN.

**Comment by nikku** [comment]
Guess this won't work due to missing IE support.

**Comment by philippfromme** [comment]
I know, it's a shame. I'm just doing a spike on this for now. We analysed the performance of bpmn-js and calculating sizes and positions of<tspan> elements is painfully slow. For IE it might be possible to use a fallback.

**Comment by nikku** [comment]
Looking forward to your results.

**Comment by philippfromme** [comment]
Using <foreignObject> for rendering only (no editing) I get the following results:

| Method | Imort Time (ms) |
| - | - |
| `<tspan>` elements | ~1663 |
| `<foreignObject>` elements | ~2944 |

Performance is much worse. 😢 

In addition to that there are the following problems:

* `<foreignObject>` element is not supported by Internet Explorer
* [canvg-browser](https://github.com/bpmn-io/canvg-browser) does not support export of `<foreignObject>` element

Conclusion:

* `<foreignObject>` element is no suitable alternative to `<tspan>` element
* `<tspan>` element does not support line breaks
* we have to stick to using individual `<tspan>` elements for text
* we should investigate possible ways of improving the performance of our algorithm 💨

**Comment by nikku** [comment]
Thanks for the comprehensive summary. Chilling results :cake:.

**Comment by philippfromme** [comment]
Gotta 😍 these `<tspan>`'s after all.
