### ISSUE TITLE
Import BPMN2 from JBPM

### ISSUE THREAD

**Issue by tejmedapally** [bpmn-io/bpmn-js#708]
I am trying to import a BPMN2 file created in JBPM.  This is a very simple process with Start, UserTask and End nodes in the workflow. I am having issues with rendering of the connections between these nodes. The sequence flow always starts and ends in the middle of the node instead of the edges. Is there a way to fix this?. See attachments for details. the BPMN2 file has a .txt extension so that i can upload the attachment. 
Code used to render the image is as below.

var xml = tempBPMN2XML; // my BPMN 2.0 xml in the attached .txt file
var viewer = new BpmnViewer({ container: '#canvas'});
viewer.importXML(xml, function (err) {
  if (err) {
	console.log('error rendering', err);
  } else {
	console.log('rendered');
	var canvas = viewer.get('canvas');
	viewer.get('canvas').zoom('fit-viewport');
  }
});

Any help will be greatly appreciated.
![workflow in jbpm](https://user-images.githubusercontent.com/19482288/29932526-260fdf98-8e3a-11e7-93bf-bf399cb6da41.png)
![workflow in bpmn io after import](https://user-images.githubusercontent.com/19482288/29932538-2a0ced98-8e3a-11e7-80c4-7a99cab59baf.png)
[org.jbpm.Simple.v1.0 (5).bpmn2.txt](https://github.com/bpmn-io/bpmn-js/files/1267690/org.jbpm.Simple.v1.0.5.bpmn2.txt)

**Comment by deysudip** [comment]
I have noticed that bpmn.js is rendering the flow correctly. Problem is with the XML itself. All the connectors have starting and ending positions in center of the element they are connected to. Any way to render it correctly with bpmn.js?

**Comment by nikku** [comment]
Yea, you could perform the adjustment for each of the elements right after import. We do that [on connection change](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/BpmnUpdater.js#L44) and you'd simply need to do it right after import, too.
