### ISSUE TITLE
Missing <defs> section in SVG generated by IE11

### ISSUE THREAD

**Issue by DetlefPeters** [bpmn-io/bpmn-js#710]
I was wondering for some time why all the arrowheads are missing in SVGs that are generated with Internet Explorer 11. By studying your `viewer.js` code, I think I have found an explanation (and a proposal for a fix):

You try to access the <defs> section of the SVG via
```
var contents = innerSVG(contentNode),
    defs = (defsNode && defsNode.outerHTML) || '';
```

But in Microsoft browsers, the property `node.outerHtml` is **not supported**, so you will always get an empty string instead of the `<defs>` section! The resulting SVG is even considered **invalid** by various applications, including e.g. Apache Batik.

Proposed fix:
Replace this declaration with
```
var contents = innerSVG(contentNode),
    defs = defsNode ? new XMLSerializer().serializeToString(defsNode).replace(/<defs[^>]*>/g,'<defs>') : '';
```
This code will work in all browsers including IE11. The replace command is called simply to eliminate the unnecessary namespace declarations that are already declared at the SVG root node.

Best regards,
  Detlef

**Comment by nikku** [comment]
Jup, [`XMLSerializer`](https://developer.mozilla.org/en-US/docs/Web/API/XMLSerializer) is web standard so I guess we could use it here.

**Comment by nikku** [comment]
But the simpler solution `<defs> + ${defsNode.innerHTML} + </defs>` would work, too right?

**Comment by DetlefPeters** [comment]
No, I don't think this will work in IE, since innerHTML is as undefined as outerHTML :-(
But a simpler solution would indeed be
`<defs> + innerSVG(defsNode} + </defs>`
using the same function call as for `contents`.

**Comment by DetlefPeters** [comment]
Is there any chance that this bug will be fixed in the next release? If I can help, let me know :-)

**Comment by DetlefPeters** [comment]
Thank you for fixing. 
Can you please update your pre-packaged bpmn-js, too? We use the bower package in our project.

Best regards,
  Detlef

**Comment by nikku** [comment]
Changes will be released with the next version of bpmn-js. You may bundle the current master branch, containing the fix, yourself. Or you wait for the release to happen :wink:.
