### ISSUE TITLE
Improve existing custom element examples

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#711]
This issue collects possible improvements to our examples and documentation, mostly collected from [our forum](https://forum.bpmn.io).

* [ ] __Example__: Show how to create popup menu entries ([ref](https://github.com/bpmn-io/bpmn-js/blob/22c628a056cf9821c4d1b60865a074548b9d9c59/lib/features/popup-menu/ReplaceMenuProvider.js#L50))

**Comment by philippfromme** [comment]
+1 This can definitely use some improvements!

**Comment by nikku** [comment]
We improved it :cake:
