### ISSUE TITLE
Properly layout on connection end re-connection

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#718]
This should avoid situations like this after the source or target of a shape got re-connected: 

![image](https://user-images.githubusercontent.com/58601/31167074-1a89a04c-a8f1-11e7-8f4a-303f8c5d02b2.png)

__Tasks__

* [ ] Layout connection while reconnecting
* [ ] Layout connection while connecting

**Comment by barmac** [comment]
Bare layout seems to be not enough, as https://github.com/bpmn-io/bpmn-js/pull/971 does not fix this. I'll tackle this issue separately.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/988.
