### ISSUE TITLE
Missing cursor when entering task name

### ISSUE THREAD

**Issue by mschoe** [bpmn-io/bpmn-js#720]
- Given
  - I'm using Cawemo with Firefox
- When
  - I double click on an element to enter a task name
- Then
  - I don't get the response that I've activated the editing mode. No cursor appears in the task

![modeling_edit_task_name_missing_cursor](https://user-images.githubusercontent.com/2777965/31656385-b6e5ff0a-b32b-11e7-8310-51a2fd820900.gif)

**Comment by nikku** [comment]
The focus on the direct editing box is lost due to their usage if bpmn-js in a React application and DOM node mounting / unmounting.

On re-mount you'd need to manually focus the opened direct-editing box again (if any is open).
