### ISSUE TITLE
bpmn-js upgrade problem 

### ISSUE THREAD

**Issue by zhujiancc** [bpmn-io/bpmn-js#724]
When you update the bpmn version  0.9.3 to 0.23.2 ,  when I  use yarn command in my project again,  many error of  diagram-js , so I lock the version to 0.9.3 .  

But now  , I find that  the lastest version change to 0.9.3 ,  the error  occur again .

So ,How should I use the bpmn-js  to avoid the version problem  in my old bpmn project

**Comment by nikku** [comment]
Please be specific a bout the error you're seeing. Please provide console errors, stack traces, ...

You're essentially upgrading from a version three years old to the current one. Some issues are to be expected.

**Comment by nikku** [comment]
`npm install bpmn-js` will now install the latest version (`0.23.x`) again.

Cf. https://github.com/bpmn-io/bpmn-js/issues/726.
