### ISSUE TITLE
Publish library distribution via [unpkg]

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#725]
Right now we expose pre-built versions of our libraries via [bower-bpmn-js](https://github.com/bpmn-io/bower-bpmn-js). As GitHub is not a CDN this requires users to `bower install` or manually download the library before actually using it (that is why we expose it pre-fetched as part of the [bpmn-js-seed](https://github.com/bpmn-io/bpmn-js-seed) project).

Bower is dead and other libraries (cf. [React](https://github.com/reactjs/react-bower)) move to bundling the distribution with the library itself and allowing users to fetch the contents via [unpkg](https://unpkg.com/#/).

I suggest that we do the same; discontinue our bower bundles and allow the library to be fetched via unpkg. 

__Tasks__

* [ ] Implement [unpkg workflow](https://unpkg.com/#workflow)
* [ ] Update examples
* [ ] Update readme
* [ ] Update `bower-bpmn-js` with deprecation notice
* [ ] Update `bpmn-js-seed`

**Comment by nikku** [comment]
@philippfromme Would be interesting to get your feedback on this.

**Comment by nikku** [comment]
Bower is effectively [discontinued](https://bower.io/blog/2017/how-to-migrate-away-from-bower/).

**Comment by philippfromme** [comment]
How should I handle this ticket? Shall I merge and than update the examples etc.?

**Comment by nikku** [comment]
Just approve it. I'll follow up with updates to our documentation.

**Comment by nikku** [comment]
Followup on reworked README: https://github.com/bpmn-io/bpmn-js/issues/760.
