### ISSUE TITLE
Missing module when compiling project with bpmn-js 0.24

### ISSUE THREAD

**Issue by Finrod927** [bpmn-io/bpmn-js#729]
I just updated bpmn-js with the latest version (0.24) in my VueJS project and the compilation failed with a missing module error :

> ERROR  Failed to compile with 1 errors
> This relative module was not found:
> * ./decode in ./node_modules/saxen/parser.js

No error with 0.23.3 version

**Comment by nikku** [comment]
This is due to the saxen dependency missing a packaged file. Should be fixed now.

Please attempt an `npm install` and report if it works for you now.

**Comment by Finrod927** [comment]
Yep, it's working now. Thanks.
