### ISSUE TITLE
message flow arrows are drawn above events

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#73]

**Comment by ISO50** [comment]
This does not only apply to message flows.
Actually we need to to correct all types of end markers. And we need also different end markers for different target types (task, event, gateway) as you can see on the following screenshot.
![endmarker](https://cloud.githubusercontent.com/assets/6464494/5662617/fad651d8-973b-11e4-8426-856e2c7f3f30.png)

**Comment by nikku** [comment]
We did a number of fixes here with the last releases. Closing this for now.
