### ISSUE TITLE
Custom Fields - dropdown's description not shown

### ISSUE THREAD

**Issue by ludoo0d0a** [bpmn-io/bpmn-js#730]
Open electron modeler or embed bpmn modeler in a web page (same result)
Use Custom Fields.

### Expected Behavior
In Custom Fields panel, all descriptions should be seen.

### Actual Behavior
Fields of type Dropdown don't display the related description.

**Comment by nikku** [comment]
How is your bug report related to bpmn-js?

**Comment by ludoo0d0a** [comment]
I speak about the Properties Panel of the bpmn-js modeler.
https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension

Look at this screenshot:
![bug dropdown desc](https://user-images.githubusercontent.com/294090/33368897-3ed0cfb0-d4f3-11e7-8724-3796fcd7707c.PNG)

Description is set in json config file, but never displayed !

**Comment by nikku** [comment]
Closing this in favor of https://github.com/bpmn-io/bpmn-js-properties-panel/issues/247.
