### ISSUE TITLE
Contributing-Request / RendererUtil

### ISSUE THREAD

**Issue by felixlinker** [bpmn-io/bpmn-js#731]
Hi there,

would you be okay with me moving all functions starting from [line 1811 in the Renderer](https://github.com/bpmn-io/bpmn-js/blob/master/lib/draw/BpmnRenderer.js#L1811) in a new module `lib/util/RendererUtil.js` analogously to `ModelUtil`, etc.? Then other people (in this case me 😉) could use them without copying them.

I'd just like to ask before making myself any work.

Kind regards
Felix

**Comment by nikku** [comment]
Makes sense, go ahead.

A few hints:

* Add test cases for `RenderUtil` existing; otherwise we'll move / remove it any time without noticing

* Import the utilities from `RenderUtil` like this:

    ```javascript
    var foo = require('./RenderUtil').foo;
    ```
