### ISSUE TITLE
bpmn-js crashes when dragging a connection endpoint over and existing toolbar

### ISSUE THREAD

**Issue by eucaos** [bpmn-io/bpmn-js#734]
### Expected Behavior

BpmnJD designer doesn't crash when dragging a connection endpoint over and existing toolbar

### Actual Behavior

BpmnJD designer crashes when dragging a connection endpoint over and existing toolbar

### Steps to reproduce the Behavior

1. Add a node on the designer surface
2. Add a second node and move it under a toolbar button
3. Create a connection between first and second node by releasing the endpoint over the second node exactly on the toolbar button.
4. BpmnJS crashes and you can’t use the editor anymore ( see the attached animated screenshot)

![bpmnjscrash](https://user-images.githubusercontent.com/6533163/33596742-7c4fa238-d9a5-11e7-9593-d23f021a68fa.gif)

**Comment by nikku** [comment]
This is adressed via https://github.com/bpmn-io/diagram-js/commit/f199f0be414b912cd138ef54f5940a820083571b and will be fixed once we release and upgrade the downstream project. Thanks for reporting.

**Comment by nikku** [comment]
Depends on diagram-js release with the fix.
