### ISSUE TITLE
Reposition gateway labels to wherever free space is

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#738]
Users would like to change the default gateway label position to be [always on top](https://forum.camunda.org/t/labels-on-gateways-should-default-to-above/3302/7).

I'd rather adjust label positions to automatically move to the free space around the gateway: 

![foo](https://user-images.githubusercontent.com/58601/33800332-233d677e-dd3e-11e7-9679-fcb4499649fa.gif)

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/5761e01ffed68b4c7f225994da6c950409b47da4.
