### ISSUE TITLE
Text Annotations and bpmn:Association rendering

### ISSUE THREAD

**Issue by fedd** [bpmn-io/bpmn-js#749]
### Expected Behavior
BPMN.io BPMN viewer and editor should be able to open models with text annotations like this: 
![assosiation](https://user-images.githubusercontent.com/311934/34867291-9ea21e70-f790-11e7-9c53-93d3a8c90a6b.png)
This was made in Activiti editor, but the text annotation is a useful feature to support in BPMN.io too.

### Actual Behavior
The editor and viewer fail to open such files, with error like this:

(taken from https://demo.bpmn.io/new)
i@https://demo.bpmn.io/bpmn/app.min.js:15:16190 require<[303]</t.exports.createLine@https://demo.bpmn.io/bpmn/app.min.js:15:16471 D@https://demo.bpmn.io/bpmn/app.min.js:2:26879 bpmn:Association@https://demo.bpmn.io/bpmn/app.min.js:3:7438 require<[27]</i.prototype.drawShape@https://demo.bpmn.io/bpmn/app.min.js:3:12761 i/<@https://demo.bpmn.io/bpmn/app.min.js:10:13168 o@https://demo.bpmn.io/bpmn/app.min.js:10:7647 require<[151]</i.prototype._invokeListener@https://demo.bpmn.io/bpmn/app.min.js:10:9350 require<[151]</i.prototype._invokeListeners@https://demo.bpmn.io/bpmn/app.min.js:10:9256 require<[151]</i.prototype.fire@https://demo.bpmn.io/bpmn/app.min.js:10:8927 require<[152]</i.prototype.drawShape@https://demo.bpmn.io/bpmn/app.min.js:10:11565 require<[152]</i.prototype.update@https://demo.bpmn.io/bpmn/app.min.js:10:12002 require<[148]</s.prototype._addElement@https://demo.bpmn.io/bpmn/app.min.js:10:1894 require<[148]</s.prototype.addShape@https://demo.bpmn.io/bpmn/app.min.js:10:1994 require<[115]</a.prototype.add@https://demo.bpmn.io/bpmn/app.min.js:7:28129 element@https://demo.bpmn.io/bpmn/app.min.js:8:2093 l@https://demo.bpmn.io/bpmn/app.min.js:7:30510 h@https://demo.bpmn.io/bpmn/app.min.js:7:30592 j@https://demo.bpmn.io/bpmn/app.min.js:8:114 M/</<@https://demo.bpmn.io/bpmn/app.min.js:8:195 x@https://demo.bpmn.io/bpmn/app.min.js:7:31798 b@https://demo.bpmn.io/bpmn/app.min.js:7:31764 i/<@https://demo.bpmn.io/bpmn/app.min.js:8:2023 i@https://demo.bpmn.io/bpmn/app.min.js:8:2011 require<[24]</o.prototype.importDefinitions@https://demo.bpmn.io/bpmn/app.min.js:2:20739 require<[24]</o.prototype.importXML/<@https://demo.bpmn.io/bpmn/app.min.js:2:19743 require<[482]</b.prototype.fromXML/<@https://demo.bpmn.io/bpmn/app.min.js:18:11028 i/<@https://demo.bpmn.io/bpmn/app.min.js:16:29837

Looks like the text annotation "bpmn:Association" module didn't prepare the dots for a renderer to connect.

### Steps to reproduce the Behavior
Open https://demo.bpmn.io/new and try to load this file:

[assocTest.bpmn20.xml.txt](https://github.com/bpmn-io/bpmn-js/files/1625467/assocTest.bpmn20.xml.txt)

**Comment by nikku** [comment]
The demo clearly shows this warning: 

```
* multiple DI elements defined for <bpmn:Association id="sid-7F2CDE56-DDD6-4218-8314-DC732A52B757" />

Cannot read property '0' of undefined

```

**Comment by nikku** [comment]
Looking closer in the diagram we see that it defines two graphical representations for the Association:

* Bounds (a rectangle), which is _WRONG_
* Waypoints (the line), which is _CORRECT_

If you correct the diagram export by removing the following lines in the XML the diagram opens correctly.

Summing up: The diagram export is broken; this is not an issue with bpmn-js.

**Comment by fedd** [comment]
Thanks, sorry, didn't notice that. Seems like activiti problem
