### ISSUE TITLE
Fire an event when an element is clicked with the right mouse button

### ISSUE THREAD

**Issue by bort2012** [bpmn-io/bpmn-js#750]
Currently there is no event fired when an element is clicked with the right mouse button.

**It would be great to have the ability to listen to right click events on elements.**

I have implemented this feature locally by adding the 'element.contextmenu' event to the InteractionEvents of diagram-js.

May I create a pull request in the diagram-js repository?

**Comment by nikku** [comment]
What prevents you from listening to right clicks?

**Comment by bort2012** [comment]
Thank you for your fast reply.

I am listening to events with the eventBus. (modeler.get('eventBus'))
For example: 
eventBus.on('shape.added', (event) => {
}

But I did not find an event in the eventBus that gets fired when I right click on an element.

**Comment by nikku** [comment]
What about `eventBus.on('element.click', ...)`?

**Comment by bort2012** [comment]
I tried this some time ago but this does only fire on the left click. Maybe I was using it the wrong way.

But I think the right click is ignored by diagram-js. In the lib/features/InteractionEvents.js on line 57. There is the following code:

```
// only react on left mouse button interactions
// for interaction events
if (!isPrimaryButton(event)) {
  return;
}
```

**Comment by nikku** [comment]
You are correct. The line you've posted effectively disables interaction events on right click.

A `contextmenu` event sounds like a good addition to add.

**Comment by bort2012** [comment]
OK. So may I create a pull request to add this?

**Comment by nikku** [comment]
Yes, we appreciate a pull request to expose this event.

Make sure to read through our [contributing guide](https://github.com/bpmn-io/diagram-js/blob/master/CONTRIBUTING.md#creating-a-pull-request), add relevant test cases etc.

**Comment by bort2012** [comment]
I created a pull request. 

Locally the "npm run all" runs all tests without error. 

But the Travis-CI fails. I can not see any error message in the log. In the log I can see that it starts to download something and then suddenly stops.

What am I doing wrong?

**Comment by nikku** [comment]
This may be due to a network outage. We'll look into the PR in the next days. Thanks!

**Comment by bort2012** [comment]
OK great, thank you!
