### ISSUE TITLE
Connections to document nodes remain visible when collapsing subprocess

### ISSUE THREAD

**Issue by FlexiGit** [bpmn-io/bpmn-js#752]
### Expected Behavior
When collapsing a subprocess all elements in the subprocess should be hidden

### Actual Behavior
Connections to documents (MessageFlow connection) stay visible

### Steps to reproduce the Behavior
Create expanded subprocess from palette.
Create task inside subprocess
Create document inside subprocess
Connect task with document
Switch subprocess to collapsed

**Comment by nikku** [comment]
As per BPMN spec, these should not be hidden. 

In fact, they should dock with the sub-process:

![image](https://user-images.githubusercontent.com/58601/35153833-56f24170-fd28-11e7-96a7-7273a30c254c.png)

**Comment by FlexiGit** [comment]
You are absolutely right. Unfortunately in the above described use case both artifacts are inside the subprocess (see Doc1). Out of curiosity I tried your use case, too (see Doc2).

![2018-01-19 15_03_51-requirements](https://user-images.githubusercontent.com/7802682/35154380-5dcbce38-fd2a-11e7-9007-80f609b7e433.png)
![2018-01-19 15_04_27-requirements](https://user-images.githubusercontent.com/7802682/35154381-5de5c77a-fd2a-11e7-8b79-c07fb18dd2b1.png)

**Comment by nikku** [comment]
We appreciate pull requests to address this issue.

**Comment by volkergersabeck** [comment]
Closing this issue since collapsing subprocesses is no more supported
