### ISSUE TITLE
Decrease the size of the BPMN-js logo when rendering from 

### ISSUE THREAD

**Issue by StephenOTT** [bpmn-io/bpmn-js#755]
when loading the js from bower-bpmn-js the default standalone example load uses a very large BPMN-js logo.  

Would be great to decrease this byt 50-75 percent..

![screen shot 2018-01-28 at 3 17 48 pm](https://user-images.githubusercontent.com/1994838/35486642-eb3a7aba-043e-11e8-9567-e1a3fbffb43f.png)

**Comment by nikku** [comment]
By very large you mean _standard size_?

**Comment by philippfromme** [comment]
It should always be the same size.

**Comment by StephenOTT** [comment]
Yes it's the same size. But you don't think it's a little large for smaller real estate?

**Comment by nikku** [comment]
There is a number of other approaches we could take, such as making it slightly opaque (and thus less obtrusive). We won't tackle this issue any time soon.
