### ISSUE TITLE
Coloring element create di="[object Object]" attrubute in source xml

### ISSUE THREAD

**Issue by romero83** [bpmn-io/bpmn-js#756]
Hi!

I am using bpmn-js version 0.26.4.
When I coloring an element by calling:
```
var elementsToColor = modelerInstance.get('selection')._selectedElements;
if (elementsToColor.length > 0) {
       modelerInstance.get('modeling').setColor(elementsToColor, {
           stroke: '#fb8c00',
           fill: '#ffe0b2'
       });
}
```
It creates di="[object Object]" attrubute at the colored element.

**Expected Behavior**
Should not generate di="[object Object]" on element in the source xml.

**Actual Behavior**
On the selected elem,  di="[object Object]" attrbute created when colored in the source xml.

Steps to reproduce the Behavior:
1. Create a new BPMN
2. Select the start event
3. Color it
4. Check xml source:
`<bpmn2:startEvent id="StartEvent_1" di="[object Object]" />`

**Comment by nikku** [comment]
I cannot reproduce the behavior you're reporting using our [demo](https://demo.bpmn.io/new).

The color feature is [extensively tested](https://github.com/bpmn-io/bpmn-js/blob/master/test/spec/features/modeling/SetColorSpec.js). Add a test that reproduces the issue you're seeing and I'm happy to reopen this issue.

**Comment by romero83** [comment]
Ok.
Here is the test case. I made it to pass because now it contains di="[object Object]".
```
'use strict';

var Modeler = require('lib/Modeler');

var TestContainer = require('mocha-test-container-support');

describe('Coloring element create di="[object Object]" attrubute in source xml #756', function() {

  var container;

  beforeEach(function() {
    container = TestContainer.get(this);
  });


  function createModeler(xml, done) {
    var modeler = new Modeler({ container: container });

    modeler.importXML(xml, function(err, warnings) {
      done(err, warnings, modeler);
    });
  }

    it('should fail because of contained di="[object Object]" attribute', function(done) {

      var xml = require('../fixtures/bpmn/simple.bpmn');

      createModeler(xml, function(err, warnings, modeler) {

        // given
        var modeling = modeler.get('modeling'),
            elementRegistry = modeler.get('elementRegistry'),
	    taskShape = elementRegistry.get('StartEvent_2');
      
	// set color for StartEvent_2
	modeling.setColor(taskShape, { fill: 'FUCHSIA', stroke: 'YELLOW' });

        // test saving process to get XML
        modeler.saveXML({ format: true }, function(err, xml) {
	  expect(xml).to.contain('<bpmn2:startEvent id="StartEvent_2" name="Start" di="[object Object]">'); // It passed but should fail !!!
          done();
        });
      });
  });
});
```

**Comment by nikku** [comment]
Thanks for the test case. I'll have a look.
