### ISSUE TITLE
Rework getting started using new pre-packaged distributions

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#760]
Allow users to get started with bpmn-js more easily:

* provide example that is a plain HTML document / links relevant unpkg(ed) pre-built resources
* think of discontinuing bpmn-js-seed
* update `README` with applied changes

This is a followup to #725 

__Tasks__

* [x] Update examples (https://github.com/bpmn-io/bpmn-js-examples/compare/master...discontinue-bower)
* [x] Update README (https://github.com/bpmn-io/bpmn-js/compare/master...discontinue-bower)
* [x] Update walkthrough (https://github.com/bpmn-io/bpmn.io/compare/live...master)
* [x] Update bower-bpmn-js (https://github.com/bpmn-io/bower-bpmn-js/compare/master...discontinue-bower)
* [x] Discontinue bpmn-js-seed / bower-bpmn-js (don't build anymore) (https://github.com/bpmn-io/bpmn-js/commit/68bfa10351a1d9b05f1c372b4e18da13c428b588)
* [x] Automatically update bpmn-js-examples during release (https://github.com/bpmn-io/bpmn-js/commit/37d70a19ca2eca859c3c508d221219ad27524968)

**Comment by nikku** [comment]
Ready to review.

**Comment by philippfromme** [comment]
Looks good to me. Shall I merge the changes and release bpmn-js?

**Comment by nikku** [comment]
I'll do it! <3

**Comment by nikku** [comment]
Merged and released as bpmn-js@0.27.0.
