### ISSUE TITLE
wrong properties shown when click blank diagram

### ISSUE THREAD

**Issue by elvisqi** [bpmn-io/bpmn-js#762]
test case:
[test.bpmn.txt](https://github.com/bpmn-io/bpmn-js/files/1702282/test.bpmn.txt)

- "bpmn-js": "^0.25.2",
- "bpmn-js-cli": "^0.15.0",
- "bpmn-js-properties-panel": "^0.19.1",
- "camunda-bpmn-moddle": "^0.13.0",
- "diagram-js": "^0.27.2",
- "jquery": "^3.2.1",

### Expected Behavior
click blank diagram will show process properties

### Actual Behavior
shown collaboration properties

![snip20180207_6](https://user-images.githubusercontent.com/3584916/35906682-73513e54-0c26-11e8-9281-6d78030a145e.png)

**Comment by nikku** [comment]
This is correct behavior.

The diagram you see is a collaboration diagram with one process in it. For this reason the root is the Collaboration, not the Process.

Click the Participant and you'll see both the Participant as well as the Process properties.
