### ISSUE TITLE
Task label text gets lost when using auto placement

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#764]
### Expected Behavior

When creating tasks and labeling them immediately, I would expect the label text to get saved when appending another activity using auto placement.

### Actual Behavior

The label text gets lost, when using auto placement:

![auto-placement](https://user-images.githubusercontent.com/2543743/36257294-92f36ec2-1256-11e8-991b-c14d9e516a19.gif)

### Steps to reproduce the Behavior

* Create a task
* Label it in the already open text area
* Append another activity using auto placement

**Comment by nikku** [comment]
Released as `v0.27.4`.
