### ISSUE TITLE
[Question] Read activiti custom properties

### ISSUE THREAD

**Issue by exejutable** [bpmn-io/bpmn-js#767]
Hey guys, is possible read the activiti custom properties?

activity bpmn modeler: https://www.activiti.org/

I see in the examples the camunda extension also how to extend bpmn properties, but activity has is custom xml tags.

**Comment by nikku** [comment]
You may read any property you like. We don't have support for custom controls built in though.

**Comment by exejutable** [comment]
But i can't see it in the properties panel

**Comment by nikku** [comment]
Correct. That is what I meant with:

>  We don't have support for custom controls built in though.
