### ISSUE TITLE
As a user, I want the 'center' button to go to diagram center instead of modeling canvas origin

### ISSUE THREAD

**Issue by CatalinaMoisuc** [bpmn-io/bpmn-js#771]
The user started modelling the diagram away from the origin and the center tool does not focus the view on the center of the diagram.​

**Note**: @nikku knows how to reproduce it.

**Comment by nikku** [comment]
As a fix in https://github.com/bpmn-io/diagram-js/commit/f5b477e845937ad98e7744e6e1724a90c71cf646 we make sure that the cached viewbox is being reset on element addition, removal and change.
