### ISSUE TITLE
Show Name of Message element

### ISSUE THREAD

**Issue by businka** [bpmn-io/bpmn-js#777]
__Is your feature request related to a problem? Please describe.__

Currently, names of message elements on message flows are not rendered

Given [this example diagram](https://github.com/bpmn-io/bpmn-js/files/1860134/Delivery.zip)

![](https://user-images.githubusercontent.com/3998764/38089798-4f00974c-3369-11e8-8f66-6c733a5354d9.png)

__Describe the solution you'd like__

Render the name of the message elements below. Consider that message flows can have labels itself.

__Describe alternatives you've considered__

Start working on #447 beforehand to create a better handling between message names and message flow labels.

**Comment by barmac** [comment]
Related to https://github.com/bpmn-io/bpmn-js/issues/447

**Comment by pinussilvestrus** [comment]
Hint: the message got rendered [at this place](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/draw/BpmnRenderer.js#L1457).

**Comment by christyjacob4** [comment]
Hi, Can i take this up ?

**Comment by pinussilvestrus** [comment]
Yes, feel free to open a PR and ask for help if you stuck 👍

**Comment by christyjacob4** [comment]
@pinussilvestrus Can you share some tips to navigate the folder structure of the repo? I'm trying to identify where I can narrow the issue down to

**Comment by pinussilvestrus** [comment]
I already gave a first hint of where to start: https://github.com/bpmn-io/bpmn-js/issues/777#issuecomment-697279882

Basically, the project is divided into features and core modules. Every module will then be put together inside the overall Modeler/Viewer class. This is a task of rendering, I guess a good start would be to look inside the `draw`, furthermore the BpmnRenderer.

**Comment by christyjacob4** [comment]
Thanks a lot @pinussilvestrus  that helps

**Comment by christyjacob4** [comment]
I have gone through the setup process here (https://github.com/bpmn-io/bpmn-js/blob/develop/.github/CONTRIBUTING.md) and have set up the repo successfully.

Where can i find the steps to build the code with my code changes and see it in action in a browser ? 
Thanks

**Comment by pinussilvestrus** [comment]
Executing `npm run dev` will execute test suites which also renders Modelers into the browser. What we mostly do is to make this [test case](https://github.com/bpmn-io/bpmn-js/blob/develop/test/spec/ModelerSpec.js#L48) unique and then run it to see a modeler and manually test new behavior.

```js
it.only('....')
```

**Comment by pinussilvestrus** [comment]
Not if you use the `only` keyword

```js
it.only('should import simple process', function() {
    var xml = require('../fixtures/bpmn/simple.bpmn');
    return createModeler(xml).then(function(result) {

      expect(result.error).not.to.exist;

      result.modeler.get('editorActions').trigger('selectElements');
    });
});
```

**Comment by christyjacob4** [comment]
Okay thank you . Let me try that 👍

**Comment by christyjacob4** [comment]
Okay everything is working now.. 
But how do I play around with the UI? everything happens so fast with the test cases. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/20852629/94674136-5cccae80-0335-11eb-99ad-a72efde4e872.gif)

**Comment by pinussilvestrus** [comment]
Did you try to click on "Debug"?

**Comment by christyjacob4** [comment]
@pinussilvestrus  Yeap!! It works now 😊

**Comment by christyjacob4** [comment]
![Screenshot 2020-10-01 at 10 07 37 AM](https://user-images.githubusercontent.com/20852629/94768769-f0ea5480-03cd-11eb-9012-884ea8dbb762.png)

I have the UI rendered and I'm trying to create a scenario as depicted in the issue. How do I add a message b/w two components?

**Comment by christyjacob4** [comment]
@pinussilvestrus  

I noticed that setting the semantic.name attribute automatically renders a label as you can see in the attached image. 
1. How is that label getting rendered? 
2. Is that the correct label to be displayed as part of this issue? If yes where can i find the code to adjust its x and y coordinates? 
3. If No, should I be using the `renderEmbeddedLabel()` function to render the label

**Comment by pinussilvestrus** [comment]
Short answer: Yes Message can have labels (= names) and it's part of this issue to render them. Inside the Renderer, you'll find a method to render external labels. The [LabelUtil](https://github.com/bpmn-io/bpmn-js/blob/2dd1e1330509d3f6db7939ad8ae22b75144396bd/lib/util/LabelUtil.js) has some interesting methods which generate information about labels related to different element types.

You also have to consider that messages also belong to message flows, which can also have a label. Two labels (one for the message and one for the flow) in that case might not be necessary.

**Comment by christyjacob4** [comment]
Can you help me understand how the label is printed in the image i shared above just by setting the `semantic.name` property ? because I couldn't find a renderLabel function within `'bpmn:MessageFlow'` function

**Comment by christyjacob4** [comment]
What I find confusing is that the code already supports rendering message labels as long as it has attributes `messageRef`  and `name` . So that makes me ask , where do I need to add these attributes to the Messages?

**Comment by pinussilvestrus** [comment]
> the code already supports rendering message labels

Can you post a screenshot that shows a message object with a label in the Modeler?

**Comment by christyjacob4** [comment]
![Screenshot 2020-10-01 at 4 39 20 PM](https://user-images.githubusercontent.com/20852629/94802095-a932ef80-0404-11eb-9ff6-e1d79d75673b.png)

is this what you meant @pinussilvestrus

**Comment by pinussilvestrus** [comment]
Does this label come from a `bpmn:MessageFlow` or a `bpmn:Message` element? The task of this issue is to render labels from `bpmn:Message` elements.

**Comment by christyjacob4** [comment]
This label comes from a `bpmn:MessageFlow` element 

by `bpmn:Message` are you referring to https://github.com/bpmn-io/bpmn-js/blob/2dd1e1330509d3f6db7939ad8ae22b75144396bd/lib/draw/BpmnRenderer.js#L560

**Comment by pinussilvestrus** [comment]
No, I mean `bpmn:Message` elements. Please make sure you are familiar with the BPMN 2.0 specification and also checked out the example diagram in the issue description.

**Comment by pinussilvestrus** [comment]
To give you kind of a hint. The message element is rendered in [the handler of the `bpmn:MessageFlow`](https://github.com/bpmn-io/bpmn-js/blob/2dd1e1330509d3f6db7939ad8ae22b75144396bd/lib/draw/BpmnRenderer.js#L1457). The issue here is that currently the label is only rendered if a `bpmn:MessageFlow` has a name, but the name of a referenced `bpmn:Message` element not got considered.

**Comment by christyjacob4** [comment]
Im referring this to get a better understanding of bpmn specs https://camunda.com/bpmn/reference/

![Screenshot 2020-10-01 at 5 09 49 PM](https://user-images.githubusercontent.com/20852629/94804810-121c6680-0409-11eb-92d6-34b37a2ab9cd.png)
Okay so if `bpmn:MessageFlow` does not have a name, I need to check if either of the `bpmn:Message` elements (highlighted in red in the image) that it connects, has a name ("Message1 in this case") and somehow pass that information to `bpmn:MessageFlow` so that it gets rendered [here](https://github.com/bpmn-io/bpmn-js/blob/2dd1e1330509d3f6db7939ad8ae22b75144396bd/lib/draw/BpmnRenderer.js#L1457)?  

Also if there are other channels we can connect it would be better

**Comment by christyjacob4** [comment]
@pinussilvestrus Can you let me know if my understanding is correct?

**Comment by pinussilvestrus** [comment]
Looking to connected message elements is a good idea. The place you linked might not be the correct place, since labels are not rendered exactly there.

I gave you some hints where label information got handled. My proposal: try to create a first solution, create a PR and then let's discuss around it.
