### ISSUE TITLE
Update conditional start event on parent change

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#778]
On parent change updates are necessary:

* event subprocess -> root - `variableEvent` property must be deleted

![foobar](https://user-images.githubusercontent.com/7633572/38242868-2f96ad94-3736-11e8-9cc7-254317134c2b.gif)

**Comment by nikku** [comment]
This must be implemented in [`camunda-bpmn-moddle`](https://github.com/camunda/camunda-bpmn-moddle).

**Comment by barmac** [comment]
The `camunda:initiator` removal applies to all start events. Let's have it in a separate issue.

**Comment by barmac** [comment]
This belongs to camunda/camunda-modeler, but cannot be transferred because of different organizations.
