### ISSUE TITLE
No snapping to data object on initial connect

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js#782]
### Expected Behavior

When I create a connection with a data object as target, I would expect that it snaps to it.

### Actual Behavior

There is no snapping, except when reconnecting it.

![data-objects](https://user-images.githubusercontent.com/2543743/38488109-a16fb504-3be2-11e8-91f1-af98f66e8a34.gif)

### Steps to reproduce the Behavior

1. Create a data object and a start event
2. Try to to connect the start event to the data object

**Comment by nikku** [comment]
We accept pull requests to address this issue.
