### ISSUE TITLE
camunda:autoStoreVariables is an unknown attribute in 1.2.0

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/bpmn-js#784]
This diagram loads without warnings with 1.1.1 and older versions, but not in 1.2.0, the attribute camunda:autoStoreVariables is unknown:

```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_0dps87n" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="1.12.0">
  <bpmn:process id="Process_1" isExecutable="true">
    <bpmn:scriptTask id="Task_12uw55t" camunda:autoStoreVariables="true" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">
      <bpmndi:BPMNShape id="ScriptTask_178ih84_di" bpmnElement="Task_12uw55t">
        <dc:Bounds x="146" y="69" width="100" height="80" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
``` 

What has changed now with `camunda:autoStoreVariables` ?

**Comment by nikku** [comment]
How is `camunda:autoStoreVariables` a valid variable in the `camunda` namespace?

**Comment by nikku** [comment]
We've tightened our validation of invalid attributes with `bpmn-moddle@5.1.0`: https://github.com/bpmn-io/bpmn-moddle/blob/master/CHANGELOG.md#510. 

`camunda:autoStoreVariables` is not known in the `camunda` namespace. The background to this change is the fact that the `camunda` namespace is regularly used to monkey patch extension attributes into the XML document, This on the other hand leads to confusing behavior on save -> import roundtrips (cf. [this forum thread](https://forum.bpmn.io/t/storing-meta-data-for-camunda-inputparameters/2226) for details and a proper way to extend things).
