### ISSUE TITLE
importXML method throws rootElement already set error // Missing override in BpmnImporter.add

### ISSUE THREAD

**Issue by MaxStroh** [bpmn-io/bpmn-js#787]
### Expected Behavior
- XMLs can be imported correctly

### Actual Behavior
- When importing any diagram, we sometimes get an error. The Canvas module throws that the rootElement is already set.
- I found out, that in the BpmnImporter add-method the method _canvas.setRootElement is called without an override = true as parameter. Is this behaviour correct?
- If we check the element, the BpmnImporter want to add, it's correctly our Process_1 root element. The current rootElement set is an empty __implicitRoot object and without override = true this __implicitRoot won't be overridden when the BpmnImporter wants to add it and the importXml method cancels with an error.

### Thrown error
Error: rootElement already set, need to specify override
Stack trace:
Canvas.prototype.setRootElement@webpack://VBCP.%5Bname%5D/./node_modules/bpmn-js/node_modules/diagram-js/lib/core/Canvas.js?:432:13
BpmnImporter.prototype.add@webpack://VBCP.%5Bname%5D/./node_modules/bpmn-js/lib/import/BpmnImporter.js?:87:5
root@webpack://VBCP.%5Bname%5D/./node_modules/bpmn-js/lib/import/Importer.js?:35:16
visitRoot@webpack://VBCP.%5Bname%5D/./node_modules/bpmn-js/lib/import/BpmnTreeWalker.js?:78:12
handleDefinitions@webpack://VBCP.%5Bname%5D/./node_modules/bpmn-js/lib/import/BpmnTreeWalker.js?:209:15
render@webpack://VBCP.%5Bname%5D/./node_modules/bpmn-js/lib/import/Importer.js?:51:5
importBpmnDiagram@webpack://VBCP.%5Bname%5D/./node_modules/bpmn-js/lib/import/Importer.js?:61:5
Viewer.prototype.importDefinitions@webpack://VBCP.%5Bname%5D/./node_modules/bpmn-js/lib/Viewer.js?:315:10
Viewer.prototype.importXML/<@webpack://VBCP.%5Bname%5D/./node_modules/bpmn-js/lib/Viewer.js?:180:5
XMLReader.prototype.fromXML/<@webpack://VBCP.%5Bname%5D/./node_modules/moddle-xml/lib/reader.js?:825:5
baseDelay/<@webpack://VBCP.%5Bname%5D/./node_modules/lodash/internal/baseDelay.js?:18:34

### Steps to reproduce the Behavior
- Bug/Error is not always reproducable, if so it is simply thrown when opening and importing some diagram

**Comment by MaxStroh** [comment]
In our case a simple override = true fix the issue, but I'm not sure if this is expected behaviour, that no override is set at this point?!

Our fix:
BpmnImporter.prototype.add = function(semantic, parentElement) {

  var di = semantic.di,
      element,
      translate = this._translate,
      hidden;

  var parentIndex;

  // ROOT ELEMENT
  // handle the special case that we deal with a
  // invisible root element (process or collaboration)
  if (is(di, 'bpmndi:BPMNPlane')) {

    // add a virtual element (not being drawn)
    element = this._elementFactory.createRoot(elementData(semantic));

    this._canvas.setRootElement(element, **true** );
}

**Comment by nikku** [comment]
Please provide a test case that allows us to reproduce this issue.

I'm sure that the test case, once you've provided it, reveals an issue with the way you use bpmn-js.

**Comment by nikku** [comment]
Happy to re-open this issue if you provide us with a test case that reproduces an actual toolkit bug.

**Comment by MaxStroh** [comment]
Hey guys,

While building a test case to show what our problem is, I saw the mistake in our code.
Because of splitting our code into modules the importXML method is in a completely other module then the calls of the getRootElement methods or the accesses to the diagram elements. In our case, the diagram wasn't completely imported before the first time another module tried to get the rootElement. 

But because of the modularity of our probject we were not able to put all the following code into this one callback of the importXML method. This would have crashed our entire architecture.

So today I found out, that there is an "import.done" event on which we can listen and wait for to ensure, that all elements are available when trying to get them. Is it recommendable to use this event? Or would you advise against listening on this event (maybe because it should be an internal used event only)? An alternative could maybe be to refactor the importXML function as an async function so we can await the result?

And a question about the events: Do you have any documentations where we can read about all or at least the most relevant / useful events thrown by the bpmn-js lib? I think this would be veeeery very helpful (not only for us)!!! :) :+1:

So thank you for your help and time! I hope you can give us a few tips about best practices for this case :)

Greetings,
Max

**Comment by ptdunlap** [comment]
For what it's worth I was able to reproduce this error by creating the modeler and then trying to drag an item from the palette to the canvas before the call to "importXML" is made. When you try to drag an item from the palette to the canvas the canvas turns a light shade of red indicating that it is not allowed. The error occurs when you then try to load a BPMN document by making the call to "importXML".

**Comment by nikku** [comment]
The error occurs due to the fact that you got a raise condition between importing (to setup the diagram) and your first modeling interaction.

As a best practice, ensure you always show a diagram, e.g. by importing an EMPTY xml file.

**Comment by ptdunlap** [comment]
Makes sense. I only encountered the error while testing edge cases. I'm pulling the diagram XML from a backend data source and wanted to see the behavior if the call to retrieve the XML didn't succeed (and subsequently the `importXML` function never being called). Instead of loading an empty XML file I decided to hide the palette (CSS) until the call to `importXML` completed properly.

**Comment by AbdurRehman91** [comment]
Hi all,I am facing the same issue of Error: rootElement already set, need to specify override. well in my case i want to import an bpmn/xml file first and then add the custom elements with the xml file.This part is important for my case.As my project majorly revolves around custom-elements and interaction with xml file.
Right now the fix can be of just changing the if condition in canvas.Js but i personally think this is not the right way.Kindly any update on this is highly appreciated 
thanks

**Comment by nikku** [comment]
@AbdurRehman91 Please raise this matter in our [forum](https://forum.bpmn.io). Clearly describe your use-case and what you'd like to achieve. Underline your description with examples that help us understand your case and we may be able to provide assistance. 

The check is there to avoid programming / library usage errors and I presume there is a proper way to implement what you'd like to achieve without monkey patching the library.
