### ISSUE TITLE
Infinite loop in Auto-place after a BoundaryEvent in a corner 

### ISSUE THREAD

**Issue by nboissel** [bpmn-io/bpmn-js#788]
### Expected Behavior

Auto-placement of element after BoundaryEvent.

### Actual Behavior

Infinite loop caused by a NaN.

### Steps to reproduce the Behavior

![Infinite loop](http://g.recordit.co/tY8nVHGKqx.gif)

Error seems to be in ./lib/features/auto-place/AutoPlaceUtil.js in L54, when orientation is set to 'top-right' or another corner, verticalDistances[orientation] returns NaN.
It then create an infinite loop.

**Comment by nikku** [comment]
Released as `v1.3.1`.
