### ISSUE TITLE
Setting element color does not set external label color

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#793]
__Reproduce__

* Set element color

__Actual Behavior__

* External label color is not set

__Expected Behavior__

* [ ] External label color is set, too

![image](https://user-images.githubusercontent.com/58601/39986415-dedd6b94-5761-11e8-9455-dc13b480dd86.png)

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/dc1f18a4972cee2d9e1bf46a6412dbb93b28506a.
