### ISSUE TITLE
updateBound error with pizza-collaboration example

### ISSUE THREAD

**Issue by stevenmoberg** [bpmn-io/bpmn-js#794]
https://github.com/bpmn-io/bpmn-js/blob/537a55bc4369d782c0138a36f863790742a1a688/lib/features/modeling/BpmnUpdater.js#L366

I get an error after drag/dropping the diagram in the pizza-collaboration.bpmn example in the Chrome Browser.

Diagram item that is causing the error has a Label with its di.label.$type == "bpmndi:BPMNLabel" and does not have any bounds witch throws an exception in min-dash.assign "cannot convert undefined or null to object"

The same diagram does not break in camunda-modeler.exe as it appears to introduce the full lodash.assign which utilizes createAssigner and does not throw an error

suggest updating to the following to account for undefined
```javascript
bounds && assign(bounds, {"
```

**Comment by nikku** [comment]
What `pizza-collaboration.bpmn` example are you referring to?

**Comment by stevenmoberg** [comment]
sorry for the confusion - the one from the colors example
https://github.com/bpmn-io/bpmn-js-examples/tree/master/colors/resources

**Comment by nikku** [comment]
Thanks for the clarification. Even in the old lodash days that code would be broken, as it would never create label bounds with the labels size and position.
