### ISSUE TITLE
Copy & paste: I can mutate the copied business object after copying

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#798]
Hint: This is due to the business object being copied by reference.

**Comment by yT0n1** [comment]
What is the ETA of a fix for this bug?

**Comment by nikku** [comment]
There is none. 

If you'd like to speed things up, file a pull request that addresses the issue.

**Comment by nikku** [comment]
Add your :+1: on the issue to indicate your interest in it being fixed.

**Comment by yT0n1** [comment]
Ok, we will discuss what makes sense for us at chor-js. Right now we are moving from bpmn-js version 3.4.3 to 6.1. I wanted to avoid having to potentially update our copypast fixes twice in case more changes were planed soon.
