### ISSUE TITLE
Boundary TimerEventDefinitions config lost when switching between interrupting and non-interrupting

### ISSUE THREAD

**Issue by nboissel** [bpmn-io/bpmn-js#799]
Hello,

The title is quite self explanatory. Configuration of boundary timer is lost when switching between interrupting and non-interrupting as its configuration is embedded in a child element and not in attributes.

Boundary timers can keep their configuration since it's just a small change in behavior.

My PR is coming for this if you also consider this as an issue.

**Comment by nikku** [comment]
This is a more general issue. 

Any boundary event that is replaced from interrupting to non-interrupting and vice versa loses its definitions.

**Comment by nboissel** [comment]
Thank you for this fix.
