### ISSUE TITLE
Switch from callbacks to promises

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#812]
We should use promises rather than callbacks in parts of our API that require asynchronity:

* `Viewer#importXML`
* `Viewer#saveXML`
* `Viewer#saveSVG`
* `Moddle#fromXML`
* `Moddle#toXML`

Why switch:

* interact nicely with ES6 `async/await`
* easier consumption for the user

__Tasks__

* [x] Decide for transition strategy
* [x] Roll out change (https://github.com/bpmn-io/bpmn-js/issues/1311)
* [ ] Update documentation (https://github.com/bpmn-io/bpmn-js-examples/issues/112)
* [ ] Blog about it (https://github.com/bpmn-io/bpmn-js/issues/1320)
* [x] :heart: IE11

**Comment by oguzeroglu** [comment]
How we'll do this:

1) We'll initially allow both Promises and Callbacks. If the developer is passing a callback, we'll simply use it, if not we'll return a Promise.
2) If the developer is using callbacks, we'll print a warning message that we're intending to deprecate this feature in a future release. (next major release)

About IE11 or any other why-are-you-still-on-this-browser that does not have Promises: **We expect developers to polyfill Promises.**

**Comment by oguzeroglu** [comment]
RFC for this ticket: https://github.com/bpmn-io/rfcs/tree/master/1-callbacks-to-async-apis
