### ISSUE TITLE
Collapsing subprocess leaves association visible

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#821]
### Steps to reproduce the Behavior

1. Create an association linking a data store to a child of a subprocess.
2. Collapse the subprocess.

### Expected Behavior

1. The association is hidden/removed or properly handled otherwise.

### Actual Behavior

1. Association stays visible.

![foo](https://user-images.githubusercontent.com/7633572/42260884-654c71a8-7f66-11e8-89cf-3663311e01fe.gif)

**Comment by nikku** [comment]
I'd rather let the association point to the sub-process than hiding it, as the semantics is _someone inside the subprocess accesses the data store_.

**Comment by nikku** [comment]
Additional note: Same happens for message flows, too.

**Comment by volkergersabeck** [comment]
Closing this issue since collapsing subprocesses is no more supported
