### ISSUE TITLE
Disallow typed Start Events inside non-event based Sub Process

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#831]
Typed events are not allowed inside sub-processes. Cf. camunda/camunda-modeler#498.

We should support untyped start events in a similar way as we support non-interrupting start events in event-based sub-processes: 
![44a7335ea784d055fe04d0b825b11d28328d1c03](https://user-images.githubusercontent.com/58601/42630599-9be1950a-85d7-11e8-8625-0683b09b28b7.gif)

__Tasks__

* [ ] Disallow morphing to typed start event inside sub-process
* [ ] Drop event type when moving start event to  sub-process

---

Cf. [forum topic](https://forum.bpmn.io/t/how-can-i-understand-this-bpmn-basic-rules/2483/4).

**Comment by MaxTru** [comment]
See [BPMN 2.0 spec](https://www.omg.org/spec/BPMN/2.0/PDF) on page 241 `There is only one type of Start Event for Sub-Processes in BPMN (see Figure 10.82): None.`
