### ISSUE TITLE
HTML DOM insertBefore() Function has a unfriendly using bug

### ISSUE THREAD

**Issue by Yue-Sword** [bpmn-io/bpmn-js#833]
browser：Chrome and IE9；
version（bpmn-js ）：bpmn-js - bpmn-viewer v2.1.0；
the bug file：bpmn-js/dist/bpmn-viewer.development.js
the bug code line： (line:2375 -2384)
```html
  function createGroup(parent, cls, childIndex) {
    var group = create('g');
    classes$1(group).add(cls);
    var index = childIndex !== undefined ? childIndex : parent.childNodes.length - 1;
    parent.insertBefore(group, parent.childNodes[index]);
    return group;
  }
```

### Expected Behavior
`node.insertBefore(newnode,existingnode) `，For  the second parameter：
when the second parameter is "undefined", we hope the function can be used in IE9 well。

### Actual Behavior
when the second parameter("existingnode") is "undefined",the IE9 report  errors ( "invalid parameter ").
and if we change the parameter as "null",the IE9 will be working well.

### Steps to reproduce the Behavior
demo code:
```html
<!DOCTYPE html>
<html>
<body>

<ul id="myList"></ul>
<p id="demo">insert something</p>
<button onclick="myFunction()">click me</button>
<script>
    function myFunction()
    {
        var newItem=document.createElement("LI");
        var textnode=document.createTextNode("Water");
        newItem.appendChild(textnode);

        var list=document.getElementById("myList");
        list.insertBefore(newItem,list.childNodes[0]);
//        list.insertBefore(newItem,null);
    }
</script>
</body>
</html>
```

**Comment by nikku** [comment]
Please provide us with a high-level, reproducible test case that shows exactly what is going on wrong under which circumstances.

**Comment by Yue-Sword** [comment]
Oh! I'm so sorry. I have done something changes.Please give attention to this problem again，thanks!
