### ISSUE TITLE
Layout manager problem on moving nodes appears on 2.4.1 version

### ISSUE THREAD

**Issue by MehdyKarimpour** [bpmn-io/bpmn-js#836]
When moving nodes, modeler creates additional sequence flows, sometimes behind the activity that could not be removed by the user.

### Expected Behavior
When you are moving nodes the layout manager should handle best path to connect sequence flows to the related nodes.

### Actual Behavior
Like version 2.3.1. It is quite okay.

### Steps to reproduce the Behavior
1. Open modeler.
2. Add nodes to have the model have mentioned in the below image.
3. Move activity to the near of End.

![image](https://user-images.githubusercontent.com/6736338/43134636-e5f7b942-8f57-11e8-8dcf-9cf461e0b559.png)

**Comment by nikku** [comment]
We are aware of this issue and are going to ship a fix soon.

**Comment by MehdyKarimpour** [comment]
Perfect

**Comment by MehdyKarimpour** [comment]
Thank you for immediate reply.
