### ISSUE TITLE
.bpmn in webpack using?

### ISSUE THREAD

**Issue by mrerhuo** [bpmn-io/bpmn-js#838]
How to configure .bpmn file in webpack.base.conf.js?

**Comment by nikku** [comment]
What are you trying to achieve?

**Comment by mrerhuo** [comment]
i using vue-cli import  bpmn-js ，but  .bpmn file is error

newDiagram.bpmn
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

**Comment by mrerhuo** [comment]
vue2

**Comment by nikku** [comment]
> You may need an appropriate loader to handle this file type.

Add the `raw-loader` to load BPMN files as text.

**Comment by akmusham** [comment]
> > You may need an appropriate loader to handle this file type.
> 
> Add the `raw-loader` to load BPMN files as text.

this did not work with me and webpack.config file is

const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: ['./index.js'],
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  },
  output: {
    path: __dirname + '/public',
    filename: 'bundle.js'
  },
  devServer: {
    inline: true,
    port: 8081,
    watchContentBase: true,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    }
  },
  module: {
    loaders: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'babel-loader',
      query: {
        presets: ['react', 'es2015', 'stage-1']
      }
    },
    {
      test: /\.css$/,
      loader: "style-loader!css-loader"
    },
    {
      test: /\.bpmn$/,
      exclude: /node_modules/,
      query: {
        presets: ['react', 'es2015', 'stage-1']
      },
      loader: 'raw-loader?name=diagrams/[name].[ext]'
    },
    {
      test: /\.scss$/,
      loader: "scss-loader!style-loader!css-loader"
    },
    {
      test: /\.png$/,
      loader: "url-loader?limit=100000"
    },
    {
      test: /\.jpg$/,
      loader: "file-loader"
    }, {
      test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
      loader: 'url?limit=10000&mimetype=application/font-woff'
    },
    {
      test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
      loader: 'url?limit=10000&mimetype=application/octet-stream'
    },
    {
      test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
      loader: 'file'
    },
    {
      test: /\.svg$/,
      exclude: /node_modules/,
      loader: 'svg-react-loader',
    }

    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      hash: true,
      template: 'index.html',
      filename: 'index.html' //relative to root of the application
    })
  ]
};
 can you please help me @nikku nikku
