### ISSUE TITLE
Message flow is disappearing, when the tasks are too close

### ISSUE THREAD

**Issue by CatalinaMoisuc** [bpmn-io/bpmn-js#843]
`Felix Anhalt` reported this on Cawemo.

### _Before_

![image 1](https://user-images.githubusercontent.com/25924333/43643770-ab122bf0-972c-11e8-9dfc-6d90dbb616ab.png)

### _After moving the tasks closer_

![image 2](https://user-images.githubusercontent.com/25924333/43643777-afc7680e-972c-11e8-8641-8148cdb8d2f7.png)

**Comment by nikku** [comment]
This is the behavior in [`bpmn-js@2.4.1`](https://github.com/bpmn-io/bpmn-js/blob/master/CHANGELOG.md#241), the latest library version:

![moveclose](https://user-images.githubusercontent.com/58601/43652670-27192d5c-9746-11e8-8117-319ff9c542c1.gif)

It should more closely resemble the user intention of (1) having tasks close together and (2) still being able to clearly see the connecting sequence flow.
