### ISSUE TITLE
Show group names

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#844]
Right now, we don't display group names, cf. [this forum thead](https://forum.bpmn.io/t/name-in-group-element-not-rendered/112):

![image](https://user-images.githubusercontent.com/58601/43843587-354312cc-9b28-11e8-9d84-38e201956a8f.png)

__Tasks__

* [ ] Render group name, taken from referenced `CategoryValue#name` (if it exists)
* [ ] Position group name based on the groups `bpmndi:BPMNLabel` position

__Resources__

* [`group_name.bpmn`](https://github.com/bpmn-io/bpmn-js/files/2270615/group_name.bpmn.txt)

---

Referenced in [forum thread](https://forum.bpmn.io/t/name-in-group-element-not-rendered/112/2).

**Comment by MartinWeberLpz** [comment]
How is it possible to add Groups in the Camunda Modeler? I don't find the menu item for this?! Please help! Thanks!

**Comment by nikku** [comment]
You cannot, cf. https://github.com/bpmn-io/bpmn-js/issues/343.

**Comment by MartinWeberLpz** [comment]
Yes, but why was it developed to show the name of a group when it is not possible to add groups?! (https://github.com/bpmn-io/bpmn-js/issues/844) For me, this is a contradiction to #343.

**Comment by nikku** [comment]
There is two perspectives to take on when looking at our toolkit:

* The viewer allows you to display _any_ BPMN diagram, independent from which tool modeled it (as long as the diagram is BPMN 2.0 spec compliant)
* The modeler is able to model diagrams with a feature set that evolves over time (priorities assigned and regularly re-evaluated by us)

Issue https://github.com/bpmn-io/bpmn-js/issues/844 describes a feature for our BPMN viewer that is valuable independent of whether we support modeling group names (https://github.com/bpmn-io/bpmn-js/issues/343) using our modeler. If you'd like to see modeling groups added to our tools, give the respective issue a :+1:.
