### ISSUE TITLE
Nuxt-js integration via npm install --save bpmn-js

### ISSUE THREAD

**Issue by mouseMD2017** [bpmn-io/bpmn-js#845]
running on arch linux (kernel 4.17.13, x86_64) I'm trying to import bpmn-js into my nuxt-js project as a module.

### Expected Behavior
Module is being imported properly, main page appears as expected

### Actual Behavior
Main page is not being shown, error: `Cannot get /`

### Steps to reproduce the Behavior
create new nuxt-js project via 
`npx create-nuxt-app mybpmn`
->no custom server or UI framework, universal, no axios, no eslint, npm

-> `cd mybpnm` 
-> `npm install --save bpmn-js`
-> `npm run dev`
-> edit & save modules section in nuxt.config.js:
`modules: [
    'bpmn-js'
  ]`
-> refresh page on localhost:3000
-> main page is not being shown due to 
`Cannot GET /`

==> How can I import bpmn-js into nuxt-js properly ?

**Comment by nikku** [comment]
What is nuxt-js? How does it bundle resources for the web? Is it ES module aware?

**Comment by mouseMD2017** [comment]
Nuxt-js [https://nuxtjs.org/guide](url) is a framework for creating Universal Vue.js Applications, which is ES module aware.
See [https://nuxtjs.org/api/configuration-modules](url)

**Comment by mouseMD2017** [comment]
@nikku: reading your last answer I deleted my multipage app, created a single page one with the same procedure, but it results in the same error, I'm afraid.

**Comment by nikku** [comment]
> I deleted my multipage app, created a single page one.

It is not related to the multi vs. single page app thing. The problem is related to the fact that nuxt-js tries to include bpmn-js in the back-end. That fails, as bpmn-js is a browser only library.

**Comment by nikku** [comment]
I'd suggest you to turn to the nuxt-js project and figure out how to include non-universal (i.e. client side only) dependencies. 

Unfortunately I cannot help you beyond this point.

**Comment by mouseMD2017** [comment]
OK, I will try, thank you very much. :)
