### ISSUE TITLE
Modeler and zoom functionality

### ISSUE THREAD

**Issue by MehdyKarimpour** [bpmn-io/bpmn-js#846]
Hi,
When user uses zoom functionality, the modeler put the diagram behind the palette.

### Expected Behavior
Modeler should consider palette position and diagram should positioned after palette 
![image](https://user-images.githubusercontent.com/6736338/43991223-6a62fd76-9d7d-11e8-9a6c-fd4863b18dc8.png)

### Actual Behavior
Diagram goes behind the palette
![image](https://user-images.githubusercontent.com/6736338/43991204-0f89a9a4-9d7d-11e8-81b0-746f85521eb0.png)

### Steps to reproduce the Behavior
1. Create a model like this
![image](https://user-images.githubusercontent.com/6736338/43991200-eba08f4e-9d7c-11e8-863b-55f0150f9379.png)

2. Press zoom button
best regards,
mehdy

**Comment by MehdyKarimpour** [comment]
Hi, nobody can help?

**Comment by nikku** [comment]
The palette floats on top of the diagram, so generally speaking this is intended behavior.

Not sure if this is a feature request, question or bug report.
