### ISSUE TITLE
BpmnModeler is not a constructor

### ISSUE THREAD

**Issue by simon9124** [bpmn-io/bpmn-js#847]
When I use in vue.js, it says that in the Console. Really want to use bpmn-js in project so how can I resolve the issue?

**Comment by nikku** [comment]
It works for [others](https://github.com/bpmn-io/bpmn-js/issues/845#issuecomment-412067771).

How do you consume the library?

**Comment by simon9124** [comment]
I use in vue like this:

mounted() {
    const BpmnModeler = require('bpmn-js/lib/Modeler')
    const propertiesPanelModule = require('bpmn-js-properties-panel')
    const propertiesProviderModule = require('bpmn-js-properties-panel/lib/provider/camunda')
    const camundaModdleDescriptor = require('camunda-bpmn-moddle/resources/camunda')

    this.container = this.$refs.content
    const canvas = this.$refs.canvas

    this.bpmnModeler = new BpmnModeler({
      container: canvas,
      propertiesPanel: {
        parent: '#js-properties-panel'
      },
      additionalModules: [propertiesPanelModule, propertiesProviderModule],
      moddleExtensions: {
        camunda: camundaModdleDescriptor
      }
   })
   this.createNewDiagram(this.bpmnModeler)
},
methods: {
    createNewDiagram() {
        const bpmnXmlStr = `<bpmn>......</bpmn>`
        this.bpmnModeler.importXML(bpmnXmlStr, function(err) {
            if (err) {
              console.error(err)
            } else {
              // that.success()
            }
        })
    }
}

so could you tell me how to use in vue-cli project?

**Comment by simon9124** [comment]
I use in vue like this:

`mounted() {
    const BpmnModeler = require('bpmn-js/lib/Modeler')
    const propertiesPanelModule = require('bpmn-js-properties-panel')
    const propertiesProviderModule = require('bpmn-js-properties-panel/lib/provider/camunda')
    const camundaModdleDescriptor = require('camunda-bpmn-moddle/resources/camunda')

    this.container = this.$refs.content
    const canvas = this.$refs.canvas

    this.bpmnModeler = new BpmnModeler({
      container: canvas,
      propertiesPanel: {
        parent: '#js-properties-panel'
      },
      additionalModules: [propertiesPanelModule, propertiesProviderModule],
      moddleExtensions: {
        camunda: camundaModdleDescriptor
      }
    })
    this.createNewDiagram(this.bpmnModeler)
  },
  methods: {
    createNewDiagram() {
      const bpmnXmlStr = '<bpmn>......</bpmn>'

      this.bpmnModeler.importXML(bpmnXmlStr, function(err) {
        if (err) {
          console.error(err)
        } else {
          // ......
        }
      })
    }
  }`

But it says "BpmnModeler is not a constructor" , so could you teach me how to use in vue-cli project?
I am really worried about the project.

**Comment by nikku** [comment]
What did you do to end up with this error?

Did you update from an old version of bpmn-js, e.g. `0.30.0`?

**Comment by simon9124** [comment]
Uh...My package.json like this:
"bpmn-js": "^2.4.1",
"bpmn-js-properties-panel": "^0.26.1",

I used this sentences to install:
"npm i bpmn-js"
"npm install --save camunda-bpmn-moddle"

Did I write something wrong with it?

**Comment by simon9124** [comment]
Yes I did it!
In vue.js I shouldn't import like "const BpmnModeler = require('bpmn-js/lib/Modeler')"
I should use "import BpmnModeler from 'bpmn-js/lib/Modeler'".

Thanks for reply me!
