### ISSUE TITLE
Positioning the project logo

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [bpmn-io/bpmn-js#848]
According to the post in https://forum.bpmn.io/t/license-questions/85/20 it is mentioned that 
`You cannot change the size and position of the logo.`
My requirement is to position the logo from the right-bottom corner to the left-bottom corner so that the logo does not overlap the properties panel. Is repositioning the logo while making sure that it remains visible at all times forbidden? What happens if the canvas is taller than the viewport and as a result the logo is not visible on page load?

**Comment by SayakMukhopadhyay** [comment]
Another situation that I have is that the logo might get temporarily overlapped by a more important UI element like when a toggleable side-nav is opened.

**Comment by nikku** [comment]
The logo is there to provide attribution. Ensure you're not hiding it / make it harder to be seen purposefully while people interact with the diagram and you should be fine.

We cannot provide you any absolution beyond this statement.

**Comment by SayakMukhopadhyay** [comment]
Thanks! This is what I believed would be reading the license but the forum post confused me a bit. Thanks for clearing this up.
