### ISSUE TITLE
Dragging message flow label over message flow causes an error

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#849]
__Reproduce__

* Create collaboration diagram with message flow + message flow label
* Drag message flow label onto message flow
* Error `Cannot access source of undefined` is raised

__Expected Behavior__

* [ ] I can move the message flow label everywhere

**Comment by stephanpelikan** [comment]
Only to be sure that you saw the same error as I recorded in the video: The error is

`TypeError: Cannot read property 'parent' of undefined`

**Comment by nikku** [comment]
Yes. The error message depends on the browser you use to reproduce the bug.
