### ISSUE TITLE
When calling saveXML the commandStack gets lost

### ISSUE THREAD

**Issue by robpal94** [bpmn-io/bpmn-js#857]
### Expected Behavior
The modelers command stack stays unchanged

### Actual Behavior
The modelers command Stack gets deleted.

### Steps to reproduce the Behavior
* Make changes
* Call `saveXML()`
* Try to undo your changes

### Environement
* bpmn-js version 2.1.0
* electron

**Comment by nikku** [comment]
I guess the issue is invalid?

**Comment by robpal94** [comment]
Yes, sorry for the confusion.
