### ISSUE TITLE
I can define different views for my BPMN diagrams

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#87]

**Comment by nikku** [comment]
This got recently covered by the [BPMN MIWG working group](https://github.com/bpmn-miwg/bpmn-miwg-test-suite) via [test case `C.4.0.bpmn`](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/blob/master/Reference/C.4.0.bpmn).

**Comment by tengzj** [comment]
dsfsd

**Comment by snakebyte85** [comment]
I have the problem to support an XML exported from another modeler, where the user can build multiple collaborations/processes per single project/xml file

I added the support to select a specific diagram to be rendered, using ID of the process or collaboration. Check my pull request https://github.com/bpmn-io/bpmn-js/pull/967 if you want to test against https://github.com/bpmn-miwg/bpmn-miwg-test-suite/blob/master/Reference/C.4.0.bpmn
