### ISSUE TITLE
Replace BpmnGlobalConnect provider with rules

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#870]
__Is your feature request related to a problem? Please describe.__

New version of `diagram-js` will break the current implementation of `GlobalConnect` tool. Because of that, it needs to be adjusted in order to perform an update in the future.

__Describe the solution you'd like__

Replace `BpmnGlobalConnect` provider with a rule for `connection.start` implementing the current logic.

__Describe alternatives you've considered__

The only alternative would be to not update `diagram-js` which is not a real alternative. Bumping a version without any changes will break the library.

__Additional context__

Related [#286](https://github.com/bpmn-io/diagram-js/pull/286)

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/871.
