### ISSUE TITLE
GlobalConnect should not allow to start connection from an end event

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#872]
__Describe the Bug__

 Global connect tool allows to try to add an outgoing connection to end event symbols. However, according to section 7.5.1 of BPMN 2.0, end events should not be able to have any outgoing connections. As a consequence, the global connect tool should not allow to try to start connection from such symbols.

__Steps to Reproduce__

1. Create an end event
2. Activate global connect tool
3. Click on the end event

__Expected Behavior__

Global connect tool should not allow to start a connection from end event symbols per default.

__Environment__

 - Browser: Chrome 69
 - OS: MacOS Mojave
 - Library version: 2.5.2

**Comment by nikku** [comment]
This is not entirely correct: End events may very well be connected to text annotations via an association and the tool should allow users to model that: 

![image](https://user-images.githubusercontent.com/58601/46789418-a84ab400-cd3c-11e8-90cf-f92f7f21c0da.png)

**Comment by barmac** [comment]
You are right. It makes sense and indeed is allowed in the documentation. Then, we should close this bug report as it's not a bug, but a feature.
