### ISSUE TITLE
Label moves twice when using space tool

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#878]
__Describe the Bug__

When using the space tool along with the sequence flow the labels will move twice.

__Steps to Reproduce__

The following reproduces the bug on [demo.bpmn.io](https://demo.bpmn.io/s/start).

![foo](https://user-images.githubusercontent.com/58601/47280532-2299f480-d5d7-11e8-8dd6-dadee90f5842.gif)

__Expected Behavior__

The label is only moved once.

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: 2.5.2

**Comment by nikku** [comment]
The problem underlying this bug is that the `LabelBehavior` [moves the label](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/behavior/LabelBehavior.js#L192) after the space tool already moved it.

**Comment by nikku** [comment]
I added a test case that reproduces the issue on the [`878-space-moves-label-twice` branch](https://github.com/bpmn-io/bpmn-js/compare/878-space-moves-label-twice).

**Comment by philippfromme** [comment]
Came across this bug again while working on https://github.com/bpmn-io/bpmn-js/issues/1019. The problem is that a couple of behaviors kick in after moving and resizing shapes. In the case of using the space tool we don't want that as we're explicitly moving and resizing elements.

**Comment by nikku** [comment]
Hints could be a way to to disallow the post-move behavior(s).

**Comment by philippfromme** [comment]
Was thinking about that. Otherwise, the space tool has to be aware of all those behaviors. 💩

**Comment by philippfromme** [comment]
@nikku something like this?

```javascript
this._modeling.moveElements(shapes, delta, null, {
    allowPreExecutionBehavior: true,
    allowPostExecutionBehavior: false
  });
```

**Comment by nikku** [comment]
Who performs the pre-execution behavior? Can't we be a bit more explicit?

**Comment by philippfromme** [comment]
Attach support is doing stuff before and afterward. We also have a nice [fix](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/attach-support/AttachSupport.js#L233) for the space tool inside attach support. 💩 It would become obsolete with the new hints. Label support also does stuff before. So we'd actually need to suppress both pre and post behavior. Only thing that would still mess everything up would be [label adjustment](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/behavior/LabelBehavior.js#L198) that moves labels around even if I suppress layout through `layout: false`.

**Comment by philippfromme** [comment]
Of course we can also do

```javascript
this._modeling.moveElements(shapes, delta, null, {
  attachSupport: false,
  labelSupport: false,
  ...
});
```

But that would also mean tighter coupling.

**Comment by nikku** [comment]
So the question is: Why do we sometimes do stuff `pre` and `post` and sometimes don't? 

If we cannot find a distinguishing hint name based on that, what about this: Add a generic `hint` that describes the source of the move operation (i.e. `source = spaceTool`). Lower level components may interpret that hint and do stuff they like.

**Comment by nikku** [comment]
The whole space tool / attach support / label support thing is a bit of a mess, I know :eyes:.

**Comment by philippfromme** [comment]
Yeah, it's quite shaky. Didn't expect to open a can of worms. 🐛

**Comment by nikku** [comment]
We could lookie lookie into dat thing together some day :eyeglasses: :beach_umbrella: :city_sunset:.

**Comment by philippfromme** [comment]
That would be nicey nicey. 🌞

**Comment by BelindaBecker** [comment]
Dear all,
is there any update on this?

We are facing this issue when modeling large diagrams and changing the layout afterwards. Especially, when moving elements with the space tool over a larger distance, the labels get lost and hard to recover.

Appreciate any info. Thanks!

**Comment by nikku** [comment]
Unfortunately we could not follow up on this bug to date.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1269
