### ISSUE TITLE
Dragging items in MS Edge

### ISSUE THREAD

**Issue by DetlefPeters** [bpmn-io/bpmn-js#879]
When dragging a node in MS Edge, the shape is placed in the upper left corner instead of under the drag cursor. This makes it impossible to select the desired drop location.

Side effects: 
1. each drag operation adds an additional "djs-drag-group" SVG group to the SVG - all other browsers reuse a single "djs-drag-group" for all drag operations
2. the "transform" property of these groups look invalid to me - I find e.g. transform="translate(2px,5px)", but according to specification it must be transform="translate(2 5)" !

Can be reproduced on demo page (https://demo.bpmn.io/new)

1. Create a node, e.g. a task
2. Drag that node to another position

__Expected Behavior__
The shape of the dragged node is under the cursor
The resulting SVG is valid

__Environment__
 - Browser: Edge 17
 - OS: Windows 10
 - Library version: 2.5.2

**Comment by nikku** [comment]
It looks like a bug in Edge, as it adds pixel values to SVG transforms. We got a similar issue reported by users that were not able to open a diagram exported on edge (https://github.com/bpmn-io/bpmn-js/issues/860).

@philippfromme Could you have a look into this one? We should one and for all verify if this is a bug in edge or one of our components.

**Comment by philippfromme** [comment]
I can reproduce this.

**Comment by DetlefPeters** [comment]
FYI: the resulting SVG from Viewer.prototype.saveSVG() contains those erratic SVG transforms, too, when called within MSEdge. We can obtain a valid SVG from it by setting
 `svgString = svgString.replace(/(\-?[0-9]*)px, (\-?[0-9]*)px/g, "$1 $2");` 
before really saving the SVG.
Maybe this can help you.

**Comment by nikku** [comment]
Fixed in `v3.2.1`.

**Comment by DetlefPeters** [comment]
Successfully tested in my project. Thanks for fixing :-)
