### ISSUE TITLE
Modeller draws big black circles

### ISSUE THREAD

**Issue by tomitrescak** [bpmn-io/bpmn-js#893]
Hi, out of the box, when trying to use modeller I'm getting the big black circles when hovering over flows:

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/2682705/47888630-a4bccf80-de99-11e8-84f8-ada83295c40d.png">

This is the code. Any idea? Thanks!!!

```
let viewer = new BpmnModeler({
        container: '#canvas'
      });

      viewer.importXML(process.model, function(err: string) {
        if (!err) {
          let c = viewer.get('canvas');
          c.zoom('fit-viewport'));
        } else {
          // tslint:disable-next-line:no-console
        }
      });
```

**Comment by tomitrescak** [comment]
Well, truth be told, I have no idea what am I doing wrong but it is not loading the toolbar and behaves completely differently to what is in the examples even though my code is almost the same, but without jQuery

**Comment by barmac** [comment]
@tomitrescak Can you please provide the whole code example or a clear way to reproduce the problem? Please use the standard bug report template to send all of necessary information: https://github.com/bpmn-io/bpmn-js/issues/new?template=BUG_REPORT.md

**Comment by tomitrescak** [comment]
Most amazing. Was hoping it would be something similar;) thanks for the awesome package!
