### ISSUE TITLE
Pasting participant into participant not rejected

### ISSUE THREAD

**Issue by mnp-mid** [bpmn-io/bpmn-js#895]
Reproduce:

- In a collaboration select participant
- Copy participant
- Hover any flow element except participant and paste (`elements.paste.rejected` is fired)
- Hover participant and paste (`elements.paste.rejected` is not fired, `elements.paste` command is added to command stack without any visual indication that it has been executed)

![2018-11-05_09-45-37](https://user-images.githubusercontent.com/7633572/47987491-ec349d00-e0df-11e8-8568-237562238c7d.gif)

__Environment__

Please complete the following information:

 - Browser: Chrome 70
 - OS: Windows 10

**Comment by nikku** [comment]
This is rendered obsolete by the new copy and paste implementation.
