### ISSUE TITLE
Reconnecting sequence flow end to participant throws error

### ISSUE THREAD

**Issue by mnp-mid** [bpmn-io/bpmn-js#896]
![2018-11-05_10-20-48](https://user-images.githubusercontent.com/7633572/47989266-ceb60200-e0e4-11e8-8bc8-dea0b8c387a6.gif)

Reproduce:

- Reconnect a sequence flow's end to a participant thus turning it into a message flow

Expected Behavior:

- No error is thrown

Actual Behavior:

- Error is thrown: ([ReplaceMenuProvider](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/popup-menu/ReplaceMenuProvider.js#L293) is called with old element (sequence flow)

__Environment__

 - Browser: Chrome 70
 - OS:  Windows 10

**Comment by barmac** [comment]
Fix for this issue might potentially resolve also this: https://github.com/bpmn-io/bpmn-js/issues/1049

**Comment by pinussilvestrus** [comment]
closed via dd3d7e9c64089b418354dd568424370db743b4e7
