### ISSUE TITLE
Rendering breaks when reconnecting sequence flow end to its source thus creating a loop

### ISSUE THREAD

**Issue by mnp-mid** [bpmn-io/bpmn-js#897]
![2018-11-05_09-35-27](https://user-images.githubusercontent.com/7633572/47986887-47659000-e0de-11e8-9caf-236f5d750a2e.gif)

__Environment__

Please complete the following information:

 - Browser: Chrome 70
 - OS:  Windows 10

---

Possible duplicate of https://github.com/bpmn-io/bpmn-js/issues/891

Depends on https://github.com/bpmn-io/bpmn-js/issues/891

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/988
