### ISSUE TITLE
Extend XML compatibility by sanitizing the result of marker id generation

### ISSUE THREAD

**Issue by linus-amg** [bpmn-io/bpmn-js#899]
When re-using the created svg (e.g. for pdf creation) ensuring XML compatibility would be of great help because other libraries need to understand the markup correctly.

__Is your feature request related to a problem? Please describe.__

When coloring bpmn elements a new marker gets generated for every color and added to the `<defs>`, the markers are then referenced to through the id of the marker in the elements where they are used. The id's value (string) currently contains the colors it represents with a hash in front of them. (example: sequenceflow-end-#FFE0B2-#FB8C00-atmnxylf462zjr2b8a0okhcb2)

__Describe the solution you'd like__

Removing the hash would increase the xml compatibility and would allow other libraries to also be able to correctly reference the markers.

__Describe alternatives you've considered__

Search and replace the hashes in the svg output.

__Additional context__

https://oreillymedia.github.io/Using_SVG/guide/markup.html#id-attr

**Comment by componentDidMount** [comment]
I need to point out here that xml attributes containing a hash seem to be valid xml, that is not the point here, it's only about interoperability between libraries. Thats also why this issue is rather a feature request than a bug report.

**Comment by nikku** [comment]
We appreciate contributions that improve things.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/972.

**Comment by nikku** [comment]
Released in `bpmn-js@3.3.0`.
