### ISSUE TITLE
IE11: Removing shape using keyboard doesn't work since Version 3.0.0

### ISSUE THREAD

**Issue by mnp-mid** [bpmn-io/bpmn-js#904]
Removing shape using keyboard doesn't work since Version 3.0.0. for IE 11
Worked fine in Version 2.5.2.

Other keyboard shortcuts like E or H are just fine.

1. Open modeler
2. click on the start event
3. Remove the element using del key.

This is not reproducable on https://demo.bpmn.io/new

Please complete the following information:

 - Browser: [IE 11]
 - OS: [Windows 10]
 - Library version: [3.0.0]

**Comment by pinussilvestrus** [comment]
I were able to reproduce it in a windows virtual machine on my macbook.
The bug is only present on IE.
