### ISSUE TITLE
iPad pro and Apple Pencil support

### ISSUE THREAD

**Issue by socialinfrastructuretechnology** [bpmn-io/bpmn-js#907]
__Is your feature request related to a problem? Please describe.__

I'm annoyed when using Apple Pencil with the iPad Pro where object selection, drag, drop, doesn't feel intuitive and often struggles to focus on the object and select at all.

__Describe the solution you'd like__

Support Apple Pencil on iPad for Safari and Chrome.

__Describe alternatives you've considered__

I use realtime boards, and the features are close enough to what I need that I might consider switching purely to this app due to the superior touch input support.

__Additional context__

I was trying to use demo.bpmn.io on an iPad Pro with Apple Pencil.

**Comment by nikku** [comment]
Could be related to general issues with [mobile / touch device support](https://github.com/bpmn-io/bpmn-js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+mobile) we as of now.

**Comment by nikku** [comment]
You may double-check our improved touch support shipped with [`bpmn-js@8.9`](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#890). Try it out on [demo.bpmn.io](https://demo.bpmn.io/). Closing this issue for the time being.
