### ISSUE TITLE
Hide overlays of children when collapsing sub process

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js#909]
__Is your feature request related to a problem? Please describe.__

As described in this [forum topic](https://forum.bpmn.io/t/how-to-hide-show-the-overlays-in-subprocess-collapsed-expanded-with-viewer/2830/3), when children of a sub process have overlays and the sub process get collapsed, the overlays are not getting hided as well. They keep beeing visible.

__Describe the solution you'd like__

Adjust the [Collapse handling](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/modeling/cmd/ToggleShapeCollapseHandler.js) to hide overlays of sub process children as well.

__Alternative Solutions__

Let users work around this issue themselves, as described in [this comment](https://forum.bpmn.io/t/how-to-hide-show-the-overlays-in-subprocess-collapsed-expanded-with-viewer/2830/6).

__Additional context__

Before collapsing

![image](https://user-images.githubusercontent.com/9433996/48894653-8e27e980-ee43-11e8-95fd-62da9c544741.png)

After collapsing

![image](https://user-images.githubusercontent.com/9433996/48894640-8405eb00-ee43-11e8-8061-6555a6d1527d.png)

**Comment by nikku** [comment]
Workaround / implementation approach exists, cf. [this comment](https://forum.bpmn.io/t/how-to-hide-show-the-overlays-in-subprocess-collapsed-expanded-with-viewer/2830/6?u=nikku).
