### ISSUE TITLE
Prevent crashing bpmn-js through errors caused by additional modules

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#919]
## Description

Additional modules that are popular like [bpmn-js-token-simulation](https://github.com/bpmn-io/bpmn-js-token-simulation) can crash bpmn-js. As of now there's no way of either preventing that or giving any useful information about the source of the crash. It is to be investigated on which side should be responsible.

### Catch Errors as a Plugin
* has been investigated in https://github.com/bpmn-io/bpmn-js-token-simulation/commit/2bd63587b0c8bd693463ffa80c95968a158c9d2d
* all constructors and methods are executed in `try...catch` statements
* any errors are logged in the console specifying the constructor/method that caused the error

### Catch Errors as bpmn-js

* bpmn-js catches errors caused by plugins OR crashes in a controlled manner indicating the source of the error

## Additional Information

bpmn-js-token-simulation Issue: https://github.com/bpmn-io/bpmn-js-token-simulation/issues/39

**Comment by nikku** [comment]
This is a research topic that we're probably not be able to pick up any time soon.
