### ISSUE TITLE
External label text doesn't fill the entire text box

### ISSUE THREAD

**Issue by jclaxton** [bpmn-io/bpmn-js#922]
__Describe the Bug__

When using a modeler extension to resize external labels, the text doesn't fill the entire box. I'm using the ResizeAllRules module included in [bpmn-js-nyan](https://github.com/bpmn-io/bpmn-js-nyan) to allow external labels (such those used for Intermediate Event names) to be resized. But when I expand a label for longer text, the text doesn't fill the space. See [here](https://forum.bpmn.io/t/name-of-textannotation-resize-eventhandler/2646/2)  for a screenshot.

Not sure if this is considered a bug since the core library doesn't support this kind of resizing, but it does seems to limit the extensibility of the library. I already have a fix for this, I'll submit a PR shortly. 

__Steps to Reproduce__

1. Setup bpmn-js-nyan.
2. Create an Intermediate Event element and give a name with about 100 characters. 
3. Make the label bigger.

__Expected Behavior__

The text should fill the entire width of the label. 

__Environment__

 - Browser: [Chrome 70]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.5.2]

**Comment by philippfromme** [comment]
Looking forward to your PR. 👍
