### ISSUE TITLE
I want to integrate modular in react js . Can any one help me in this

### ISSUE THREAD

**Issue by vishaldenzil** [bpmn-io/bpmn-js#926]

**Comment by pinussilvestrus** [comment]
Hi @vishaldenzil 
Please consider using the [forum](https://forum.bpmn.io/)  if you want help or have specific questions. The GitHub issues aren't the right place for it.

However, there is still an open [issue](https://github.com/bpmn-io/bpmn-js-examples/issues/73) for creating a React example.

**Comment by nikku** [comment]
Checkout [this comment](https://github.com/bpmn-io/bpmn-js-examples/issues/73#issuecomment-477193972) if you still need help.
