### ISSUE TITLE
How to add a custom button to the toolbar to the right of the shape after clicking the shape

### ISSUE THREAD

**Issue by Super-Mumoo** [bpmn-io/bpmn-js#930]
Hey, I am using the pre-packaged version of bpmn. I want to add some custom buttons to the tools that pop up on the right side of the shape (such as the delete button) after clicking the shape to do some other operations I need. How can I do this?
![123](https://user-images.githubusercontent.com/38457677/50678517-0506f380-103a-11e9-9200-d13e3cee0e1a.jpg)

**Comment by philippfromme** [comment]
For questions regarding the toolkit please head to our [forum](https://forum.bpmn.io).

**Comment by Super-Mumoo** [comment]
I don't know if you saw my message.
I have been busy with other things for the past two days. I forgot to say that I have solved this problem. Although I am just a rookie and I don’t understand the code very well, I still want to post it here for other friends to refer to.
![image](https://user-images.githubusercontent.com/38457677/50761168-aee9b880-12a4-11e9-822e-99e68850f807.png)



I don't know if the image will be uploaded successfully, so the text explains: Search for "group: 'connect'" in "bpmn-modeler.js", you will get two results, about 32700~32800 lines, there are authors here. Write the judgment condition to decide whether to register these icon buttons (let's call it this way), you can also write your own judgment conditions to execute the custom button you need to add.

**Comment by Super-Mumoo** [comment]
Thank you for your work

**Comment by philippfromme** [comment]
Modifying the bundle is possible though not encouraged. A proper solution would be to [create you own bundle](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-bundle) and overriding the [ContextPadProvider](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/context-pad/ContextPadProvider.js) with your modified version.
