### ISSUE TITLE
Add isHorizontal=true to Participant / Lane DI shapes

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#934]
__Is your feature request related to a problem? Please describe.__

The `isHorizontal` attribute on participant and lane DI shapes is meta-data that helps editors to understand how these elements are laid out. Quoting from the BPMN spec (p. 373): 

> + isHorizontal : Boolean [0..1]
> an optional attribute that should be used only for Pools and Lanes. It determines if it should be depicted horizontally (true) or vertically (false).

The attribute is not necessarily required, thus this feature request falls into the forgiveness / compatibility category.

__Describe the solution you'd like__

We should add the attributes, as we only support horizontal modeling anyway and "fix" existing diagrams by gradually introducing the 

* [ ] add `isHorizontal=true` on newly created participant / lane DI shapes
* [ ] add `isHorizontal=true` on update participant / lane DI shapes

__Describe alternatives you've considered__

* ignore compatibility concerns and keep things as is

__Additional context__

Reported in https://github.com/camunda/camunda-modeler/issues/1096, too.

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/936
