### ISSUE TITLE
Improved sequence flow layout for overlapping content

### ISSUE THREAD

**Issue by volkergersabeck** [bpmn-io/bpmn-js#935]
__Problem__

User creates a sequence of tasks A, B, and C. Afterwards they realize that task B is only optional. Then the user adds two gateways right before and after task B. 
When the user adds a sequence flow between both gateways, then this sequence flow is rendered behind task B.
In this case, the user needs to know where to click to be able to grab the sequence flow and drag it to a different position. There is no way to directly grab the drag-handle of the sequence flow, and also it is hardly visible that there is a new sequence flow.

__Solution__

When a sequence flow is added between two elements and another sequence flow would be fully covered by the new sequence flow (i.e. both lines are not visually distinguishable), then add the new sequence flow in a different layout (e.g. as a three-part polyline). 

See the screenshot attached for the desired solution.

__Alternative solution__

By rendering all sequence flows on top of tasks, the situation above would be easier to solve for the user, however, it still requires the user to "fix" the layout.

The rendering on top would also not solve the same issue if two sequence flows are added between to tasks. The user would not see that there is a second sequence flow on top of the first. (see second screenshot below)

__Sequence flows between gateways__

![screen shot 2019-01-23 at 16 37 51](https://user-images.githubusercontent.com/232571/51617969-a4c6eb80-1f2d-11e9-9f7c-1049811e81c3.png)

__Sequence flows between tasks__

![screen shot 2019-01-23 at 16 50 12](https://user-images.githubusercontent.com/232571/51618665-fc198b80-1f2e-11e9-965d-5cf3e2c9037e.png)

**Comment by nikku** [comment]
Good idea to support that standard modeling case a bit better.

I'd love to try out a prototype to see how it feels. This will help us to better understand when to bail out and stop optimizing in more complex.

**Comment by nikku** [comment]
A better solution is probably to show lint errors, as duplicate sequence flows are a severe problem.

Cf. [`no-duplicate-sequence-flows`](https://github.com/bpmn-io/bpmnlint/blob/master/docs/rules/no-duplicate-sequence-flows.md), a rule in [bpmnlint](https://github.com/bpmn-io/bpmnlint) that validates this.
