### ISSUE TITLE
Modeler does not let me drop a element in diagram

### ISSUE THREAD

**Issue by mariohmol** [bpmn-io/bpmn-js#937]
__Describe the Bug__

I'm trying to implement an angular component for this project. The modeler works but when i try to drag an drop an element to the viewer it gives me a forbidden icon and do not let drop it.

__Steps to Reproduce__

Referring to:

* https://github.com/mariohmol/ng-bpmn/issues/2

You can see the live example here:

https://stackblitz.com/edit/ng-bpmn

__Expected Behavior__

Let drag and drop items into the diagram

ps: later on when this is component is more stable we can put this on the bpmnjs org .. would be a pleasure to collaborate =)

**Comment by nikku** [comment]
@mariohmol Thanks for letting us know you're building something on top of our libraries. 

Unfortunately third party extensions are outside our library scope, thus we can only help you on a best-effort basis. Please ask this question (it is a usage related question, not a bug) [in our forum](https://forum.bpmn.io/) and we'll attempt to help you there. 

We are not a free support machine though, which means we ask you to provide the necessary context, a screen cast showing the _broken_ behavior, console errors, steps you undertook to try to understand things, etc.

**Comment by nikku** [comment]
If you are sure this is an actual bpmn-js bug, attach the concrete steps to reproduce and we are happy to reopen this issue.

**Comment by mariohmol** [comment]
I can go until the dragstart.. which works.. but i cant see where is the dragstop listener to drop

**Comment by nikku** [comment]
For your information: The demo you provide does not run for me (console reports various security access related errors; probably due to my restrictive browser configuration).

**Comment by mariohmol** [comment]
Ok.. so basically to have this clean... its 2 steps.. clone the repo, `npm i & npm start` and will see without warnings.. check it out
<img width="882" alt="captura de tela 2019-01-25 as 9 02 15 pm" src="https://user-images.githubusercontent.com/5495763/51777511-90791f00-20e4-11e9-858a-b9b3e9cc7f5d.png">

**Comment by mariohmol** [comment]
What i can see so far.. is the inside de SVG.. some groups does not have the size of the view..  for example.. the `<g class="viewport"` its not with height and width = 0px
