### ISSUE TITLE
Sequence flow ends do not crop after undo/redo

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#940]
__Describe the Bug__

After deleting a task (`A` in the screencast below) and performing undo / redo the underlying sequence flow does not crop anymore, resulting in a broken layout:

![screencapture](https://user-images.githubusercontent.com/58601/53153932-c9a89000-35b9-11e9-9901-83f540f62323.gif)

__Steps to Reproduce__

* Open [test diagram](https://github.com/bpmn-io/bpmn-js/files/2888280/diagram_1.bpmn.txt)
* Delete Task `A`
* Undo
* Redo
* Sequence flow connecting start event and other task is not cropped on task / event border

__Expected Behavior__

* Cropping works.

__Environment__

Please complete the following information:

 - Browser: Chrome
 - OS: Arch Linux
 - Library version: v3.2.1

---

Possible duplicate of https://github.com/bpmn-io/bpmn-js/issues/891

Depends on https://github.com/bpmn-io/bpmn-js/issues/891

**Comment by barmac** [comment]
Findings:
* we do not trigger layout when reconnecting elements
* simply adding layout doesn't help as we fall into this line https://github.com/bpmn-io/diagram-js/blob/master/lib/layout/ManhattanLayout.js#L368

I need to add a test case for proper layout with Manhattan.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/971.
