### ISSUE TITLE
diagramUrl  dont load from local url

### ISSUE THREAD

**Issue by amir3164** [bpmn-io/bpmn-js#941]
iam add diagramUrl   from local project but dont load and dnot allow add digram
```
var diagramUrl = '/diagram.bpmn';

      // modeler instance
      var bpmnModeler = new BpmnJS({
        container: '#canvas',
        keyboard: {
          bindTo: window
        }
      });
```
![untitled](https://user-images.githubusercontent.com/10501720/53467351-1df4b980-3a6b-11e9-96f5-db5eac33fa03.png)

**Comment by pinussilvestrus** [comment]
Hi @amir3164 

Did you take a look inside the [bpmn-js starter example](https://github.com/bpmn-io/bpmn-js-examples/blob/master/starter/viewer.html)? It feels unclear to me how you try to import your diagram inside the Modeler. Can you provide some more information about your use case, or is the snippet you shared the only code?

Note: Please always feel free to use [our forum](https://forum.bpmn.io/). It might be a better place for asking questions.

**Comment by nikku** [comment]
The toolkit does not allow you to open a diagram via URL.

Load the diagram using your favorite AJAX library and open it via the `Modeler#importXML` method.
