### ISSUE TITLE
How to create custom properties panel as modal?

### ISSUE THREAD

**Issue by bahmansh** [bpmn-io/bpmn-js#942]
Hi
I need to open properties panel as an modal when click on any elements and after submit modal properties add to element.

**Comment by bahmansh** [comment]
I need to use workflow in my project. I want to convert workflow to xml and extract my required data such as tasks, conditions, transitions and so on from it and save them in database and based on them my application will execute workflows.

I investigated some javascript bpmn tools such as mxgraph and bpmn-js. Finally, I decided to use bpmn-js.

My problem is that I want to add some attribute to elements, for example I want to add a receiver to a task or phone number to another task and so on. I need to open a modal form when i clicked on any element. How can I do that?

**Comment by nikku** [comment]
What did you try? What did not work?

Did you have a look into our [existing examples](https://github.com/bpmn-io/bpmn-js-examples) already?

**Comment by bahmansh** [comment]
> What did you try? What did not work?
> 
> Did you have a look into our [existing examples](https://github.com/bpmn-io/bpmn-js-examples) already?

Yes I have.
I have explained in above.
I need to open modal form and set some properties there then add them to xml properties.

**Comment by pinussilvestrus** [comment]
Did you already write some code to achieve what you want and can share with us? The [properties panel](https://github.com/bpmn-io/bpmn-js-properties-panel) isn't meant to be used inside other kinds of UI elements, so you will have to implement your own implementation of this properties modal.

**Comment by pinussilvestrus** [comment]
Edit: maybe you can have a look on an example Nico created: https://github.com/nikku/bpmn-js-extension-demo

It shows how to create a custom `PropertiesPanel`.

**Comment by nikku** [comment]
Thanks for your further input @pinussilvestrus.

We'll close this issue for now and are happy to re-open it if you come up with concrete pointers for the things you tried already and what did not work.
