### ISSUE TITLE
Lanes are movable with arrow keys

### ISSUE THREAD

**Issue by mnp-mid** [bpmn-io/bpmn-js#943]
The selected lane is movable with arrow keys

1. Create participant
2. Add a lane to participant
3. click on participant. (Participant moves with content)
4. click on lane. (Only the lane moves)

![bpmn modeler _ demo bpmn io - internet explorer 2019-03-05 09-24-23_s](https://user-images.githubusercontent.com/33545902/53791046-bc2fc600-3f28-11e9-8d5b-b0ba7923c8a3.gif)

__Expected Behavior__

The lane should not be movable at all. 
Currently draging the lane with the mouse is not allowed and should stay this way.

__Environment__
 - Browser: [Chrome 72.0.3626.119]

**Comment by nikku** [comment]
Good catch.

**Comment by nikku** [comment]
Unfortunately we do not hook in existing rules right now at all.

This needs a fix in diagram-js, cf. https://github.com/bpmn-io/diagram-js/issues/312.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1185.
