### ISSUE TITLE
Labels are left visible when moved subprocess is collapsed

### ISSUE THREAD

**Issue by yT0n1** [bpmn-io/bpmn-js#945]
__Describe the Bug__

When a subprocess contains a label for an event and the subprocess is moved and then collapsed, the label is left visible. 

![bug](https://user-images.githubusercontent.com/4279289/54036999-5b6ceb80-41bd-11e9-8935-7d5d95bae983.gif)

__Steps to Reproduce__

1. Create subprocess
2. Add Start Event
3. Add label to event
4. Move event or subprocess
5. Collaps subprocess

__Expected Behavior__

The label should be hidden when the subprocess is collapsed

__Reason__
I have a suspicion why this happens: When the Subprocess is moved, the label is removed as its child and becomes a child of the diagram root element. This seems to happen in _BpmnOrderingProvider_ under _getOrdering_.

__Environment__
This can be reproduced on https://demo.bpmn.io/new
Please complete the following information:

 - Browser: Firefox 66.0b13 
 - OS: MacOS 10.14

**Comment by philippfromme** [comment]
I can reproduce this. Thanks for reporting.

**Comment by nikku** [comment]
This is probably introduced in `v3.0.4` as a side effect of a label fix (cf. [CHANGELOG#304](https://github.com/bpmn-io/bpmn-js/blob/master/CHANGELOG.md#304)).

Could you validate if `v3.0.3` still works in the correct manner from your point of view?

**Comment by yT0n1** [comment]
Yes, the problem does not seem to appear in v3.0.3

**Comment by nikku** [comment]
Fixed with bpmn-js@9:

![capture QxxhiG_optimized](https://user-images.githubusercontent.com/58601/156212301-e50127fb-2e41-4a01-80b2-abb9b79791a1.gif)
