### ISSUE TITLE
[Translations] doc/translations.json is missing the replacements

### ISSUE THREAD

**Issue by lwolle** [bpmn-io/bpmn-js#946]
## Description

While trying to use a custom translations module and closely following the i18n [example](https://github.com/bpmn-io/bpmn-js-i18n) I noticed, that the keys for the template string replacements are missing in `docs/translations.json` and in the linked example repo.

## Steps to reproduce the behavior:

![animation](https://user-images.githubusercontent.com/20285765/54141355-cde00480-4425-11e9-9444-e45ca6911436.gif)

The screencast was taken on the [online demo](http://demo.bpmn.io/new). You'll see that the label of the process object "Start Event" reads "Start Event". In Contrast, the hover title of the toolbar option reads "Create StartEvent". 
"Create StartEvent" is equivalent to the template string or a parametrized message: "Create {type}". The value for the replacement of "{type}" is injected by the library as {type: "StartEvent"}. The list of possible values for the replacement of the message parameters is missing in the docs and the i18n example repo.

Possible parameter keys are: `type`, `element`, `parent`. 

## Expected Behavior

I would expect a list of message paramters and possible replacement values to be part of the docs or the i18n example.

**Comment by pinussilvestrus** [comment]
Hi @lwolle 
thanks your sharing your thoughts? As I understand correctly, your feature request includes adding proper documentation of `replacement keys` right? So it's correct, it's missing. We currently think about several improvements regarding our documentation (ping @barmac). Maybe improvements regarding how to deal with translations would be one point.

If you have any suggestions on how to document this part, feel free to open a pull request! ❤️

**Comment by lwolle** [comment]
Hi @pinussilvestrus,
thanks for getting back to me. Yeah, you correctly understood my point. It would be very nice if documentation in general and this particular point about the translations would be a little more extensive. Personally, I really would appreciate if the documentation would not only be based on the examples (but thanks for that for sure). As I understand bpmn-js, lot's of configuration is possible, and thus I'd personally like to see these options in the docs.

A good starting point would be the translations, and providing the keys for the translate function (built-in or custom) in a chapter in the doc and explain how the translate function works.

**Comment by nikku** [comment]
> A good starting point would be the translations, and providing the keys for the translate function (built-in or custom) in a chapter in the doc and explain how the translate function works.

For the moment I suggest we put the stuff up on [bpmn-js-i18n](https://github.com/bpmn-io/bpmn-js-i18n).

> As I understand bpmn-js, lot's of configuration is possible, and thus I'd personally like to see these options in the docs.

If you got ideas how to build not-to-convoluted, easy-to-read and maintainable documentation, tell us! What is _the docs_ you refer to?

Regarding implementation, we have a [translation reporter](https://github.com/bpmn-io/bpmn-js/blob/master/test/config/translation-reporter.js) that collects all translations. It could collect the replacements (and comment them, too).

To follow up on this task I'd suggest:

* Collect the information using an improved translation reporter
* Document it ([bpmn-js-i18n](https://github.com/bpmn-io/bpmn-js-i18n) looks like a good place for now)

@lwolle We are open for your contribution!
