### ISSUE TITLE
Adding Message Flows to Pool Boundaries is Tricky When Pool Once Had More Than One Lane

### ISSUE THREAD

**Issue by sebwarnke** [bpmn-io/bpmn-js#950]
__Describe the Bug__

When I try to connect a message flow to the boundary of a pool that had more than one lane this is only possible by dropping the connector at the header of the pool; not anymore inside the single lane of the pool

__Steps to Reproduce__

1. Create two pools
2. Connect both pools using the connector tool by clicking first in one pool's body and then in the other pool's body
3. Add an additional lane to one of the pools
4. Remove that lane right away
5. Repeat step 2.

![NWPPriWPfl](https://user-images.githubusercontent.com/26740468/54624728-3b1b1780-4a6e-11e9-830b-3957d8b91cf7.gif)

__Expected Behavior__

I can connect both pools like I did in step 2.

__Environment__

Please complete the following information:
- Camunda Modeler 2.2.4
- Camunda Modeler 3.0.0-beta.3.3358

**Comment by pinussilvestrus** [comment]
This relates to an issue reported inside the Camunda Modeler (https://github.com/camunda/camunda-modeler/issues/1213). 

This could be a little nice improvement in terms of UX. Maybe it's worth it to put it inside the next milestone. What do you think @nikku?

**Comment by nikku** [comment]
Our next milestone is huge already :wink:.

Let's queue this inb

**Comment by pinussilvestrus** [comment]
Closed via 19be51abc76894db9e2f7743891ebefd4bb79719
