### ISSUE TITLE
Improve navigation in container elements

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js#957]
__Is your feature request related to a problem? Please describe.__

As described in https://github.com/camunda/camunda-modeler/issues/238 it is very hard to navigate through huge container elements (as pools, lanes, subprocesses or, additionally, groups).

__Describe the solution you'd like__

Improve the situation. One possible solution is sketched in [this comment](https://github.com/camunda/camunda-modeler/issues/238#issuecomment-470062772):

> Applying to all container elements (pools, lanes and sub processes):
> 
> - container elements may only be moved after they have been selected
> - container elements may only be selected on the border (or when clicking their labels)
> - dragging inside a container element should move the canvas, if the container has not been selected

__Describe alternatives you've considered__

.

__Additional context__

* Relates to https://github.com/camunda/camunda-modeler/issues/238

**Comment by barmac** [comment]
Reopened via https://github.com/bpmn-io/bpmn-js/pull/1118

**Comment by nikku** [comment]
Restored on `develop` via https://github.com/bpmn-io/bpmn-js/commit/bee05f19a737b627c930e60fc991a3fab6fcd565.
