### ISSUE TITLE
IE 11 - Replace Option Menu is wrong positioning

### ISSUE THREAD

**Issue by mnp-mid** [bpmn-io/bpmn-js#965]
__Describe the Bug__

The Replace Option Menu is wrong positioned in the IE 11. This seems to happen only by zooming out. 

![bpmn modeler _ demo bpmn io - Internet Explorer 2019-04-03 10-50-03_s](https://user-images.githubusercontent.com/33545902/55466253-1a6ec800-55ff-11e9-97b5-e26de0c0c1bd.gif)

__Steps to Reproduce__

1. Create a diagram with participant and task
2. Zoom outside
3. Click on the Task and select the replace option

__Expected Behavior__

The Replace option is positoned correctly

__Environment__
 - Browser: [IE 11]
 - OS: [Windows 10]

**Comment by mnp-mid** [comment]
It seems to me that the issue is some where in **PopupMenu.prototype._assureIsInbounds**.

The getReplaceMenuPosition() method provides a position with something like x: 900 and y: 300 in my case and in the call statement with **popupMenu.open(element, 'bpmn-replace', position);** (ContextPadProvider.js) the cursor events provide something ilke x: 10 and y: 15 and they are taken at the end.

It seems like there is a missing condition in **PopupMenu.prototype._assureIsInbounds** for this. 

if (overAxis.x && overAxis.y) {
    left = cursorPosition.x - containerWidth + 'px';
    top = cursorPosition.y - containerHeight + 'px';
  } else if (overAxis.x) {
    left = cursorPosition.x - containerWidth + 'px';
    top = cursorPosition.y + 'px';
  } else if (overAxis.y && cursorPosition.y < containerHeight) {
    left = cursorPosition.x + 'px';
    top = 10 + 'px';
  } else if (overAxis.y) {
    left = cursorPosition.x + 'px';
    top = cursorPosition.y - containerHeight + 'px';
  }

**Comment by pinussilvestrus** [comment]
Hi @mnp-mid ,
thanks for reporting! I was able to reproduce it on Windows 8 + IE11, but not on Mac. Additionally thanks for investigating the bug 👍 Maybe you can share a possible fix with a proper test case? We are always open for external contribution 🙂

**Comment by nikku** [comment]
Closing this issue, as we phase out IE 11 support and won't fix this bug anymore. 

Still accepting external contributions on it.
