### ISSUE TITLE
Introduce Grid Snapping

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#973]
Grid snapping allows our users to create good looking diagrams faster, with less frustration.

__Tasks__

* [x] Basic grid snapping integration (https://github.com/bpmn-io/diagram-js/pull/316, https://github.com/bpmn-io/bpmn-js/pull/974)
* [x] Integrate grid snapping with existing features 
    * [x] [Auto Place](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/auto-place/AutoPlace.js)
    * [x] [Auto Resize](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/auto-resize/AutoResize.js)
    * [x] [Copy Paste](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/copy-paste/CopyPaste.js)
    * [x] [Space Tool](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/space-tool/SpaceTool.js)
    * [x] [Toggle Collapse](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/modeling/cmd/ToggleShapeCollapseHandler.js)
    * [x] [Connection Layout](https://github.com/bpmn-io/diagram-js/issues/323)

# Details

## Auto Place

All of its [distances are multiples of 10](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/auto-place/AutoPlaceUtil.js#L14), but these are measured between the outer edges of shapes. Since events are 36 by 36 the append position won't be on the grid.

## Auto Resize

Should behave similarly to resize taking constraints into account.

## Copy Paste

Each elements relative position will be preserved. Elements that were snapped before will be snapped afterward.

## Space Tool

Should move elements in distances that are multiples of 10. Elements that were snapped before will be snapped afterward.

## Toggle Collapse

Should be handled appropriately by auto resize.

# Things we will not touch:

1. [Adaptive Label Positioning](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/behavior/AdaptiveLabelPositioningBehavior.js)
2. [Label Adjustment](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/behavior/LabelBehavior.js)
3. [Align Elements](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/align-elements/AlignElements.js)
4. [Distribute Elements](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/distribute-elements/DistributeElements.js)
5. [Keyboard Move Selection](https://github.com/bpmn-io/diagram-js/blob/master/lib/features/keyboard-move-selection/KeyboardMoveSelection.js)

---

Required by https://github.com/camunda/camunda-modeler/issues/1019

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/diagram-js/pull/330.
