### ISSUE TITLE
Custom fill and stroke colors make markers disappear

### ISSUE THREAD

**Issue by FlexiGit** [bpmn-io/bpmn-js#981]
__Describe the Bug__

When you use more complex color values for defaultFillColor and defaultStrokeColor (e.g. rgba() function) the renderer will use theses values in the ids for markers. As the ids then contain characters not valid for urls and element references in svg the marker cannot be linked. This finally results in missing markers in the svg image (e.g. missing arrow heads for sequence flows).

Afaics this is the only place where complex color values do not work.

__Steps to Reproduce__

Define defaultFillColor and defaultStrokeColor like this:
```
bpmnRenderer: {
    defaultFillColor: "rgba(255,255,255,0.95)",
    defaultStrokeColor: "rgba(30,30,30,1)"
}
```

https://jsfiddle.net/y1nq86sm/

__Expected Behavior__

* [ ] Escape colors used in marker ids so that resulting IDs are valid

__Environment__

 - Browser: Chrome
 - OS: Win 10
 - Library version: 3.3.1

**Comment by nikku** [comment]
Find a partial fix here: https://github.com/bpmn-io/bpmn-js/pull/972/commits/e7b1e535f08e252d5ce1d4c553d7cc519b115584

**Comment by FlexiGit** [comment]
In which way is the suggested fix partial? Where could this lead to problems?

And: When will this be integrated into an release? Since the BpmnRenderer is quite an integral part of the library, I'm not very fond of completely replacing it on the consuming side.

**Comment by nikku** [comment]
I have [added a comment](https://github.com/bpmn-io/bpmn-js/commit/e7b1e535f08e252d5ce1d4c553d7cc519b115584#r33193659).

**Comment by nikku** [comment]
It also seems to be something that broke with a recent Chrome release.

**Comment by nikku** [comment]
Will be fixed via https://github.com/bpmn-io/bpmn-js/commit/aaff6d95f2044cf92169876685f119cd9bac9f1b.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/972.
