### ISSUE TITLE
How to convert input box into drop-down box

### ISSUE THREAD

**Issue by illsion** [bpmn-io/bpmn-js#984]
After the integration of bpmn-js and vue, how can we not change the bpmn-js-properties-panel component code, and control the input box to drop-down box through the BpmnModeler object, such as the input box corresponding to Form Key to drop-down box?

**Comment by nikku** [comment]
Please provide more context, i.e. by adding screenshots. What input box do you refer to?

**Comment by pinussilvestrus** [comment]
I'll close this because no extra context was given. @illsion please reopen the issue if you have more to share.
