### ISSUE TITLE
Element order is not updated in BPMNDI

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#985]
__Describe the Bug__

As mentioned in [this comment](https://github.com/camunda/camunda-modeler/issues/1326#issuecomment-481867940) the BPMN spec mandates that the order of elements in the BPMNDI section should always reflect the actual layering on the diagram.

We do ignore that fact completely and add elements to the BPMNDI section on a first created, first added basis. This results in [display bugs](https://github.com/camunda/camunda-modeler/issues/1326) when roundtripping with other, standards compliant tools.

__Steps to Reproduce__

* Create a task
* Create a sub process
* Move task to sub process
* Export Diagram
* __Task is exported before sub process in BPMNDI__
 
__Expected Behavior__

* [ ] Task position in DI is updated according to actual visibility

__Note:__ This is not simple to accomplish, as we must effectively update all nested elements, too.

__Environment__

Please complete the following information:

 - Browser: Any (independent)
 - OS: Any (independent)
 - Library version: `v3.3.1`

**Comment by nikku** [comment]
Idea: If we cannot get the ordering done efficiently during modeling, build a pre-export extension that normalizes things before safe. We got a few utilities that [go the same route, already](https://github.com/bpmn-io/awesome-bpmn-io#misc).

**Comment by falko** [comment]
Awesome, thx!

**Comment by barmac** [comment]
Looking forward to your feedback! It's coming with the 3.7.1 release :)
