### ISSUE TITLE
How can i get the "element"?

### ISSUE THREAD

**Issue by Super-Mumoo** [bpmn-io/bpmn-js#986]
when i click the lsit, callback function will return tow parameters: event&element
![image](https://user-images.githubusercontent.com/38457677/56354008-5744dc80-6205-11e9-8491-50399ee5fb55.png)
like this
![image](https://user-images.githubusercontent.com/38457677/56354119-907d4c80-6205-11e9-88f4-b36bc2ace991.png)
now i want get the "element" by the element’s id(like "Task_1m0dxcv")
![image](https://user-images.githubusercontent.com/38457677/56354294-ef42c600-6205-11e9-98fc-bb196a7ee861.png)
Is there such a way?

**Comment by nikku** [comment]
What do you refer to as the _element_? We distinguish different kinds of elements: 

* The _element_ as in diagram element is the diagram-js representation of a visible shape (or connection)
* The _element_ as in business object is the BPMN 2.0 representation of a visible shape, accessible via _diagramElement.businessObject_
* The _element_ as in DOM node is the actual visual thing, added to the DOM, clickable by you. You may retrieve it via the `ElementRegistry`: `ElementRegistry#getGraphics(diagramElement)`.

**Comment by Super-Mumoo** [comment]
Sorry, my description doesn't seem to be detailed enough.

This parameter returned here.
![image](https://user-images.githubusercontent.com/38457677/56401814-48097180-628d-11e9-8fdd-8692d6f85014.png)
![image](https://user-images.githubusercontent.com/38457677/56401817-4dff5280-628d-11e9-9865-ce95249ff9ed.png)
if i console.log the "element", I'll get such an object.
![image](https://user-images.githubusercontent.com/38457677/56401925-d2ea6c00-628d-11e9-967f-9ebfb7b44ea0.png)
i want get the object, or the "BusinessObject" in this object
Can I get the object by the "data-element-id"?
Or in other ways？

**Comment by Super-Mumoo** [comment]
i find it in "bpmnModeler._moddle.ids._seed.hats"
My idea now is to traverse "bpmnModeler. _moddle. ids. _seed. hats" to find the element I want.
bpmnModeler is from new BpmnJS
