### ISSUE TITLE
Redoing element removal does not restore exactly same waypoints

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#989]
__Describe the Bug__

Waypoints restored via redo might be different than after original command. This happens on element removal.

Revealed in https://github.com/bpmn-io/bpmn-js/pull/988

Test case available in https://github.com/bpmn-io/bpmn-js/tree/989-correct-waypoints-restore-on-element-removal

__Steps to Reproduce__

![removal](https://user-images.githubusercontent.com/28307541/56366935-7e46e280-61f4-11e9-9ba9-b739a3c30597.gif)

1. Connect three elements positioned diagonally
2. Remove the middle element
3. Undo
4. Redo

The connection has different waypoints than after removal.

__Expected Behavior__

Waypoints should be the same.

__Environment__

Please complete the following information:

 - Browser: Chrome
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
Most likely related to [this comment](https://github.com/bpmn-io/diagram-js/pull/320#discussion_r276703165).
