### ISSUE TITLE
Color shapes and transitions

### ISSUE THREAD

**Issue by kant1981** [bpmn-io/bpmn-js#99]
Hi guys,

I have one concern on how to render a highlighted edge between two activities.

Is that possible to achieve this by using bpmn-js? If yes, how? If no, can you guys put the feature in? I suppose it is not a bad idea for this project.

Thanks in advance,
Huiying

**Comment by cristinasantamarina** [comment]
Coloring would be super handy for a project I'm doing - is this something you are considering?

**Comment by nikku** [comment]
Yes, just not at the moment. You can add a class to a drawn element via `canvas#addMarker` and provide custom coloring via CSS.

**Comment by cristinasantamarina** [comment]
Thanks for the quick answer nikku - could you help me a bit more there, dummy that down a bit? I can try to do this on my own but I can't come up with where i can edit the css. Thanks!

**Comment by cristinasantamarina** [comment]
@nikku I have installed the app and I have access to the code locally but I can't figure out 

- which of the 2 css files I shall edit.
- how to edit colours for specific boxes - where do my worksflows sleep?
- how to package this so that I can share the little hack with other ppl in my team.

Maybe this helps. Thanks!

**Comment by nikku** [comment]
We will provide an example for this in the near future (https://github.com/bpmn-io/bpmn-js-examples/issues/7).

Feel free to address your usage related questions/concerns in our [project forums](https://forum.bpmn.io).

**Comment by nikku** [comment]
I created [an example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/colors) showing how to do this.

**Comment by skin27** [comment]
Would be nice if coloring can be done from the user interface, instead of the code options. Is this issue already higher on the roadmap?

**Comment by vkatushenok** [comment]
Please see #629 (in progress) and related #390 😉 .

**Comment by skin27** [comment]
That's great news!

**Comment by jisqaqov** [comment]
It's been already 2 years, since this issue have been created. In my opinion, it is crucial to implement this feature. Could you please give feedback when you are going to make this happen. For instance, i want to highlight completed and active tasks with different colors in diagram.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/issues/629.

**Comment by nikku** [comment]
@jisqaqov Awesome, how you thumbs up your own comment :+1:.
