### ISSUE TITLE
Collapsing an element with message flows creates dangling connections

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#991]
__Describe the Bug__

Collapsing an element with message flows creates dangling connections.

__Steps to Reproduce__

1. Create a subprocess with elements with message flows or a pool with message flows
2. Collapse the element
3. Notice dangling connections

* Subprocess
![collapse-subprocess](https://user-images.githubusercontent.com/28307541/56587783-6c918080-65e2-11e9-80d1-814c70bb8f3f.gif)

* Pool (only with `master`)
![collapsed-pool](https://user-images.githubusercontent.com/28307541/56587786-6c918080-65e2-11e9-8ead-0da7eb12c9a5.gif)

__Expected Behavior__

Message flows should be laid out or removed.

__Environment__

Please complete the following information:

 - Browser: Chrome 73
 - OS: MacOS
 - Library version: `master` and current demo

---

Related to https://github.com/bpmn-io/bpmn-js/issues/945 (labels being left visible)

**Comment by barmac** [comment]
Related to https://github.com/bpmn-io/bpmn-js/issues/752

**Comment by nikku** [comment]
Closed with bpmn-js@9:

![capture vKfFt9_optimized](https://user-images.githubusercontent.com/58601/156213156-b5692c87-3489-45d0-8b96-b94c2afded66.gif)
