### ISSUE TITLE
Snap to original position

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#993]
__Is your feature request related to a problem? Please describe.__

Snapping helps me to align elements with each other. However, as of now we only snap to other elements, not to the elements origin. With the introduction of grid snapping this leads to frustrating situations where the snapping behavior disallows me to drop the element back to the original position:

![foo_1](https://user-images.githubusercontent.com/58601/56590854-0c9dd880-65e8-11e9-80b2-ffb68068f1c2.gif)

The appropriate behavior when snapping to the original position is allowed: 

![foo](https://user-images.githubusercontent.com/58601/56590873-16274080-65e8-11e9-9278-2a01baeec7f1.gif)

We should consider whether we snap to an elements original position, too. Additionally, we should consider to add the same (snap to original position) behavior for bendpoint and connection segment moving. Otherwise the same quirky behavior can be observed during bendpoint snapping, too:

![foo_1](https://user-images.githubusercontent.com/58601/56591450-09571c80-65e9-11e9-8c98-ef97b1b42df2.gif)

__Describe the solution you'd like__

* Elements snap to their origin so that I have a choice whether to snap the element to the grid (or keep it as is)
* Grid Snapping activates after snap to origin
* Bendpoints and connection segments snap to their original position _before_ grid snapping is considered

__Describe alternatives you've considered__

In general we should aim for the following:

* Grid snapping should help you to gradually improve diagrams
* Grid snapping should never break existing connection layouts

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1023
