### ISSUE TITLE
Modeling#setColor changes the size of the corresponding label

### ISSUE THREAD

**Issue by rene5141** [bpmn-io/bpmn-js#998]
__Describe the Bug__
I have find a bug when using the Modeling#setColor method to highlight a specific BPMN element.
When I change the color of an element with the Modeling#setColor method, the size of the corresponding label is changed. This resizing is then stored in the BPMN file, which is in my opinion not a clean behavior…

__Steps to Reproduce__

1. Create an BPMN element
2. Save this BPMN diagram into an XML file 1
3. Change the color of this element from black to blue
4. Revert this color change by changing the color of this element from blue to black
5. Save the BPMN diagram into an XML file 2

__Expected Behavior__

The XML file 1 and the XML file 2 should be identically, but they aren't! 
The size of the corresponding labels has ben changed...

__Environment__

 - Browser: IE 11
 - OS: Windows 10
 - Library version: 3.3.1

__Related Code__
```
function addElementHighlighting(id) {
    var shape = getByDiId(id);

    if (shape !== null) {
        var elementsToColor = [shape];
        var modeling = modeler.get('modeling');
        modeling.setColor(elementsToColor,
            {
                stroke: 'black',
                fill: 'LightSkyBlue'
            });
    } else {
        console.log("Shape ID " + id + " not found to highlight!");
    }
}
```

```
function removeElementHighlighting(id) {
    var shape = getByDiId(id);

    if (shape !== null) {
        var elementsToColor = [shape];
        var modeling = modeler.get('modeling');
        modeling.setColor(elementsToColor,
            {
                stroke: 'black',
                fill: 'white'
            });
    } else {
        console.log("Element ID " + id + " not found to delete highlighting!");
    }
}
```

```
function getByDiId(id) {
    var elementRegistry = modeler.get('elementRegistry');
    var elementList = elementRegistry.getAll();
    var len = elementList.length;

    var items = [];

    elementRegistry.forEach(function (regItem, gfx) {
        items.push(regItem);
    });

    for (var i = 0; i < items.length; i++) {
        var item = items[i];
        if (item.businessObject.di.id === id) {
            return item;
        }
    }
    return null;
}
```

**Comment by nikku** [comment]
Thanks for filing this issue.

The behavior you observe is expected, as we always update the label bounds [with any label change](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/BpmnUpdater.js#L159), including setting colors.

We chose to go down this road to compensate for tools that do not serialize proper label bounds. You can find this touch-and-repair pattern in many parts of our tool.

Given that additional background information, could you elaborate on why changing the label size is a problem?

**Comment by rene5141** [comment]
> Given that additional background information, could you elaborate on why changing the label size is a problem?
Normally it would be no problem, but we use the Modeling#setColor method to temporarily highlight a BPMN element in the Modeler. As a result, this highlighting triggers a change in our model and is saved in our XML representation, which is in fact no true change in the model (e.g. when a element is deleted, or an element is moved in the diagram, ...)

**Comment by nikku** [comment]
Thanks for the clarification.

There exists other ways to implement temporary highlighting, e.g. a custom renderer that takes some additional properties or configuration into account, a CSS overlay, ...

Closing this particular issue, as we won't fix the described behavior.
